//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core6502DotNet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core6502DotNet.src.Utility.ConfigConstants", typeof(ConfigConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;caseSensitive&quot;:false,&quot;defines&quot;:[&quot;MYLABEL&quot;],&quot;ignoreColons&quot;:false,&quot;includePath&quot;:&quot;/includes&quot;,&quot;listingOptions&quot;:{&quot;labelPath&quot;:&quot;labeldump.asm&quot;,&quot;listPath&quot;:&quot;source_list.asm&quot;,&quot;noAssembly&quot;:false,&quot;noDisassembly&quot;:false,&quot;noSource&quot;:false,&quot;verbose&quot;:false},&quot;loggingOptions&quot;:{&quot;checksum&quot;:false,&quot;errorPath&quot;:&quot;errors.txt&quot;,&quot;noWarnings&quot;:false,&quot;quietMode&quot;:false,&quot;warningsAsErrors&quot;:false,&quot;warnLeft&quot;:true},&quot;outputFile&quot;:&quot;object.bin&quot;,&quot;sources&quot;:[&quot;source.asm&quot;],&quot;sections&quot;:[{&quot;name&quot;:&quot;text&quot;,&quot;starts&quot;:&quot;$1000&quot;,&quot;ends&quot;:&quot;$4000&quot;},{&quot;name&quot;:&quot;data&quot;,&quot;star [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CONFIG_FULL {
            get {
                return ResourceManager.GetString("CONFIG_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;sources&quot;:[&quot;source.asm&quot;]}.
        /// </summary>
        internal static string CONFIG_MIN {
            get {
                return ResourceManager.GetString("CONFIG_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;properties&quot;:{&quot;caseSensitive&quot;:{&quot;type&quot;:&quot;boolean&quot;,&quot;default&quot;:false},&quot;ignoreColons&quot;:{&quot;type&quot;:&quot;boolean&quot;,&quot;default&quot;:false},&quot;defines&quot;:{&quot;type&quot;:&quot;array&quot;,&quot;default&quot;:[],&quot;items&quot;:{&quot;type&quot;:&quot;string&quot;}},&quot;includePath&quot;:{&quot;type&quot;:&quot;string&quot;,&quot;default&quot;:&quot;&quot;},&quot;listingOptions&quot;:{&quot;type&quot;:&quot;object&quot;,&quot;default&quot;:{},&quot;properties&quot;:{&quot;labelPath&quot;:{&quot;type&quot;:&quot;string&quot;,&quot;default&quot;:&quot;&quot;},&quot;listPath&quot;:{&quot;type&quot;:&quot;string&quot;,&quot;default&quot;:&quot;&quot;},&quot;noAssembly&quot;:{&quot;type&quot;:&quot;boolean&quot;,&quot;default&quot;:false},&quot;noDisassembly&quot;:{&quot;type&quot;:&quot;boolean&quot;,&quot;default&quot;:false},&quot;noSource&quot;:{&quot;type&quot;:&quot;boolean&quot;,&quot;default&quot;:f [rest of string was truncate....
        /// </summary>
        internal static string CONFIG_SCHEMA {
            get {
                return ResourceManager.GetString("CONFIG_SCHEMA", resourceCulture);
            }
        }
    }
}
