//-----------------------------------------------------------------------------
// Copyright (c) 2017-2020 informedcitizenry <informedcitizenry@gmail.com>
//
// Licensed under the MIT license. See LICENSE for full license information.
// 
//-----------------------------------------------------------------------------

using System.Collections.Generic;

namespace Core6502DotNet.m6502
{
    /// <summary>
    /// A line assembler that will assemble into 6502 instructions.
    /// </summary>
    public sealed partial class Asm6502 : AssemblerBase
    {
        enum Modes
        {
            Implied      = 0b00000000000000000000,
            ZeroPage     = 0b00000000000000000001,
            Absolute     = 0b00000000000000000011,
            Long         = 0b00000000000000000111,
            SizeMask     = 0b00000000000000000111,
            Indirect     = 0b00000000000000001000,
            DirectPage   = 0b00000000000000010000,
            IndexedX     = 0b00000000000000100000,
            InnerX       = 0b00000000000001000000,
            IndexedY     = 0b00000000000010000000,
            IndexedZ     = 0b00000000000100000000,
            IndexedS     = 0b00000000001000000000,
            IndexedSp    = 0b00000000010000000000,
            TwoOpBit     = 0b00000000100000000000,
            TwoOperand   = 0b00000000100000000001,
            ThreeOperand = 0b00000001000000000000,
            Bit0         = 0b00000010000000000000,
            Bit1         = 0b00000110000000000000,
            Bit2         = 0b00001010000000000000,
            Bit3         = 0b00001110000000000000,
            Bit4         = 0b00010010000000000000,
            Bit5         = 0b00010110000000000000,
            Bit6         = 0b00011010000000000000,
            Bit7         = 0b00011110000000000000,
            Immediate    = 0b00100000000000000001,
            RelativeBit  = 0b01000000000000000000,
            Relative     = 0b01000000000000000001,
            MemModMask   = 0b01111111111111111000,
            ModeMask     = 0b01111111111111111111,
            ForceWidth   = 0b10000000000000000000,
            AbsoluteX    = Absolute     | IndexedX,
            AbsoluteY    = Absolute     | IndexedY,
            ZeroPageX    = ZeroPage     | IndexedX,
            ZeroPageY    = ZeroPage     | IndexedY,
            ZeroPageS    = ZeroPage     | IndexedS,
            LongX        = Long         | IndexedX,
            IndX         = ZeroPage     | InnerX    | Indirect,
            IndY         = ZeroPageY    | Indirect,
            IndZ         = ZeroPage     | Indirect  | IndexedZ,
            IndS         = IndY         | IndexedS,
            IndSp        = IndY         | IndexedSp,
            IndZp        = ZeroPage     | Indirect,
            IndAbs       = Absolute     | Indirect,
            IndAbsX      = Absolute     | Indirect  | InnerX,
            Dir          = ZeroPage     | DirectPage,
            DirAbs       = Absolute     | DirectPage,
            DirY         = Dir          | IndexedY,
            DirIndMask   = Indirect     | DirectPage,
            RelativeAbs  = Relative     | Absolute,
            ThreeOpRel   = ThreeOperand | RelativeBit,
            ThreeOpAbs   = ThreeOperand | Absolute,
            Zp0          = TwoOperand   | Bit0,
            Zp1          = TwoOperand   | Bit1,
            Zp2          = TwoOperand   | Bit2,
            Zp3          = TwoOperand   | Bit3,
            Zp4          = TwoOperand   | Bit4,
            Zp5          = TwoOperand   | Bit5,
            Zp6          = TwoOperand   | Bit6,
            Zp7          = TwoOperand   | Bit7,
            ThreeOpRel0  = ZeroPage     | ThreeOpRel | Bit0,
            ThreeOpRel1  = ZeroPage     | ThreeOpRel | Bit1,
            ThreeOpRel2  = ZeroPage     | ThreeOpRel | Bit2,
            ThreeOpRel3  = ZeroPage     | ThreeOpRel | Bit3,
            ThreeOpRel4  = ZeroPage     | ThreeOpRel | Bit4,
            ThreeOpRel5  = ZeroPage     | ThreeOpRel | Bit5,
            ThreeOpRel6  = ZeroPage     | ThreeOpRel | Bit6,
            ThreeOpRel7  = ZeroPage     | ThreeOpRel | Bit7,
            ImmAbs       = Immediate    | Absolute,
            TestBitZp    = Immediate    | TwoOperand,
            TestBitAbs   = Immediate    | TwoOperand | Absolute,
            TestBitZpX   = Immediate    | TwoOperand | IndexedX,
            TestBitAbsX  = Immediate    | TwoOperand | Absolute | IndexedX,
            TestBitFlag  = TestBitZp    & MemModMask
        };
        #region Members
    
        string _cpu;
        bool _m16, _x16;
        IReadOnlyDictionary<(string Mnem, Modes Mode), CpuInstruction> _selectedInstructions;
        static double[] s_evaled;
        static readonly Dictionary<(string Mnem, Modes Mode), CpuInstruction> s_opcodes6502 = 
            new Dictionary<(string Mnem, Modes Mode), CpuInstruction>()
        {
            { ("brk", Modes.Implied     ), new CpuInstruction( "6502",    0x00) },
            { ("ora", Modes.IndX        ), new CpuInstruction( "6502",    0x01, 2) },
            { ("ora", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x05, 2) },
            { ("asl", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x06, 2) },
            { ("php", Modes.Implied     ), new CpuInstruction( "6502",    0x08) },
            { ("ora", Modes.Immediate   ), new CpuInstruction( "6502",    0x09, 2) },
            { ("asl", Modes.Implied     ), new CpuInstruction( "6502",    0x0a) },
            { ("ora", Modes.Absolute    ), new CpuInstruction( "6502",    0x0d, 3) },
            { ("asl", Modes.Absolute    ), new CpuInstruction( "6502",    0x0e, 3) },
            { ("bpl", Modes.Relative    ), new CpuInstruction( "6502",    0x10, 2) },
            { ("ora", Modes.IndY        ), new CpuInstruction( "6502",    0x11, 2) },
            { ("ora", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x15, 2) },
            { ("asl", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x16, 2) },
            { ("clc", Modes.Implied     ), new CpuInstruction( "6502",    0x18) },
            { ("ora", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0x19, 3) },
            { ("top", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x1c, 3) },
            { ("ora", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x1d, 3) },
            { ("asl", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x1e, 3) },
            { ("jsr", Modes.Absolute    ), new CpuInstruction( "6502",    0x20, 3) },
            { ("and", Modes.IndX        ), new CpuInstruction( "6502",    0x21, 2) },
            { ("bit", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x24, 2) },
            { ("and", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x25, 2) },
            { ("rol", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x26, 2) },
            { ("plp", Modes.Implied     ), new CpuInstruction( "6502",    0x28) },
            { ("and", Modes.Immediate   ), new CpuInstruction( "6502",    0x29, 2) },
            { ("rol", Modes.Implied     ), new CpuInstruction( "6502",    0x2a) },
            { ("bit", Modes.Absolute    ), new CpuInstruction( "6502",    0x2c, 3) },
            { ("and", Modes.Absolute    ), new CpuInstruction( "6502",    0x2d, 3) },
            { ("rol", Modes.Absolute    ), new CpuInstruction( "6502",    0x2e, 3) },
            { ("bmi", Modes.Relative    ), new CpuInstruction( "6502",    0x30, 2) },
            { ("and", Modes.IndY        ), new CpuInstruction( "6502",    0x31, 2) },
            { ("and", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x35, 2) },
            { ("rol", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x36, 2) },
            { ("sec", Modes.Implied     ), new CpuInstruction( "6502",    0x38) },
            { ("and", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0x39, 3) },
            { ("and", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x3d, 3) },
            { ("rol", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x3e, 3) },
            { ("rti", Modes.Implied     ), new CpuInstruction( "6502",    0x40) },
            { ("eor", Modes.IndX        ), new CpuInstruction( "6502",    0x41, 2) },
            { ("eor", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x45, 2) },
            { ("lsr", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x46, 2) },
            { ("pha", Modes.Implied     ), new CpuInstruction( "6502",    0x48) },
            { ("eor", Modes.Immediate   ), new CpuInstruction( "6502",    0x49, 2) },
            { ("lsr", Modes.Implied     ), new CpuInstruction( "6502",    0x4a) },
            { ("jmp", Modes.Absolute    ), new CpuInstruction( "6502",    0x4c, 3) },
            { ("eor", Modes.Absolute    ), new CpuInstruction( "6502",    0x4d, 3) },
            { ("lsr", Modes.Absolute    ), new CpuInstruction( "6502",    0x4e, 3) },
            { ("bvc", Modes.Relative    ), new CpuInstruction( "6502",    0x50, 2) },
            { ("eor", Modes.IndY        ), new CpuInstruction( "6502",    0x51, 2) },
            { ("eor", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x55, 2) },
            { ("lsr", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x56, 2) },
            { ("cli", Modes.Implied     ), new CpuInstruction( "6502",    0x58) },
            { ("eor", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0x59, 3) },
            { ("eor", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x5d, 3) },
            { ("lsr", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x5e, 3) },
            { ("rts", Modes.Implied     ), new CpuInstruction( "6502",    0x60) },
            { ("adc", Modes.IndX        ), new CpuInstruction( "6502",    0x61, 2) },
            { ("adc", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x65, 2) },
            { ("ror", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x66, 2) },
            { ("pla", Modes.Implied     ), new CpuInstruction( "6502",    0x68) },
            { ("adc", Modes.Immediate   ), new CpuInstruction( "6502",    0x69, 2) },
            { ("ror", Modes.Implied     ), new CpuInstruction( "6502",    0x6a) },
            { ("jmp", Modes.IndAbs      ), new CpuInstruction( "6502",    0x6c, 3) },
            { ("adc", Modes.Absolute    ), new CpuInstruction( "6502",    0x6d, 3) },
            { ("ror", Modes.Absolute    ), new CpuInstruction( "6502",    0x6e, 3) },
            { ("bvs", Modes.Relative    ), new CpuInstruction( "6502",    0x70, 2) },
            { ("adc", Modes.IndY        ), new CpuInstruction( "6502",    0x71, 2) },
            { ("adc", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x75, 2) },
            { ("ror", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x76, 2) },
            { ("sei", Modes.Implied     ), new CpuInstruction( "6502",    0x78) },
            { ("adc", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0x79, 3) },
            { ("adc", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x7d, 3) },
            { ("ror", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x7e, 3) },
            { ("sta", Modes.IndX        ), new CpuInstruction( "6502",    0x81, 2) },
            { ("sty", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x84, 2) },
            { ("sta", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x85, 2) },
            { ("stx", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x86, 2) },
            { ("dey", Modes.Implied     ), new CpuInstruction( "6502",    0x88) },
            { ("txa", Modes.Implied     ), new CpuInstruction( "6502",    0x8a) },
            { ("sty", Modes.Absolute    ), new CpuInstruction( "6502",    0x8c, 3) },
            { ("sta", Modes.Absolute    ), new CpuInstruction( "6502",    0x8d, 3) },
            { ("stx", Modes.Absolute    ), new CpuInstruction( "6502",    0x8e, 3) },
            { ("bcc", Modes.Relative    ), new CpuInstruction( "6502",    0x90, 2) },
            { ("sta", Modes.IndY        ), new CpuInstruction( "6502",    0x91, 2) },
            { ("sty", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x94, 2) },
            { ("sta", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x95, 2) },
            { ("stx", Modes.ZeroPageY   ), new CpuInstruction( "6502",    0x96, 2) },
            { ("tya", Modes.Implied     ), new CpuInstruction( "6502",    0x98) },
            { ("sta", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0x99, 3) },
            { ("txs", Modes.Implied     ), new CpuInstruction( "6502",    0x9a) },
            { ("sta", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x9d, 3) },
            { ("ldy", Modes.Immediate   ), new CpuInstruction( "6502",    0xa0, 2) },
            { ("lda", Modes.IndX        ), new CpuInstruction( "6502",    0xa1, 2) },
            { ("ldx", Modes.Immediate   ), new CpuInstruction( "6502",    0xa2, 2) },
            { ("ldy", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xa4, 2) },
            { ("lda", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xa5, 2) },
            { ("ldx", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xa6, 2) },
            { ("tay", Modes.Implied     ), new CpuInstruction( "6502",    0xa8) },
            { ("lda", Modes.Immediate   ), new CpuInstruction( "6502",    0xa9, 2) },
            { ("tax", Modes.Implied     ), new CpuInstruction( "6502",    0xaa) },
            { ("ldy", Modes.Absolute    ), new CpuInstruction( "6502",    0xac, 3) },
            { ("lda", Modes.Absolute    ), new CpuInstruction( "6502",    0xad, 3) },
            { ("ldx", Modes.Absolute    ), new CpuInstruction( "6502",    0xae, 3) },
            { ("bcs", Modes.Relative    ), new CpuInstruction( "6502",    0xb0, 2) },
            { ("lda", Modes.IndY        ), new CpuInstruction( "6502",    0xb1, 2) },
            { ("ldy", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0xb4, 2) },
            { ("lda", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0xb5, 2) },
            { ("ldx", Modes.ZeroPageY   ), new CpuInstruction( "6502",    0xb6, 2) },
            { ("clv", Modes.Implied     ), new CpuInstruction( "6502",    0xb8) },
            { ("lda", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0xb9, 3) },
            { ("tsx", Modes.Implied     ), new CpuInstruction( "6502",    0xba) },
            { ("ldy", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0xbc, 3) },
            { ("lda", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0xbd, 3) },
            { ("ldx", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0xbe, 3) },
            { ("cpy", Modes.Immediate   ), new CpuInstruction( "6502",    0xc0, 2) },
            { ("cmp", Modes.IndX        ), new CpuInstruction( "6502",    0xc1, 2) },
            { ("cpy", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xc4, 2) },
            { ("cmp", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xc5, 2) },
            { ("dec", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xc6, 2) },
            { ("iny", Modes.Implied     ), new CpuInstruction( "6502",    0xc8) },
            { ("cmp", Modes.Immediate   ), new CpuInstruction( "6502",    0xc9, 2) },
            { ("dex", Modes.Implied     ), new CpuInstruction( "6502",    0xca) },
            { ("cpy", Modes.Absolute    ), new CpuInstruction( "6502",    0xcc, 3) },
            { ("cmp", Modes.Absolute    ), new CpuInstruction( "6502",    0xcd, 3) },
            { ("dec", Modes.Absolute    ), new CpuInstruction( "6502",    0xce, 3) },
            { ("bne", Modes.Relative    ), new CpuInstruction( "6502",    0xd0, 2) },
            { ("cmp", Modes.IndY        ), new CpuInstruction( "6502",    0xd1, 2) },
            { ("cmp", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0xd5, 2) },
            { ("dec", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0xd6, 2) },
            { ("cld", Modes.Implied     ), new CpuInstruction( "6502",    0xd8) },
            { ("cmp", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0xd9, 3) },
            { ("cmp", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0xdd, 3) },
            { ("dec", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0xde, 3) },
            { ("cpx", Modes.Immediate   ), new CpuInstruction( "6502",    0xe0, 2) },
            { ("sbc", Modes.IndX        ), new CpuInstruction( "6502",    0xe1, 2) },
            { ("cpx", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xe4, 2) },
            { ("sbc", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xe5, 2) },
            { ("inc", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xe6, 2) },
            { ("inx", Modes.Implied     ), new CpuInstruction( "6502",    0xe8) },
            { ("sbc", Modes.Immediate   ), new CpuInstruction( "6502",    0xe9, 2) },
            { ("nop", Modes.Implied     ), new CpuInstruction( "6502",    0xea) },
            { ("cpx", Modes.Absolute    ), new CpuInstruction( "6502",    0xec, 3) },
            { ("sbc", Modes.Absolute    ), new CpuInstruction( "6502",    0xed, 3) },
            { ("inc", Modes.Absolute    ), new CpuInstruction( "6502",    0xee, 3) },
            { ("beq", Modes.Relative    ), new CpuInstruction( "6502",    0xf0, 2) },
            { ("sbc", Modes.IndY        ), new CpuInstruction( "6502",    0xf1, 2) },
            { ("sbc", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0xf5, 2) },
            { ("inc", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0xf6, 2) },
            { ("sed", Modes.Implied     ), new CpuInstruction( "6502",    0xf8) },
            { ("sbc", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0xf9, 3) },
            { ("sbc", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0xfd, 3) },
            { ("inc", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0xfe, 3) },
        };
        static readonly Dictionary<(string Mnem, Modes Mode), CpuInstruction> s_opcodes65C02 = 
            new Dictionary<(string Mnem, Modes Mode), CpuInstruction>()
        {
            { ("tsb", Modes.ZeroPage    ), new CpuInstruction( "65C02",   0x04, 2) },
            { ("tsb", Modes.Absolute    ), new CpuInstruction( "65C02",   0x0c, 3) },
            { ("ora", Modes.IndZp       ), new CpuInstruction( "65C02",   0x12, 2) },
            { ("trb", Modes.ZeroPage    ), new CpuInstruction( "65C02",   0x14, 2) },
            { ("inc", Modes.Implied     ), new CpuInstruction( "65C02",   0x1a) },
            { ("trb", Modes.Absolute    ), new CpuInstruction( "65C02",   0x1c, 3) },
            { ("and", Modes.IndZp       ), new CpuInstruction( "65C02",   0x32, 2) },
            { ("bit", Modes.ZeroPageX   ), new CpuInstruction( "65C02",   0x34, 2) },
            { ("dec", Modes.Implied     ), new CpuInstruction( "65C02",   0x3a) },
            { ("bit", Modes.AbsoluteX   ), new CpuInstruction( "65C02",   0x3c, 3) },
            { ("eor", Modes.IndZp       ), new CpuInstruction( "65C02",   0x52, 2) },
            { ("phy", Modes.Implied     ), new CpuInstruction( "65C02",   0x5a) },
            { ("stz", Modes.ZeroPage    ), new CpuInstruction( "65C02",   0x64, 2) },
            { ("adc", Modes.IndZp       ), new CpuInstruction( "65C02",   0x72, 2) },
            { ("stz", Modes.ZeroPageX   ), new CpuInstruction( "65C02",   0x74, 2) },
            { ("ply", Modes.Implied     ), new CpuInstruction( "65C02",   0x7a) },
            { ("jmp", Modes.IndAbsX     ), new CpuInstruction( "65C02",   0x7c, 3) },
            { ("bra", Modes.Relative    ), new CpuInstruction( "65C02",   0x80, 2) },
            { ("bit", Modes.Immediate   ), new CpuInstruction( "65C02",   0x89, 2) },
            { ("sta", Modes.IndZp       ), new CpuInstruction( "65C02",   0x92, 2) },
            { ("stz", Modes.Absolute    ), new CpuInstruction( "65C02",   0x9c, 3) },
            { ("stz", Modes.AbsoluteX   ), new CpuInstruction( "65C02",   0x9e, 3) },
            { ("lda", Modes.IndZp       ), new CpuInstruction( "65C02",   0xb2, 2) },
            { ("cmp", Modes.IndZp       ), new CpuInstruction( "65C02",   0xd2, 2) },
            { ("phx", Modes.Implied     ), new CpuInstruction( "65C02",   0xda) },
            { ("sbc", Modes.IndZp       ), new CpuInstruction( "65C02",   0xf2, 2) },
            { ("plx", Modes.Implied     ), new CpuInstruction( "65C02",   0xfa) },
        };
        static readonly Dictionary<(string Mnem, Modes Mode), CpuInstruction> s_opcodesW65C02 = 
            new Dictionary<(string Mnem, Modes Mode), CpuInstruction>()
        {
            { ("wai", Modes.Implied     ), new CpuInstruction( "W65C02",  0xcb) },
            { ("stp", Modes.Implied     ), new CpuInstruction( "W65C02",  0xdb) }
        };
        static readonly Dictionary<(string Mnem, Modes Mode), CpuInstruction> s_opcodesR65C02 = 
            new Dictionary<(string Mnem, Modes Mode), CpuInstruction>()
        {
            { ("rmb", Modes.Zp0         ), new CpuInstruction( "R65C02",  0x07, 2) },
            { ("bbr", Modes.ThreeOpRel0 ), new CpuInstruction( "R65C02",  0x0f, 3) },
            { ("rmb", Modes.Zp1         ), new CpuInstruction( "R65C02",  0x17, 2) },
            { ("bbr", Modes.ThreeOpRel1 ), new CpuInstruction( "R65C02",  0x1f, 3) },
            { ("rmb", Modes.Zp2         ), new CpuInstruction( "R65C02",  0x27, 2) },
            { ("bbr", Modes.ThreeOpRel2 ), new CpuInstruction( "R65C02",  0x2f, 3) },
            { ("rmb", Modes.Zp3         ), new CpuInstruction( "R65C02",  0x37, 2) },
            { ("bbr", Modes.ThreeOpRel3 ), new CpuInstruction( "R65C02",  0x3f, 3) },
            { ("rmb", Modes.Zp4         ), new CpuInstruction( "R65C02",  0x47, 2) },
            { ("bbr", Modes.ThreeOpRel4 ), new CpuInstruction( "R65C02",  0x4f, 3) },
            { ("rmb", Modes.Zp5         ), new CpuInstruction( "R65C02",  0x57, 2) },
            { ("bbr", Modes.ThreeOpRel5 ), new CpuInstruction( "R65C02",  0x5f, 3) },
            { ("rmb", Modes.Zp6         ), new CpuInstruction( "R65C02",  0x67, 2) },
            { ("bbr", Modes.ThreeOpRel6 ), new CpuInstruction( "R65C02",  0x6f, 3) },
            { ("rmb", Modes.Zp7         ), new CpuInstruction( "R65C02",  0x77, 2) },
            { ("bbr", Modes.ThreeOpRel7 ), new CpuInstruction( "R65C02",  0x7f, 3) },
            { ("smb", Modes.Zp0         ), new CpuInstruction( "R65C02",  0x87, 2) },
            { ("bbs", Modes.ThreeOpRel  ), new CpuInstruction( "R65C02",  0x8f, 3) },
            { ("smb", Modes.Zp1         ), new CpuInstruction( "R65C02",  0x97, 2) },
            { ("bbs", Modes.ThreeOpRel1 ), new CpuInstruction( "R65C02",  0x9f, 3) },
            { ("smb", Modes.Zp2         ), new CpuInstruction( "R65C02",  0xa7, 2) },
            { ("bbs", Modes.ThreeOpRel2 ), new CpuInstruction( "R65C02",  0xaf, 3) },
            { ("smb", Modes.Zp3         ), new CpuInstruction( "R65C02",  0xb7, 2) },
            { ("bbs", Modes.ThreeOpRel3 ), new CpuInstruction( "R65C02",  0xbf, 3) },
            { ("smb", Modes.Zp4         ), new CpuInstruction( "R65C02",  0xc7, 2) },
            { ("bbs", Modes.ThreeOpRel4 ), new CpuInstruction( "R65C02",  0xcf, 3) },
            { ("smb", Modes.Zp5         ), new CpuInstruction( "R65C02",  0xd7, 2) },
            { ("bbs", Modes.ThreeOpRel5 ), new CpuInstruction( "R65C02",  0xdf, 3) },
            { ("smb", Modes.Zp6         ), new CpuInstruction( "R65C02",  0xe7, 2) },
            { ("bbs", Modes.ThreeOpRel6 ), new CpuInstruction( "R65C02",  0xef, 3) },
            { ("smb", Modes.Zp7         ), new CpuInstruction( "R65C02",  0xf7, 2) },
            { ("bbs", Modes.ThreeOpRel7 ), new CpuInstruction( "R65C02",  0xff, 3) },
        };
        static readonly Dictionary<(string Mnem, Modes Mode), CpuInstruction> s_opcodesHuC6280 = 
            new Dictionary<(string Mnem, Modes Mode), CpuInstruction>()
        {
            { ("sxy", Modes.Implied     ), new CpuInstruction( "HuC6280", 0x03) },
            { ("ora", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0x12, 3) },
            { ("st1", Modes.Immediate   ), new CpuInstruction( "HuC6280", 0x13, 2) },
            { ("sax", Modes.Implied     ), new CpuInstruction( "HuC6280", 0x23) },
            { ("st2", Modes.Immediate   ), new CpuInstruction( "HuC6280", 0x23, 2) },
            { ("and", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0x32, 3) },
            { ("say", Modes.Implied     ), new CpuInstruction( "HuC6280", 0x43) },
            { ("tma", Modes.Immediate   ), new CpuInstruction( "HuC6280", 0x43, 2) },
            { ("eor", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0x52, 3) },
            { ("tam", Modes.Immediate   ), new CpuInstruction( "HuC6280", 0x53, 2) },
            { ("csl", Modes.Implied     ), new CpuInstruction( "HuC6280", 0x54) },
            { ("cla", Modes.Implied     ), new CpuInstruction( "HuC6280", 0x62) },
            { ("adc", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0x72, 3) },
            { ("tii", Modes.ThreeOpAbs  ), new CpuInstruction( "HuC6280", 0x73, 7) },
            { ("clx", Modes.Implied     ), new CpuInstruction( "HuC6280", 0x82) },
            { ("tst", Modes.TestBitZp   ), new CpuInstruction( "HuC6280", 0x83, 3) },
            { ("sta", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0x92, 3) },
            { ("tst", Modes.TestBitZpX  ), new CpuInstruction( "HuC6280", 0x93, 3) },
            { ("tst", Modes.TestBitAbs  ), new CpuInstruction( "HuC6280", 0xa3, 4) },
            { ("lda", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0xb2, 3) },
            { ("tst", Modes.TestBitAbsX ), new CpuInstruction( "HuC6280", 0xb3, 4) },
            { ("cly", Modes.Implied     ), new CpuInstruction( "HuC6280", 0xc2) },
            { ("tdd", Modes.ThreeOpAbs  ), new CpuInstruction( "HuC6280", 0xc3, 7) },
            { ("cmp", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0xd2, 3) },
            { ("tin", Modes.ThreeOpAbs  ), new CpuInstruction( "HuC6280", 0xd3, 7) },
            { ("csh", Modes.Implied     ), new CpuInstruction( "HuC6280", 0xd4) },
            { ("tia", Modes.ThreeOpAbs  ), new CpuInstruction( "HuC6280", 0xe3, 7) },
            { ("sbc", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0xf2, 3) },
            { ("tai", Modes.ThreeOpAbs  ), new CpuInstruction( "HuC6280", 0xf3, 7) },
            { ("set", Modes.Implied     ), new CpuInstruction( "HuC6280", 0xf4) }
        };
        static readonly Dictionary<(string Mnem, Modes Mode), CpuInstruction> s_opcodes65CE02 = 
            new Dictionary<(string Mnem, Modes Mode), CpuInstruction>()
        {
            { ("cle", Modes.Implied     ), new CpuInstruction( "65CE02",  0x03) },
            { ("see", Modes.Implied     ), new CpuInstruction( "65CE02",  0x04) },
            { ("tsy", Modes.Implied     ), new CpuInstruction( "65CE02",  0x0b) },
            { ("ora", Modes.IndZ        ), new CpuInstruction( "65CE02",  0x12, 2) },
            { ("bpl", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0x13, 3) },
            { ("inz", Modes.Implied     ), new CpuInstruction( "65CE02",  0x1b) },
            { ("jsr", Modes.IndAbs      ), new CpuInstruction( "65CE02",  0x22, 3) },
            { ("jsr", Modes.IndAbsX     ), new CpuInstruction( "65CE02",  0x23, 3) },
            { ("tys", Modes.Implied     ), new CpuInstruction( "65CE02",  0x2b) },
            { ("and", Modes.IndZ        ), new CpuInstruction( "65CE02",  0x32, 2) },
            { ("bmi", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0x33, 3) },
            { ("dez", Modes.Implied     ), new CpuInstruction( "65CE02",  0x3b) },
            { ("neg", Modes.Implied     ), new CpuInstruction( "65CE02",  0x43) },
            { ("asr", Modes.Implied     ), new CpuInstruction( "65CE02",  0x44) },
            { ("asr", Modes.ZeroPage    ), new CpuInstruction( "65CE02",  0x44, 2) },
            { ("taz", Modes.Implied     ), new CpuInstruction( "65CE02",  0x4b) },
            { ("eor", Modes.IndZ        ), new CpuInstruction( "65CE02",  0x52, 2) },
            { ("bvc", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0x53, 3) },
            { ("asr", Modes.ZeroPageX   ), new CpuInstruction( "65CE02",  0x54, 2) },
            { ("tab", Modes.Implied     ), new CpuInstruction( "65CE02",  0x5b) },
            { ("map", Modes.Implied     ), new CpuInstruction( "65CE02",  0x5c) },
            { ("rtn", Modes.Implied     ), new CpuInstruction( "65CE02",  0x63) },
            { ("bsr", Modes.Absolute    ), new CpuInstruction( "65CE02",  0x63, 3) },
            { ("tza", Modes.Implied     ), new CpuInstruction( "65CE02",  0x6b) },
            { ("adc", Modes.IndZ        ), new CpuInstruction( "65CE02",  0x72, 2) },
            { ("bvs", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0x73, 3) },
            { ("tba", Modes.Implied     ), new CpuInstruction( "65CE02",  0x7b) },
            { ("sta", Modes.IndSp       ), new CpuInstruction( "65CE02",  0x82, 2) },
            { ("bra", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0x83, 3) },
            { ("sty", Modes.AbsoluteX   ), new CpuInstruction( "65CE02",  0x8b, 3) },
            { ("sta", Modes.IndZ        ), new CpuInstruction( "65CE02",  0x92, 2) },
            { ("bcc", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0x93, 3) },
            { ("blt", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0x93, 3) },
            { ("stx", Modes.AbsoluteY   ), new CpuInstruction( "65CE02",  0x9b, 3) },
            { ("ldz", Modes.Immediate   ), new CpuInstruction( "65CE02",  0xa3, 2) },
            { ("ldz", Modes.Absolute    ), new CpuInstruction( "65CE02",  0xab, 3) },
            { ("lda", Modes.IndZ        ), new CpuInstruction( "65CE02",  0xb2, 2) },
            { ("bcs", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0xb3, 3) },
            { ("bge", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0xb3, 3) },
            { ("ldz", Modes.AbsoluteX   ), new CpuInstruction( "65CE02",  0xbb, 3) },
            { ("cpz", Modes.Immediate   ), new CpuInstruction( "65CE02",  0xc2, 2) },
            { ("dew", Modes.ZeroPage    ), new CpuInstruction( "65CE02",  0xc3, 2) },
            { ("asw", Modes.Absolute    ), new CpuInstruction( "65CE02",  0xcb, 3) },
            { ("cmp", Modes.IndZ        ), new CpuInstruction( "65CE02",  0xd2, 2) },
            { ("bne", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0xd3, 3) },
            { ("cpz", Modes.ZeroPage    ), new CpuInstruction( "65CE02",  0xd4, 2) },
            { ("phz", Modes.Implied     ), new CpuInstruction( "65CE02",  0xdb) },
            { ("cpz", Modes.Absolute    ), new CpuInstruction( "65CE02",  0xdc, 3) },
            { ("lda", Modes.IndSp       ), new CpuInstruction( "65CE02",  0xe2, 2) },
            { ("inw", Modes.ZeroPage    ), new CpuInstruction( "65CE02",  0xe3, 2) },
            { ("row", Modes.Absolute    ), new CpuInstruction( "65CE02",  0xeb, 3) },
            { ("sbc", Modes.IndZ        ), new CpuInstruction( "65CE02",  0xf2, 2) },
            { ("beq", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0xf3, 3) },
            { ("phw", Modes.ImmAbs      ), new CpuInstruction( "65CE02",  0xf4, 3) },
            { ("plz", Modes.Implied     ), new CpuInstruction( "65CE02",  0xfb) },
            { ("phw", Modes.Absolute    ), new CpuInstruction( "65CE02",  0xfc, 2) }
        };
        static readonly Dictionary<(string Mnem, Modes Mode), CpuInstruction> s_opcodes65816 = 
            new Dictionary<(string Mnem, Modes Mode), CpuInstruction>()
        {
            { ("cop", Modes.Implied     ), new CpuInstruction( "65816",   0x03) },
            { ("cop", Modes.Immediate   ), new CpuInstruction( "65816",   0x02, 2) },
            { ("ora", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0x03, 2) },
            { ("ora", Modes.Dir         ), new CpuInstruction( "65816",   0x07, 2) },
            { ("phd", Modes.Implied     ), new CpuInstruction( "65816",   0x0b) },
            { ("ora", Modes.Long        ), new CpuInstruction( "65816",   0x0f, 4) },
            { ("ora", Modes.IndS        ), new CpuInstruction( "65816",   0x13, 2) },
            { ("ora", Modes.DirY        ), new CpuInstruction( "65816",   0x17, 2) },
            { ("tcs", Modes.Implied     ), new CpuInstruction( "65816",   0x1b) },
            { ("ora", Modes.LongX       ), new CpuInstruction( "65816",   0x1f, 4) },
            { ("jsl", Modes.Long        ), new CpuInstruction( "65816",   0x22, 4) },
            { ("jsr", Modes.Long        ), new CpuInstruction( "65816",   0x22, 4) },
            { ("and", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0x23, 2) },
            { ("and", Modes.Dir         ), new CpuInstruction( "65816",   0x27, 2) },
            { ("pld", Modes.Implied     ), new CpuInstruction( "65816",   0x2b) },
            { ("and", Modes.Long        ), new CpuInstruction( "65816",   0x2f, 4) },
            { ("and", Modes.IndS        ), new CpuInstruction( "65816",   0x33, 2) },
            { ("and", Modes.DirY        ), new CpuInstruction( "65816",   0x37, 2) },
            { ("tsc", Modes.Implied     ), new CpuInstruction( "65816",   0x3b) },
            { ("and", Modes.LongX       ), new CpuInstruction( "65816",   0x3f, 4) },
            { ("wdm", Modes.Implied     ), new CpuInstruction( "65816",   0x43) },
            { ("eor", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0x43, 2) },
            { ("mvp", Modes.TwoOperand  ), new CpuInstruction( "65816",   0x44, 3) },
            { ("eor", Modes.Dir         ), new CpuInstruction( "65816",   0x47, 2) },
            { ("phk", Modes.Implied     ), new CpuInstruction( "65816",   0x4b) },
            { ("eor", Modes.Long        ), new CpuInstruction( "65816",   0x4f, 4) },
            { ("eor", Modes.IndS        ), new CpuInstruction( "65816",   0x53, 2) },
            { ("mvn", Modes.TwoOperand  ), new CpuInstruction( "65816",   0x54, 3) },
            { ("eor", Modes.DirY        ), new CpuInstruction( "65816",   0x57, 2) },
            { ("tcd", Modes.Implied     ), new CpuInstruction( "65816",   0x5b) },
            { ("jml", Modes.Long        ), new CpuInstruction( "65816",   0x5c, 4) },
            { ("jmp", Modes.Long        ), new CpuInstruction( "65816",   0x5c, 4) },
            { ("eor", Modes.LongX       ), new CpuInstruction( "65816",   0x5f, 4) },
            { ("per", Modes.RelativeAbs ), new CpuInstruction( "65816",   0x62, 3) },
            { ("adc", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0x63, 2) },
            { ("adc", Modes.Dir         ), new CpuInstruction( "65816",   0x67, 2) },
            { ("rtl", Modes.Implied     ), new CpuInstruction( "65816",   0x6b) },
            { ("adc", Modes.Long        ), new CpuInstruction( "65816",   0x6f, 4) },
            { ("adc", Modes.IndS        ), new CpuInstruction( "65816",   0x73, 2) },
            { ("adc", Modes.DirY        ), new CpuInstruction( "65816",   0x77, 2) },
            { ("tdc", Modes.Implied     ), new CpuInstruction( "65816",   0x7b) },
            { ("adc", Modes.LongX       ), new CpuInstruction( "65816",   0x7f, 4) },
            { ("brl", Modes.RelativeAbs ), new CpuInstruction( "65816",   0x82, 3) },
            { ("sta", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0x83, 2) },
            { ("sta", Modes.Dir         ), new CpuInstruction( "65816",   0x87, 2) },
            { ("phb", Modes.Implied     ), new CpuInstruction( "65816",   0x8b) },
            { ("sta", Modes.Long        ), new CpuInstruction( "65816",   0x8f, 4) },
            { ("sta", Modes.IndS        ), new CpuInstruction( "65816",   0x93, 2) },
            { ("sta", Modes.DirY        ), new CpuInstruction( "65816",   0x97, 2) },
            { ("txy", Modes.Implied     ), new CpuInstruction( "65816",   0x9b) },
            { ("sta", Modes.LongX       ), new CpuInstruction( "65816",   0x9f, 4) },
            { ("lda", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0xa3, 2) },
            { ("lda", Modes.Dir         ), new CpuInstruction( "65816",   0xa7, 2) },
            { ("plb", Modes.Implied     ), new CpuInstruction( "65816",   0xab) },
            { ("lda", Modes.Long        ), new CpuInstruction( "65816",   0xaf, 4) },
            { ("lda", Modes.IndS        ), new CpuInstruction( "65816",   0xb3, 2) },
            { ("lda", Modes.DirY        ), new CpuInstruction( "65816",   0xb7, 2) },
            { ("tyx", Modes.Implied     ), new CpuInstruction( "65816",   0xbb) },
            { ("lda", Modes.LongX       ), new CpuInstruction( "65816",   0xbf, 4) },
            { ("rep", Modes.Immediate   ), new CpuInstruction( "65816",   0xc2, 2) },
            { ("cmp", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0xc3, 2) },
            { ("cmp", Modes.Dir         ), new CpuInstruction( "65816",   0xc7, 2) },
            { ("cmp", Modes.Long        ), new CpuInstruction( "65816",   0xcf, 4) },
            { ("cmp", Modes.IndS        ), new CpuInstruction( "65816",   0xd3, 2) },
            { ("pei", Modes.IndZp       ), new CpuInstruction( "65816",   0xd4, 2) },
            { ("cmp", Modes.DirY        ), new CpuInstruction( "65816",   0xd7, 2) },
            { ("jmp", Modes.DirAbs      ), new CpuInstruction( "65816",   0xdc, 3) },
            { ("cmp", Modes.LongX       ), new CpuInstruction( "65816",   0xdf, 4) },
            { ("sep", Modes.Immediate   ), new CpuInstruction( "65816",   0xe2, 2) },
            { ("sbc", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0xe3, 2) },
            { ("sbc", Modes.Dir         ), new CpuInstruction( "65816",   0xe7, 2) },
            { ("xba", Modes.Implied     ), new CpuInstruction( "65816",   0xeb) },
            { ("sbc", Modes.Long        ), new CpuInstruction( "65816",   0xef, 4) },
            { ("sbc", Modes.IndS        ), new CpuInstruction( "65816",   0xf3, 2) },
            { ("pea", Modes.ImmAbs      ), new CpuInstruction( "65816",   0xf4, 3) },
            { ("pea", Modes.Absolute    ), new CpuInstruction( "65816",   0xf4, 3) }, // both are acceptable
            { ("sbc", Modes.DirY        ), new CpuInstruction( "65816",   0xf7, 2) },
            { ("xce", Modes.Implied     ), new CpuInstruction( "65816",   0xfb) },
            { ("sbc", Modes.LongX       ), new CpuInstruction( "65816",   0xff, 4) },
        };
        static readonly Dictionary<(string Mnem, Modes Mode), CpuInstruction> s_opcodes6502i = 
            new Dictionary<(string Mnem, Modes Mode), CpuInstruction>()
        {
            { ("jam", Modes.Implied     ), new CpuInstruction( "6502i",   0x03) },
            { ("slo", Modes.IndX        ), new CpuInstruction( "6502i",   0x03, 2) },
            { ("dop", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0x04, 2) },
            { ("slo", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0x07, 2) },
            { ("top", Modes.Implied     ), new CpuInstruction( "6502i",   0x0c) },
            { ("top", Modes.Absolute    ), new CpuInstruction( "6502i",   0x0c, 3) },
            { ("slo", Modes.Absolute    ), new CpuInstruction( "6502i",   0x0f, 3) },
            { ("stp", Modes.Implied     ), new CpuInstruction( "6502i",   0x13) },
            { ("slo", Modes.IndY        ), new CpuInstruction( "6502i",   0x13, 2) },
            { ("dop", Modes.ZeroPageX   ), new CpuInstruction( "6502i",   0x14, 2) },
            { ("slo", Modes.ZeroPageX   ), new CpuInstruction( "6502i",   0x17, 2) },
            { ("slo", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0x1b, 3) },
            { ("slo", Modes.AbsoluteX   ), new CpuInstruction( "6502i",   0x1f, 3) },
            { ("rla", Modes.IndX        ), new CpuInstruction( "6502i",   0x23, 2) },
            { ("rla", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0x27, 2) },
            { ("anc", Modes.Immediate   ), new CpuInstruction( "6502i",   0x2b, 2) },
            { ("rla", Modes.Absolute    ), new CpuInstruction( "6502i",   0x2f, 3) },
            { ("rla", Modes.IndY        ), new CpuInstruction( "6502i",   0x33, 2) },
            { ("rla", Modes.ZeroPageX   ), new CpuInstruction( "6502i",   0x37, 2) },
            { ("rla", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0x3b, 3) },
            { ("rla", Modes.AbsoluteX   ), new CpuInstruction( "6502i",   0x3f, 3) },
            { ("sre", Modes.IndX        ), new CpuInstruction( "6502i",   0x43, 2) },
            { ("sre", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0x47, 2) },
            { ("asr", Modes.Immediate   ), new CpuInstruction( "6502i",   0x4b, 2) },
            { ("sre", Modes.Absolute    ), new CpuInstruction( "6502i",   0x4f, 3) },
            { ("sre", Modes.IndY        ), new CpuInstruction( "6502i",   0x53, 2) },
            { ("sre", Modes.ZeroPageX   ), new CpuInstruction( "6502i",   0x57, 2) },
            { ("sre", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0x5b, 3) },
            { ("sre", Modes.AbsoluteX   ), new CpuInstruction( "6502i",   0x5f, 3) },
            { ("rra", Modes.IndX        ), new CpuInstruction( "6502i",   0x63, 2) },
            { ("rra", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0x67, 2) },
            { ("arr", Modes.Immediate   ), new CpuInstruction( "6502i",   0x6b, 2) },
            { ("rra", Modes.Absolute    ), new CpuInstruction( "6502i",   0x6f, 3) },
            { ("rra", Modes.IndY        ), new CpuInstruction( "6502i",   0x73, 2) },
            { ("rra", Modes.ZeroPageX   ), new CpuInstruction( "6502i",   0x77, 2) },
            { ("rra", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0x7b, 3) },
            { ("rra", Modes.AbsoluteX   ), new CpuInstruction( "6502i",   0x7f, 3) },
            { ("dop", Modes.Implied     ), new CpuInstruction( "6502i",   0x80) },
            { ("dop", Modes.Immediate   ), new CpuInstruction( "6502i",   0x80, 2) },
            { ("sax", Modes.IndX        ), new CpuInstruction( "6502i",   0x83, 2) },
            { ("sax", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0x87, 2) },
            { ("ane", Modes.Immediate   ), new CpuInstruction( "6502i",   0x8b, 2) },
            { ("sax", Modes.Absolute    ), new CpuInstruction( "6502i",   0x8f, 3) },
            { ("sha", Modes.IndY        ), new CpuInstruction( "6502i",   0x93, 2) },
            { ("sax", Modes.ZeroPageY   ), new CpuInstruction( "6502i",   0x97, 2) },
            { ("tas", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0x9b, 3) },
            { ("shy", Modes.AbsoluteX   ), new CpuInstruction( "6502i",   0x9c, 3) },
            { ("shx", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0x9e, 3) },
            { ("sha", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0x9f, 3) },
            { ("lax", Modes.IndX        ), new CpuInstruction( "6502i",   0xa3, 2) },
            { ("lax", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0xa7, 2) },
            { ("lax", Modes.Absolute    ), new CpuInstruction( "6502i",   0xaf, 3) },
            { ("lax", Modes.IndY        ), new CpuInstruction( "6502i",   0xb3, 2) },
            { ("lax", Modes.ZeroPageY   ), new CpuInstruction( "6502i",   0xb7, 2) },
            { ("las", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0xbb, 3) },
            { ("lax", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0xbf, 3) },
            { ("dcp", Modes.IndX        ), new CpuInstruction( "6502i",   0xc3, 2) },
            { ("dcp", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0xc7, 2) },
            { ("sax", Modes.Immediate   ), new CpuInstruction( "6502i",   0xcb, 2) },
            { ("dcp", Modes.Absolute    ), new CpuInstruction( "6502i",   0xcf, 3) },
            { ("dcp", Modes.IndY        ), new CpuInstruction( "6502i",   0xd3, 2) },
            { ("dcp", Modes.ZeroPageX   ), new CpuInstruction( "6502i",   0xd7, 2) },
            { ("dcp", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0xdb, 3) },
            { ("dcp", Modes.AbsoluteX   ), new CpuInstruction( "6502i",   0xdf, 3) },
            { ("isb", Modes.IndX        ), new CpuInstruction( "6502i",   0xe3, 2) },
            { ("isb", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0xe7, 2) },
            { ("isb", Modes.Absolute    ), new CpuInstruction( "6502i",   0xef, 3) },
            { ("isb", Modes.IndY        ), new CpuInstruction( "6502i",   0xf3, 2) },
            { ("isb", Modes.ZeroPageX   ), new CpuInstruction( "6502i",   0xf7, 2) },
            { ("isb", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0xfb, 3) },
            { ("isb", Modes.AbsoluteX   ), new CpuInstruction( "6502i",   0xff, 3) },
        };
        static readonly IReadOnlyDictionary<Modes, string> s_modeFormats = new Dictionary<Modes, string>
        {
            { Modes.Implied,        string.Empty                },
            { Modes.Immediate,      "#${0:x2}"                  },
            { Modes.ImmAbs,         "#${0:x4}"                  },
            { Modes.ZeroPage,       "${0:x2}"                   },
            { Modes.ZeroPageS,      "${0:x2},s"                 },
            { Modes.ZeroPageX,      "${0:x2},x"                 },
            { Modes.ZeroPageY,      "${0:x2},y"                 },
            { Modes.Relative,       "${0:x4}"                   },
            { Modes.RelativeAbs,    "${0:x4}"                   },
            { Modes.Absolute,       "${0:x4}"                   },
            { Modes.AbsoluteX,      "${0:x4},x"                 },
            { Modes.AbsoluteY,      "${0:x4},y"                 },
            { Modes.Long,           "${0:x6}"                   },
            { Modes.LongX,          "${0:x6},x"                 },
            { Modes.IndZp,          "(${0:x2})"                 },
            { Modes.IndS,           "(${0:x2},s),y"             },
            { Modes.IndSp,          "(${0:x2},sp),y"            },
            { Modes.IndX,           "(${0:x2},x)"               },
            { Modes.IndY,           "(${0:x2}),y"               },
            { Modes.IndZ,           "(${0:x2}),z"               },
            { Modes.IndAbs,         "(${0:x4})"                 },
            { Modes.IndAbsX,        "(${0:x4},x)"               },
            { Modes.Dir,            "[${0:x2}]"                 },
            { Modes.DirY,           "[${0:x2}],y"               },
            { Modes.DirAbs,         "[${0:x4}]"                 },
            { Modes.Zp0,            "0,${0:x2}"                 },
            { Modes.Zp1,            "1,${0:x2}"                 },
            { Modes.Zp2,            "2,${0:x2}"                 },
            { Modes.Zp3,            "3,${0:x2}"                 },
            { Modes.Zp4,            "4,${0:x2}"                 },
            { Modes.Zp5,            "5,${0:x2}"                 },
            { Modes.Zp6,            "6,${0:x2}"                 },
            { Modes.Zp7,            "7,${0:x2}"                 },
            { Modes.TwoOperand,     "${0:x2},${1:x2}"           },
            { Modes.TestBitZp,      "#${0:x2},${1:x2}"          },
            { Modes.TestBitZpX,     "#${0:x2},${1:x2},x"        },
            { Modes.TestBitAbs,     "#${0:x2},${1:x4}"          },
            { Modes.TestBitAbsX,    "#${0:x2},${1:x4},x"        },
            { Modes.ThreeOpRel0,    "0,${0:x2},${1:x4}"         },
            { Modes.ThreeOpRel1,    "1,${0:x2},${1:x4}"         },
            { Modes.ThreeOpRel2,    "2,${0:x2},${1:x4}"         },
            { Modes.ThreeOpRel3,    "3,${0:x2},${1:x4}"         },
            { Modes.ThreeOpRel4,    "4,${0:x2},${1:x4}"         },
            { Modes.ThreeOpRel5,    "5,${0:x2},${1:x4}"         },
            { Modes.ThreeOpRel6,    "6,${0:x2},${1:x4}"         },
            { Modes.ThreeOpRel7,    "7,${0:x2},${1:x4}"         },
            { Modes.ThreeOpAbs,     "${0:x4},${1:x4},${2:x4}"   }
        };
        static readonly IReadOnlyDictionary<string, string> s_pseudoBranchTranslations = 
            new Dictionary<string, string>
        {
            { "jcc", "bcs" },
            { "jcs", "bcc" },
            { "jeq", "bne" },
            { "jmi", "bpl" },
            { "jne", "beq" },
            { "jvc", "bvs" },
            { "jvs", "bvc" }
        };

        #endregion

        #region Properties

        /// <summary>
        /// Gets an array of the 65xx-based CPUs whose mnemonics this assembler recognizes.
        /// </summary>
        /// <value>The supported CPUs.</value>
        public static string[] SupportedCPUs { get; } =
        {
            "6502",
            "6502i",
            "65C02",
            "HuC6280",
            "R65C02",
            "65CE02",
            "65816",
            "65CS02"
        };

        #endregion

    }
}