//-----------------------------------------------------------------------------
// Copyright (c) 2017-2020 informedcitizenry <informedcitizenry@gmail.com>
//
// Licensed under the MIT license. See LICENSE for full license information.
// 
//-----------------------------------------------------------------------------

//using DotNetAsm;
using System.Collections.Generic;

namespace Core6502DotNet.m6502
{
    /// <summary>
    /// A line assembler that will assemble into 6502 instructions.
    /// </summary>
    public sealed partial class Asm6502 : AssemblerBase
    {
        enum Modes
        {
            Implied      = 0b0000000000000000000,
            ZeroPage     = 0b0000000000000000001,
            Absolute     = 0b0000000000000000011,
            Long         = 0b0000000000000000111,
            SizeMask     = 0b0000000000000000111,
            Indirect     = 0b0000000000000001000,
            DirectPage   = 0b0000000000000010000,
            IndexedX     = 0b0000000000000100000,
            InnerX       = 0b0000000000001000000,
            IndexedY     = 0b0000000000010000000,
            IndexedZ     = 0b0000000000100000000,
            IndexedS     = 0b0000000001000000000,
            IndexedSp    = 0b0000000010000000000,
            TwoOperand   = 0b0000000100000000001,
            ThreeOperand = 0b0000001000000000001,
            Bit1         = 0b0000010000000000000,
            Bit2         = 0b0000100000000000000,
            Bit3         = 0b0000110000000000000,
            Bit4         = 0b0001000000000000000,
            Bit5         = 0b0001010000000000000,
            Bit6         = 0b0001100000000000000,
            Bit7         = 0b0001110000000000000,
            Immediate    = 0b0010000000000000001,
            RelativeBit  = 0b0100000000000000000,
            Relative     = 0b0100000000000000001,
            MemModMask   = 0b0111111111111111000,
            ModeMask     = 0b0111111111111111111,
            ForceWidth   = 0b1000000000000000000,
            AbsoluteX    = Absolute     | IndexedX,
            AbsoluteY    = Absolute     | IndexedY,
            ZeroPageX    = ZeroPage     | IndexedX,
            ZeroPageY    = ZeroPage     | IndexedY,
            ZeroPageS    = ZeroPage     | IndexedS,
            LongX        = Long         | IndexedX,
            IndX         = ZeroPage     | InnerX    | Indirect,
            IndY         = ZeroPageY    | Indirect,
            IndZ         = ZeroPage     | Indirect  | IndexedZ,
            IndS         = IndY         | IndexedS,
            IndSp        = IndY         | IndexedSp,
            IndZp        = ZeroPage     | Indirect,
            IndAbs       = Absolute     | Indirect,
            IndAbsX      = Absolute     | Indirect  | InnerX,
            Dir          = ZeroPage     | DirectPage,
            DirAbs       = Absolute     | DirectPage,
            DirY         = Dir          | IndexedY,
            DirIndMask   = Indirect     | DirectPage,
            RelativeAbs  = Relative     | Absolute,
            ThreeOpRel   = ThreeOperand | Relative,
            ThreeOpAbs   = ThreeOperand | Absolute,
            Zp0          = TwoOperand,
            Zp1          = TwoOperand   | Bit1,
            Zp2          = TwoOperand   | Bit2,
            Zp3          = TwoOperand   | Bit3,
            Zp4          = TwoOperand   | Bit4,
            Zp5          = TwoOperand   | Bit5,
            Zp6          = TwoOperand   | Bit6,
            Zp7          = TwoOperand   | Bit7,
            ThreeOpRel0  = ThreeOpRel,
            ThreeOpRel1  = ThreeOpRel   | Bit1,
            ThreeOpRel2  = ThreeOpRel   | Bit2,
            ThreeOpRel3  = ThreeOpRel   | Bit3,
            ThreeOpRel4  = ThreeOpRel   | Bit4,
            ThreeOpRel5  = ThreeOpRel   | Bit5,
            ThreeOpRel6  = ThreeOpRel   | Bit6,
            ThreeOpRel7  = ThreeOpRel   | Bit7,
            ImmAbs       = Immediate    | Absolute,
            TestBitZp    = Immediate    | TwoOperand,
            TestBitAbs   = Immediate    | TwoOperand | Absolute,
            TestBitZpX   = Immediate    | TwoOperand | IndexedX,
            TestBitAbsX  = Immediate    | TwoOperand | Absolute | IndexedX,
            TestBitFlag  = TestBitZp    & MemModMask
        };
        #region Members
    
        string _cpu;
        bool _m16, _x16;
        Dictionary<MnemMode, CpuInstruction> _selectedInstructions;
        static double[] _evaled;
        static readonly Dictionary<MnemMode, CpuInstruction> _opcodes6502 = new Dictionary<MnemMode, CpuInstruction>()
        {
            { new MnemMode("brk", Modes.Implied     ), new CpuInstruction( "6502",    0x00) },
            { new MnemMode("ora", Modes.IndX        ), new CpuInstruction( "6502",    0x01, 2) },
            { new MnemMode("ora", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x05, 2) },
            { new MnemMode("asl", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x06, 2) },
            { new MnemMode("php", Modes.Implied     ), new CpuInstruction( "6502",    0x08) },
            { new MnemMode("ora", Modes.Immediate   ), new CpuInstruction( "6502",    0x09, 2) },
            { new MnemMode("asl", Modes.Implied     ), new CpuInstruction( "6502",    0x0a) },
            { new MnemMode("ora", Modes.Absolute    ), new CpuInstruction( "6502",    0x0d, 3) },
            { new MnemMode("asl", Modes.Absolute    ), new CpuInstruction( "6502",    0x0e, 3) },
            { new MnemMode("bpl", Modes.Relative    ), new CpuInstruction( "6502",    0x10, 2) },
            { new MnemMode("ora", Modes.IndY        ), new CpuInstruction( "6502",    0x11, 2) },
            { new MnemMode("ora", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x15, 2) },
            { new MnemMode("asl", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x16, 2) },
            { new MnemMode("clc", Modes.Implied     ), new CpuInstruction( "6502",    0x18) },
            { new MnemMode("ora", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0x19, 3) },
            { new MnemMode("top", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x1c, 3) },
            { new MnemMode("ora", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x1d, 3) },
            { new MnemMode("asl", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x1e, 3) },
            { new MnemMode("jsr", Modes.Absolute    ), new CpuInstruction( "6502",    0x20, 3) },
            { new MnemMode("and", Modes.IndX        ), new CpuInstruction( "6502",    0x21, 2) },
            { new MnemMode("bit", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x24, 2) },
            { new MnemMode("and", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x25, 2) },
            { new MnemMode("rol", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x26, 2) },
            { new MnemMode("plp", Modes.Implied     ), new CpuInstruction( "6502",    0x28) },
            { new MnemMode("and", Modes.Immediate   ), new CpuInstruction( "6502",    0x29, 2) },
            { new MnemMode("rol", Modes.Implied     ), new CpuInstruction( "6502",    0x2a) },
            { new MnemMode("bit", Modes.Absolute    ), new CpuInstruction( "6502",    0x2c, 3) },
            { new MnemMode("and", Modes.Absolute    ), new CpuInstruction( "6502",    0x2d, 3) },
            { new MnemMode("rol", Modes.Absolute    ), new CpuInstruction( "6502",    0x2e, 3) },
            { new MnemMode("bmi", Modes.Relative    ), new CpuInstruction( "6502",    0x30, 2) },
            { new MnemMode("and", Modes.IndY        ), new CpuInstruction( "6502",    0x31, 2) },
            { new MnemMode("and", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x35, 2) },
            { new MnemMode("rol", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x36, 2) },
            { new MnemMode("sec", Modes.Implied     ), new CpuInstruction( "6502",    0x38) },
            { new MnemMode("and", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0x39, 3) },
            { new MnemMode("and", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x3d, 3) },
            { new MnemMode("rol", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x3e, 3) },
            { new MnemMode("rti", Modes.Implied     ), new CpuInstruction( "6502",    0x40) },
            { new MnemMode("eor", Modes.IndX        ), new CpuInstruction( "6502",    0x41, 2) },
            { new MnemMode("eor", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x45, 2) },
            { new MnemMode("lsr", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x46, 2) },
            { new MnemMode("pha", Modes.Implied     ), new CpuInstruction( "6502",    0x48) },
            { new MnemMode("eor", Modes.Immediate   ), new CpuInstruction( "6502",    0x49, 2) },
            { new MnemMode("lsr", Modes.Implied     ), new CpuInstruction( "6502",    0x4a) },
            { new MnemMode("jmp", Modes.Absolute    ), new CpuInstruction( "6502",    0x4c, 3) },
            { new MnemMode("eor", Modes.Absolute    ), new CpuInstruction( "6502",    0x4d, 3) },
            { new MnemMode("lsr", Modes.Absolute    ), new CpuInstruction( "6502",    0x4e, 3) },
            { new MnemMode("bvc", Modes.Relative    ), new CpuInstruction( "6502",    0x50, 2) },
            { new MnemMode("eor", Modes.IndY        ), new CpuInstruction( "6502",    0x51, 2) },
            { new MnemMode("eor", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x55, 2) },
            { new MnemMode("lsr", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x56, 2) },
            { new MnemMode("cli", Modes.Implied     ), new CpuInstruction( "6502",    0x58) },
            { new MnemMode("eor", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0x59, 3) },
            { new MnemMode("eor", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x5d, 3) },
            { new MnemMode("lsr", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x5e, 3) },
            { new MnemMode("rts", Modes.Implied     ), new CpuInstruction( "6502",    0x60) },
            { new MnemMode("adc", Modes.IndX        ), new CpuInstruction( "6502",    0x61, 2) },
            { new MnemMode("adc", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x65, 2) },
            { new MnemMode("ror", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x66, 2) },
            { new MnemMode("pla", Modes.Implied     ), new CpuInstruction( "6502",    0x68) },
            { new MnemMode("adc", Modes.Immediate   ), new CpuInstruction( "6502",    0x69, 2) },
            { new MnemMode("ror", Modes.Implied     ), new CpuInstruction( "6502",    0x6a) },
            { new MnemMode("jmp", Modes.IndAbs      ), new CpuInstruction( "6502",    0x6c, 3) },
            { new MnemMode("adc", Modes.Absolute    ), new CpuInstruction( "6502",    0x6d, 3) },
            { new MnemMode("ror", Modes.Absolute    ), new CpuInstruction( "6502",    0x6e, 3) },
            { new MnemMode("bvs", Modes.Relative    ), new CpuInstruction( "6502",    0x70, 2) },
            { new MnemMode("adc", Modes.IndY        ), new CpuInstruction( "6502",    0x71, 2) },
            { new MnemMode("adc", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x75, 2) },
            { new MnemMode("ror", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x76, 2) },
            { new MnemMode("sei", Modes.Implied     ), new CpuInstruction( "6502",    0x78) },
            { new MnemMode("adc", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0x79, 3) },
            { new MnemMode("adc", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x7d, 3) },
            { new MnemMode("ror", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x7e, 3) },
            { new MnemMode("sta", Modes.IndX        ), new CpuInstruction( "6502",    0x81, 2) },
            { new MnemMode("sty", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x84, 2) },
            { new MnemMode("sta", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x85, 2) },
            { new MnemMode("stx", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x86, 2) },
            { new MnemMode("dey", Modes.Implied     ), new CpuInstruction( "6502",    0x88) },
            { new MnemMode("txa", Modes.Implied     ), new CpuInstruction( "6502",    0x8a) },
            { new MnemMode("sty", Modes.Absolute    ), new CpuInstruction( "6502",    0x8c, 3) },
            { new MnemMode("sta", Modes.Absolute    ), new CpuInstruction( "6502",    0x8d, 3) },
            { new MnemMode("stx", Modes.Absolute    ), new CpuInstruction( "6502",    0x8e, 3) },
            { new MnemMode("bcc", Modes.Relative    ), new CpuInstruction( "6502",    0x90, 2) },
            { new MnemMode("sta", Modes.IndY        ), new CpuInstruction( "6502",    0x91, 2) },
            { new MnemMode("sty", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x94, 2) },
            { new MnemMode("sta", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x95, 2) },
            { new MnemMode("stx", Modes.ZeroPageY   ), new CpuInstruction( "6502",    0x96, 2) },
            { new MnemMode("tya", Modes.Implied     ), new CpuInstruction( "6502",    0x98) },
            { new MnemMode("sta", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0x99, 3) },
            { new MnemMode("txs", Modes.Implied     ), new CpuInstruction( "6502",    0x9a) },
            { new MnemMode("sta", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x9d, 3) },
            { new MnemMode("ldy", Modes.Immediate   ), new CpuInstruction( "6502",    0xa0, 2) },
            { new MnemMode("lda", Modes.IndX        ), new CpuInstruction( "6502",    0xa1, 2) },
            { new MnemMode("ldx", Modes.Immediate   ), new CpuInstruction( "6502",    0xa2, 2) },
            { new MnemMode("ldy", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xa4, 2) },
            { new MnemMode("lda", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xa5, 2) },
            { new MnemMode("ldx", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xa6, 2) },
            { new MnemMode("tay", Modes.Implied     ), new CpuInstruction( "6502",    0xa8) },
            { new MnemMode("lda", Modes.Immediate   ), new CpuInstruction( "6502",    0xa9, 2) },
            { new MnemMode("tax", Modes.Implied     ), new CpuInstruction( "6502",    0xaa) },
            { new MnemMode("ldy", Modes.Absolute    ), new CpuInstruction( "6502",    0xac, 3) },
            { new MnemMode("lda", Modes.Absolute    ), new CpuInstruction( "6502",    0xad, 3) },
            { new MnemMode("ldx", Modes.Absolute    ), new CpuInstruction( "6502",    0xae, 3) },
            { new MnemMode("bcs", Modes.Relative    ), new CpuInstruction( "6502",    0xb0, 2) },
            { new MnemMode("lda", Modes.IndY        ), new CpuInstruction( "6502",    0xb1, 2) },
            { new MnemMode("ldy", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0xb4, 2) },
            { new MnemMode("lda", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0xb5, 2) },
            { new MnemMode("ldx", Modes.ZeroPageY   ), new CpuInstruction( "6502",    0xb6, 2) },
            { new MnemMode("clv", Modes.Implied     ), new CpuInstruction( "6502",    0xb8) },
            { new MnemMode("lda", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0xb9, 3) },
            { new MnemMode("tsx", Modes.Implied     ), new CpuInstruction( "6502",    0xba) },
            { new MnemMode("ldy", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0xbc, 3) },
            { new MnemMode("lda", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0xbd, 3) },
            { new MnemMode("ldx", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0xbe, 3) },
            { new MnemMode("cpy", Modes.Immediate   ), new CpuInstruction( "6502",    0xc0, 2) },
            { new MnemMode("cmp", Modes.IndX        ), new CpuInstruction( "6502",    0xc1, 2) },
            { new MnemMode("cpy", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xc4, 2) },
            { new MnemMode("cmp", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xc5, 2) },
            { new MnemMode("dec", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xc6, 2) },
            { new MnemMode("iny", Modes.Implied     ), new CpuInstruction( "6502",    0xc8) },
            { new MnemMode("cmp", Modes.Immediate   ), new CpuInstruction( "6502",    0xc9, 2) },
            { new MnemMode("dex", Modes.Implied     ), new CpuInstruction( "6502",    0xca) },
            { new MnemMode("cpy", Modes.Absolute    ), new CpuInstruction( "6502",    0xcc, 3) },
            { new MnemMode("cmp", Modes.Absolute    ), new CpuInstruction( "6502",    0xcd, 3) },
            { new MnemMode("dec", Modes.Absolute    ), new CpuInstruction( "6502",    0xce, 3) },
            { new MnemMode("bne", Modes.Relative    ), new CpuInstruction( "6502",    0xd0, 2) },
            { new MnemMode("cmp", Modes.IndY        ), new CpuInstruction( "6502",    0xd1, 2) },
            { new MnemMode("cmp", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0xd5, 2) },
            { new MnemMode("dec", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0xd6, 2) },
            { new MnemMode("cld", Modes.Implied     ), new CpuInstruction( "6502",    0xd8) },
            { new MnemMode("cmp", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0xd9, 3) },
            { new MnemMode("cmp", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0xdd, 3) },
            { new MnemMode("dec", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0xde, 3) },
            { new MnemMode("cpx", Modes.Immediate   ), new CpuInstruction( "6502",    0xe0, 2) },
            { new MnemMode("sbc", Modes.IndX        ), new CpuInstruction( "6502",    0xe1, 2) },
            { new MnemMode("cpx", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xe4, 2) },
            { new MnemMode("sbc", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xe5, 2) },
            { new MnemMode("inc", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xe6, 2) },
            { new MnemMode("inx", Modes.Implied     ), new CpuInstruction( "6502",    0xe8) },
            { new MnemMode("sbc", Modes.Immediate   ), new CpuInstruction( "6502",    0xe9, 2) },
            { new MnemMode("nop", Modes.Implied     ), new CpuInstruction( "6502",    0xea) },
            { new MnemMode("cpx", Modes.Absolute    ), new CpuInstruction( "6502",    0xec, 3) },
            { new MnemMode("sbc", Modes.Absolute    ), new CpuInstruction( "6502",    0xed, 3) },
            { new MnemMode("inc", Modes.Absolute    ), new CpuInstruction( "6502",    0xee, 3) },
            { new MnemMode("beq", Modes.Relative    ), new CpuInstruction( "6502",    0xf0, 2) },
            { new MnemMode("sbc", Modes.IndY        ), new CpuInstruction( "6502",    0xf1, 2) },
            { new MnemMode("sbc", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0xf5, 2) },
            { new MnemMode("inc", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0xf6, 2) },
            { new MnemMode("sed", Modes.Implied     ), new CpuInstruction( "6502",    0xf8) },
            { new MnemMode("sbc", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0xf9, 3) },
            { new MnemMode("sbc", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0xfd, 3) },
            { new MnemMode("inc", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0xfe, 3) },
        };
        static readonly Dictionary<MnemMode, CpuInstruction> _opcodes65C02 = new Dictionary<MnemMode, CpuInstruction>()
        {
            { new MnemMode("tsb", Modes.ZeroPage    ), new CpuInstruction( "65C02",   0x04, 2) },
            { new MnemMode("tsb", Modes.Absolute    ), new CpuInstruction( "65C02",   0x0c, 3) },
            { new MnemMode("ora", Modes.IndZp       ), new CpuInstruction( "65C02",   0x12, 2) },
            { new MnemMode("trb", Modes.ZeroPage    ), new CpuInstruction( "65C02",   0x14, 2) },
            { new MnemMode("inc", Modes.Implied     ), new CpuInstruction( "65C02",   0x1a) },
            { new MnemMode("trb", Modes.Absolute    ), new CpuInstruction( "65C02",   0x1c, 3) },
            { new MnemMode("and", Modes.IndZp       ), new CpuInstruction( "65C02",   0x32, 2) },
            { new MnemMode("bit", Modes.ZeroPageX   ), new CpuInstruction( "65C02",   0x34, 2) },
            { new MnemMode("dec", Modes.Implied     ), new CpuInstruction( "65C02",   0x3a) },
            { new MnemMode("bit", Modes.AbsoluteX   ), new CpuInstruction( "65C02",   0x3c, 3) },
            { new MnemMode("eor", Modes.IndZp       ), new CpuInstruction( "65C02",   0x52, 2) },
            { new MnemMode("phy", Modes.Implied     ), new CpuInstruction( "65C02",   0x5a) },
            { new MnemMode("stz", Modes.ZeroPage    ), new CpuInstruction( "65C02",   0x64, 2) },
            { new MnemMode("adc", Modes.IndZp       ), new CpuInstruction( "65C02",   0x72, 2) },
            { new MnemMode("stz", Modes.ZeroPageX   ), new CpuInstruction( "65C02",   0x74, 2) },
            { new MnemMode("ply", Modes.Implied     ), new CpuInstruction( "65C02",   0x7a) },
            { new MnemMode("jmp", Modes.IndAbsX     ), new CpuInstruction( "65C02",   0x7c, 3) },
            { new MnemMode("bra", Modes.Relative    ), new CpuInstruction( "65C02",   0x80, 2) },
            { new MnemMode("bit", Modes.Immediate   ), new CpuInstruction( "65C02",   0x89, 2) },
            { new MnemMode("sta", Modes.IndZp       ), new CpuInstruction( "65C02",   0x92, 2) },
            { new MnemMode("stz", Modes.Absolute    ), new CpuInstruction( "65C02",   0x9c, 3) },
            { new MnemMode("stz", Modes.AbsoluteX   ), new CpuInstruction( "65C02",   0x9e, 3) },
            { new MnemMode("lda", Modes.IndZp       ), new CpuInstruction( "65C02",   0xb2, 2) },
            { new MnemMode("cmp", Modes.IndZp       ), new CpuInstruction( "65C02",   0xd2, 2) },
            { new MnemMode("phx", Modes.Implied     ), new CpuInstruction( "65C02",   0xda) },
            { new MnemMode("sbc", Modes.IndZp       ), new CpuInstruction( "65C02",   0xf2, 2) },
            { new MnemMode("plx", Modes.Implied     ), new CpuInstruction( "65C02",   0xfa) },
        };
        static readonly Dictionary<MnemMode, CpuInstruction> _opcodesW65C02 = new Dictionary<MnemMode, CpuInstruction>()
        {
            { new MnemMode("wai", Modes.Implied     ), new CpuInstruction( "W65C02",  0xcb) },
            { new MnemMode("stp", Modes.Implied     ), new CpuInstruction( "W65C02",  0xdb) }
        };
        static readonly Dictionary<MnemMode, CpuInstruction> _opcodesR65C02 = new Dictionary<MnemMode, CpuInstruction>()
        {
            { new MnemMode("rmb", Modes.Zp0         ), new CpuInstruction( "R65C02",  0x07, 2) },
            { new MnemMode("bbr", Modes.ThreeOpRel0 ), new CpuInstruction( "R65C02",  0x0f, 3) },
            { new MnemMode("rmb", Modes.Zp1         ), new CpuInstruction( "R65C02",  0x17, 2) },
            { new MnemMode("bbr", Modes.ThreeOpRel1 ), new CpuInstruction( "R65C02",  0x1f, 3) },
            { new MnemMode("rmb", Modes.Zp2         ), new CpuInstruction( "R65C02",  0x27, 2) },
            { new MnemMode("bbr", Modes.ThreeOpRel2 ), new CpuInstruction( "R65C02",  0x2f, 3) },
            { new MnemMode("rmb", Modes.Zp3         ), new CpuInstruction( "R65C02",  0x37, 2) },
            { new MnemMode("bbr", Modes.ThreeOpRel3 ), new CpuInstruction( "R65C02",  0x3f, 3) },
            { new MnemMode("rmb", Modes.Zp4         ), new CpuInstruction( "R65C02",  0x47, 2) },
            { new MnemMode("bbr", Modes.ThreeOpRel4 ), new CpuInstruction( "R65C02",  0x4f, 3) },
            { new MnemMode("rmb", Modes.Zp5         ), new CpuInstruction( "R65C02",  0x57, 2) },
            { new MnemMode("bbr", Modes.ThreeOpRel5 ), new CpuInstruction( "R65C02",  0x5f, 3) },
            { new MnemMode("rmb", Modes.Zp6         ), new CpuInstruction( "R65C02",  0x67, 2) },
            { new MnemMode("bbr", Modes.ThreeOpRel6 ), new CpuInstruction( "R65C02",  0x6f, 3) },
            { new MnemMode("rmb", Modes.Zp7         ), new CpuInstruction( "R65C02",  0x77, 2) },
            { new MnemMode("bbr", Modes.ThreeOpRel7 ), new CpuInstruction( "R65C02",  0x7f, 3) },
            { new MnemMode("smb", Modes.Zp0         ), new CpuInstruction( "R65C02",  0x87, 2) },
            { new MnemMode("bbs", Modes.ThreeOpRel  ), new CpuInstruction( "R65C02",  0x8f, 3) },
            { new MnemMode("smb", Modes.Zp1         ), new CpuInstruction( "R65C02",  0x97, 2) },
            { new MnemMode("bbs", Modes.ThreeOpRel1 ), new CpuInstruction( "R65C02",  0x9f, 3) },
            { new MnemMode("smb", Modes.Zp2         ), new CpuInstruction( "R65C02",  0xa7, 2) },
            { new MnemMode("bbs", Modes.ThreeOpRel2 ), new CpuInstruction( "R65C02",  0xaf, 3) },
            { new MnemMode("smb", Modes.Zp3         ), new CpuInstruction( "R65C02",  0xb7, 2) },
            { new MnemMode("bbs", Modes.ThreeOpRel3 ), new CpuInstruction( "R65C02",  0xbf, 3) },
            { new MnemMode("smb", Modes.Zp4         ), new CpuInstruction( "R65C02",  0xc7, 2) },
            { new MnemMode("bbs", Modes.ThreeOpRel4 ), new CpuInstruction( "R65C02",  0xcf, 3) },
            { new MnemMode("smb", Modes.Zp5         ), new CpuInstruction( "R65C02",  0xd7, 2) },
            { new MnemMode("bbs", Modes.ThreeOpRel5 ), new CpuInstruction( "R65C02",  0xdf, 3) },
            { new MnemMode("smb", Modes.Zp6         ), new CpuInstruction( "R65C02",  0xe7, 2) },
            { new MnemMode("bbs", Modes.ThreeOpRel6 ), new CpuInstruction( "R65C02",  0xef, 3) },
            { new MnemMode("smb", Modes.Zp7         ), new CpuInstruction( "R65C02",  0xf7, 2) },
            { new MnemMode("bbs", Modes.ThreeOpRel7 ), new CpuInstruction( "R65C02",  0xff, 3) },
        };
        static readonly Dictionary<MnemMode, CpuInstruction> _opcodesHuC6280 = new Dictionary<MnemMode, CpuInstruction>()
        {
            { new MnemMode("sxy", Modes.Implied     ), new CpuInstruction( "HuC6280", 0x03) },
            { new MnemMode("ora", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0x12, 3) },
            { new MnemMode("st1", Modes.Immediate   ), new CpuInstruction( "HuC6280", 0x13, 2) },
            { new MnemMode("sax", Modes.Implied     ), new CpuInstruction( "HuC6280", 0x23) },
            { new MnemMode("st2", Modes.Immediate   ), new CpuInstruction( "HuC6280", 0x23, 2) },
            { new MnemMode("and", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0x32, 3) },
            { new MnemMode("say", Modes.Implied     ), new CpuInstruction( "HuC6280", 0x43) },
            { new MnemMode("tma", Modes.Immediate   ), new CpuInstruction( "HuC6280", 0x43, 2) },
            { new MnemMode("eor", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0x52, 3) },
            { new MnemMode("tam", Modes.Immediate   ), new CpuInstruction( "HuC6280", 0x53, 2) },
            { new MnemMode("cla", Modes.Implied     ), new CpuInstruction( "HuC6280", 0x63) },
            { new MnemMode("adc", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0x72, 3) },
            { new MnemMode("tii", Modes.ThreeOpAbs  ), new CpuInstruction( "HuC6280", 0x73, 7) },
            { new MnemMode("clx", Modes.Implied     ), new CpuInstruction( "HuC6280", 0x83) },
            { new MnemMode("tst", Modes.TestBitZp   ), new CpuInstruction( "HuC6280", 0x83, 3) },
            { new MnemMode("sta", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0x92, 3) },
            { new MnemMode("tst", Modes.TestBitZpX  ), new CpuInstruction( "HuC6280", 0x93, 3) },
            { new MnemMode("tst", Modes.TestBitAbs  ), new CpuInstruction( "HuC6280", 0xa3, 4) },
            { new MnemMode("lda", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0xb2, 3) },
            { new MnemMode("tst", Modes.TestBitAbsX ), new CpuInstruction( "HuC6280", 0xb3, 4) },
            { new MnemMode("cly", Modes.Implied     ), new CpuInstruction( "HuC6280", 0xc3) },
            { new MnemMode("tdd", Modes.ThreeOpAbs  ), new CpuInstruction( "HuC6280", 0xc3, 7) },
            { new MnemMode("cmp", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0xd2, 3) },
            { new MnemMode("tin", Modes.ThreeOpAbs  ), new CpuInstruction( "HuC6280", 0xd3, 7) },
            { new MnemMode("csh", Modes.Implied     ), new CpuInstruction( "HuC6280", 0xd4) },
            { new MnemMode("tia", Modes.ThreeOpAbs  ), new CpuInstruction( "HuC6280", 0xe3, 7) },
            { new MnemMode("sbc", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0xf2, 3) },
            { new MnemMode("tai", Modes.ThreeOpAbs  ), new CpuInstruction( "HuC6280", 0xf3, 7) },
            { new MnemMode("set", Modes.Implied     ), new CpuInstruction( "HuC6280", 0xf4) }
        };
        static readonly Dictionary<MnemMode, CpuInstruction> _opcodes65CE02 = new Dictionary<MnemMode, CpuInstruction>()
        {
            { new MnemMode("cle", Modes.Implied     ), new CpuInstruction( "65CE02",  0x03) },
            { new MnemMode("see", Modes.Implied     ), new CpuInstruction( "65CE02",  0x04) },
            { new MnemMode("tsy", Modes.Implied     ), new CpuInstruction( "65CE02",  0x0b) },
            { new MnemMode("ora", Modes.IndZ        ), new CpuInstruction( "65CE02",  0x12, 2) },
            { new MnemMode("bpl", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0x13, 3) },
            { new MnemMode("inz", Modes.Implied     ), new CpuInstruction( "65CE02",  0x1b) },
            { new MnemMode("jsr", Modes.IndAbs      ), new CpuInstruction( "65CE02",  0x22, 3) },
            { new MnemMode("jsr", Modes.IndAbsX     ), new CpuInstruction( "65CE02",  0x23, 3) },
            { new MnemMode("tys", Modes.Implied     ), new CpuInstruction( "65CE02",  0x2b) },
            { new MnemMode("and", Modes.IndZ        ), new CpuInstruction( "65CE02",  0x32, 2) },
            { new MnemMode("bmi", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0x33, 3) },
            { new MnemMode("dez", Modes.Implied     ), new CpuInstruction( "65CE02",  0x3b) },
            { new MnemMode("neg", Modes.Implied     ), new CpuInstruction( "65CE02",  0x43) },
            { new MnemMode("asr", Modes.Implied     ), new CpuInstruction( "65CE02",  0x44) },
            { new MnemMode("asr", Modes.ZeroPage    ), new CpuInstruction( "65CE02",  0x44, 2) },
            { new MnemMode("taz", Modes.Implied     ), new CpuInstruction( "65CE02",  0x4b) },
            { new MnemMode("eor", Modes.IndZ        ), new CpuInstruction( "65CE02",  0x52, 2) },
            { new MnemMode("bvc", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0x53, 3) },
            { new MnemMode("asr", Modes.ZeroPageX   ), new CpuInstruction( "65CE02",  0x54, 2) },
            { new MnemMode("tab", Modes.Implied     ), new CpuInstruction( "65CE02",  0x5b) },
            { new MnemMode("map", Modes.Implied     ), new CpuInstruction( "65CE02",  0x5c) },
            { new MnemMode("rtn", Modes.Implied     ), new CpuInstruction( "65CE02",  0x63) },
            { new MnemMode("bsr", Modes.Absolute    ), new CpuInstruction( "65CE02",  0x63, 3) },
            { new MnemMode("tza", Modes.Implied     ), new CpuInstruction( "65CE02",  0x6b) },
            { new MnemMode("adc", Modes.IndZ        ), new CpuInstruction( "65CE02",  0x72, 2) },
            { new MnemMode("bvs", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0x73, 3) },
            { new MnemMode("tba", Modes.Implied     ), new CpuInstruction( "65CE02",  0x7b) },
            { new MnemMode("sta", Modes.IndSp       ), new CpuInstruction( "65CE02",  0x82, 2) },
            { new MnemMode("bra", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0x83, 3) },
            { new MnemMode("sty", Modes.AbsoluteX   ), new CpuInstruction( "65CE02",  0x8b, 3) },
            { new MnemMode("sta", Modes.IndZ        ), new CpuInstruction( "65CE02",  0x92, 2) },
            { new MnemMode("bcc", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0x93, 3) },
            { new MnemMode("blt", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0x93, 3) },
            { new MnemMode("stx", Modes.AbsoluteY   ), new CpuInstruction( "65CE02",  0x9b, 3) },
            { new MnemMode("ldz", Modes.Immediate   ), new CpuInstruction( "65CE02",  0xa3, 2) },
            { new MnemMode("ldz", Modes.Absolute    ), new CpuInstruction( "65CE02",  0xab, 3) },
            { new MnemMode("lda", Modes.IndZ        ), new CpuInstruction( "65CE02",  0xb2, 2) },
            { new MnemMode("bcs", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0xb3, 3) },
            { new MnemMode("bge", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0xb3, 3) },
            { new MnemMode("ldz", Modes.AbsoluteX   ), new CpuInstruction( "65CE02",  0xbb, 3) },
            { new MnemMode("cpz", Modes.Immediate   ), new CpuInstruction( "65CE02",  0xc2, 2) },
            { new MnemMode("dew", Modes.ZeroPage    ), new CpuInstruction( "65CE02",  0xc3, 2) },
            { new MnemMode("asw", Modes.Absolute    ), new CpuInstruction( "65CE02",  0xcb, 3) },
            { new MnemMode("cmp", Modes.IndZ        ), new CpuInstruction( "65CE02",  0xd2, 2) },
            { new MnemMode("bne", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0xd3, 3) },
            { new MnemMode("cpz", Modes.ZeroPage    ), new CpuInstruction( "65CE02",  0xd4, 2) },
            { new MnemMode("phz", Modes.Implied     ), new CpuInstruction( "65CE02",  0xdb) },
            { new MnemMode("cpz", Modes.Absolute    ), new CpuInstruction( "65CE02",  0xdc, 3) },
            { new MnemMode("lda", Modes.IndSp       ), new CpuInstruction( "65CE02",  0xe2, 2) },
            { new MnemMode("inw", Modes.ZeroPage    ), new CpuInstruction( "65CE02",  0xe3, 2) },
            { new MnemMode("row", Modes.Absolute    ), new CpuInstruction( "65CE02",  0xeb, 3) },
            { new MnemMode("sbc", Modes.IndZ        ), new CpuInstruction( "65CE02",  0xf2, 2) },
            { new MnemMode("beq", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0xf3, 3) },
            { new MnemMode("phw", Modes.ImmAbs      ), new CpuInstruction( "65CE02",  0xf4, 3) },
            { new MnemMode("plz", Modes.Implied     ), new CpuInstruction( "65CE02",  0xfb) },
            { new MnemMode("phw", Modes.Absolute    ), new CpuInstruction( "65CE02",  0xfc, 2) }
        };
        static readonly Dictionary<MnemMode, CpuInstruction> _opcodes65816 = new Dictionary<MnemMode, CpuInstruction>()
        {
            { new MnemMode("cop", Modes.Implied     ), new CpuInstruction( "65816",   0x03) },
            { new MnemMode("cop", Modes.Immediate   ), new CpuInstruction( "65816",   0x02, 2) },
            { new MnemMode("ora", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0x03, 2) },
            { new MnemMode("ora", Modes.Dir         ), new CpuInstruction( "65816",   0x07, 2) },
            { new MnemMode("phd", Modes.Implied     ), new CpuInstruction( "65816",   0x0b) },
            { new MnemMode("ora", Modes.Long        ), new CpuInstruction( "65816",   0x0f, 4) },
            { new MnemMode("ora", Modes.IndS        ), new CpuInstruction( "65816",   0x13, 2) },
            { new MnemMode("ora", Modes.DirY        ), new CpuInstruction( "65816",   0x17, 2) },
            { new MnemMode("tcs", Modes.Implied     ), new CpuInstruction( "65816",   0x1b) },
            { new MnemMode("ora", Modes.LongX       ), new CpuInstruction( "65816",   0x1f, 4) },
            { new MnemMode("jsl", Modes.Long        ), new CpuInstruction( "65816",   0x22, 4) },
            { new MnemMode("jsr", Modes.Long        ), new CpuInstruction( "65816",   0x22, 4) },
            { new MnemMode("and", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0x23, 2) },
            { new MnemMode("and", Modes.Dir         ), new CpuInstruction( "65816",   0x27, 2) },
            { new MnemMode("pld", Modes.Implied     ), new CpuInstruction( "65816",   0x2b) },
            { new MnemMode("and", Modes.Long        ), new CpuInstruction( "65816",   0x2f, 4) },
            { new MnemMode("and", Modes.IndS        ), new CpuInstruction( "65816",   0x33, 2) },
            { new MnemMode("and", Modes.DirY        ), new CpuInstruction( "65816",   0x37, 2) },
            { new MnemMode("tsc", Modes.Implied     ), new CpuInstruction( "65816",   0x3b) },
            { new MnemMode("and", Modes.LongX       ), new CpuInstruction( "65816",   0x3f, 4) },
            { new MnemMode("wdm", Modes.Implied     ), new CpuInstruction( "65816",   0x43) },
            { new MnemMode("eor", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0x43, 2) },
            { new MnemMode("mvp", Modes.TwoOperand  ), new CpuInstruction( "65816",   0x44, 3) },
            { new MnemMode("eor", Modes.Dir         ), new CpuInstruction( "65816",   0x47, 2) },
            { new MnemMode("phk", Modes.Implied     ), new CpuInstruction( "65816",   0x4b) },
            { new MnemMode("eor", Modes.Long        ), new CpuInstruction( "65816",   0x4f, 4) },
            { new MnemMode("eor", Modes.IndS        ), new CpuInstruction( "65816",   0x53, 2) },
            { new MnemMode("mvn", Modes.TwoOperand  ), new CpuInstruction( "65816",   0x54, 3) },
            { new MnemMode("eor", Modes.DirY        ), new CpuInstruction( "65816",   0x57, 2) },
            { new MnemMode("tcd", Modes.Implied     ), new CpuInstruction( "65816",   0x5b) },
            { new MnemMode("jml", Modes.Long        ), new CpuInstruction( "65816",   0x5c, 4) },
            { new MnemMode("jmp", Modes.Long        ), new CpuInstruction( "65816",   0x5c, 4) },
            { new MnemMode("eor", Modes.LongX       ), new CpuInstruction( "65816",   0x5f, 4) },
            { new MnemMode("per", Modes.RelativeAbs ), new CpuInstruction( "65816",   0x62, 3) },
            { new MnemMode("adc", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0x63, 2) },
            { new MnemMode("adc", Modes.Dir         ), new CpuInstruction( "65816",   0x67, 2) },
            { new MnemMode("rtl", Modes.Implied     ), new CpuInstruction( "65816",   0x6b) },
            { new MnemMode("adc", Modes.Long        ), new CpuInstruction( "65816",   0x6f, 4) },
            { new MnemMode("adc", Modes.IndS        ), new CpuInstruction( "65816",   0x73, 2) },
            { new MnemMode("adc", Modes.DirY        ), new CpuInstruction( "65816",   0x77, 2) },
            { new MnemMode("tdc", Modes.Implied     ), new CpuInstruction( "65816",   0x7b) },
            { new MnemMode("adc", Modes.LongX       ), new CpuInstruction( "65816",   0x7f, 4) },
            { new MnemMode("brl", Modes.RelativeAbs ), new CpuInstruction( "65816",   0x82, 3) },
            { new MnemMode("sta", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0x83, 2) },
            { new MnemMode("sta", Modes.Dir         ), new CpuInstruction( "65816",   0x87, 2) },
            { new MnemMode("phb", Modes.Implied     ), new CpuInstruction( "65816",   0x8b) },
            { new MnemMode("sta", Modes.Long        ), new CpuInstruction( "65816",   0x8f, 4) },
            { new MnemMode("sta", Modes.IndS        ), new CpuInstruction( "65816",   0x93, 2) },
            { new MnemMode("sta", Modes.DirY        ), new CpuInstruction( "65816",   0x97, 2) },
            { new MnemMode("txy", Modes.Implied     ), new CpuInstruction( "65816",   0x9b) },
            { new MnemMode("sta", Modes.LongX       ), new CpuInstruction( "65816",   0x9f, 4) },
            { new MnemMode("lda", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0xa3, 2) },
            { new MnemMode("lda", Modes.Dir         ), new CpuInstruction( "65816",   0xa7, 2) },
            { new MnemMode("plb", Modes.Implied     ), new CpuInstruction( "65816",   0xab) },
            { new MnemMode("lda", Modes.Long        ), new CpuInstruction( "65816",   0xaf, 4) },
            { new MnemMode("lda", Modes.IndS        ), new CpuInstruction( "65816",   0xb3, 2) },
            { new MnemMode("lda", Modes.DirY        ), new CpuInstruction( "65816",   0xb7, 2) },
            { new MnemMode("tyx", Modes.Implied     ), new CpuInstruction( "65816",   0xbb) },
            { new MnemMode("lda", Modes.LongX       ), new CpuInstruction( "65816",   0xbf, 4) },
            { new MnemMode("rep", Modes.Immediate   ), new CpuInstruction( "65816",   0xc2, 2) },
            { new MnemMode("cmp", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0xc3, 2) },
            { new MnemMode("cmp", Modes.Dir         ), new CpuInstruction( "65816",   0xc7, 2) },
            { new MnemMode("cmp", Modes.Long        ), new CpuInstruction( "65816",   0xcf, 4) },
            { new MnemMode("cmp", Modes.IndS        ), new CpuInstruction( "65816",   0xd3, 2) },
            { new MnemMode("pei", Modes.IndZp       ), new CpuInstruction( "65816",   0xd4, 2) },
            { new MnemMode("cmp", Modes.DirY        ), new CpuInstruction( "65816",   0xd7, 2) },
            { new MnemMode("jmp", Modes.DirAbs      ), new CpuInstruction( "65816",   0xdc, 3) },
            { new MnemMode("cmp", Modes.LongX       ), new CpuInstruction( "65816",   0xdf, 4) },
            { new MnemMode("sep", Modes.Immediate   ), new CpuInstruction( "65816",   0xe2, 2) },
            { new MnemMode("sbc", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0xe3, 2) },
            { new MnemMode("sbc", Modes.Dir         ), new CpuInstruction( "65816",   0xe7, 2) },
            { new MnemMode("xba", Modes.Implied     ), new CpuInstruction( "65816",   0xeb) },
            { new MnemMode("sbc", Modes.Long        ), new CpuInstruction( "65816",   0xef, 4) },
            { new MnemMode("sbc", Modes.IndS        ), new CpuInstruction( "65816",   0xf3, 2) },
            { new MnemMode("pea", Modes.ImmAbs      ), new CpuInstruction( "65816",   0xf4, 3) },
            { new MnemMode("pea", Modes.Absolute    ), new CpuInstruction( "65816",   0xf4, 3) }, // both are acceptable
            { new MnemMode("sbc", Modes.DirY        ), new CpuInstruction( "65816",   0xf7, 2) },
            { new MnemMode("xce", Modes.Implied     ), new CpuInstruction( "65816",   0xfb) },
            { new MnemMode("sbc", Modes.LongX       ), new CpuInstruction( "65816",   0xff, 4) },
        };
        static readonly Dictionary<MnemMode, CpuInstruction> _opcodes6502i = new Dictionary<MnemMode, CpuInstruction>()
        {
            { new MnemMode("jam", Modes.Implied     ), new CpuInstruction( "6502i",   0x03) },
            { new MnemMode("slo", Modes.IndX        ), new CpuInstruction( "6502i",   0x03, 2) },
            { new MnemMode("dop", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0x04, 2) },
            { new MnemMode("slo", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0x07, 2) },
            { new MnemMode("top", Modes.Implied     ), new CpuInstruction( "6502i",   0x0c) },
            { new MnemMode("top", Modes.Absolute    ), new CpuInstruction( "6502i",   0x0c, 3) },
            { new MnemMode("slo", Modes.Absolute    ), new CpuInstruction( "6502i",   0x0f, 3) },
            { new MnemMode("stp", Modes.Implied     ), new CpuInstruction( "6502i",   0x13) },
            { new MnemMode("slo", Modes.IndY        ), new CpuInstruction( "6502i",   0x13, 2) },
            { new MnemMode("dop", Modes.ZeroPageX   ), new CpuInstruction( "6502i",   0x14, 2) },
            { new MnemMode("slo", Modes.ZeroPageX   ), new CpuInstruction( "6502i",   0x17, 2) },
            { new MnemMode("slo", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0x1b, 3) },
            { new MnemMode("slo", Modes.AbsoluteX   ), new CpuInstruction( "6502i",   0x1f, 3) },
            { new MnemMode("rla", Modes.IndX        ), new CpuInstruction( "6502i",   0x23, 2) },
            { new MnemMode("rla", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0x27, 2) },
            { new MnemMode("anc", Modes.Immediate   ), new CpuInstruction( "6502i",   0x2b, 2) },
            { new MnemMode("rla", Modes.Absolute    ), new CpuInstruction( "6502i",   0x2f, 3) },
            { new MnemMode("rla", Modes.IndY        ), new CpuInstruction( "6502i",   0x33, 2) },
            { new MnemMode("rla", Modes.ZeroPageX   ), new CpuInstruction( "6502i",   0x37, 2) },
            { new MnemMode("rla", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0x3b, 3) },
            { new MnemMode("rla", Modes.AbsoluteX   ), new CpuInstruction( "6502i",   0x3f, 3) },
            { new MnemMode("sre", Modes.IndX        ), new CpuInstruction( "6502i",   0x43, 2) },
            { new MnemMode("sre", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0x47, 2) },
            { new MnemMode("asr", Modes.Immediate   ), new CpuInstruction( "6502i",   0x4b, 2) },
            { new MnemMode("sre", Modes.Absolute    ), new CpuInstruction( "6502i",   0x4f, 3) },
            { new MnemMode("sre", Modes.IndY        ), new CpuInstruction( "6502i",   0x53, 2) },
            { new MnemMode("sre", Modes.ZeroPageX   ), new CpuInstruction( "6502i",   0x57, 2) },
            { new MnemMode("sre", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0x5b, 3) },
            { new MnemMode("sre", Modes.AbsoluteX   ), new CpuInstruction( "6502i",   0x5f, 3) },
            { new MnemMode("rra", Modes.IndX        ), new CpuInstruction( "6502i",   0x63, 2) },
            { new MnemMode("rra", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0x67, 2) },
            { new MnemMode("arr", Modes.Immediate   ), new CpuInstruction( "6502i",   0x6b, 2) },
            { new MnemMode("rra", Modes.Absolute    ), new CpuInstruction( "6502i",   0x6f, 3) },
            { new MnemMode("rra", Modes.IndY        ), new CpuInstruction( "6502i",   0x73, 2) },
            { new MnemMode("rra", Modes.ZeroPageX   ), new CpuInstruction( "6502i",   0x77, 2) },
            { new MnemMode("rra", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0x7b, 3) },
            { new MnemMode("rra", Modes.AbsoluteX   ), new CpuInstruction( "6502i",   0x7f, 3) },
            { new MnemMode("dop", Modes.Implied     ), new CpuInstruction( "6502i",   0x80) },
            { new MnemMode("dop", Modes.Immediate   ), new CpuInstruction( "6502i",   0x80, 2) },
            { new MnemMode("sax", Modes.IndX        ), new CpuInstruction( "6502i",   0x83, 2) },
            { new MnemMode("sax", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0x87, 2) },
            { new MnemMode("ane", Modes.Immediate   ), new CpuInstruction( "6502i",   0x8b, 2) },
            { new MnemMode("sax", Modes.Absolute    ), new CpuInstruction( "6502i",   0x8f, 3) },
            { new MnemMode("sha", Modes.IndY        ), new CpuInstruction( "6502i",   0x93, 2) },
            { new MnemMode("sax", Modes.ZeroPageY   ), new CpuInstruction( "6502i",   0x97, 2) },
            { new MnemMode("tas", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0x9b, 3) },
            { new MnemMode("shy", Modes.AbsoluteX   ), new CpuInstruction( "6502i",   0x9c, 3) },
            { new MnemMode("shx", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0x9e, 3) },
            { new MnemMode("sha", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0x9f, 3) },
            { new MnemMode("lax", Modes.IndX        ), new CpuInstruction( "6502i",   0xa3, 2) },
            { new MnemMode("lax", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0xa7, 2) },
            { new MnemMode("lax", Modes.Absolute    ), new CpuInstruction( "6502i",   0xaf, 3) },
            { new MnemMode("lax", Modes.IndY        ), new CpuInstruction( "6502i",   0xb3, 2) },
            { new MnemMode("lax", Modes.ZeroPageY   ), new CpuInstruction( "6502i",   0xb7, 2) },
            { new MnemMode("las", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0xbb, 3) },
            { new MnemMode("lax", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0xbf, 3) },
            { new MnemMode("dcp", Modes.IndX        ), new CpuInstruction( "6502i",   0xc3, 2) },
            { new MnemMode("dcp", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0xc7, 2) },
            { new MnemMode("sax", Modes.Immediate   ), new CpuInstruction( "6502i",   0xcb, 2) },
            { new MnemMode("dcp", Modes.Absolute    ), new CpuInstruction( "6502i",   0xcf, 3) },
            { new MnemMode("dcp", Modes.IndY        ), new CpuInstruction( "6502i",   0xd3, 2) },
            { new MnemMode("dcp", Modes.ZeroPageX   ), new CpuInstruction( "6502i",   0xd7, 2) },
            { new MnemMode("dcp", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0xdb, 3) },
            { new MnemMode("dcp", Modes.AbsoluteX   ), new CpuInstruction( "6502i",   0xdf, 3) },
            { new MnemMode("isb", Modes.IndX        ), new CpuInstruction( "6502i",   0xe3, 2) },
            { new MnemMode("isb", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0xe7, 2) },
            { new MnemMode("isb", Modes.Absolute    ), new CpuInstruction( "6502i",   0xef, 3) },
            { new MnemMode("isb", Modes.IndY        ), new CpuInstruction( "6502i",   0xf3, 2) },
            { new MnemMode("isb", Modes.ZeroPageX   ), new CpuInstruction( "6502i",   0xf7, 2) },
            { new MnemMode("isb", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0xfb, 3) },
            { new MnemMode("isb", Modes.AbsoluteX   ), new CpuInstruction( "6502i",   0xff, 3) },
        };
        static readonly Dictionary<Modes, string> _modeFormats = new Dictionary<Modes, string>
        {
            { Modes.Implied,        string.Empty                },
            { Modes.Immediate,      "#${0:x2}"                  },
            { Modes.ImmAbs,         "#${0:x4}"                  },
            { Modes.ZeroPage,       "${0:x2}"                   },
            { Modes.ZeroPageS,      "${0:x2},s"                 },
            { Modes.ZeroPageX,      "${0:x2},x"                 },
            { Modes.ZeroPageY,      "${0:x2},y"                 },
            { Modes.Relative,       "${0:x4}"                   },
            { Modes.RelativeAbs,    "${0:x4}"                   },
            { Modes.Absolute,       "${0:x4}"                   },
            { Modes.AbsoluteX,      "${0:x4},x"                 },
            { Modes.AbsoluteY,      "${0:x4},y"                 },
            { Modes.Long,           "${0:x6}"                   },
            { Modes.LongX,          "${0:x6},x"                 },
            { Modes.IndZp,          "(${0:x2})"                 },
            { Modes.IndS,           "(${0:x2},s),y"             },
            { Modes.IndSp,          "(${0:x2},sp),y"            },
            { Modes.IndX,           "(${0:x2},x)"               },
            { Modes.IndY,           "(${0:x2}),y"               },
            { Modes.IndZ,           "(${0:x2}),z"               },
            { Modes.IndAbs,         "(${0:x4})"                 },
            { Modes.IndAbsX,        "(${0:x4},x)"               },
            { Modes.Dir,            "[${0:x2}]"                 },
            { Modes.DirY,           "[${0:x2}],y"               },
            { Modes.DirAbs,         "[${0:x4}]"                 },
            { Modes.Zp1,            "1,${0:x2}"                 },
            { Modes.Zp2,            "2,${0:x2}"                 },
            { Modes.Zp3,            "3,${0:x2}"                 },
            { Modes.Zp4,            "4,${0:x2}"                 },
            { Modes.Zp5,            "5,${0:x2}"                 },
            { Modes.Zp6,            "6,${0:x2}"                 },
            { Modes.Zp7,            "7,${0:x2}"                 },
            { Modes.TwoOperand,     "${0:x2},${1:x2}"           },
            { Modes.TestBitZp,      "#${0:x2},${1:x2}"          },
            { Modes.TestBitZpX,     "#${0:x2},${1:x2},x"        },
            { Modes.TestBitAbs,     "#${0:x2},${1:x4}"          },
            { Modes.TestBitAbsX,    "#${0:x2},${1:x4},x"        },
            { Modes.ThreeOpRel0,    "0,${0:x2},${1:x4}"         },
            { Modes.ThreeOpRel1,    "1,${0:x2},${1:x4}"         },
            { Modes.ThreeOpRel2,    "2,${0:x2},${1:x4}"         },
            { Modes.ThreeOpRel3,    "3,${0:x2},${1:x4}"         },
            { Modes.ThreeOpRel4,    "4,${0:x2},${1:x4}"         },
            { Modes.ThreeOpRel5,    "5,${0:x2},${1:x4}"         },
            { Modes.ThreeOpRel6,    "6,${0:x2},${1:x4}"         },
            { Modes.ThreeOpRel7,    "7,${0:x2},${1:x4}"         },
            { Modes.ThreeOpAbs,     "${0:x4},${1:x4},${2:x4}"   }
        };
        static readonly Dictionary<string, string> _pseudoBranchTranslations = new Dictionary<string, string>
        {
            { "jcc", "bcs" },
            { "jcs", "bcc" },
            { "jeq", "bne" },
            { "jmi", "bpl" },
            { "jne", "beq" },
            { "jvc", "bvs" },
            { "jvs", "bvc" }
        };

        #endregion

        #region Properties

        /// <summary>
        /// Gets an array of the 65xx-based CPUs whose mnemonics this assembler recognizes.
        /// </summary>
        /// <value>The supported CPUs.</value>
        public static string[] SupportedCPUs { get; } =
        {
            "6502",
            "6502i",
            "65C02",
            "HuC6280",
            "R65C02",
            "65CE02",
            "65816",
            "65CS02"
        };

        #endregion

    }
}