//-----------------------------------------------------------------------------
// Copyright (c) 2017-2023 informedcitizenry <informedcitizenry@gmail.com>
//
// Licensed under the MIT license. See LICENSE for full license information.
// 
//-----------------------------------------------------------------------------

namespace Sixty502DotNet.Shared;

/// <summary>
/// The bit flags for all of the M6809 index operations.
/// </summary>
public static class M6809IndexFlags
{
    public const int Offset5bit = 0b0001_1111,
                     AutoInc1   = 0b1000_0000,
                     AutoInc2   = 0b1000_0001,
                     AutoDec1   = 0b1000_0010,
                     AutoDec2   = 0b1000_0011,
                     ZeroOffset = 0b1000_0100,
                     AccBOffset = 0b1000_0101,
                     AccAOffset = 0b1000_0110,
                     Offset8bit = 0b1000_1000,
                     Offset16   = 0b1000_1001,
                     AccDOffset = 0b1000_1011,
                     PC8BitOffs = 0b1000_1100,
                     PC16Bit    = 0b1000_1101,
                     OffsetMask = 0b1000_1111,
                     Indirect   = 0b1001_0000,
                     Extended   = 0b1001_1111,
                     X          = 0b0000_0000,
                     Y          = 0b0010_0000,
                     U          = 0b0100_0000,
                     S          = 0b0110_0000,
                     IndexMask  = 0b0110_0000;
};

public sealed partial class M680xInstructionEncoder
{
    private static readonly Dictionary<int, M6xxOpcode> s_m6800Opcodes = new()
    {
        //                                          Impl      Zp     Rel     Abs     Imm     ZpX  RelAbs  ImmAbs
        { SyntaxParser.ASL,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x78,    Bad,   0x68,    Bad,    Bad) },
        { SyntaxParser.BCC,  new M6xxOpcode(    Bad,    Bad,   0x24,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BCS,  new M6xxOpcode(    Bad,    Bad,   0x25,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BEQ,  new M6xxOpcode(    Bad,    Bad,   0x27,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BMI,  new M6xxOpcode(    Bad,    Bad,   0x2B,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BNE,  new M6xxOpcode(    Bad,    Bad,   0x26,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BPL,  new M6xxOpcode(    Bad,    Bad,   0x2A,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BVC,  new M6xxOpcode(    Bad,    Bad,   0x28,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BVS,  new M6xxOpcode(    Bad,    Bad,   0x29,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.CLC,  new M6xxOpcode(   0x0C,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.CLI,  new M6xxOpcode(   0x0E,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.CLV,  new M6xxOpcode(   0x0A,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.DEC,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x7A,    Bad,   0x6A,    Bad,    Bad) },
        { SyntaxParser.DEX,  new M6xxOpcode(   0x09,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.INC,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x7C,    Bad,   0x6C,    Bad,    Bad) },
        { SyntaxParser.INX,  new M6xxOpcode(   0x08,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.JMP,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x7E,    Bad,   0x6E,    Bad,    Bad) },
        { SyntaxParser.JSR,  new M6xxOpcode(    Bad,    Bad,    Bad,   0xBD,    Bad,   0xAD,    Bad,    Bad) },
        { SyntaxParser.LDX,  new M6xxOpcode(    Bad,   0xDE,    Bad,   0xFE,    Bad,   0xEE,    Bad,   0xCE) },
        { SyntaxParser.LSR,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x74,    Bad,   0x64,    Bad,    Bad) },
        { SyntaxParser.NOP,  new M6xxOpcode(   0x01,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.ROL,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x79,    Bad,   0x69,    Bad,    Bad) },
        { SyntaxParser.ROR,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x76,    Bad,   0x66,    Bad,    Bad) },
        { SyntaxParser.RTI,  new M6xxOpcode(   0x3B,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.RTS,  new M6xxOpcode(   0x39,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.SEC,  new M6xxOpcode(   0x0D,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.SEI,  new M6xxOpcode(   0x0F,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.STX,  new M6xxOpcode(    Bad,   0xDF,    Bad,   0xFF,    Bad,   0xEF,    Bad,    Bad) },
        //                                          Impl      Zp     Rel     Abs     Imm     ZpX  RelAbs  ImmAbs
        { SyntaxParser.TSX,  new M6xxOpcode(   0x30,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.TXS,  new M6xxOpcode(   0x35,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.ASR,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x77,    Bad,   0x67,    Bad,    Bad) },
        { SyntaxParser.BRA,  new M6xxOpcode(    Bad,    Bad,   0x20,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BGE,  new M6xxOpcode(    Bad,    Bad,   0x2C,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BLT,  new M6xxOpcode(    Bad,    Bad,   0x2D,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BSR,  new M6xxOpcode(    Bad,    Bad,   0x8D,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.TAB,  new M6xxOpcode(   0x16,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.TBA,  new M6xxOpcode(   0x17,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.ABA,  new M6xxOpcode(   0x1B,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.ADCA, new M6xxOpcode(    Bad,   0x99,    Bad,   0xB9,   0x89,   0xA9,    Bad,    Bad) },
        { SyntaxParser.ADCB, new M6xxOpcode(    Bad,   0xD9,    Bad,   0xF9,   0xC9,   0xE9,    Bad,    Bad) },
        { SyntaxParser.ADDA, new M6xxOpcode(    Bad,   0x9B,    Bad,   0xBB,   0x8B,   0xAB,    Bad,    Bad) },
        { SyntaxParser.ADDB, new M6xxOpcode(    Bad,   0xDB,    Bad,   0xFB,   0xCB,   0xEB,    Bad,    Bad) },
        { SyntaxParser.ANDA, new M6xxOpcode(    Bad,   0x94,    Bad,   0xB4,   0x84,   0xA4,    Bad,    Bad) },
        { SyntaxParser.ANDB, new M6xxOpcode(    Bad,   0xD4,    Bad,   0xF4,   0xC4,   0xE4,    Bad,    Bad) },
        { SyntaxParser.ASLA, new M6xxOpcode(   0x48,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.ASLB, new M6xxOpcode(   0x58,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.ASRA, new M6xxOpcode(   0x47,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.ASRB, new M6xxOpcode(   0x57,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BGT,  new M6xxOpcode(    Bad,    Bad,   0x2E,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BHI,  new M6xxOpcode(    Bad,    Bad,   0x22,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BITA, new M6xxOpcode(    Bad,   0x95,    Bad,   0xB5,   0x85,   0xA5,    Bad,    Bad) },
        { SyntaxParser.BITB, new M6xxOpcode(    Bad,   0xD5,    Bad,   0xF5,   0xC5,   0xE5,    Bad,    Bad) },
        { SyntaxParser.BLE,  new M6xxOpcode(    Bad,    Bad,   0x2F,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BLS,  new M6xxOpcode(    Bad,    Bad,   0x23,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.CBA,  new M6xxOpcode(   0x11,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.CLR,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x7F,    Bad,   0x6F,    Bad,    Bad) },
        //                                          Impl      Zp     Rel     Abs     Imm     ZpX  RelAbs  ImmAbs
        { SyntaxParser.CLRA, new M6xxOpcode(   0x4F,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.CLRB, new M6xxOpcode(   0x5F,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.CMPA, new M6xxOpcode(    Bad,   0x91,    Bad,   0xB1,   0x81,   0xA1,    Bad,    Bad) },
        { SyntaxParser.CMPB, new M6xxOpcode(    Bad,   0xD1,    Bad,   0xF1,   0xC1,   0xE1,    Bad,    Bad) },
        { SyntaxParser.COM,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x73,    Bad,   0x63,    Bad,    Bad) },
        { SyntaxParser.COMA, new M6xxOpcode(   0x43,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.COMB, new M6xxOpcode(   0x53,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.CPXA, new M6xxOpcode(    Bad,   0x9C,    Bad,   0xBC,   0x8C,   0xAC,    Bad,    Bad) },
        { SyntaxParser.DECA, new M6xxOpcode(   0x4A,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.DECB, new M6xxOpcode(   0x5A,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.DES,  new M6xxOpcode(   0x34,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.EORA, new M6xxOpcode(    Bad,   0x98,    Bad,   0xB8,   0x88,   0xA8,    Bad,    Bad) },
        { SyntaxParser.EORB, new M6xxOpcode(    Bad,   0xD8,    Bad,   0xF8,   0xC8,   0xE8,    Bad,    Bad) },
        { SyntaxParser.INCA, new M6xxOpcode(   0x4C,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.INCB, new M6xxOpcode(   0x5C,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.INS,  new M6xxOpcode(   0x31,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.LDAA, new M6xxOpcode(    Bad,   0x96,    Bad,   0xB6,   0x86,   0xA6,    Bad,    Bad) },
        { SyntaxParser.LDAB, new M6xxOpcode(    Bad,   0xD6,    Bad,   0xF6,   0xC6,   0xE6,    Bad,    Bad) },
        { SyntaxParser.LDS,  new M6xxOpcode(    Bad,   0x9E,    Bad,   0xBE,    Bad,   0xAE,    Bad,   0x8E) },
        { SyntaxParser.LSRA, new M6xxOpcode(   0x44,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.LSRB, new M6xxOpcode(   0x54,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.NEGA, new M6xxOpcode(   0x40,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.NEGB, new M6xxOpcode(   0x50,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.ORAA, new M6xxOpcode(    Bad,   0x9A,    Bad,   0xBA,   0x8A,   0xAA,    Bad,    Bad) },
        { SyntaxParser.ORAB, new M6xxOpcode(    Bad,   0xDA,    Bad,   0xFA,   0xCA,   0xEA,    Bad,    Bad) },
        { SyntaxParser.PSHA, new M6xxOpcode(   0x36,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.PSHB, new M6xxOpcode(   0x37,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.PULA, new M6xxOpcode(   0x32,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        //                                          Impl      Zp     Rel     Abs     Imm     ZpX  RelAbs  ImmAbs
        { SyntaxParser.PULB, new M6xxOpcode(   0x33,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.ROLA, new M6xxOpcode(   0x49,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.ROLB, new M6xxOpcode(   0x59,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.RORA, new M6xxOpcode(   0x46,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.RORB, new M6xxOpcode(   0x56,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.SBA,  new M6xxOpcode(   0x10,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.SBCA, new M6xxOpcode(    Bad,   0x92,    Bad,   0xB2,   0x82,   0xA2,    Bad,    Bad) },
        { SyntaxParser.SBCB, new M6xxOpcode(    Bad,   0xD2,    Bad,   0xF2,   0xC2,   0xE2,    Bad,    Bad) },
        { SyntaxParser.SEV,  new M6xxOpcode(   0x0B,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.STAA, new M6xxOpcode(    Bad,   0x97,    Bad,   0xB7,   0xC7,   0xA7,    Bad,    Bad) },
        { SyntaxParser.STAB, new M6xxOpcode(    Bad,   0xD7,    Bad,   0xF7,    Bad,   0xE7,    Bad,    Bad) },
        { SyntaxParser.STS,  new M6xxOpcode(    Bad,   0x9F,    Bad,   0xBF,    Bad,   0xAF,    Bad,    Bad) },
        { SyntaxParser.SUBA, new M6xxOpcode(    Bad,   0x90,    Bad,   0xB0,   0x80,   0xA0,    Bad,    Bad) },
        { SyntaxParser.SUBB, new M6xxOpcode(    Bad,   0xD0,    Bad,   0xF0,   0xC0,   0xE0,    Bad,    Bad) },
        { SyntaxParser.SWI,  new M6xxOpcode(   0x3F,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.TAP,  new M6xxOpcode(   0x06,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.TPA,  new M6xxOpcode(   0x07,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.TSTA, new M6xxOpcode(   0x4D,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.TSTB, new M6xxOpcode(   0x5D,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.DAA,  new M6xxOpcode(   0x19,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.NEG,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x70,    Bad,   0x60,    Bad,    Bad) },
        { SyntaxParser.TST,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x7D,    Bad,   0x6D,    Bad,    Bad) },
        { SyntaxParser.WAI,  new M6xxOpcode(   0x3E,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
    };

    private readonly static Dictionary<int, Instruction> s_m6800Disassembly = new()
    {
        { 0x01, new Instruction("nop", 0x01) },
        { 0x06, new Instruction("tap", 0x06) },
        { 0x07, new Instruction("tpa", 0x07) },
        { 0x08, new Instruction("inx", 0x08) },
        { 0x09, new Instruction("dex", 0x09) },
        { 0x0a, new Instruction("clv", 0x0a) },
        { 0x0b, new Instruction("sev", 0x0b) },
        { 0x0c, new Instruction("clc", 0x0c) },
        { 0x0d, new Instruction("sec", 0x0d) },
        { 0x0e, new Instruction("cli", 0x0e) },
        { 0x0f, new Instruction("sei", 0x0f) },
        { 0x10, new Instruction("sba", 0x10) },
        { 0x11, new Instruction("cba", 0x11) },
        { 0x16, new Instruction("tab", 0x16) },
        { 0x17, new Instruction("tba", 0x17) },
        { 0x19, new Instruction("daa", 0x19) },
        { 0x1b, new Instruction("aba", 0x1b) },
        { 0x20, new Instruction("bra ${0:x4}", 0x20, 2, true) },
        { 0x22, new Instruction("bhi ${0:x4}", 0x22, 2, true) },
        { 0x23, new Instruction("bls ${0:x4}", 0x23, 2, true) },
        { 0x24, new Instruction("bcc ${0:x4}", 0x24, 2, true) },
        { 0x25, new Instruction("bcs ${0:x4}", 0x25, 2, true) },
        { 0x26, new Instruction("bne ${0:x4}", 0x26, 2, true) },
        { 0x27, new Instruction("beq ${0:x4}", 0x27, 2, true) },
        { 0x28, new Instruction("bvc ${0:x4}", 0x28, 2, true) },
        { 0x29, new Instruction("bvs ${0:x4}", 0x29, 2, true) },
        { 0x2a, new Instruction("bpl ${0:x4}", 0x2a, 2, true) },
        { 0x2b, new Instruction("bmi ${0:x4}", 0x2b, 2, true) },
        { 0x2c, new Instruction("bge ${0:x4}", 0x2c, 2, true) },
        { 0x2d, new Instruction("blt ${0:x4}", 0x2d, 2, true) },
        { 0x2e, new Instruction("bgt ${0:x4}", 0x2e, 2, true) },
        { 0x2f, new Instruction("ble ${0:x4}", 0x2f, 2, true) },
        { 0x30, new Instruction("tsx", 0x30) },
        { 0x31, new Instruction("ins", 0x31) },
        { 0x32, new Instruction("pula", 0x32) },
        { 0x33, new Instruction("pulb", 0x33) },
        { 0x34, new Instruction("des", 0x34) },
        { 0x35, new Instruction("txs", 0x35) },
        { 0x36, new Instruction("psha", 0x36) },
        { 0x37, new Instruction("pshb", 0x37) },
        { 0x39, new Instruction("rts", 0x39) },
        { 0x3b, new Instruction("rti", 0x3b) },
        { 0x3e, new Instruction("wai", 0x3e) },
        { 0x3f, new Instruction("swi", 0x3f) },
        { 0x40, new Instruction("nega", 0x40) },
        { 0x43, new Instruction("coma", 0x43) },
        { 0x44, new Instruction("lsra", 0x44) },
        { 0x46, new Instruction("rora", 0x46) },
        { 0x47, new Instruction("asra", 0x47) },
        { 0x48, new Instruction("asla", 0x48) },
        { 0x49, new Instruction("rola", 0x49) },
        { 0x4a, new Instruction("deca", 0x4a) },
        { 0x4c, new Instruction("inca", 0x4c) },
        { 0x4d, new Instruction("tsta", 0x4d) },
        { 0x4f, new Instruction("clra", 0x4f) },
        { 0x50, new Instruction("negb", 0x50) },
        { 0x53, new Instruction("comb", 0x53) },
        { 0x54, new Instruction("lsrb", 0x54) },
        { 0x56, new Instruction("rorb", 0x56) },
        { 0x57, new Instruction("asrb", 0x57) },
        { 0x58, new Instruction("aslb", 0x58) },
        { 0x59, new Instruction("rolb", 0x59) },
        { 0x5a, new Instruction("decb", 0x5a) },
        { 0x5c, new Instruction("incb", 0x5c) },
        { 0x5d, new Instruction("tstb", 0x5d) },
        { 0x5f, new Instruction("clrb", 0x5f) },
        { 0x60, new Instruction("neg ${0:x2},x", 0x60, 2) },
        { 0x63, new Instruction("com ${0:x2},x", 0x63, 2) },
        { 0x64, new Instruction("lsr ${0:x2},x", 0x64, 2) },
        { 0x66, new Instruction("ror ${0:x2},x", 0x66, 2) },
        { 0x67, new Instruction("asr ${0:x2},x", 0x67, 2) },
        { 0x68, new Instruction("asl ${0:x2},x", 0x68, 2) },
        { 0x69, new Instruction("rol ${0:x2},x", 0x69, 2) },
        { 0x6a, new Instruction("dec ${0:x2},x", 0x6a, 2) },
        { 0x6c, new Instruction("inc ${0:x2},x", 0x6c, 2) },
        { 0x6d, new Instruction("tst ${0:x2},x", 0x6d, 2) },
        { 0x6e, new Instruction("jmp ${0:x2},x", 0x6e, 2) },
        { 0x6f, new Instruction("clr ${0:x2},x", 0x6f, 2) },
        { 0x70, new Instruction("neg ${0:x4}", 0x70, 3) },
        { 0x73, new Instruction("com ${0:x4}", 0x73, 3) },
        { 0x74, new Instruction("lsr ${0:x4}", 0x74, 3) },
        { 0x76, new Instruction("ror ${0:x4}", 0x76, 3) },
        { 0x77, new Instruction("asr ${0:x4}", 0x77, 3) },
        { 0x78, new Instruction("asl ${0:x4}", 0x78, 3) },
        { 0x79, new Instruction("rol ${0:x4}", 0x79, 3) },
        { 0x7a, new Instruction("dec ${0:x4}", 0x7a, 3) },
        { 0x7c, new Instruction("inc ${0:x4}", 0x7c, 3) },
        { 0x7d, new Instruction("tst ${0:x4}", 0x7d, 3) },
        { 0x7e, new Instruction("jmp ${0:x4}", 0x7e, 3) },
        { 0x7f, new Instruction("clr ${0:x4}", 0x7f, 3) },
        { 0x80, new Instruction("suba #${0:x2}", 0x80, 2) },
        { 0x81, new Instruction("cmpa #${0:x2}", 0x81, 2) },
        { 0x82, new Instruction("sbca #${0:x2}", 0x82, 2) },
        { 0x84, new Instruction("anda #${0:x2}", 0x84, 2) },
        { 0x85, new Instruction("bita #${0:x2}", 0x85, 2) },
        { 0x86, new Instruction("ldaa #${0:x2}", 0x86, 2) },
        { 0x88, new Instruction("eora #${0:x2}", 0x88, 2) },
        { 0x89, new Instruction("adca #${0:x2}", 0x89, 2) },
        { 0x8a, new Instruction("oraa #${0:x2}", 0x8a, 2) },
        { 0x8b, new Instruction("adda #${0:x2}", 0x8b, 2) },
        { 0x8c, new Instruction("cpxa #${0:x2}", 0x8c, 2) },
        { 0x8d, new Instruction("bsr ${0:x4}", 0x8d, 2) },
        { 0x8e, new Instruction("lds #${0:x4}", 0x8e, 3) },
        { 0x90, new Instruction("suba ${0:x2}", 0x90, 2) },
        { 0x91, new Instruction("cmpa ${0:x2}", 0x91, 2) },
        { 0x92, new Instruction("sbca ${0:x2}", 0x92, 2) },
        { 0x94, new Instruction("anda ${0:x2}", 0x94, 2) },
        { 0x95, new Instruction("bita ${0:x2}", 0x95, 2) },
        { 0x96, new Instruction("ldaa ${0:x2}", 0x96, 2) },
        { 0x97, new Instruction("staa ${0:x2}", 0x97, 2) },
        { 0x98, new Instruction("eora ${0:x2}", 0x98, 2) },
        { 0x99, new Instruction("adca ${0:x2}", 0x99, 2) },
        { 0x9a, new Instruction("oraa ${0:x2}", 0x9a, 2) },
        { 0x9b, new Instruction("adda ${0:x2}", 0x9b, 2) },
        { 0x9c, new Instruction("cpxa ${0:x2}", 0x9c, 2) },
        { 0x9e, new Instruction("lds ${0:x2}", 0x9e, 2) },
        { 0x9f, new Instruction("sts ${0:x2}", 0x9f, 2) },
        { 0xa0, new Instruction("suba ${0:x2},x", 0xa0, 2) },
        { 0xa1, new Instruction("cmpa ${0:x2},x", 0xa1, 2) },
        { 0xa2, new Instruction("sbca ${0:x2},x", 0xa2, 2) },
        { 0xa4, new Instruction("anda ${0:x2},x", 0xa4, 2) },
        { 0xa5, new Instruction("bita ${0:x2},x", 0xa5, 2) },
        { 0xa6, new Instruction("ldaa ${0:x2},x", 0xa6, 2) },
        { 0xa7, new Instruction("staa ${0:x2},x", 0xa7, 2) },
        { 0xa8, new Instruction("eora ${0:x2},x", 0xa8, 2) },
        { 0xa9, new Instruction("adca ${0:x2},x", 0xa9, 2) },
        { 0xaa, new Instruction("oraa ${0:x2},x", 0xaa, 2) },
        { 0xab, new Instruction("adda ${0:x2},x", 0xab, 2) },
        { 0xac, new Instruction("cpxa ${0:x2},x", 0xac, 2) },
        { 0xad, new Instruction("jsr ${0:x2},x", 0xad, 2) },
        { 0xae, new Instruction("lds ${0:x2},x", 0xae, 2) },
        { 0xaf, new Instruction("sts ${0:x2},x", 0xaf, 2) },
        { 0xb0, new Instruction("suba ${0:x4}", 0xb0, 3) },
        { 0xb1, new Instruction("cmpa ${0:x4}", 0xb1, 3) },
        { 0xb2, new Instruction("sbca ${0:x4}", 0xb2, 3) },
        { 0xb4, new Instruction("anda ${0:x4}", 0xb4, 3) },
        { 0xb5, new Instruction("bita ${0:x4}", 0xb5, 3) },
        { 0xb6, new Instruction("ldaa ${0:x4}", 0xb6, 3) },
        { 0xb7, new Instruction("staa ${0:x4}", 0xb7, 3) },
        { 0xb8, new Instruction("eora ${0:x4}", 0xb8, 3) },
        { 0xb9, new Instruction("adca ${0:x4}", 0xb9, 3) },
        { 0xba, new Instruction("oraa ${0:x4}", 0xba, 3) },
        { 0xbb, new Instruction("adda ${0:x4}", 0xbb, 3) },
        { 0xbc, new Instruction("cpxa ${0:x4}", 0xbc, 3) },
        { 0xbd, new Instruction("jsr ${0:x4}", 0xbd, 3) },
        { 0xbe, new Instruction("lds ${0:x4}", 0xbe, 3) },
        { 0xbf, new Instruction("sts ${0:x4}", 0xbf, 3) },
        { 0xc0, new Instruction("subb #${0:x2}", 0xc0, 2) },
        { 0xc1, new Instruction("cmpb #${0:x2}", 0xc1, 2) },
        { 0xc2, new Instruction("sbcb #${0:x2}", 0xc2, 2) },
        { 0xc4, new Instruction("andb #${0:x2}", 0xc4, 2) },
        { 0xc5, new Instruction("bitb #${0:x2}", 0xc5, 2) },
        { 0xc6, new Instruction("ldab #${0:x2}", 0xc6, 2) },
        { 0xc7, new Instruction("staa #${0:x2}", 0xc7, 2) },
        { 0xc8, new Instruction("eorb #${0:x2}", 0xc8, 2) },
        { 0xc9, new Instruction("adcb #${0:x2}", 0xc9, 2) },
        { 0xca, new Instruction("orab #${0:x2}", 0xca, 2) },
        { 0xcb, new Instruction("addb #${0:x2}", 0xcb, 2) },
        { 0xce, new Instruction("ldx #${0:x4}", 0xce, 3) },
        { 0xd0, new Instruction("subb ${0:x2}", 0xd0, 2) },
        { 0xd1, new Instruction("cmpb ${0:x2}", 0xd1, 2) },
        { 0xd2, new Instruction("sbcb ${0:x2}", 0xd2, 2) },
        { 0xd4, new Instruction("andb ${0:x2}", 0xd4, 2) },
        { 0xd5, new Instruction("bitb ${0:x2}", 0xd5, 2) },
        { 0xd6, new Instruction("ldab ${0:x2}", 0xd6, 2) },
        { 0xd7, new Instruction("stab ${0:x2}", 0xd7, 2) },
        { 0xd8, new Instruction("eorb ${0:x2}", 0xd8, 2) },
        { 0xd9, new Instruction("adcb ${0:x2}", 0xd9, 2) },
        { 0xda, new Instruction("orab ${0:x2}", 0xda, 2) },
        { 0xdb, new Instruction("addb ${0:x2}", 0xdb, 2) },
        { 0xde, new Instruction("ldx ${0:x2}", 0xde, 2) },
        { 0xdf, new Instruction("stx ${0:x2}", 0xdf, 2) },
        { 0xe0, new Instruction("subb ${0:x2},x", 0xe0, 2) },
        { 0xe1, new Instruction("cmpb ${0:x2},x", 0xe1, 2) },
        { 0xe2, new Instruction("sbcb ${0:x2},x", 0xe2, 2) },
        { 0xe4, new Instruction("andb ${0:x2},x", 0xe4, 2) },
        { 0xe5, new Instruction("bitb ${0:x2},x", 0xe5, 2) },
        { 0xe6, new Instruction("ldab ${0:x2},x", 0xe6, 2) },
        { 0xe7, new Instruction("stab ${0:x2},x", 0xe7, 2) },
        { 0xe8, new Instruction("eorb ${0:x2},x", 0xe8, 2) },
        { 0xe9, new Instruction("adcb ${0:x2},x", 0xe9, 2) },
        { 0xea, new Instruction("orab ${0:x2},x", 0xea, 2) },
        { 0xeb, new Instruction("addb ${0:x2},x", 0xeb, 2) },
        { 0xee, new Instruction("ldx ${0:x2},x", 0xee, 2) },
        { 0xef, new Instruction("stx ${0:x2},x", 0xef, 2) },
        { 0xf0, new Instruction("subb ${0:x4}", 0xf0, 3) },
        { 0xf1, new Instruction("cmpb ${0:x4}", 0xf1, 3) },
        { 0xf2, new Instruction("sbcb ${0:x4}", 0xf2, 3) },
        { 0xf4, new Instruction("andb ${0:x4}", 0xf4, 3) },
        { 0xf5, new Instruction("bitb ${0:x4}", 0xf5, 3) },
        { 0xf6, new Instruction("ldab ${0:x4}", 0xf6, 3) },
        { 0xf7, new Instruction("stab ${0:x4}", 0xf7, 3) },
        { 0xf8, new Instruction("eorb ${0:x4}", 0xf8, 3) },
        { 0xf9, new Instruction("adcb ${0:x4}", 0xf9, 3) },
        { 0xfa, new Instruction("orab ${0:x4}", 0xfa, 3) },
        { 0xfb, new Instruction("addb ${0:x4}", 0xfb, 3) },
        { 0xfe, new Instruction("ldx ${0:x4}", 0xfe, 3) },
        { 0xff, new Instruction("stx ${0:x4}", 0xff, 3) },
    };

    private static readonly Dictionary<int, M6xxOpcode> s_m6809Opcodes = new()
    {
        //                                          Impl      Zp     Rel     Abs     Imm     ZpX  RelAbs  ImmAbs
        { SyntaxParser.ASL,  new M6xxOpcode(    Bad,   0x08,    Bad,   0x78,    Bad,   0x68,    Bad,    Bad) },
        { SyntaxParser.BCC,  new M6xxOpcode(    Bad,    Bad,   0x24,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BCS,  new M6xxOpcode(    Bad,    Bad,   0x25,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BEQ,  new M6xxOpcode(    Bad,    Bad,   0x27,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BMI,  new M6xxOpcode(    Bad,    Bad,   0x2B,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BNE,  new M6xxOpcode(    Bad,    Bad,   0x26,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BPL,  new M6xxOpcode(    Bad,    Bad,   0x2A,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BVC,  new M6xxOpcode(    Bad,    Bad,   0x28,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BVS,  new M6xxOpcode(    Bad,    Bad,   0x29,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.DEC,  new M6xxOpcode(    Bad,   0x0A,    Bad,   0x7A,    Bad,   0x6A,    Bad,    Bad) },
        { SyntaxParser.INC,  new M6xxOpcode(    Bad,   0x0C,    Bad,   0x7C,    Bad,   0x6C,    Bad,    Bad) },
        { SyntaxParser.JMP,  new M6xxOpcode(    Bad,   0x0E,    Bad,   0x7E,    Bad,   0x6E,    Bad,    Bad) },
        { SyntaxParser.JSR,  new M6xxOpcode(    Bad,   0x9D,    Bad,   0xBD,    Bad,   0xAD,    Bad,    Bad) },
        { SyntaxParser.LDA,  new M6xxOpcode(    Bad,   0x96,    Bad,   0xB6,   0x86,   0xA6,    Bad,    Bad) },
        { SyntaxParser.LDX,  new M6xxOpcode(    Bad,   0x9E,    Bad,   0xBE,    Bad,   0xAE,    Bad,   0x8E) },
        { SyntaxParser.LDY,  new M6xxOpcode(    Bad, 0x109E,    Bad, 0x10BE,    Bad, 0x10AE,    Bad, 0x108E) },
        { SyntaxParser.LSR,  new M6xxOpcode(    Bad,   0x04,    Bad,   0x74,    Bad,   0x64,    Bad,    Bad) },
        { SyntaxParser.NOP,  new M6xxOpcode(   0x12,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.ORA,  new M6xxOpcode(    Bad,   0x9A,    Bad,   0xBA,   0x8A,   0xAA,    Bad,    Bad) },
        { SyntaxParser.ROL,  new M6xxOpcode(    Bad,   0x09,    Bad,   0x79,    Bad,   0x69,    Bad,    Bad) },
        { SyntaxParser.ROR,  new M6xxOpcode(    Bad,   0x06,    Bad,   0x76,    Bad,   0x66,    Bad,    Bad) },
        { SyntaxParser.RTI,  new M6xxOpcode(   0x3B,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.RTS,  new M6xxOpcode(   0x39,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.STA,  new M6xxOpcode(    Bad,   0x97,    Bad,   0xB7,    Bad,   0xA7,    Bad,    Bad) },
        { SyntaxParser.STX,  new M6xxOpcode(    Bad,   0x9F,    Bad,   0xBF,    Bad,   0xAF,    Bad,    Bad) },
        { SyntaxParser.STY,  new M6xxOpcode(    Bad, 0x109F,    Bad, 0x10BF,    Bad, 0x10AF,    Bad,    Bad) },
        //                                          Impl      Zp     Rel     Abs     Imm     ZpX  RelAbs  ImmAbs
        { SyntaxParser.ASR,  new M6xxOpcode(    Bad,   0x07,    Bad,   0x77,    Bad,   0x67,    Bad,    Bad) },
        { SyntaxParser.BRA,  new M6xxOpcode(    Bad,    Bad,   0x20,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BGE,  new M6xxOpcode(    Bad,    Bad,   0x2C,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BLT,  new M6xxOpcode(    Bad,    Bad,   0x2D,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BSR,  new M6xxOpcode(    Bad,    Bad,   0x8D,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.ADCA, new M6xxOpcode(    Bad,   0x99,    Bad,   0xB9,   0x89,   0xA9,    Bad,    Bad) },
        { SyntaxParser.ADCB, new M6xxOpcode(    Bad,   0xD9,    Bad,   0xF9,   0xC9,   0xE9,    Bad,    Bad) },
        { SyntaxParser.ADDA, new M6xxOpcode(    Bad,   0x9B,    Bad,   0xBB,   0x8B,   0xAB,    Bad,    Bad) },
        { SyntaxParser.ADDB, new M6xxOpcode(    Bad,   0xDB,    Bad,   0xFB,   0xCB,   0xEB,    Bad,    Bad) },
        { SyntaxParser.ANDA, new M6xxOpcode(    Bad,   0x94,    Bad,   0xB4,   0x84,   0xA4,    Bad,    Bad) },
        { SyntaxParser.ANDB, new M6xxOpcode(    Bad,   0xD4,    Bad,   0xF4,   0xC4,   0xE4,    Bad,    Bad) },
        { SyntaxParser.ASLA, new M6xxOpcode(   0x48,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.ASLB, new M6xxOpcode(   0x58,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.ASRA, new M6xxOpcode(   0x47,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.ASRB, new M6xxOpcode(   0x57,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BGT,  new M6xxOpcode(    Bad,    Bad,   0x2E,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BHI,  new M6xxOpcode(    Bad,    Bad,   0x22,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BITA, new M6xxOpcode(    Bad,   0x95,    Bad,   0xB5,   0x85,   0xA5,    Bad,    Bad) },
        { SyntaxParser.BITB, new M6xxOpcode(    Bad,   0xD5,    Bad,   0xF5,   0xC5,   0xE5,    Bad,    Bad) },
        { SyntaxParser.BLE,  new M6xxOpcode(    Bad,    Bad,   0x2F,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BLS,  new M6xxOpcode(    Bad,    Bad,   0x23,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.CLR,  new M6xxOpcode(    Bad,   0x0F,    Bad,   0x7F,    Bad,   0x6F,    Bad,    Bad) },
        { SyntaxParser.CLRA, new M6xxOpcode(   0x4F,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.CLRB, new M6xxOpcode(   0x5F,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.CMPA, new M6xxOpcode(    Bad,   0x91,    Bad,   0xB1,   0x81,   0xA1,    Bad,    Bad) },
        { SyntaxParser.CMPB, new M6xxOpcode(    Bad,   0xD1,    Bad,   0xF1,   0xC1,   0xE1,    Bad,    Bad) },
        { SyntaxParser.COM,  new M6xxOpcode(    Bad,   0x03,    Bad,   0x73,    Bad,   0x63,    Bad,    Bad) },
        { SyntaxParser.COMA, new M6xxOpcode(   0x43,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        //                                          Impl      Zp     Rel     Abs     Imm     ZpX  RelAbs  ImmAbs
        { SyntaxParser.COMB, new M6xxOpcode(   0x53,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.CPXA, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.DECA, new M6xxOpcode(   0x4A,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.DECB, new M6xxOpcode(   0x5A,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.EORA, new M6xxOpcode(    Bad,   0x98,    Bad,   0xB8,   0x88,   0xA8,    Bad,    Bad) },
        { SyntaxParser.EORB, new M6xxOpcode(    Bad,   0xD8,    Bad,   0xF8,   0xC8,   0xE8,    Bad,    Bad) },
        { SyntaxParser.INCA, new M6xxOpcode(   0x4C,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.INCB, new M6xxOpcode(   0x5C,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.LDS,  new M6xxOpcode(    Bad, 0x10DE,    Bad, 0x10FE,    Bad, 0x10EE,    Bad, 0x10CE) },
        { SyntaxParser.LSRA, new M6xxOpcode(   0x44,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.LSRB, new M6xxOpcode(   0x54,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.NEGA, new M6xxOpcode(   0x40,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.NEGB, new M6xxOpcode(   0x50,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.ORAA, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.ROLA, new M6xxOpcode(   0x49,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.ROLB, new M6xxOpcode(   0x59,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.RORA, new M6xxOpcode(   0x46,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.RORB, new M6xxOpcode(   0x56,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.SBCA, new M6xxOpcode(    Bad,   0x92,    Bad,   0xB2,   0x82,   0xA2,    Bad,    Bad) },
        { SyntaxParser.SBCB, new M6xxOpcode(    Bad,   0xD2,    Bad,   0xF2,   0xC2,   0xE2,    Bad,    Bad) },
        { SyntaxParser.STS,  new M6xxOpcode(    Bad, 0x10DF,    Bad, 0x10FF,    Bad, 0x10EF,    Bad,    Bad) },
        { SyntaxParser.SUBA, new M6xxOpcode(    Bad,   0x90,    Bad,   0xB0,   0x80,   0xA0,    Bad,    Bad) },
        { SyntaxParser.SUBB, new M6xxOpcode(    Bad,   0xD0,    Bad,   0xF0,   0xC0,   0xE0,    Bad,    Bad) },
        { SyntaxParser.SWI,  new M6xxOpcode(   0x3F,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.TSTA, new M6xxOpcode(   0x4D,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.TSTB, new M6xxOpcode(   0x5D,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.ABX,  new M6xxOpcode(   0x3A,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.ADDD, new M6xxOpcode(    Bad,   0xD3,    Bad,   0xF2,    Bad,   0xE3,    Bad,   0xC3) },
        //                                          Impl      Zp     Rel     Abs     Imm     ZpX  RelAbs  ImmAbs
        { SyntaxParser.ANDCC,new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,   0x1C,    Bad,    Bad,    Bad) },
        { SyntaxParser.BHS,  new M6xxOpcode(    Bad,    Bad,   0x24,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BLO,  new M6xxOpcode(    Bad,    Bad,   0x25,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.BRN,  new M6xxOpcode(    Bad,    Bad,   0x21,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.CMPD, new M6xxOpcode(    Bad, 0x1093,    Bad, 0x10B3,    Bad, 0x10A3,    Bad, 0x1083) },
        { SyntaxParser.CMPS, new M6xxOpcode(    Bad, 0x119C,    Bad, 0x11BC,    Bad, 0x11AC,    Bad, 0x118C) },
        { SyntaxParser.CMPU, new M6xxOpcode(    Bad, 0x1193,    Bad, 0x11B3,    Bad, 0x11A3,    Bad, 0x1183) },
        { SyntaxParser.CMPX, new M6xxOpcode(    Bad,   0x9C,    Bad,   0xBC,    Bad,   0xAC,    Bad,   0x8C) },
        { SyntaxParser.CMPY, new M6xxOpcode(    Bad, 0x109C,    Bad, 0x10BC,    Bad, 0x10AC,    Bad, 0x108C) },
        { SyntaxParser.CWAI, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,   0x3C,    Bad,    Bad,    Bad) },
        { SyntaxParser.DAA,  new M6xxOpcode(   0x19,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.EXG,  new M6xxOpcode(    Bad,   0x1E,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.LBCC, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x1024,    Bad) },
        { SyntaxParser.LBCS, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x1025,    Bad) },
        { SyntaxParser.LBEQ, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x1027,    Bad) },
        { SyntaxParser.LBGE, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x102C,    Bad) },
        { SyntaxParser.LBGT, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x102E,    Bad) },
        { SyntaxParser.LBHI, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x1022,    Bad) },
        { SyntaxParser.LBHS, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x1024,    Bad) },
        { SyntaxParser.LBLE, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x102F,    Bad) },
        { SyntaxParser.LBLO, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x1025,    Bad) },
        { SyntaxParser.LBLS, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x1023,    Bad) },
        { SyntaxParser.LBLT, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x102D,    Bad) },
        { SyntaxParser.LBMI, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x102B,    Bad) },
        { SyntaxParser.LBNE, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x1026,    Bad) },
        { SyntaxParser.LBPL, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x102A,    Bad) },
        { SyntaxParser.LBRA, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,   0x16,    Bad) },
        { SyntaxParser.LBRN, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x1021,    Bad) },
        //                                          Impl      Zp     Rel     Abs     Imm     ZpX  RelAbs  ImmAbs
        { SyntaxParser.LBSR, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,   0x17,    Bad) },
        { SyntaxParser.LBVC, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x1028,    Bad) },
        { SyntaxParser.LBVS, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x1029,    Bad) },
        { SyntaxParser.LDB,  new M6xxOpcode(    Bad,   0xD6,    Bad,   0xF6,   0xC6,   0xE6,    Bad,    Bad) },
        { SyntaxParser.LDD,  new M6xxOpcode(    Bad,   0xDC,    Bad,   0xFC,    Bad,   0xEC,    Bad,   0xCC) },
        { SyntaxParser.LDU,  new M6xxOpcode(    Bad,   0xDE,    Bad,   0xFE,    Bad,   0xEE,    Bad,   0xCE) },
        { SyntaxParser.LEAS, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,   0x32,    Bad,    Bad) },
        { SyntaxParser.LEAU, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,   0x33,    Bad,    Bad) },
        { SyntaxParser.LEAX, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,   0x30,    Bad,    Bad) },
        { SyntaxParser.LEAY, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,   0x31,    Bad,    Bad) },
        { SyntaxParser.LSL,  new M6xxOpcode(    Bad,   0x08,    Bad,   0x78,    Bad,   0x68,    Bad,    Bad) },
        { SyntaxParser.LSLA, new M6xxOpcode(   0x48,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.LSLB, new M6xxOpcode(   0x58,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.MUL,  new M6xxOpcode(   0x3D,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.NEG,  new M6xxOpcode(    Bad,   0x00,    Bad,   0x70,    Bad,   0x60,    Bad,    Bad) },
        { SyntaxParser.ORB,  new M6xxOpcode(    Bad,   0xDA,    Bad,   0xFA,   0xCA,   0xEA,    Bad,    Bad) },
        { SyntaxParser.ORCC, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,   0x1A,    Bad,    Bad,    Bad) },
        { SyntaxParser.PSHS, new M6xxOpcode(    Bad,   0x34,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.PSHU, new M6xxOpcode(    Bad,   0x36,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.PULS, new M6xxOpcode(    Bad,   0x35,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.PULU, new M6xxOpcode(    Bad,   0x37,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.SEX,  new M6xxOpcode(   0x1D,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.STB,  new M6xxOpcode(    Bad,   0xD7,    Bad,   0xF7,    Bad,   0xE7,    Bad,    Bad) },
        { SyntaxParser.STD,  new M6xxOpcode(    Bad,   0xDD,    Bad,   0xFD,    Bad,   0xED,    Bad,    Bad) },
        { SyntaxParser.STU,  new M6xxOpcode(    Bad,   0xDF,    Bad,   0xFF,    Bad,   0xEF,    Bad,    Bad) },
        { SyntaxParser.SUBD, new M6xxOpcode(    Bad,   0x93,    Bad,   0xB3,    Bad,   0xA3,    Bad,   0x83) },
        { SyntaxParser.SWI2, new M6xxOpcode( 0x103F,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.SWI3, new M6xxOpcode( 0x113F,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.SYNC, new M6xxOpcode(   0x13,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.TFR,  new M6xxOpcode(    Bad,   0x1F,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { SyntaxParser.TST,  new M6xxOpcode(    Bad,   0x0D,    Bad,   0x7D,    Bad,   0x6D,    Bad,    Bad) }
    };
 
    private readonly static Dictionary<int, Instruction> s_m6809Disassembly = new()
    {
        { 0x00, new Instruction("neg ${0:x2}", 0x00, 2) },
        { 0x03, new Instruction("com ${0:x2}", 0x03, 2) },
        { 0x04, new Instruction("lsr ${0:x2}", 0x04, 2) },
        { 0x06, new Instruction("ror ${0:x2}", 0x06, 2) },
        { 0x07, new Instruction("asr ${0:x2}", 0x07, 2) },
        { 0x08, new Instruction("lsl ${0:x2}", 0x08, 2) },
        { 0x09, new Instruction("rol ${0:x2}", 0x09, 2) },
        { 0x0a, new Instruction("dec ${0:x2}", 0x0a, 2) },
        { 0x0c, new Instruction("inc ${0:x2}", 0x0c, 2) },
        { 0x0d, new Instruction("tst ${0:x2}", 0x0d, 2) },
        { 0x0e, new Instruction("jmp ${0:x2}", 0x0e, 2) },
        { 0x0f, new Instruction("clr ${0:x2}", 0x0f, 2) },
        { 0x1021, new Instruction("lbrn ${0:x4}", 0x1021, 4, true, true) },
        { 0x1022, new Instruction("lbhi ${0:x4}", 0x1022, 4, true, true) },
        { 0x1023, new Instruction("lbls ${0:x4}", 0x1023, 4, true, true) },
        { 0x1024, new Instruction("lbhs ${0:x4}", 0x1024, 4, true, true) },
        { 0x1025, new Instruction("lblo ${0:x4}", 0x1025, 4, true, true) },
        { 0x1026, new Instruction("lbne ${0:x4}", 0x1026, 4, true, true) },
        { 0x1027, new Instruction("lbeq ${0:x4}", 0x1027, 4, true, true) },
        { 0x1028, new Instruction("lbvc ${0:x4}", 0x1028, 4, true, true) },
        { 0x1029, new Instruction("lbvs ${0:x4}", 0x1029, 4, true, true) },
        { 0x102a, new Instruction("lbpl ${0:x4}", 0x102a, 4, true, true) },
        { 0x102b, new Instruction("lbmi ${0:x4}", 0x102b, 4, true, true) },
        { 0x102c, new Instruction("lbge ${0:x4}", 0x102c, 4, true, true) },
        { 0x102d, new Instruction("lblt ${0:x4}", 0x102d, 4, true, true) },
        { 0x102e, new Instruction("lbgt ${0:x4}", 0x102e, 4, true, true) },
        { 0x102f, new Instruction("lble ${0:x4}", 0x102f, 4, true, true) },
        { 0x103f, new Instruction("swi2", 0x103f, 2) },
        { 0x1083, new Instruction("cmpd #${0:x4}", 0x1083, 4) },
        { 0x108c, new Instruction("cmpy #${0:x4}", 0x108c, 4) },
        { 0x108e, new Instruction("ldy #${0:x4}", 0x108e, 4) },
        { 0x1093, new Instruction("cmpd ${0:x2}", 0x1093, 3) },
        { 0x109c, new Instruction("cmpy ${0:x2}", 0x109c, 3) },
        { 0x109e, new Instruction("ldy ${0:x2}", 0x109e, 3) },
        { 0x109f, new Instruction("sty ${0:x2}", 0x109f, 3) },
        { 0x10a3, new Instruction("cmpd", 0x10a3, 3) },
        { 0x10ac, new Instruction("cmpy", 0x10ac, 3) },
        { 0x10ae, new Instruction("ldy", 0x10ae, 3) },
        { 0x10af, new Instruction("sty", 0x10af, 3) },
        { 0x10b3, new Instruction("cmpd ${0:x4}", 0x10b3, 4) },
        { 0x10bc, new Instruction("cmpy ${0:x4}", 0x10bc, 4) },
        { 0x10be, new Instruction("ldy ${0:x4}", 0x10be, 4) },
        { 0x10bf, new Instruction("sty ${0:x4}", 0x10bf, 4) },
        { 0x10ce, new Instruction("lds #${0:x4}", 0x10ce, 4) },
        { 0x10de, new Instruction("lds ${0:x2}", 0x10de, 3) },
        { 0x10df, new Instruction("sts ${0:x2}", 0x10df, 3) },
        { 0x10ee, new Instruction("lds", 0x10ee, 3) },
        { 0x10ef, new Instruction("sts", 0x10ef, 3) },
        { 0x10fe, new Instruction("lds ${0:x4}", 0x10fe, 4) },
        { 0x10ff, new Instruction("sts ${0:x4}", 0x10ff, 4) },
        { 0x113f, new Instruction("swi3", 0x113f, 2) },
        { 0x1183, new Instruction("cmpu #${0:x4}", 0x1183, 4) },
        { 0x118c, new Instruction("cmps #${0:x4}", 0x118c, 4) },
        { 0x1193, new Instruction("cmpu ${0:x2}", 0x1193, 3) },
        { 0x119c, new Instruction("cmps ${0:x2}", 0x119c, 3) },
        { 0x11a3, new Instruction("cmpu", 0x11a3, 3) },
        { 0x11ac, new Instruction("cmps", 0x11ac, 3) },
        { 0x11b3, new Instruction("cmpu ${0:x4}", 0x11b3, 4) },
        { 0x11bc, new Instruction("cmps ${0:x4}", 0x11bc, 4) },
        { 0x12, new Instruction("nop", 0x12) },
        { 0x13, new Instruction("sync", 0x13) },
        { 0x16, new Instruction("lbra ${0:x4}", 0x16, 3, true, true) },
        { 0x17, new Instruction("lbsr ${0:x4}", 0x17, 3, true, true) },
        { 0x19, new Instruction("daa", 0x19) },
        { 0x1a, new Instruction("orcc #${0:x2}", 0x1a, 2) },
        { 0x1c, new Instruction("andcc #${0:x2}", 0x1c, 2) },
        { 0x1d, new Instruction("sex", 0x1d) },
        { 0x1e, new Instruction("exg", 0x1e, 2) },
        { 0x1f, new Instruction("tfr", 0x1f, 2) },
        { 0x20, new Instruction("bra ${0:x4}", 0x20, 2, true) },
        { 0x21, new Instruction("brn ${0:x4}", 0x21, 2, true) },
        { 0x22, new Instruction("bhi ${0:x4}", 0x22, 2, true) },
        { 0x23, new Instruction("bls ${0:x4}", 0x23, 2, true) },
        { 0x24, new Instruction("bhs ${0:x4}", 0x24, 2, true) },
        { 0x25, new Instruction("blo ${0:x4}", 0x25, 2, true) },
        { 0x26, new Instruction("bne ${0:x4}", 0x26, 2, true) },
        { 0x27, new Instruction("beq ${0:x4}", 0x27, 2, true) },
        { 0x28, new Instruction("bvc ${0:x4}", 0x28, 2, true) },
        { 0x29, new Instruction("bvs ${0:x4}", 0x29, 2, true) },
        { 0x2a, new Instruction("bpl ${0:x4}", 0x2a, 2, true) },
        { 0x2b, new Instruction("bmi ${0:x4}", 0x2b, 2, true) },
        { 0x2c, new Instruction("bge ${0:x4}", 0x2c, 2, true) },
        { 0x2d, new Instruction("blt ${0:x4}", 0x2d, 2, true) },
        { 0x2e, new Instruction("bgt ${0:x4}", 0x2e, 2, true) },
        { 0x2f, new Instruction("ble ${0:x4}", 0x2f, 2, true) },
        { 0x30, new Instruction("leax", 0x30, 2) },
        { 0x31, new Instruction("leay", 0x31, 2) },
        { 0x32, new Instruction("leas", 0x32, 2) },
        { 0x33, new Instruction("leau", 0x33, 2) },
        { 0x34, new Instruction("pshs", 0x34, 2) },
        { 0x35, new Instruction("puls", 0x35, 2) },
        { 0x36, new Instruction("pshu", 0x36, 2) },
        { 0x37, new Instruction("pulu", 0x37, 2) },
        { 0x39, new Instruction("rts", 0x39) },
        { 0x3a, new Instruction("abx", 0x3a) },
        { 0x3b, new Instruction("rti", 0x3b) },
        { 0x3c, new Instruction("cwai #${0:x2}", 0x3c, 2) },
        { 0x3d, new Instruction("mul", 0x3d) },
        { 0x3f, new Instruction("swi", 0x3f) },
        { 0x40, new Instruction("nega", 0x40) },
        { 0x43, new Instruction("coma", 0x43) },
        { 0x44, new Instruction("lsra", 0x44) },
        { 0x46, new Instruction("rora", 0x46) },
        { 0x47, new Instruction("asra", 0x47) },
        { 0x48, new Instruction("lsla", 0x48) },
        { 0x49, new Instruction("rola", 0x49) },
        { 0x4a, new Instruction("deca", 0x4a) },
        { 0x4c, new Instruction("inca", 0x4c) },
        { 0x4d, new Instruction("tsta", 0x4d) },
        { 0x4f, new Instruction("clra", 0x4f) },
        { 0x50, new Instruction("negb", 0x50) },
        { 0x53, new Instruction("comb", 0x53) },
        { 0x54, new Instruction("lsrb", 0x54) },
        { 0x56, new Instruction("rorb", 0x56) },
        { 0x57, new Instruction("asrb", 0x57) },
        { 0x58, new Instruction("aslb", 0x58) },
        { 0x59, new Instruction("rolb", 0x59) },
        { 0x5a, new Instruction("decb", 0x5a) },
        { 0x5c, new Instruction("incb", 0x5c) },
        { 0x5d, new Instruction("tstb", 0x5d) },
        { 0x5f, new Instruction("clrb", 0x5f) },
        { 0x60, new Instruction("neg", 0x60, 2) },
        { 0x63, new Instruction("com", 0x63, 2) },
        { 0x64, new Instruction("lsr", 0x64, 2) },
        { 0x66, new Instruction("ror", 0x66, 2) },
        { 0x67, new Instruction("asr", 0x67, 2) },
        { 0x68, new Instruction("lsl", 0x68, 2) },
        { 0x69, new Instruction("rol", 0x69, 2) },
        { 0x6a, new Instruction("dec", 0x6a, 2) },
        { 0x6c, new Instruction("inc", 0x6c, 2) },
        { 0x6d, new Instruction("tst", 0x6d, 2) },
        { 0x6e, new Instruction("jmp", 0x6e, 2) },
        { 0x6f, new Instruction("clr", 0x6f, 2) },
        { 0x70, new Instruction("neg ${0:x4}", 0x70, 3) },
        { 0x73, new Instruction("com ${0:x4}", 0x73, 3) },
        { 0x74, new Instruction("lsr ${0:x4}", 0x74, 3) },
        { 0x76, new Instruction("ror ${0:x4}", 0x76, 3) },
        { 0x77, new Instruction("asr ${0:x4}", 0x77, 3) },
        { 0x78, new Instruction("lsl ${0:x4}", 0x78, 3) },
        { 0x79, new Instruction("rol ${0:x4}", 0x79, 3) },
        { 0x7a, new Instruction("dec ${0:x4}", 0x7a, 3) },
        { 0x7c, new Instruction("inc ${0:x4}", 0x7c, 3) },
        { 0x7d, new Instruction("tst ${0:x4}", 0x7d, 3) },
        { 0x7e, new Instruction("jmp ${0:x4}", 0x7e, 3) },
        { 0x7f, new Instruction("clr ${0:x4}", 0x7f, 3) },
        { 0x80, new Instruction("suba #${0:x2}", 0x80, 2) },
        { 0x81, new Instruction("cmpa #${0:x2}", 0x81, 2) },
        { 0x82, new Instruction("sbca #${0:x2}", 0x82, 2) },
        { 0x83, new Instruction("subd #${0:x4}", 0x83, 3) },
        { 0x84, new Instruction("anda #${0:x2}", 0x84, 2) },
        { 0x85, new Instruction("bita #${0:x2}", 0x85, 2) },
        { 0x86, new Instruction("lda #${0:x2}", 0x86, 2) },
        { 0x88, new Instruction("eora #${0:x2}", 0x88, 2) },
        { 0x89, new Instruction("adca #${0:x2}", 0x89, 2) },
        { 0x8a, new Instruction("ora #${0:x2}", 0x8a, 2) },
        { 0x8b, new Instruction("adda #${0:x2}", 0x8b, 2) },
        { 0x8c, new Instruction("cmpx #${0:x4}", 0x8c, 3) },
        { 0x8d, new Instruction("bsr ${0:x4}", 0x8d, 2, true) },
        { 0x8e, new Instruction("ldx #${0:x4}", 0x8e, 3) },
        { 0x90, new Instruction("suba ${0:x2}", 0x90, 2) },
        { 0x91, new Instruction("cmpa ${0:x2}", 0x91, 2) },
        { 0x92, new Instruction("sbca ${0:x2}", 0x92, 2) },
        { 0x93, new Instruction("subd ${0:x2}", 0x93, 2) },
        { 0x94, new Instruction("anda ${0:x2}", 0x94, 2) },
        { 0x95, new Instruction("bita ${0:x2}", 0x95, 2) },
        { 0x96, new Instruction("lda ${0:x2}", 0x96, 2) },
        { 0x97, new Instruction("sta ${0:x2}", 0x97, 2) },
        { 0x98, new Instruction("eora ${0:x2}", 0x98, 2) },
        { 0x99, new Instruction("adca ${0:x2}", 0x99, 2) },
        { 0x9a, new Instruction("ora ${0:x2}", 0x9a, 2) },
        { 0x9b, new Instruction("adda ${0:x2}", 0x9b, 2) },
        { 0x9c, new Instruction("cmpx ${0:x2}", 0x9c, 2) },
        { 0x9d, new Instruction("jsr ${0:x2}", 0x9d, 2) },
        { 0x9e, new Instruction("ldx ${0:x2}", 0x9e, 2) },
        { 0x9f, new Instruction("stx ${0:x2}", 0x9f, 2) },
        { 0xa0, new Instruction("suba", 0xa0, 2) },
        { 0xa1, new Instruction("cmpa", 0xa1, 2) },
        { 0xa2, new Instruction("sbca", 0xa2, 2) },
        { 0xa3, new Instruction("subd", 0xa3, 2) },
        { 0xa4, new Instruction("anda", 0xa4, 2) },
        { 0xa5, new Instruction("bita", 0xa5, 2) },
        { 0xa6, new Instruction("lda", 0xa6, 2) },
        { 0xa7, new Instruction("sta", 0xa7, 2) },
        { 0xa8, new Instruction("eora", 0xa8, 2) },
        { 0xa9, new Instruction("adca", 0xa9, 2) },
        { 0xaa, new Instruction("ora", 0xaa, 2) },
        { 0xab, new Instruction("adda", 0xab, 2) },
        { 0xac, new Instruction("cmpx", 0xac, 2) },
        { 0xad, new Instruction("jsr", 0xad, 2) },
        { 0xae, new Instruction("ldx", 0xae, 2) },
        { 0xaf, new Instruction("stx", 0xaf, 2) },
        { 0xb0, new Instruction("suba ${0:x4}", 0xb0, 3) },
        { 0xb1, new Instruction("cmpa ${0:x4}", 0xb1, 3) },
        { 0xb2, new Instruction("sbca ${0:x4}", 0xb2, 3) },
        { 0xb3, new Instruction("subd ${0:x4}", 0xb3, 3) },
        { 0xb4, new Instruction("anda ${0:x4}", 0xb4, 3) },
        { 0xb5, new Instruction("bita ${0:x4}", 0xb5, 3) },
        { 0xb6, new Instruction("lda ${0:x4}", 0xb6, 3) },
        { 0xb7, new Instruction("sta ${0:x4}", 0xb7, 3) },
        { 0xb8, new Instruction("eora ${0:x4}", 0xb8, 3) },
        { 0xb9, new Instruction("adca ${0:x4}", 0xb9, 3) },
        { 0xba, new Instruction("ora ${0:x4}", 0xba, 3) },
        { 0xbb, new Instruction("adda ${0:x4}", 0xbb, 3) },
        { 0xbc, new Instruction("cmpx ${0:x4}", 0xbc, 3) },
        { 0xbd, new Instruction("jsr ${0:x4}", 0xbd, 3) },
        { 0xbe, new Instruction("ldx ${0:x4}", 0xbe, 3) },
        { 0xbf, new Instruction("stx ${0:x4}", 0xbf, 3) },
        { 0xc0, new Instruction("subb #${0:x2}", 0xc0, 2) },
        { 0xc1, new Instruction("cmpb #${0:x2}", 0xc1, 2) },
        { 0xc2, new Instruction("sbcb #${0:x2}", 0xc2, 2) },
        { 0xc3, new Instruction("addd #${0:x4}", 0xc3, 3) },
        { 0xc4, new Instruction("andb #${0:x2}", 0xc4, 2) },
        { 0xc5, new Instruction("bitb #${0:x2}", 0xc5, 2) },
        { 0xc6, new Instruction("ldb #${0:x2}", 0xc6, 2) },
        { 0xc8, new Instruction("eorb #${0:x2}", 0xc8, 2) },
        { 0xc9, new Instruction("adcb #${0:x2}", 0xc9, 2) },
        { 0xca, new Instruction("orb #${0:x2}", 0xca, 2) },
        { 0xcb, new Instruction("addb #${0:x2}", 0xcb, 2) },
        { 0xcc, new Instruction("ldd #${0:x4}", 0xcc, 3) },
        { 0xce, new Instruction("ldu #${0:x4}", 0xce, 3) },
        { 0xd0, new Instruction("subb ${0:x2}", 0xd0, 2) },
        { 0xd1, new Instruction("cmpb ${0:x2}", 0xd1, 2) },
        { 0xd2, new Instruction("sbcb ${0:x2}", 0xd2, 2) },
        { 0xd3, new Instruction("addd ${0:x2}", 0xd3, 2) },
        { 0xd4, new Instruction("andb ${0:x2}", 0xd4, 2) },
        { 0xd5, new Instruction("bitb ${0:x2}", 0xd5, 2) },
        { 0xd6, new Instruction("ldb ${0:x2}", 0xd6, 2) },
        { 0xd7, new Instruction("stb ${0:x2}", 0xd7, 2) },
        { 0xd8, new Instruction("eorb ${0:x2}", 0xd8, 2) },
        { 0xd9, new Instruction("adcb ${0:x2}", 0xd9, 2) },
        { 0xda, new Instruction("orb ${0:x2}", 0xda, 2) },
        { 0xdb, new Instruction("addb ${0:x2}", 0xdb, 2) },
        { 0xdc, new Instruction("ldd ${0:x2}", 0xdc, 2) },
        { 0xdd, new Instruction("std ${0:x2}", 0xdd, 2) },
        { 0xde, new Instruction("ldu ${0:x2}", 0xde, 2) },
        { 0xdf, new Instruction("stu ${0:x2}", 0xdf, 2) },
        { 0xe0, new Instruction("subb", 0xe0, 2) },
        { 0xe1, new Instruction("cmpb", 0xe1, 2) },
        { 0xe2, new Instruction("sbcb", 0xe2, 2) },
        { 0xe3, new Instruction("addd", 0xe3, 2) },
        { 0xe4, new Instruction("andb", 0xe4, 2) },
        { 0xe5, new Instruction("bitb", 0xe5, 2) },
        { 0xe6, new Instruction("ldb", 0xe6, 2) },
        { 0xe7, new Instruction("stb", 0xe7, 2) },
        { 0xe8, new Instruction("eorb", 0xe8, 2) },
        { 0xe9, new Instruction("adcb", 0xe9, 2) },
        { 0xea, new Instruction("orb", 0xea, 2) },
        { 0xeb, new Instruction("addb", 0xeb, 2) },
        { 0xec, new Instruction("ldd", 0xec, 2) },
        { 0xed, new Instruction("std", 0xed, 2) },
        { 0xee, new Instruction("ldu", 0xee, 2) },
        { 0xef, new Instruction("stu", 0xef, 2) },
        { 0xf0, new Instruction("subb ${0:x4}", 0xf0, 3) },
        { 0xf1, new Instruction("cmpb ${0:x4}", 0xf1, 3) },
        { 0xf2, new Instruction("addd ${0:x4}", 0xf2, 3) },
        { 0xf4, new Instruction("andb ${0:x4}", 0xf4, 3) },
        { 0xf5, new Instruction("bitb ${0:x4}", 0xf5, 3) },
        { 0xf6, new Instruction("ldb ${0:x4}", 0xf6, 3) },
        { 0xf7, new Instruction("stb ${0:x4}", 0xf7, 3) },
        { 0xf8, new Instruction("eorb ${0:x4}", 0xf8, 3) },
        { 0xf9, new Instruction("adcb ${0:x4}", 0xf9, 3) },
        { 0xfa, new Instruction("orb ${0:x4}", 0xfa, 3) },
        { 0xfb, new Instruction("addb ${0:x4}", 0xfb, 3) },
        { 0xfc, new Instruction("ldd ${0:x4}", 0xfc, 3) },
        { 0xfd, new Instruction("std ${0:x4}", 0xfd, 3) },
        { 0xfe, new Instruction("ldu ${0:x4}", 0xfe, 3) },
        { 0xff, new Instruction("stu ${0:x4}", 0xff, 3) },
    };

    private static readonly HashSet<int> s_m6809IndexedCodes = new()
    {
        0x30,
        0x31,
        0x32,
        0x33,
        0x60,
        0x63,
        0x64,
        0x66,
        0x67,
        0x68,
        0x68,
        0x69,
        0x6a,
        0x6c,
        0x6d,
        0x6e,
        0x6f,
        0xa0,
        0xa1,
        0xa2,
        0xa3,
        0xa4,
        0xa5,
        0xa6,
        0xa7,
        0xa8,
        0xa9,
        0xaa,
        0xab,
        0xac,
        0xad,
        0xae,
        0xaf,
        0xe0,
        0xe1,
        0xe2,
        0xe3,
        0xe4,
        0xe5,
        0xe6,
        0xe7,
        0xe8,
        0xe9,
        0xea,
        0xeb,
        0xec,
        0xed,
        0xee,
        0xef,
        0x10a3,
        0x10ac,
        0x10ae,
        0x10af,
        0x10ee,
        0x10ef,
        0x11a3,
        0x11ac,
    };

    private static readonly int[] s_regOpcodes =
    {
        0x1e, 0x1f, 0x34, 0x35, 0x36, 0x37
    };

    private static readonly Dictionary<int, int> s_exchangeModes = new()
    {
        { SyntaxParser.D,  0b0000 },
        { SyntaxParser.X,  0b0001 },
        { SyntaxParser.Y,  0b0010 },
        { SyntaxParser.U,  0b0011 },
        { SyntaxParser.S,  0b0100 },
        { SyntaxParser.PC, 0b0101 },
        { SyntaxParser.A,  0b1000 },
        { SyntaxParser.B,  0b1001 },
        { SyntaxParser.CC, 0b1010 },
        { SyntaxParser.DP, 0b1011 }
    };

    private static readonly Dictionary<int, string> s_exchangeRegsLu = new()
    {
        { 0b0000, "d" },
        { 0b0001, "x" },
        { 0b0010, "y" },
        { 0b0011, "u" },
        { 0b0100, "s" },
        { 0b0101, "pc" },
        { 0b1000, "a" },
        { 0b1001, "b" },
        { 0b1010, "cc" },
        { 0b1011, "dp" }
    };

    private static readonly Dictionary<int, int> s_pushPullModes = new()
    {
        { SyntaxParser.PC, 0b1000_0000 },
        { SyntaxParser.S,  0b0100_0000 },
        { SyntaxParser.U,  0b0100_0000 },
        { SyntaxParser.Y,  0b0010_0000 },
        { SyntaxParser.X,  0b0001_0000 },
        { SyntaxParser.DP, 0b0000_1000 },
        { SyntaxParser.D,  0b0000_0110 },
        { SyntaxParser.B,  0b0000_0100 },
        { SyntaxParser.A,  0b0000_0010 },
        { SyntaxParser.CC, 0b0000_0001 }
    };

    private static readonly Dictionary<int, string> s_pushPullRegsLu = new()
    {
        { 0b1000_0000, "pc" },
        { 0b0100_0000, "su" },
        { 0b0010_0000, "y" },
        { 0b0001_0000, "x" },
        { 0b0000_1000, "dp" },
        { 0b0000_0110, "d" },
        { 0b0000_0100, "b" },
        { 0b0000_0010, "a" },
        { 0b0000_0001, "cc" }
    };

    private static readonly Dictionary<int, int> s_accumulatorRegs = new()
    {
        { SyntaxParser.A, 0b0110 },
        { SyntaxParser.B, 0b0101 },
        { SyntaxParser.D, 0b1011 }
    };

    private static readonly Dictionary<int, int> s_indexRegs = new()
    {
        {  SyntaxParser.X, 0b0_00_00000 },
        {  SyntaxParser.Y, 0b0_01_00000 },
        {  SyntaxParser.U, 0b0_10_00000 },
        {  SyntaxParser.S, 0b0_11_00000 }
    };

    private static readonly Dictionary<int, char> s_indexRegsReverseLu = new()
    {
        { 0b0_00_00000, 'x' },
        { 0b0_01_00000, 'y' },
        { 0b0_10_00000, 'u' },
        { 0b0_11_00000, 's' }
    };

    private static readonly Dictionary<int, int> s_increments = new()
    {
        { SyntaxParser.Plus,         0b00 },
        { SyntaxParser.DoublePlus,   0b01 },
        { SyntaxParser.Hyphen,       0b10 },
        { SyntaxParser.DoubleHyphen, 0b11 }
    };

}

