//-----------------------------------------------------------------------------
// Copyright (c) 2017-2021 informedcitizenry <informedcitizenry@gmail.com>
//
// Licensed under the MIT license. See LICENSE for full license information.
// 
//-----------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Core6502DotNet.m680x
{
    public sealed partial class M6809Asm : MotorolaBase
    {
        // 6809 Post-Byte Bits for Indexed and Indirect Addressing:
        // +---------------------------------------------------------------+
        // |          Bit Number           |                               |
        // +---+---+---+---+---+---+---+---+       Addressing Mode         |
        // | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0 |                               |
        // +-------------------------------+-------------------------------+
        // | 0 | R | R | x | x | x | x | x | 5-Bit Offset                  |
        // | 1 | R | R | 0 | 0 | 0 | 0 | 0 | Autoimcrement by One          |
        // | 1 | R | R | I | 0 | 0 | 0 | 1 | Autoincrement by Two          |
        // | 1 | R | R | 0 | 0 | 0 | 1 | 0 | Autodecrement by One          |
        // | 1 | R | R | I | 0 | 0 | 1 | 1 | Autodecrement by Two          |
        // | 1 | R | R | I | 0 | 1 | 0 | 0 | Zero Offset                   |
        // | 1 | R | R | I | 0 | 1 | 0 | 1 | Accumulator B Offset          |
        // | 1 | R | R | I | 0 | 1 | 1 | 0 | Accumulator A Offset          |
        // | 1 | R | R | I | 1 | 0 | 0 | 0 | 8-Bit Offset                  |
        // | 1 | R | R | I | 1 | 0 | 0 | 1 | 16-Bit Offset                 |
        // | 1 | R | R | I | 1 | 0 | 1 | 1 | Accumulator D Offset          |
        // | 1 | x | x | I | 1 | 1 | 0 | 0 | Program Counter 8-Bit Offset  |
        // | 1 | x | x | I | 1 | 1 | 0 | 1 | Program Counter 16-Bit Offset |
        // | 1 | x | x | 1 | 1 | 1 | 1 | 1 | Extended Indirect             |
        // +---+---+---+---+---+---+---+---+-------------------------------+
        // |                                                               |
        // | Indirect Bit (bit 4):                                         |
        // |  I = 1 for Indirect, I = 0 for direct                         |
        // |                                                               |  
        // | Register Bits (bits 5 and 6):                                 |
        // |  00 R = X                                                     |
        // |  01 R = Y                                                     |
        // |  10 R = U                                                     |
        // |  11 R = S                                                     |
        // |                                                               |
        // +---------------------------------------------------------------+

        // Examples:

        // leax +1,x    => 30 01
        // leax $10,PC  => 30 8C 0D
        // leay [234,u] => 31 D9 EA
        // lda ,--x     => A6 83
        [Flags]
        enum IndexModes
        {
            None     = 0,
            By2Bit   = 0b0000_0001,
            Offsbit  = 0b0000_0100,
            Inc1     = 0b1000_0000,
            Inc2     = 0b1000_0001,
            Dec1     = 0b1000_0010,
            Dec2     = 0b1000_0011,
            ZeroOffs = 0b1000_0100,
            AccB     = 0b1000_0101,
            AccA     = 0b1000_0110,
            Offset8  = 0b1000_1000,
            Offset16 = 0b1000_1001,
            AccD     = 0b1000_1011,
            PC8      = 0b1000_1100,
            PC16     = 0b1000_1101,
            Indir    = 0b0001_0000,
            YReg     = 0b0010_0000,
            UReg     = 0b0100_0000,
            SReg     = 0b0110_0000,
            ExtInd   = 0b1001_1111,
            OffsMask = 0b1000_1111,
            Mask     = 0b1111_1111,
            XReg     = None
        };

        readonly Dictionary<StringView, IndexModes> _ixRegisterModes;

        readonly Dictionary<StringView, IndexModes> _offsRegisterModes;

        readonly Dictionary<StringView, byte> _exchangeModes;

        readonly Dictionary<StringView, byte> _pushPullModes;

        static readonly Dictionary<(string Mnem, Modes Mode), CpuInstruction> s_opcodes6800 =
            new Dictionary<(string Mnem, Modes Mode), CpuInstruction>()
        {   
            { ("nop",  Modes.Implied     ), new CpuInstruction( "m6800",    0x01) },
            { ("tap",  Modes.Implied     ), new CpuInstruction( "m6800",    0x06) },
            { ("tpa",  Modes.Implied     ), new CpuInstruction( "m6800",    0x07) },
            { ("inx",  Modes.Implied     ), new CpuInstruction( "m6800",    0x08) },
            { ("dex",  Modes.Implied     ), new CpuInstruction( "m6800",    0x09) },
            { ("clv",  Modes.Implied     ), new CpuInstruction( "m6800",    0x0a) },
            { ("sev",  Modes.Implied     ), new CpuInstruction( "m6800",    0x0b) },
            { ("clc",  Modes.Implied     ), new CpuInstruction( "m6800",    0x0c) },
            { ("sec",  Modes.Implied     ), new CpuInstruction( "m6800",    0x0d) },
            { ("cli",  Modes.Implied     ), new CpuInstruction( "m6800",    0x0e) },
            { ("sei",  Modes.Implied     ), new CpuInstruction( "m6800",    0x0f) },
            { ("sba",  Modes.Implied     ), new CpuInstruction( "m6800",    0x10) },
            { ("cba",  Modes.Implied     ), new CpuInstruction( "m6800",    0x11) },
            { ("tab",  Modes.Implied     ), new CpuInstruction( "m6800",    0x16) },
            { ("tba",  Modes.Implied     ), new CpuInstruction( "m6800",    0x17) },
            { ("daa",  Modes.Implied     ), new CpuInstruction( "m6800",    0x19) },
            { ("aba",  Modes.Implied     ), new CpuInstruction( "m6800",    0x1b) },
            { ("bra",  Modes.Relative    ), new CpuInstruction( "m6800",    0x20, 2) },
            { ("bhi",  Modes.Relative    ), new CpuInstruction( "m6800",    0x22, 2) },
            { ("bls",  Modes.Relative    ), new CpuInstruction( "m6800",    0x23, 2) },
            { ("bcc",  Modes.Relative    ), new CpuInstruction( "m6800",    0x24, 2) },
            { ("bcs",  Modes.Relative    ), new CpuInstruction( "m6800",    0x25, 2) },
            { ("bne",  Modes.Relative    ), new CpuInstruction( "m6800",    0x26, 2) },
            { ("beq",  Modes.Relative    ), new CpuInstruction( "m6800",    0x27, 2) },
            { ("bvc",  Modes.Relative    ), new CpuInstruction( "m6800",    0x28, 2) },
            { ("bvs",  Modes.Relative    ), new CpuInstruction( "m6800",    0x29, 2) },
            { ("bpl",  Modes.Relative    ), new CpuInstruction( "m6800",    0x2a, 2) },
            { ("bmi",  Modes.Relative    ), new CpuInstruction( "m6800",    0x2b, 2) },
            { ("bge",  Modes.Relative    ), new CpuInstruction( "m6800",    0x2c, 2) },
            { ("blt",  Modes.Relative    ), new CpuInstruction( "m6800",    0x2d, 2) },
            { ("bgt",  Modes.Relative    ), new CpuInstruction( "m6800",    0x2e, 2) },
            { ("ble",  Modes.Relative    ), new CpuInstruction( "m6800",    0x2f, 2) },
            { ("tsx",  Modes.Implied     ), new CpuInstruction( "m6800",    0x30) },
            { ("ins",  Modes.Implied     ), new CpuInstruction( "m6800",    0x31) },
            { ("pula", Modes.Implied     ), new CpuInstruction( "m6800",    0x32) },
            { ("pulb", Modes.Implied     ), new CpuInstruction( "m6800",    0x33) },
            { ("des",  Modes.Implied     ), new CpuInstruction( "m6800",    0x34) },
            { ("txs",  Modes.Implied     ), new CpuInstruction( "m6800",    0x35) },
            { ("psha", Modes.Implied     ), new CpuInstruction( "m6800",    0x36) },
            { ("pshb", Modes.Implied     ), new CpuInstruction( "m6800",    0x37) },
            { ("rts",  Modes.Implied     ), new CpuInstruction( "m6800",    0x39) },
            { ("rti",  Modes.Implied     ), new CpuInstruction( "m6800",    0x3b) },
            { ("wai",  Modes.Implied     ), new CpuInstruction( "m6800",    0x3e) },
            { ("swi",  Modes.Implied     ), new CpuInstruction( "m6800",    0x3f) },
            { ("nega", Modes.Implied     ), new CpuInstruction( "m6800",    0x40) },
            { ("coma", Modes.Implied     ), new CpuInstruction( "m6800",    0x43) },
            { ("lsra", Modes.Implied     ), new CpuInstruction( "m6800",    0x44) },
            { ("rora", Modes.Implied     ), new CpuInstruction( "m6800",    0x46) },
            { ("asra", Modes.Implied     ), new CpuInstruction( "m6800",    0x47) },
            { ("asla", Modes.Implied     ), new CpuInstruction( "m6800",    0x48) },
            { ("rola", Modes.Implied     ), new CpuInstruction( "m6800",    0x49) },
            { ("deca", Modes.Implied     ), new CpuInstruction( "m6800",    0x4a) },
            { ("inca", Modes.Implied     ), new CpuInstruction( "m6800",    0x4c) },
            { ("tsta", Modes.Implied     ), new CpuInstruction( "m6800",    0x4d) },
            { ("clra", Modes.Implied     ), new CpuInstruction( "m6800",    0x4f) },
            { ("negb", Modes.Implied     ), new CpuInstruction( "m6800",    0x50) },
            { ("comb", Modes.Implied     ), new CpuInstruction( "m6800",    0x53) },
            { ("lsrb", Modes.Implied     ), new CpuInstruction( "m6800",    0x54) },
            { ("rorb", Modes.Implied     ), new CpuInstruction( "m6800",    0x56) },
            { ("asrb", Modes.Implied     ), new CpuInstruction( "m6800",    0x57) },
            { ("aslb", Modes.Implied     ), new CpuInstruction( "m6800",    0x58) },
            { ("rolb", Modes.Implied     ), new CpuInstruction( "m6800",    0x59) },
            { ("decb", Modes.Implied     ), new CpuInstruction( "m6800",    0x5a) },
            { ("incb", Modes.Implied     ), new CpuInstruction( "m6800",    0x5c) },
            { ("tstb", Modes.Implied     ), new CpuInstruction( "m6800",    0x5d) },
            { ("clrb", Modes.Implied     ), new CpuInstruction( "m6800",    0x5f) },
            { ("neg",  Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0x60, 2) },
            { ("com",  Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0x63, 2) },
            { ("lsr",  Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0x64, 2) },
            { ("ror",  Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0x66, 2) },
            { ("asr",  Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0x67, 2) },
            { ("asl",  Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0x68, 2) },
            { ("rol",  Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0x69, 2) },
            { ("dec",  Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0x6a, 2) },
            { ("inc",  Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0x6c, 2) },
            { ("tst",  Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0x6d, 2) },
            { ("jmp",  Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0x6e, 2) },
            { ("clr",  Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0x6f, 2) },
            { ("neg",  Modes.Absolute    ), new CpuInstruction( "m6800",    0x70, 3) },
            { ("com",  Modes.Absolute    ), new CpuInstruction( "m6800",    0x73, 3) },
            { ("lsr",  Modes.Absolute    ), new CpuInstruction( "m6800",    0x74, 3) },
            { ("ror",  Modes.Absolute    ), new CpuInstruction( "m6800",    0x76, 3) },
            { ("asr",  Modes.Absolute    ), new CpuInstruction( "m6800",    0x77, 3) },
            { ("asl",  Modes.Absolute    ), new CpuInstruction( "m6800",    0x78, 3) },
            { ("rol",  Modes.Absolute    ), new CpuInstruction( "m6800",    0x79, 3) },
            { ("dec",  Modes.Absolute    ), new CpuInstruction( "m6800",    0x7a, 3) },
            { ("inc",  Modes.Absolute    ), new CpuInstruction( "m6800",    0x7c, 3) },
            { ("tst",  Modes.Absolute    ), new CpuInstruction( "m6800",    0x7d, 3) },
            { ("jmp",  Modes.Absolute    ), new CpuInstruction( "m6800",    0x7e, 3) },
            { ("clr",  Modes.Absolute    ), new CpuInstruction( "m6800",    0x7f, 3) },
            { ("suba", Modes.Immediate   ), new CpuInstruction( "m6800",    0x80, 2) },
            { ("cmpa", Modes.Immediate   ), new CpuInstruction( "m6800",    0x81, 2) },
            { ("sbca", Modes.Immediate   ), new CpuInstruction( "m6800",    0x82, 2) },
            { ("anda", Modes.Immediate   ), new CpuInstruction( "m6800",    0x84, 2) },
            { ("bita", Modes.Immediate   ), new CpuInstruction( "m6800",    0x85, 2) },
            { ("ldaa", Modes.Immediate   ), new CpuInstruction( "m6800",    0x86, 2) },
            { ("eora", Modes.Immediate   ), new CpuInstruction( "m6800",    0x88, 2) },
            { ("adca", Modes.Immediate   ), new CpuInstruction( "m6800",    0x89, 2) },
            { ("oraa", Modes.Immediate   ), new CpuInstruction( "m6800",    0x8a, 2) },
            { ("adda", Modes.Immediate   ), new CpuInstruction( "m6800",    0x8b, 2) },
            { ("cpxa", Modes.Immediate   ), new CpuInstruction( "m6800",    0x8c, 2) },
            { ("bsr",  Modes.Relative    ), new CpuInstruction( "m6800",    0x8d, 2) },
            { ("lds",  Modes.ImmAbs      ), new CpuInstruction( "m6800",    0x8e, 3) },
            { ("suba", Modes.ZeroPage    ), new CpuInstruction( "m6800",    0x90, 2) },
            { ("cmpa", Modes.ZeroPage    ), new CpuInstruction( "m6800",    0x91, 2) },
            { ("sbca", Modes.ZeroPage    ), new CpuInstruction( "m6800",    0x92, 2) },
            { ("anda", Modes.ZeroPage    ), new CpuInstruction( "m6800",    0x94, 2) },
            { ("bita", Modes.ZeroPage    ), new CpuInstruction( "m6800",    0x95, 2) },
            { ("ldaa", Modes.ZeroPage    ), new CpuInstruction( "m6800",    0x96, 2) },
            { ("staa", Modes.ZeroPage    ), new CpuInstruction( "m6800",    0x97, 2) },
            { ("eora", Modes.ZeroPage    ), new CpuInstruction( "m6800",    0x98, 2) },
            { ("adca", Modes.ZeroPage    ), new CpuInstruction( "m6800",    0x99, 2) },
            { ("oraa", Modes.ZeroPage    ), new CpuInstruction( "m6800",    0x9a, 2) },
            { ("adda", Modes.ZeroPage    ), new CpuInstruction( "m6800",    0x9b, 2) },
            { ("cpxa", Modes.ZeroPage    ), new CpuInstruction( "m6800",    0x9c, 2) },
            { ("lds",  Modes.ZeroPage    ), new CpuInstruction( "m6800",    0x9e, 2) },
            { ("sts",  Modes.ZeroPage    ), new CpuInstruction( "m6800",    0x9f, 2) },
            { ("suba", Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xa0, 2) },
            { ("cmpa", Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xa1, 2) },
            { ("sbca", Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xa2, 2) },
            { ("anda", Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xa4, 2) },
            { ("bita", Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xa5, 2) },
            { ("ldaa", Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xa6, 2) },
            { ("staa", Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xa7, 2) },
            { ("eora", Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xa8, 2) },
            { ("adca", Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xa9, 2) },
            { ("oraa", Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xaa, 2) },
            { ("adda", Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xab, 2) },
            { ("cpxa", Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xac, 2) },
            { ("jsr",  Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xad, 2) },
            { ("lds",  Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xae, 2) },
            { ("sts",  Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xaf, 2) },
            { ("suba", Modes.Absolute    ), new CpuInstruction( "m6800",    0xb0, 3) },
            { ("cmpa", Modes.Absolute    ), new CpuInstruction( "m6800",    0xb1, 3) },
            { ("sbca", Modes.Absolute    ), new CpuInstruction( "m6800",    0xb2, 3) },
            { ("anda", Modes.Absolute    ), new CpuInstruction( "m6800",    0xb4, 3) },
            { ("bita", Modes.Absolute    ), new CpuInstruction( "m6800",    0xb5, 3) },
            { ("ldaa", Modes.Absolute    ), new CpuInstruction( "m6800",    0xb6, 3) },
            { ("staa", Modes.Absolute    ), new CpuInstruction( "m6800",    0xb7, 3) },
            { ("eora", Modes.Absolute    ), new CpuInstruction( "m6800",    0xb8, 3) },
            { ("adca", Modes.Absolute    ), new CpuInstruction( "m6800",    0xb9, 3) },
            { ("oraa", Modes.Absolute    ), new CpuInstruction( "m6800",    0xba, 3) },
            { ("adda", Modes.Absolute    ), new CpuInstruction( "m6800",    0xbb, 3) },
            { ("cpxa", Modes.Absolute    ), new CpuInstruction( "m6800",    0xbc, 3) },
            { ("jsr",  Modes.Absolute    ), new CpuInstruction( "m6800",    0xbd, 3) },
            { ("lds",  Modes.Absolute    ), new CpuInstruction( "m6800",    0xbe, 3) },
            { ("sts",  Modes.Absolute    ), new CpuInstruction( "m6800",    0xbf, 3) },
            { ("subb", Modes.Immediate   ), new CpuInstruction( "m6800",    0xc0, 2) },
            { ("cmpb", Modes.Immediate   ), new CpuInstruction( "m6800",    0xc1, 2) },
            { ("sbcb", Modes.Immediate   ), new CpuInstruction( "m6800",    0xc2, 2) },
            { ("andb", Modes.Immediate   ), new CpuInstruction( "m6800",    0xc4, 2) },
            { ("bitb", Modes.Immediate   ), new CpuInstruction( "m6800",    0xc5, 2) },
            { ("ldab", Modes.Immediate   ), new CpuInstruction( "m6800",    0xc6, 2) },
            { ("staa", Modes.Immediate   ), new CpuInstruction( "m6800",    0xc7, 2) },
            { ("eorb", Modes.Immediate   ), new CpuInstruction( "m6800",    0xc8, 2) },
            { ("adcb", Modes.Immediate   ), new CpuInstruction( "m6800",    0xc9, 2) },
            { ("orab", Modes.Immediate   ), new CpuInstruction( "m6800",    0xca, 2) },
            { ("addb", Modes.Immediate   ), new CpuInstruction( "m6800",    0xcb, 2) },
            { ("ldx",  Modes.ImmAbs      ), new CpuInstruction( "m6800",    0xce, 3) },
            { ("subb", Modes.ZeroPage    ), new CpuInstruction( "m6800",    0xd0, 2) },
            { ("cmpb", Modes.ZeroPage    ), new CpuInstruction( "m6800",    0xd1, 2) },
            { ("sbcb", Modes.ZeroPage    ), new CpuInstruction( "m6800",    0xd2, 2) },
            { ("andb", Modes.ZeroPage    ), new CpuInstruction( "m6800",    0xd4, 2) },
            { ("bitb", Modes.ZeroPage    ), new CpuInstruction( "m6800",    0xd5, 2) },
            { ("ldab", Modes.ZeroPage    ), new CpuInstruction( "m6800",    0xd6, 2) },
            { ("stab", Modes.ZeroPage    ), new CpuInstruction( "m6800",    0xd7, 2) },
            { ("eorb", Modes.ZeroPage    ), new CpuInstruction( "m6800",    0xd8, 2) },
            { ("adcb", Modes.ZeroPage    ), new CpuInstruction( "m6800",    0xd9, 2) },
            { ("orab", Modes.ZeroPage    ), new CpuInstruction( "m6800",    0xda, 2) },
            { ("addb", Modes.ZeroPage    ), new CpuInstruction( "m6800",    0xdb, 2) },
            { ("ldx",  Modes.ZeroPage    ), new CpuInstruction( "m6800",    0xde, 2) },
            { ("stx",  Modes.ZeroPage    ), new CpuInstruction( "m6800",    0xdf, 2) },
            { ("subb", Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xe0, 2) },
            { ("cmpb", Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xe1, 2) },
            { ("sbcb", Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xe2, 2) },
            { ("andb", Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xe4, 2) },
            { ("bitb", Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xe5, 2) },
            { ("ldab", Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xe6, 2) },
            { ("stab", Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xe7, 2) },
            { ("eorb", Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xe8, 2) },
            { ("adcb", Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xe9, 2) },
            { ("orab", Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xea, 2) },
            { ("addb", Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xeb, 2) },
            { ("ldx",  Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xee, 2) },
            { ("stx",  Modes.ZeroPageX   ), new CpuInstruction( "m6800",    0xef, 2) },
            { ("subb", Modes.Absolute    ), new CpuInstruction( "m6800",    0xf0, 3) },
            { ("cmpb", Modes.Absolute    ), new CpuInstruction( "m6800",    0xf1, 3) },
            { ("sbcb", Modes.Absolute    ), new CpuInstruction( "m6800",    0xf2, 3) },
            { ("andb", Modes.Absolute    ), new CpuInstruction( "m6800",    0xf4, 3) },
            { ("bitb", Modes.Absolute    ), new CpuInstruction( "m6800",    0xf5, 3) },
            { ("ldab", Modes.Absolute    ), new CpuInstruction( "m6800",    0xf6, 3) },
            { ("stab", Modes.Absolute    ), new CpuInstruction( "m6800",    0xf7, 3) },
            { ("eorb", Modes.Absolute    ), new CpuInstruction( "m6800",    0xf8, 3) },
            { ("adcb", Modes.Absolute    ), new CpuInstruction( "m6800",    0xf9, 3) },
            { ("orab", Modes.Absolute    ), new CpuInstruction( "m6800",    0xfa, 3) },
            { ("addb", Modes.Absolute    ), new CpuInstruction( "m6800",    0xfb, 3) },
            { ("ldx",  Modes.Absolute    ), new CpuInstruction( "m6800",    0xfe, 3) },
            { ("stx",  Modes.Absolute    ), new CpuInstruction( "m6800",    0xff, 3) }
        };

        static readonly Dictionary<(string Mnem, Modes Mode), CpuInstruction> s_opcodes6809 =
            new Dictionary<(string Mnem, Modes Mode), CpuInstruction>()
        {
            { ("neg",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x00, 2) },
            { ("com",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x03, 2) },
            { ("lsr",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x04, 2) },
            { ("ror",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x06, 2) },
            { ("asr",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x07, 2) },
            { ("asl",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x08, 2) },
            { ("lsl",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x08, 2) },
            { ("rol",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x09, 2) },
            { ("dec",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x0a, 2) },
            { ("inc",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x0c, 2) },
            { ("tst",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x0d, 2) },
            { ("jmp",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x0e, 2) },
            { ("clr",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x0f, 2) },
            { ("nop",   Modes.Implied     ), new CpuInstruction( "m6809",    0x12) },
            { ("sync",  Modes.Implied     ), new CpuInstruction( "m6809",    0x13) },
            { ("lbra",  Modes.RelativeAbs ), new CpuInstruction( "m6809",    0x16, 3) },
            { ("lbsr",  Modes.RelativeAbs ), new CpuInstruction( "m6809",    0x17, 3) },
            { ("daa",   Modes.Implied     ), new CpuInstruction( "m6809",    0x19) },
            { ("orcc",  Modes.Immediate   ), new CpuInstruction( "m6809",    0x1a, 2) },
            { ("andcc", Modes.Immediate   ), new CpuInstruction( "m6809",    0x1c, 2) },
            { ("sex",   Modes.Implied     ), new CpuInstruction( "m6809",    0x1d) },
            { ("exg",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x1e, 2) },
            { ("tfr",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x1f, 2) },
            { ("bra",   Modes.Relative    ), new CpuInstruction( "m6809",    0x20, 2) },
            { ("brn",   Modes.Relative    ), new CpuInstruction( "m6809",    0x21, 2) },
            { ("bhi",   Modes.Relative    ), new CpuInstruction( "m6809",    0x22, 2) },
            { ("bls",   Modes.Relative    ), new CpuInstruction( "m6809",    0x23, 2) },
            { ("bcc",   Modes.Relative    ), new CpuInstruction( "m6809",    0x24, 2) },
            { ("bhs",   Modes.Relative    ), new CpuInstruction( "m6809",    0x24, 2) },
            { ("bcs",   Modes.Relative    ), new CpuInstruction( "m6809",    0x25, 2) },
            { ("blo",   Modes.Relative    ), new CpuInstruction( "m6809",    0x25, 2) },
            { ("bne",   Modes.Relative    ), new CpuInstruction( "m6809",    0x26, 2) },
            { ("beq",   Modes.Relative    ), new CpuInstruction( "m6809",    0x27, 2) },
            { ("bvc",   Modes.Relative    ), new CpuInstruction( "m6809",    0x28, 2) },
            { ("bvs",   Modes.Relative    ), new CpuInstruction( "m6809",    0x29, 2) },
            { ("bpl",   Modes.Relative    ), new CpuInstruction( "m6809",    0x2a, 2) },
            { ("bmi",   Modes.Relative    ), new CpuInstruction( "m6809",    0x2b, 2) },
            { ("bge",   Modes.Relative    ), new CpuInstruction( "m6809",    0x2c, 2) },
            { ("blt",   Modes.Relative    ), new CpuInstruction( "m6809",    0x2d, 2) },
            { ("bgt",   Modes.Relative    ), new CpuInstruction( "m6809",    0x2e, 2) },
            { ("ble",   Modes.Relative    ), new CpuInstruction( "m6809",    0x2f, 2) },
            { ("leax",  Modes.IndexedX    ), new CpuInstruction( "m6809",    0x30, 2) },
            { ("leay",  Modes.IndexedX    ), new CpuInstruction( "m6809",    0x31, 2) },
            { ("leas",  Modes.IndexedX    ), new CpuInstruction( "m6809",    0x32, 2) },
            { ("leau",  Modes.IndexedX    ), new CpuInstruction( "m6809",    0x33, 2) },
            { ("pshs",  Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x34, 2) },
            { ("puls",  Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x35, 2) },
            { ("pshu",  Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x36, 2) },
            { ("pulu",  Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x37, 2) },
            { ("rts",   Modes.Implied     ), new CpuInstruction( "m6809",    0x39) },
            { ("abx",   Modes.Implied     ), new CpuInstruction( "m6809",    0x3a) },
            { ("rti",   Modes.Implied     ), new CpuInstruction( "m6809",    0x3b) },
            { ("cwai",  Modes.Implied     ), new CpuInstruction( "m6809",    0x3c) },
            { ("mul",   Modes.Implied     ), new CpuInstruction( "m6809",    0x3d) },
            { ("swi",   Modes.Implied     ), new CpuInstruction( "m6809",    0x3f) },
            { ("nega",  Modes.Implied     ), new CpuInstruction( "m6809",    0x40) },
            { ("coma",  Modes.Implied     ), new CpuInstruction( "m6809",    0x43) },
            { ("lsra",  Modes.Implied     ), new CpuInstruction( "m6809",    0x44) },
            { ("rora",  Modes.Implied     ), new CpuInstruction( "m6809",    0x46) },
            { ("asra",  Modes.Implied     ), new CpuInstruction( "m6809",    0x47) },
            { ("asla",  Modes.Implied     ), new CpuInstruction( "m6809",    0x48) },
            { ("lsla",  Modes.Implied     ), new CpuInstruction( "m6809",    0x48) },
            { ("rola",  Modes.Implied     ), new CpuInstruction( "m6809",    0x49) },
            { ("deca",  Modes.Implied     ), new CpuInstruction( "m6809",    0x4a) },
            { ("inca",  Modes.Implied     ), new CpuInstruction( "m6809",    0x4c) },
            { ("tsta",  Modes.Implied     ), new CpuInstruction( "m6809",    0x4d) },
            { ("clra",  Modes.Implied     ), new CpuInstruction( "m6809",    0x4f) },
            { ("negb",  Modes.Implied     ), new CpuInstruction( "m6809",    0x50) },
            { ("comb",  Modes.Implied     ), new CpuInstruction( "m6809",    0x53) },
            { ("lsrb",  Modes.Implied     ), new CpuInstruction( "m6809",    0x54) },
            { ("rorb",  Modes.Implied     ), new CpuInstruction( "m6809",    0x56) },
            { ("asrb",  Modes.Implied     ), new CpuInstruction( "m6809",    0x57) },
            { ("aslb",  Modes.Implied     ), new CpuInstruction( "m6809",    0x58) },
            { ("lslb",  Modes.Implied     ), new CpuInstruction( "m6809",    0x58) },
            { ("rolb",  Modes.Implied     ), new CpuInstruction( "m6809",    0x59) },
            { ("decb",  Modes.Implied     ), new CpuInstruction( "m6809",    0x5a) },
            { ("incb",  Modes.Implied     ), new CpuInstruction( "m6809",    0x5c) },
            { ("tstb",  Modes.Implied     ), new CpuInstruction( "m6809",    0x5d) },
            { ("clrb",  Modes.Implied     ), new CpuInstruction( "m6809",    0x5f) },
            { ("neg",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0x60, 2) },
            { ("com",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0x63, 2) },
            { ("lsr",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0x64, 2) },
            { ("ror",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0x66, 2) },
            { ("asr",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0x67, 2) },
            { ("asl",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0x68, 2) },
            { ("lsl",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0x68, 2) },
            { ("rol",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0x69, 2) },
            { ("dec",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0x6a, 2) },
            { ("inc",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0x6c, 2) },
            { ("tst",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0x6d, 2) },
            { ("jmp",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0x6e, 2) },
            { ("clr",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0x6f, 2) },
            { ("neg",   Modes.Absolute    ), new CpuInstruction( "m6809",    0x70, 3) },
            { ("com",   Modes.Absolute    ), new CpuInstruction( "m6809",    0x73, 3) },
            { ("lsr",   Modes.Absolute    ), new CpuInstruction( "m6809",    0x74, 3) },
            { ("ror",   Modes.Absolute    ), new CpuInstruction( "m6809",    0x76, 3) },
            { ("asr",   Modes.Absolute    ), new CpuInstruction( "m6809",    0x77, 3) },
            { ("asl",   Modes.Absolute    ), new CpuInstruction( "m6809",    0x78, 3) },
            { ("lsl",   Modes.Absolute    ), new CpuInstruction( "m6809",    0x78, 3) },
            { ("rol",   Modes.Absolute    ), new CpuInstruction( "m6809",    0x79, 3) },
            { ("dec",   Modes.Absolute    ), new CpuInstruction( "m6809",    0x7a, 3) },
            { ("inc",   Modes.Absolute    ), new CpuInstruction( "m6809",    0x7c, 3) },
            { ("tst",   Modes.Absolute    ), new CpuInstruction( "m6809",    0x7d, 3) },
            { ("jmp",   Modes.Absolute    ), new CpuInstruction( "m6809",    0x7e, 3) },
            { ("clr",   Modes.Absolute    ), new CpuInstruction( "m6809",    0x7f, 3) },
            { ("suba",  Modes.Immediate   ), new CpuInstruction( "m6809",    0x80, 2) },
            { ("cmpa",  Modes.Immediate   ), new CpuInstruction( "m6809",    0x81, 2) },
            { ("sbca",  Modes.Immediate   ), new CpuInstruction( "m6809",    0x82, 2) },
            { ("subd",  Modes.ImmAbs      ), new CpuInstruction( "m6809",    0x83, 3) },
            { ("anda",  Modes.Immediate   ), new CpuInstruction( "m6809",    0x84, 2) },
            { ("bita",  Modes.Immediate   ), new CpuInstruction( "m6809",    0x85, 2) },
            { ("lda",   Modes.Immediate   ), new CpuInstruction( "m6809",    0x86, 2) },
            { ("eora",  Modes.Immediate   ), new CpuInstruction( "m6809",    0x88, 2) },
            { ("adca",  Modes.Immediate   ), new CpuInstruction( "m6809",    0x89, 2) },
            { ("oraa",  Modes.Immediate   ), new CpuInstruction( "m6809",    0x8a, 2) },
            { ("adda",  Modes.Immediate   ), new CpuInstruction( "m6809",    0x8b, 2) },
            { ("cmpx",  Modes.ImmAbs      ), new CpuInstruction( "m6809",    0x8c, 3) },
            { ("bsr",   Modes.Relative    ), new CpuInstruction( "m6809",    0x8d, 2) },
            { ("ldx",   Modes.ImmAbs      ), new CpuInstruction( "m6809",    0x8e, 3) },
            { ("suba",  Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x90, 2) },
            { ("cmpa",  Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x91, 2) },
            { ("sbca",  Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x92, 2) },
            { ("subd",  Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x93, 2) },
            { ("anda",  Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x94, 2) },
            { ("bita",  Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x95, 2) },
            { ("lda",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x96, 2) },
            { ("sta",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x97, 2) },
            { ("eora",  Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x98, 2) },
            { ("adca",  Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x99, 2) },
            { ("ora",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x9a, 2) },
            { ("adda",  Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x9b, 2) },
            { ("cmpx",  Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x9c, 2) },
            { ("jsr",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x9d, 2) },
            { ("ldx",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x9e, 2) },
            { ("stx",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0x9f, 2) },
            { ("suba",  Modes.IndexedX    ), new CpuInstruction( "m6809",    0xa0, 2) },
            { ("cmpa",  Modes.IndexedX    ), new CpuInstruction( "m6809",    0xa1, 2) },
            { ("sbca",  Modes.IndexedX    ), new CpuInstruction( "m6809",    0xa2, 2) },
            { ("subd",  Modes.IndexedX    ), new CpuInstruction( "m6809",    0xa3, 2) },
            { ("anda",  Modes.IndexedX    ), new CpuInstruction( "m6809",    0xa4, 2) },
            { ("bita",  Modes.IndexedX    ), new CpuInstruction( "m6809",    0xa5, 2) },
            { ("lda",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0xa6, 2) },
            { ("sta",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0xa7, 2) },
            { ("eora",  Modes.IndexedX    ), new CpuInstruction( "m6809",    0xa8, 2) },
            { ("adca",  Modes.IndexedX    ), new CpuInstruction( "m6809",    0xa9, 2) },
            { ("ora",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0xaa, 2) },
            { ("adda",  Modes.IndexedX    ), new CpuInstruction( "m6809",    0xab, 2) },
            { ("cmpx",  Modes.IndexedX    ), new CpuInstruction( "m6809",    0xac, 2) },
            { ("jsr",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0xad, 2) },
            { ("ldx",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0xae, 2) },
            { ("stx",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0xaf, 2) },
            { ("suba",  Modes.Absolute    ), new CpuInstruction( "m6809",    0xb0, 3) },
            { ("cmpa",  Modes.Absolute    ), new CpuInstruction( "m6809",    0xb1, 3) },
            { ("sbca",  Modes.Absolute    ), new CpuInstruction( "m6809",    0xb2, 3) },
            { ("subd",  Modes.Absolute    ), new CpuInstruction( "m6809",    0xb3, 3) },
            { ("anda",  Modes.Absolute    ), new CpuInstruction( "m6809",    0xb4, 3) },
            { ("bita",  Modes.Absolute    ), new CpuInstruction( "m6809",    0xb5, 3) },
            { ("lda",   Modes.Absolute    ), new CpuInstruction( "m6809",    0xb6, 3) },
            { ("sta",   Modes.Absolute    ), new CpuInstruction( "m6809",    0xb7, 3) },
            { ("eora",  Modes.Absolute    ), new CpuInstruction( "m6809",    0xb8, 3) },
            { ("adca",  Modes.Absolute    ), new CpuInstruction( "m6809",    0xb9, 3) },
            { ("ora",   Modes.Absolute    ), new CpuInstruction( "m6809",    0xba, 3) },
            { ("adda",  Modes.Absolute    ), new CpuInstruction( "m6809",    0xbb, 3) },
            { ("cpxa",  Modes.Absolute    ), new CpuInstruction( "m6809",    0xbc, 3) },
            { ("jsr",   Modes.Absolute    ), new CpuInstruction( "m6809",    0xbd, 3) },
            { ("ldx",   Modes.Absolute    ), new CpuInstruction( "m6809",    0xbe, 3) },
            { ("stx",   Modes.Absolute    ), new CpuInstruction( "m6809",    0xbf, 3) },
            { ("subb",  Modes.Immediate   ), new CpuInstruction( "m6809",    0xc0, 2) },
            { ("cmpb",  Modes.Immediate   ), new CpuInstruction( "m6809",    0xc1, 2) },
            { ("sbcb",  Modes.Immediate   ), new CpuInstruction( "m6809",    0xc2, 2) },
            { ("addd",  Modes.ImmAbs      ), new CpuInstruction( "m6809",    0xc3, 3) },
            { ("andb",  Modes.Immediate   ), new CpuInstruction( "m6809",    0xc4, 2) },
            { ("bitb",  Modes.Immediate   ), new CpuInstruction( "m6809",    0xc5, 2) },
            { ("ldb",   Modes.Immediate   ), new CpuInstruction( "m6809",    0xc6, 2) },
            { ("eorb",  Modes.Immediate   ), new CpuInstruction( "m6809",    0xc8, 2) },
            { ("adcb",  Modes.Immediate   ), new CpuInstruction( "m6809",    0xc9, 2) },
            { ("orb",   Modes.Immediate   ), new CpuInstruction( "m6809",    0xca, 2) },
            { ("addb",  Modes.Immediate   ), new CpuInstruction( "m6809",    0xcb, 2) },
            { ("ldd",   Modes.ImmAbs      ), new CpuInstruction( "m6809",    0xcc, 3) },
            { ("ldu",   Modes.ImmAbs      ), new CpuInstruction( "m6809",    0xce, 3) },
            { ("subb",  Modes.ZeroPage    ), new CpuInstruction( "m6809",    0xd0, 2) },
            { ("cmpb",  Modes.ZeroPage    ), new CpuInstruction( "m6809",    0xd1, 2) },
            { ("sbcb",  Modes.ZeroPage    ), new CpuInstruction( "m6809",    0xd2, 2) },
            { ("addd",  Modes.ZeroPage    ), new CpuInstruction( "m6809",    0xd3, 2) },
            { ("andb",  Modes.ZeroPage    ), new CpuInstruction( "m6809",    0xd4, 2) },
            { ("bitb",  Modes.ZeroPage    ), new CpuInstruction( "m6809",    0xd5, 2) },
            { ("ldb",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0xd6, 2) },
            { ("stb",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0xd7, 2) },
            { ("eorb",  Modes.ZeroPage    ), new CpuInstruction( "m6809",    0xd8, 2) },
            { ("adcb",  Modes.ZeroPage    ), new CpuInstruction( "m6809",    0xd9, 2) },
            { ("orb",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0xda, 2) },
            { ("addb",  Modes.ZeroPage    ), new CpuInstruction( "m6809",    0xdb, 2) },
            { ("ldd",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0xdc, 2) },
            { ("std",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0xdd, 2) },
            { ("ldu",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0xde, 2) },
            { ("stu",   Modes.ZeroPage    ), new CpuInstruction( "m6809",    0xdf, 2) },
            { ("subb",  Modes.IndexedX    ), new CpuInstruction( "m6809",    0xe0, 2) },
            { ("cmpb",  Modes.IndexedX    ), new CpuInstruction( "m6809",    0xe1, 2) },
            { ("sbcb",  Modes.IndexedX    ), new CpuInstruction( "m6809",    0xe2, 2) },
            { ("addd",  Modes.IndexedX    ), new CpuInstruction( "m6809",    0xe3, 2) },
            { ("andb",  Modes.IndexedX    ), new CpuInstruction( "m6809",    0xe4, 2) },
            { ("bitb",  Modes.IndexedX    ), new CpuInstruction( "m6809",    0xe5, 2) },
            { ("ldb",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0xe6, 2) },
            { ("stb",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0xe7, 2) },
            { ("eorb",  Modes.IndexedX    ), new CpuInstruction( "m6809",    0xe8, 2) },
            { ("adcb",  Modes.IndexedX    ), new CpuInstruction( "m6809",    0xe9, 2) },
            { ("orb",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0xea, 2) },
            { ("addb",  Modes.IndexedX    ), new CpuInstruction( "m6809",    0xeb, 2) },
            { ("ldd",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0xec, 2) },
            { ("std",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0xed, 2) },
            { ("ldu",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0xee, 2) },
            { ("stu",   Modes.IndexedX    ), new CpuInstruction( "m6809",    0xef, 2) },
            { ("subb",  Modes.Absolute    ), new CpuInstruction( "m6809",    0xf0, 3) },
            { ("cmpb",  Modes.Absolute    ), new CpuInstruction( "m6809",    0xf1, 3) },
            { ("sbcb",  Modes.Absolute    ), new CpuInstruction( "m6809",    0xf2, 3) },
            { ("addd",  Modes.Absolute    ), new CpuInstruction( "m6809",    0xf2, 3) },
            { ("andb",  Modes.Absolute    ), new CpuInstruction( "m6809",    0xf4, 3) },
            { ("bitb",  Modes.Absolute    ), new CpuInstruction( "m6809",    0xf5, 3) },
            { ("ldb",   Modes.Absolute    ), new CpuInstruction( "m6809",    0xf6, 3) },
            { ("stb",   Modes.Absolute    ), new CpuInstruction( "m6809",    0xf7, 3) },
            { ("eorb",  Modes.Absolute    ), new CpuInstruction( "m6809",    0xf8, 3) },
            { ("adcb",  Modes.Absolute    ), new CpuInstruction( "m6809",    0xf9, 3) },
            { ("orb",   Modes.Absolute    ), new CpuInstruction( "m6809",    0xfa, 3) },
            { ("addb",  Modes.Absolute    ), new CpuInstruction( "m6809",    0xfb, 3) },
            { ("ldd",   Modes.Absolute    ), new CpuInstruction( "m6809",    0xfc, 3) },
            { ("std",   Modes.Absolute    ), new CpuInstruction( "m6809",    0xfd, 3) },
            { ("ldu",   Modes.Absolute    ), new CpuInstruction( "m6809",    0xfe, 3) },
            { ("stu",   Modes.Absolute    ), new CpuInstruction( "m6809",    0xff, 3) },
            { ("lbrn",  Modes.RelativeAbs ), new CpuInstruction( "m6809",  0x1021, 4) },
            { ("lbhi",  Modes.RelativeAbs ), new CpuInstruction( "m6809",  0x1022, 4) },
            { ("lbls",  Modes.RelativeAbs ), new CpuInstruction( "m6809",  0x1023, 4) },
            { ("lbcc",  Modes.RelativeAbs ), new CpuInstruction( "m6809",  0x1024, 4) },
            { ("lbhs",  Modes.RelativeAbs ), new CpuInstruction( "m6809",  0x1024, 4) },
            { ("lbcs",  Modes.RelativeAbs ), new CpuInstruction( "m6809",  0x1025, 4) },
            { ("lblo",  Modes.RelativeAbs ), new CpuInstruction( "m6809",  0x1025, 4) },
            { ("lbne",  Modes.RelativeAbs ), new CpuInstruction( "m6809",  0x1026, 4) },
            { ("lbeq",  Modes.RelativeAbs ), new CpuInstruction( "m6809",  0x1027, 4) },
            { ("lbvc",  Modes.RelativeAbs ), new CpuInstruction( "m6809",  0x1028, 4) },
            { ("lbvs",  Modes.RelativeAbs ), new CpuInstruction( "m6809",  0x1029, 4) },
            { ("lbpl",  Modes.RelativeAbs ), new CpuInstruction( "m6809",  0x102a, 4) },
            { ("lbmi",  Modes.RelativeAbs ), new CpuInstruction( "m6809",  0x102b, 4) },
            { ("lbge",  Modes.RelativeAbs ), new CpuInstruction( "m6809",  0x102c, 4) },
            { ("lblt",  Modes.RelativeAbs ), new CpuInstruction( "m6809",  0x102d, 4) },
            { ("lbgt",  Modes.RelativeAbs ), new CpuInstruction( "m6809",  0x102e, 4) },
            { ("lble",  Modes.RelativeAbs ), new CpuInstruction( "m6809",  0x102f, 4) },
            { ("swi2",  Modes.Implied     ), new CpuInstruction( "m6809",  0x103f, 2) },
            { ("cmpd",  Modes.ImmAbs      ), new CpuInstruction( "m6809",  0x1083, 4) },
            { ("cmpy",  Modes.ImmAbs      ), new CpuInstruction( "m6809",  0x108c, 4) },
            { ("ldy",   Modes.ImmAbs      ), new CpuInstruction( "m6809",  0x108e, 4) },
            { ("cmpd",  Modes.ZeroPage    ), new CpuInstruction( "m6809",  0x1093, 3) },
            { ("cmpy",  Modes.ZeroPage    ), new CpuInstruction( "m6809",  0x109c, 3) },
            { ("ldy",   Modes.ZeroPage    ), new CpuInstruction( "m6809",  0x109e, 3) },
            { ("sty",   Modes.ZeroPage    ), new CpuInstruction( "m6809",  0x109f, 3) },
            { ("cmpd",  Modes.IndexedX    ), new CpuInstruction( "m6809",  0x10a3, 3) },
            { ("cmpy",  Modes.IndexedX    ), new CpuInstruction( "m6809",  0x10ac, 3) },
            { ("ldy",   Modes.IndexedX    ), new CpuInstruction( "m6809",  0x10ae, 3) },
            { ("sty",   Modes.IndexedX    ), new CpuInstruction( "m6809",  0x10af, 3) },
            { ("cmpd",  Modes.Absolute    ), new CpuInstruction( "m6809",  0x10b3, 4) },
            { ("cmpy",  Modes.Absolute    ), new CpuInstruction( "m6809",  0x10bc, 4) },
            { ("ldy",   Modes.Absolute    ), new CpuInstruction( "m6809",  0x10be, 4) },
            { ("sty",   Modes.Absolute    ), new CpuInstruction( "m6809",  0x10bf, 4) },
            { ("lds",   Modes.ImmAbs      ), new CpuInstruction( "m6809",  0x10ce, 4) },
            { ("lds",   Modes.ZeroPage    ), new CpuInstruction( "m6809",  0x10de, 3) },
            { ("sts",   Modes.ZeroPage    ), new CpuInstruction( "m6809",  0x10df, 3) },
            { ("lds",   Modes.IndexedX    ), new CpuInstruction( "m6809",  0x10ee, 3) },
            { ("sts",   Modes.IndexedX    ), new CpuInstruction( "m6809",  0x10ef, 3) },
            { ("lds",   Modes.Absolute    ), new CpuInstruction( "m6809",  0x10fe, 4) },
            { ("sts",   Modes.Absolute    ), new CpuInstruction( "m6809",  0x10ff, 4) },
            { ("swi3",  Modes.Implied     ), new CpuInstruction( "m6809",  0x113f, 2) },
            { ("cmpu",  Modes.ImmAbs      ), new CpuInstruction( "m6809",  0x1183, 4) },
            { ("cmps",  Modes.ImmAbs      ), new CpuInstruction( "m6809",  0x118c, 4) },
            { ("cmpu",  Modes.ZeroPage    ), new CpuInstruction( "m6809",  0x1193, 3) },
            { ("cmps",  Modes.ZeroPage    ), new CpuInstruction( "m6809",  0x119c, 3) },
            { ("cmpu",  Modes.IndexedX    ), new CpuInstruction( "m6809",  0x11a3, 3) },
            { ("cmps",  Modes.IndexedX    ), new CpuInstruction( "m6809",  0x11ac, 3) },
            { ("cmpu",  Modes.Absolute    ), new CpuInstruction( "m6809",  0x11b3, 4) },
            { ("cmps",  Modes.Absolute    ), new CpuInstruction( "m6809",  0x11bc, 4) }
        };
    }
}