//-----------------------------------------------------------------------------
// Copyright (c) 2017-2022 informedcitizenry <informedcitizenry@gmail.com>
//
// Licensed under the MIT license. See LICENSE for full license information.
// 
//-----------------------------------------------------------------------------

using System.Collections.Generic;

namespace Sixty502DotNet
{
    /// <summary>
    /// A class responsible for assembly of 65xx source.
    /// </summary>
    public partial class M65xx : MotorolaBase
    {
        private string _cpu;
        private bool _auto;
        private bool _m16;
        private bool _x16;

        private static readonly HashSet<int> s_impliedAccumulator = new()
        {
            Sixty502DotNetParser.ASL, Sixty502DotNetParser.LSR,
            Sixty502DotNetParser.ROL, Sixty502DotNetParser.ROR
        };

        private static readonly Dictionary<Instruction, Opcode> s_6502 = new()
        {
            { new Instruction(Sixty502DotNetParser.BRK, Implied     ), new Opcode("6502",    0x00 ) },
            { new Instruction(Sixty502DotNetParser.ORA, IndX        ), new Opcode("6502",    0x01, 2 ) },
            { new Instruction(Sixty502DotNetParser.ORA, ZeroPage    ), new Opcode("6502",    0x05, 2 ) },
            { new Instruction(Sixty502DotNetParser.ASL, ZeroPage    ), new Opcode("6502",    0x06, 2 ) },
            { new Instruction(Sixty502DotNetParser.PHP, Implied     ), new Opcode("6502",    0x08 ) },
            { new Instruction(Sixty502DotNetParser.ORA, Immediate   ), new Opcode("6502",    0x09, 2 ) },
            { new Instruction(Sixty502DotNetParser.ASL, Implied     ), new Opcode("6502",    0x0a ) },
            { new Instruction(Sixty502DotNetParser.ORA, Absolute    ), new Opcode("6502",    0x0d, 3 ) },
            { new Instruction(Sixty502DotNetParser.ASL, Absolute    ), new Opcode("6502",    0x0e, 3 ) },
            { new Instruction(Sixty502DotNetParser.BPL, Relative    ), new Opcode("6502",    0x10, 2 ) },
            { new Instruction(Sixty502DotNetParser.ORA, IndY        ), new Opcode("6502",    0x11, 2 ) },
            { new Instruction(Sixty502DotNetParser.ORA, ZeroPageX   ), new Opcode("6502",    0x15, 2 ) },
            { new Instruction(Sixty502DotNetParser.ASL, ZeroPageX   ), new Opcode("6502",    0x16, 2 ) },
            { new Instruction(Sixty502DotNetParser.CLC, Implied     ), new Opcode("6502",    0x18 ) },
            { new Instruction(Sixty502DotNetParser.ORA, AbsoluteY   ), new Opcode("6502",    0x19, 3 ) },
            { new Instruction(Sixty502DotNetParser.ORA, AbsoluteX   ), new Opcode("6502",    0x1d, 3 ) },
            { new Instruction(Sixty502DotNetParser.ASL, AbsoluteX   ), new Opcode("6502",    0x1e, 3 ) },
            { new Instruction(Sixty502DotNetParser.JSR, Absolute    ), new Opcode("6502",    0x20, 3 ) },
            { new Instruction(Sixty502DotNetParser.AND, IndX        ), new Opcode("6502",    0x21, 2 ) },
            { new Instruction(Sixty502DotNetParser.BIT, ZeroPage    ), new Opcode("6502",    0x24, 2 ) },
            { new Instruction(Sixty502DotNetParser.AND, ZeroPage    ), new Opcode("6502",    0x25, 2 ) },
            { new Instruction(Sixty502DotNetParser.ROL, ZeroPage    ), new Opcode("6502",    0x26, 2 ) },
            { new Instruction(Sixty502DotNetParser.PLP, Implied     ), new Opcode("6502",    0x28 ) },
            { new Instruction(Sixty502DotNetParser.AND, Immediate   ), new Opcode("6502",    0x29, 2 ) },
            { new Instruction(Sixty502DotNetParser.ROL, Implied     ), new Opcode("6502",    0x2a ) },
            { new Instruction(Sixty502DotNetParser.BIT, Absolute    ), new Opcode("6502",    0x2c, 3 ) },
            { new Instruction(Sixty502DotNetParser.AND, Absolute    ), new Opcode("6502",    0x2d, 3 ) },
            { new Instruction(Sixty502DotNetParser.ROL, Absolute    ), new Opcode("6502",    0x2e, 3 ) },
            { new Instruction(Sixty502DotNetParser.BMI, Relative    ), new Opcode("6502",    0x30, 2 ) },
            { new Instruction(Sixty502DotNetParser.AND, IndY        ), new Opcode("6502",    0x31, 2 ) },
            { new Instruction(Sixty502DotNetParser.AND, ZeroPageX   ), new Opcode("6502",    0x35, 2 ) },
            { new Instruction(Sixty502DotNetParser.ROL, ZeroPageX   ), new Opcode("6502",    0x36, 2 ) },
            { new Instruction(Sixty502DotNetParser.SEC, Implied     ), new Opcode("6502",    0x38 ) },
            { new Instruction(Sixty502DotNetParser.AND, AbsoluteY   ), new Opcode("6502",    0x39, 3 ) },
            { new Instruction(Sixty502DotNetParser.AND, AbsoluteX   ), new Opcode("6502",    0x3d, 3 ) },
            { new Instruction(Sixty502DotNetParser.ROL, AbsoluteX   ), new Opcode("6502",    0x3e, 3 ) },
            { new Instruction(Sixty502DotNetParser.RTI, Implied     ), new Opcode("6502",    0x40 ) },
            { new Instruction(Sixty502DotNetParser.EOR, IndX        ), new Opcode("6502",    0x41, 2 ) },
            { new Instruction(Sixty502DotNetParser.EOR, ZeroPage    ), new Opcode("6502",    0x45, 2 ) },
            { new Instruction(Sixty502DotNetParser.LSR, ZeroPage    ), new Opcode("6502",    0x46, 2 ) },
            { new Instruction(Sixty502DotNetParser.PHA, Implied     ), new Opcode("6502",    0x48 ) },
            { new Instruction(Sixty502DotNetParser.EOR, Immediate   ), new Opcode("6502",    0x49, 2 ) },
            { new Instruction(Sixty502DotNetParser.LSR, Implied     ), new Opcode("6502",    0x4a ) },
            { new Instruction(Sixty502DotNetParser.JMP, Absolute    ), new Opcode("6502",    0x4c, 3 ) },
            { new Instruction(Sixty502DotNetParser.EOR, Absolute    ), new Opcode("6502",    0x4d, 3 ) },
            { new Instruction(Sixty502DotNetParser.LSR, Absolute    ), new Opcode("6502",    0x4e, 3 ) },
            { new Instruction(Sixty502DotNetParser.BVC, Relative    ), new Opcode("6502",    0x50, 2 ) },
            { new Instruction(Sixty502DotNetParser.EOR, IndY        ), new Opcode("6502",    0x51, 2 ) },
            { new Instruction(Sixty502DotNetParser.EOR, ZeroPageX   ), new Opcode("6502",    0x55, 2 ) },
            { new Instruction(Sixty502DotNetParser.LSR, ZeroPageX   ), new Opcode("6502",    0x56, 2 ) },
            { new Instruction(Sixty502DotNetParser.CLI, Implied     ), new Opcode("6502",    0x58 ) },
            { new Instruction(Sixty502DotNetParser.EOR, AbsoluteY   ), new Opcode("6502",    0x59, 3 ) },
            { new Instruction(Sixty502DotNetParser.EOR, AbsoluteX   ), new Opcode("6502",    0x5d, 3 ) },
            { new Instruction(Sixty502DotNetParser.LSR, AbsoluteX   ), new Opcode("6502",    0x5e, 3 ) },
            { new Instruction(Sixty502DotNetParser.RTS, Implied     ), new Opcode("6502",    0x60 ) },
            { new Instruction(Sixty502DotNetParser.ADC, IndX        ), new Opcode("6502",    0x61, 2 ) },
            { new Instruction(Sixty502DotNetParser.ADC, ZeroPage    ), new Opcode("6502",    0x65, 2 ) },
            { new Instruction(Sixty502DotNetParser.ROR, ZeroPage    ), new Opcode("6502",    0x66, 2 ) },
            { new Instruction(Sixty502DotNetParser.PLA, Implied     ), new Opcode("6502",    0x68 ) },
            { new Instruction(Sixty502DotNetParser.ADC, Immediate   ), new Opcode("6502",    0x69, 2 ) },
            { new Instruction(Sixty502DotNetParser.ROR, Implied     ), new Opcode("6502",    0x6a ) },
            { new Instruction(Sixty502DotNetParser.JMP, IndAbs      ), new Opcode("6502",    0x6c, 3 ) },
            { new Instruction(Sixty502DotNetParser.ADC, Absolute    ), new Opcode("6502",    0x6d, 3 ) },
            { new Instruction(Sixty502DotNetParser.ROR, Absolute    ), new Opcode("6502",    0x6e, 3 ) },
            { new Instruction(Sixty502DotNetParser.BVS, Relative    ), new Opcode("6502",    0x70, 2 ) },
            { new Instruction(Sixty502DotNetParser.ADC, IndY        ), new Opcode("6502",    0x71, 2 ) },
            { new Instruction(Sixty502DotNetParser.ADC, ZeroPageX   ), new Opcode("6502",    0x75, 2 ) },
            { new Instruction(Sixty502DotNetParser.ROR, ZeroPageX   ), new Opcode("6502",    0x76, 2 ) },
            { new Instruction(Sixty502DotNetParser.SEI, Implied     ), new Opcode("6502",    0x78 ) },
            { new Instruction(Sixty502DotNetParser.ADC, AbsoluteY   ), new Opcode("6502",    0x79, 3 ) },
            { new Instruction(Sixty502DotNetParser.ADC, AbsoluteX   ), new Opcode("6502",    0x7d, 3 ) },
            { new Instruction(Sixty502DotNetParser.ROR, AbsoluteX   ), new Opcode("6502",    0x7e, 3 ) },
            { new Instruction(Sixty502DotNetParser.STA, IndX        ), new Opcode("6502",    0x81, 2 ) },
            { new Instruction(Sixty502DotNetParser.STY, ZeroPage    ), new Opcode("6502",    0x84, 2 ) },
            { new Instruction(Sixty502DotNetParser.STA, ZeroPage    ), new Opcode("6502",    0x85, 2 ) },
            { new Instruction(Sixty502DotNetParser.STX, ZeroPage    ), new Opcode("6502",    0x86, 2 ) },
            { new Instruction(Sixty502DotNetParser.DEY, Implied     ), new Opcode("6502",    0x88 ) },
            { new Instruction(Sixty502DotNetParser.TXA, Implied     ), new Opcode("6502",    0x8a ) },
            { new Instruction(Sixty502DotNetParser.STY, Absolute    ), new Opcode("6502",    0x8c, 3 ) },
            { new Instruction(Sixty502DotNetParser.STA, Absolute    ), new Opcode("6502",    0x8d, 3 ) },
            { new Instruction(Sixty502DotNetParser.STX, Absolute    ), new Opcode("6502",    0x8e, 3 ) },
            { new Instruction(Sixty502DotNetParser.BCC, Relative    ), new Opcode("6502",    0x90, 2 ) },
            { new Instruction(Sixty502DotNetParser.STA, IndY        ), new Opcode("6502",    0x91, 2 ) },
            { new Instruction(Sixty502DotNetParser.STY, ZeroPageX   ), new Opcode("6502",    0x94, 2 ) },
            { new Instruction(Sixty502DotNetParser.STA, ZeroPageX   ), new Opcode("6502",    0x95, 2 ) },
            { new Instruction(Sixty502DotNetParser.STX, ZeroPageY   ), new Opcode("6502",    0x96, 2 ) },
            { new Instruction(Sixty502DotNetParser.TYA, Implied     ), new Opcode("6502",    0x98 ) },
            { new Instruction(Sixty502DotNetParser.STA, AbsoluteY   ), new Opcode("6502",    0x99, 3 ) },
            { new Instruction(Sixty502DotNetParser.TXS, Implied     ), new Opcode("6502",    0x9a ) },
            { new Instruction(Sixty502DotNetParser.STA, AbsoluteX   ), new Opcode("6502",    0x9d, 3 ) },
            { new Instruction(Sixty502DotNetParser.LDY, Immediate   ), new Opcode("6502",    0xa0, 2 ) },
            { new Instruction(Sixty502DotNetParser.LDA, IndX        ), new Opcode("6502",    0xa1, 2 ) },
            { new Instruction(Sixty502DotNetParser.LDX, Immediate   ), new Opcode("6502",    0xa2, 2 ) },
            { new Instruction(Sixty502DotNetParser.LDY, ZeroPage    ), new Opcode("6502",    0xa4, 2 ) },
            { new Instruction(Sixty502DotNetParser.LDA, ZeroPage    ), new Opcode("6502",    0xa5, 2 ) },
            { new Instruction(Sixty502DotNetParser.LDX, ZeroPage    ), new Opcode("6502",    0xa6, 2 ) },
            { new Instruction(Sixty502DotNetParser.TAY, Implied     ), new Opcode("6502",    0xa8 ) },
            { new Instruction(Sixty502DotNetParser.LDA, Immediate   ), new Opcode("6502",    0xa9, 2 ) },
            { new Instruction(Sixty502DotNetParser.TAX, Implied     ), new Opcode("6502",    0xaa ) },
            { new Instruction(Sixty502DotNetParser.LDY, Absolute    ), new Opcode("6502",    0xac, 3 ) },
            { new Instruction(Sixty502DotNetParser.LDA, Absolute    ), new Opcode("6502",    0xad, 3 ) },
            { new Instruction(Sixty502DotNetParser.LDX, Absolute    ), new Opcode("6502",    0xae, 3 ) },
            { new Instruction(Sixty502DotNetParser.BCS, Relative    ), new Opcode("6502",    0xb0, 2 ) },
            { new Instruction(Sixty502DotNetParser.LDA, IndY        ), new Opcode("6502",    0xb1, 2 ) },
            { new Instruction(Sixty502DotNetParser.LDY, ZeroPageX   ), new Opcode("6502",    0xb4, 2 ) },
            { new Instruction(Sixty502DotNetParser.LDA, ZeroPageX   ), new Opcode("6502",    0xb5, 2 ) },
            { new Instruction(Sixty502DotNetParser.LDX, ZeroPageY   ), new Opcode("6502",    0xb6, 2 ) },
            { new Instruction(Sixty502DotNetParser.CLV, Implied     ), new Opcode("6502",    0xb8 ) },
            { new Instruction(Sixty502DotNetParser.LDA, AbsoluteY   ), new Opcode("6502",    0xb9, 3 ) },
            { new Instruction(Sixty502DotNetParser.TSX, Implied     ), new Opcode("6502",    0xba ) },
            { new Instruction(Sixty502DotNetParser.LDY, AbsoluteX   ), new Opcode("6502",    0xbc, 3 ) },
            { new Instruction(Sixty502DotNetParser.LDA, AbsoluteX   ), new Opcode("6502",    0xbd, 3 ) },
            { new Instruction(Sixty502DotNetParser.LDX, AbsoluteY   ), new Opcode("6502",    0xbe, 3 ) },
            { new Instruction(Sixty502DotNetParser.CPY, Immediate   ), new Opcode("6502",    0xc0, 2 ) },
            { new Instruction(Sixty502DotNetParser.CMP, IndX        ), new Opcode("6502",    0xc1, 2 ) },
            { new Instruction(Sixty502DotNetParser.CPY, ZeroPage    ), new Opcode("6502",    0xc4, 2 ) },
            { new Instruction(Sixty502DotNetParser.CMP, ZeroPage    ), new Opcode("6502",    0xc5, 2 ) },
            { new Instruction(Sixty502DotNetParser.DEC, ZeroPage    ), new Opcode("6502",    0xc6, 2 ) },
            { new Instruction(Sixty502DotNetParser.INY, Implied     ), new Opcode("6502",    0xc8 ) },
            { new Instruction(Sixty502DotNetParser.CMP, Immediate   ), new Opcode("6502",    0xc9, 2 ) },
            { new Instruction(Sixty502DotNetParser.DEX, Implied     ), new Opcode("6502",    0xca ) },
            { new Instruction(Sixty502DotNetParser.CPY, Absolute    ), new Opcode("6502",    0xcc, 3 ) },
            { new Instruction(Sixty502DotNetParser.CMP, Absolute    ), new Opcode("6502",    0xcd, 3 ) },
            { new Instruction(Sixty502DotNetParser.DEC, Absolute    ), new Opcode("6502",    0xce, 3 ) },
            { new Instruction(Sixty502DotNetParser.BNE, Relative    ), new Opcode("6502",    0xd0, 2 ) },
            { new Instruction(Sixty502DotNetParser.CMP, IndY        ), new Opcode("6502",    0xd1, 2 ) },
            { new Instruction(Sixty502DotNetParser.CMP, ZeroPageX   ), new Opcode("6502",    0xd5, 2 ) },
            { new Instruction(Sixty502DotNetParser.DEC, ZeroPageX   ), new Opcode("6502",    0xd6, 2 ) },
            { new Instruction(Sixty502DotNetParser.CLD, Implied     ), new Opcode("6502",    0xd8 ) },
            { new Instruction(Sixty502DotNetParser.CMP, AbsoluteY   ), new Opcode("6502",    0xd9, 3 ) },
            { new Instruction(Sixty502DotNetParser.CMP, AbsoluteX   ), new Opcode("6502",    0xdd, 3 ) },
            { new Instruction(Sixty502DotNetParser.DEC, AbsoluteX   ), new Opcode("6502",    0xde, 3 ) },
            { new Instruction(Sixty502DotNetParser.CPX, Immediate   ), new Opcode("6502",    0xe0, 2 ) },
            { new Instruction(Sixty502DotNetParser.SBC, IndX        ), new Opcode("6502",    0xe1, 2 ) },
            { new Instruction(Sixty502DotNetParser.CPX, ZeroPage    ), new Opcode("6502",    0xe4, 2 ) },
            { new Instruction(Sixty502DotNetParser.SBC, ZeroPage    ), new Opcode("6502",    0xe5, 2 ) },
            { new Instruction(Sixty502DotNetParser.INC, ZeroPage    ), new Opcode("6502",    0xe6, 2 ) },
            { new Instruction(Sixty502DotNetParser.INX, Implied     ), new Opcode("6502",    0xe8 ) },
            { new Instruction(Sixty502DotNetParser.SBC, Immediate   ), new Opcode("6502",    0xe9, 2 ) },
            { new Instruction(Sixty502DotNetParser.NOP, Implied     ), new Opcode("6502",    0xea ) },
            { new Instruction(Sixty502DotNetParser.CPX, Absolute    ), new Opcode("6502",    0xec, 3 ) },
            { new Instruction(Sixty502DotNetParser.SBC, Absolute    ), new Opcode("6502",    0xed, 3 ) },
            { new Instruction(Sixty502DotNetParser.INC, Absolute    ), new Opcode("6502",    0xee, 3 ) },
            { new Instruction(Sixty502DotNetParser.BEQ, Relative    ), new Opcode("6502",    0xf0, 2 ) },
            { new Instruction(Sixty502DotNetParser.SBC, IndY        ), new Opcode("6502",    0xf1, 2 ) },
            { new Instruction(Sixty502DotNetParser.SBC, ZeroPageX   ), new Opcode("6502",    0xf5, 2 ) },
            { new Instruction(Sixty502DotNetParser.INC, ZeroPageX   ), new Opcode("6502",    0xf6, 2 ) },
            { new Instruction(Sixty502DotNetParser.SED, Implied     ), new Opcode("6502",    0xf8 ) },
            { new Instruction(Sixty502DotNetParser.SBC, AbsoluteY   ), new Opcode("6502",    0xf9, 3 ) },
            { new Instruction(Sixty502DotNetParser.SBC, AbsoluteX   ), new Opcode("6502",    0xfd, 3 ) },
            { new Instruction(Sixty502DotNetParser.INC, AbsoluteX   ), new Opcode("6502",    0xfe, 3 ) }
        };

        private static readonly Dictionary<Instruction, Opcode> s_6502i = new()
        {
            { new Instruction(Sixty502DotNetParser.JAM, Implied     ), new Opcode("6502i",   0x03) },
            { new Instruction(Sixty502DotNetParser.SLO, IndX        ), new Opcode("6502i",   0x03, 2) },
            { new Instruction(Sixty502DotNetParser.DOP, ZeroPage    ), new Opcode("6502i",   0x04, 2) },
            { new Instruction(Sixty502DotNetParser.SLO, ZeroPage    ), new Opcode("6502i",   0x07, 2) },
            { new Instruction(Sixty502DotNetParser.TOP, Implied     ), new Opcode("6502i",   0x0c) },
            { new Instruction(Sixty502DotNetParser.TOP, Absolute    ), new Opcode("6502i",   0x0c, 3) },
            { new Instruction(Sixty502DotNetParser.SLO, Absolute    ), new Opcode("6502i",   0x0f, 3) },
            { new Instruction(Sixty502DotNetParser.STP, Implied     ), new Opcode("6502i",   0x13) },
            { new Instruction(Sixty502DotNetParser.SLO, IndY        ), new Opcode("6502i",   0x13, 2) },
            { new Instruction(Sixty502DotNetParser.DOP, ZeroPageX   ), new Opcode("6502i",   0x14, 2) },
            { new Instruction(Sixty502DotNetParser.SLO, ZeroPageX   ), new Opcode("6502i",   0x17, 2) },
            { new Instruction(Sixty502DotNetParser.SLO, AbsoluteY   ), new Opcode("6502i",   0x1b, 3) },
            { new Instruction(Sixty502DotNetParser.SLO, AbsoluteX   ), new Opcode("6502i",   0x1f, 3) },
            { new Instruction(Sixty502DotNetParser.RLA, IndX        ), new Opcode("6502i",   0x23, 2) },
            { new Instruction(Sixty502DotNetParser.RLA, ZeroPage    ), new Opcode("6502i",   0x27, 2) },
            { new Instruction(Sixty502DotNetParser.ANC, Immediate   ), new Opcode("6502i",   0x2b, 2) },
            { new Instruction(Sixty502DotNetParser.RLA, Absolute    ), new Opcode("6502i",   0x2f, 3) },
            { new Instruction(Sixty502DotNetParser.RLA, IndY        ), new Opcode("6502i",   0x33, 2) },
            { new Instruction(Sixty502DotNetParser.RLA, ZeroPageX   ), new Opcode("6502i",   0x37, 2) },
            { new Instruction(Sixty502DotNetParser.RLA, AbsoluteY   ), new Opcode("6502i",   0x3b, 3) },
            { new Instruction(Sixty502DotNetParser.RLA, AbsoluteX   ), new Opcode("6502i",   0x3f, 3) },
            { new Instruction(Sixty502DotNetParser.SRE, IndX        ), new Opcode("6502i",   0x43, 2) },
            { new Instruction(Sixty502DotNetParser.SRE, ZeroPage    ), new Opcode("6502i",   0x47, 2) },
            { new Instruction(Sixty502DotNetParser.ASR, Immediate   ), new Opcode("6502i",   0x4b, 2) },
            { new Instruction(Sixty502DotNetParser.SRE, Absolute    ), new Opcode("6502i",   0x4f, 3) },
            { new Instruction(Sixty502DotNetParser.SRE, IndY        ), new Opcode("6502i",   0x53, 2) },
            { new Instruction(Sixty502DotNetParser.SRE, ZeroPageX   ), new Opcode("6502i",   0x57, 2) },
            { new Instruction(Sixty502DotNetParser.SRE, AbsoluteY   ), new Opcode("6502i",   0x5b, 3) },
            { new Instruction(Sixty502DotNetParser.SRE, AbsoluteX   ), new Opcode("6502i",   0x5f, 3) },
            { new Instruction(Sixty502DotNetParser.RRA, IndX        ), new Opcode("6502i",   0x63, 2) },
            { new Instruction(Sixty502DotNetParser.RRA, ZeroPage    ), new Opcode("6502i",   0x67, 2) },
            { new Instruction(Sixty502DotNetParser.ARR, Immediate   ), new Opcode("6502i",   0x6b, 2) },
            { new Instruction(Sixty502DotNetParser.RRA, Absolute    ), new Opcode("6502i",   0x6f, 3) },
            { new Instruction(Sixty502DotNetParser.RRA, IndY        ), new Opcode("6502i",   0x73, 2) },
            { new Instruction(Sixty502DotNetParser.RRA, ZeroPageX   ), new Opcode("6502i",   0x77, 2) },
            { new Instruction(Sixty502DotNetParser.RRA, AbsoluteY   ), new Opcode("6502i",   0x7b, 3) },
            { new Instruction(Sixty502DotNetParser.RRA, AbsoluteX   ), new Opcode("6502i",   0x7f, 3) },
            { new Instruction(Sixty502DotNetParser.DOP, Implied     ), new Opcode("6502i",   0x80) },
            { new Instruction(Sixty502DotNetParser.DOP, Immediate   ), new Opcode("6502i",   0x80, 2) },
            { new Instruction(Sixty502DotNetParser.SAX, IndX        ), new Opcode("6502i",   0x83, 2) },
            { new Instruction(Sixty502DotNetParser.SAX, ZeroPage    ), new Opcode("6502i",   0x87, 2) },
            { new Instruction(Sixty502DotNetParser.ANE, Immediate   ), new Opcode("6502i",   0x8b, 2) },
            { new Instruction(Sixty502DotNetParser.SAX, Absolute    ), new Opcode("6502i",   0x8f, 3) },
            { new Instruction(Sixty502DotNetParser.SHA, IndY        ), new Opcode("6502i",   0x93, 2) },
            { new Instruction(Sixty502DotNetParser.SAX, ZeroPageY   ), new Opcode("6502i",   0x97, 2) },
            { new Instruction(Sixty502DotNetParser.TAS, AbsoluteY   ), new Opcode("6502i",   0x9b, 3) },
            { new Instruction(Sixty502DotNetParser.SHY, AbsoluteX   ), new Opcode("6502i",   0x9c, 3) },
            { new Instruction(Sixty502DotNetParser.SHX, AbsoluteY   ), new Opcode("6502i",   0x9e, 3) },
            { new Instruction(Sixty502DotNetParser.SHA, AbsoluteY   ), new Opcode("6502i",   0x9f, 3) },
            { new Instruction(Sixty502DotNetParser.LAX, IndX        ), new Opcode("6502i",   0xa3, 2) },
            { new Instruction(Sixty502DotNetParser.LAX, ZeroPage    ), new Opcode("6502i",   0xa7, 2) },
            { new Instruction(Sixty502DotNetParser.LAX, Absolute    ), new Opcode("6502i",   0xaf, 3) },
            { new Instruction(Sixty502DotNetParser.LAX, IndY        ), new Opcode("6502i",   0xb3, 2) },
            { new Instruction(Sixty502DotNetParser.LAX, ZeroPageY   ), new Opcode("6502i",   0xb7, 2) },
            { new Instruction(Sixty502DotNetParser.LAS, AbsoluteY   ), new Opcode("6502i",   0xbb, 3) },
            { new Instruction(Sixty502DotNetParser.LAX, AbsoluteY   ), new Opcode("6502i",   0xbf, 3) },
            { new Instruction(Sixty502DotNetParser.DCP, IndX        ), new Opcode("6502i",   0xc3, 2) },
            { new Instruction(Sixty502DotNetParser.DCP, ZeroPage    ), new Opcode("6502i",   0xc7, 2) },
            { new Instruction(Sixty502DotNetParser.SAX, Immediate   ), new Opcode("6502i",   0xcb, 2) },
            { new Instruction(Sixty502DotNetParser.DCP, Absolute    ), new Opcode("6502i",   0xcf, 3) },
            { new Instruction(Sixty502DotNetParser.DCP, IndY        ), new Opcode("6502i",   0xd3, 2) },
            { new Instruction(Sixty502DotNetParser.DCP, ZeroPageX   ), new Opcode("6502i",   0xd7, 2) },
            { new Instruction(Sixty502DotNetParser.DCP, AbsoluteY   ), new Opcode("6502i",   0xdb, 3) },
            { new Instruction(Sixty502DotNetParser.DCP, AbsoluteX   ), new Opcode("6502i",   0xdf, 3) },
            { new Instruction(Sixty502DotNetParser.ISB, IndX        ), new Opcode("6502i",   0xe3, 2) },
            { new Instruction(Sixty502DotNetParser.ISB, ZeroPage    ), new Opcode("6502i",   0xe7, 2) },
            { new Instruction(Sixty502DotNetParser.ISB, Absolute    ), new Opcode("6502i",   0xef, 3) },
            { new Instruction(Sixty502DotNetParser.ISB, IndY        ), new Opcode("6502i",   0xf3, 2) },
            { new Instruction(Sixty502DotNetParser.ISB, ZeroPageX   ), new Opcode("6502i",   0xf7, 2) },
            { new Instruction(Sixty502DotNetParser.ISB, AbsoluteY   ), new Opcode("6502i",   0xfb, 3) },
            { new Instruction(Sixty502DotNetParser.ISB, AbsoluteX   ), new Opcode("6502i",   0xff, 3) }
        };

        private static readonly Dictionary<Instruction, Opcode> s_65816 = new()
        {
            { new Instruction(Sixty502DotNetParser.COP, Immediate   ), new Opcode("65816", 0x02, 2) },
            { new Instruction(Sixty502DotNetParser.ORA, ZeroPageS   ), new Opcode("65816", 0x03, 2) },
            { new Instruction(Sixty502DotNetParser.ORA, Dir         ), new Opcode("65816", 0x07, 2) },
            { new Instruction(Sixty502DotNetParser.PHD, Implied     ), new Opcode("65816", 0x0b) },
            { new Instruction(Sixty502DotNetParser.ORA, Long        ), new Opcode("65816", 0x0f, 4) },
            { new Instruction(Sixty502DotNetParser.ORA, IndS        ), new Opcode("65816", 0x13, 2) },
            { new Instruction(Sixty502DotNetParser.ORA, DirY        ), new Opcode("65816", 0x17, 2) },
            { new Instruction(Sixty502DotNetParser.TCS, Implied     ), new Opcode("65816", 0x1b) },
            { new Instruction(Sixty502DotNetParser.ORA, LongX       ), new Opcode("65816", 0x1f, 4) },
            { new Instruction(Sixty502DotNetParser.JSL, Long        ), new Opcode("65816", 0x22, 4) },
            { new Instruction(Sixty502DotNetParser.JSR, Long        ), new Opcode("65816", 0x22, 4) },
            { new Instruction(Sixty502DotNetParser.AND, ZeroPageS   ), new Opcode("65816", 0x23, 2) },
            { new Instruction(Sixty502DotNetParser.AND, Dir         ), new Opcode("65816", 0x27, 2) },
            { new Instruction(Sixty502DotNetParser.PLD, Implied     ), new Opcode("65816", 0x2b) },
            { new Instruction(Sixty502DotNetParser.AND, Long        ), new Opcode("65816", 0x2f, 4) },
            { new Instruction(Sixty502DotNetParser.AND, IndS        ), new Opcode("65816", 0x33, 2) },
            { new Instruction(Sixty502DotNetParser.AND, DirY        ), new Opcode("65816", 0x37, 2) },
            { new Instruction(Sixty502DotNetParser.TSC, Implied     ), new Opcode("65816", 0x3b) },
            { new Instruction(Sixty502DotNetParser.AND, LongX       ), new Opcode("65816", 0x3f, 4) },
            { new Instruction(Sixty502DotNetParser.WDM, Implied     ), new Opcode("65816", 0x42) },
            { new Instruction(Sixty502DotNetParser.EOR, ZeroPageS   ), new Opcode("65816", 0x43, 2) },
            { new Instruction(Sixty502DotNetParser.MVP, TwoOperand  ), new Opcode("65816", 0x44, 3) },
            { new Instruction(Sixty502DotNetParser.EOR, Dir         ), new Opcode("65816", 0x47, 2) },
            { new Instruction(Sixty502DotNetParser.PHK, Implied     ), new Opcode("65816", 0x4b) },
            { new Instruction(Sixty502DotNetParser.EOR, Long        ), new Opcode("65816", 0x4f, 4) },
            { new Instruction(Sixty502DotNetParser.EOR, IndS        ), new Opcode("65816", 0x53, 2) },
            { new Instruction(Sixty502DotNetParser.MVN, TwoOperand  ), new Opcode("65816", 0x54, 3) },
            { new Instruction(Sixty502DotNetParser.EOR, DirY        ), new Opcode("65816", 0x57, 2) },
            { new Instruction(Sixty502DotNetParser.TCD, Implied     ), new Opcode("65816", 0x5b) },
            { new Instruction(Sixty502DotNetParser.JML, Long        ), new Opcode("65816", 0x5c, 4) },
            { new Instruction(Sixty502DotNetParser.JMP, Long        ), new Opcode("65816", 0x5c, 4) },
            { new Instruction(Sixty502DotNetParser.EOR, LongX       ), new Opcode("65816", 0x5f, 4) },
            { new Instruction(Sixty502DotNetParser.PER, RelativeAbs ), new Opcode("65816", 0x62, 3) },
            { new Instruction(Sixty502DotNetParser.ADC, ZeroPageS   ), new Opcode("65816", 0x63, 2) },
            { new Instruction(Sixty502DotNetParser.ADC, Dir         ), new Opcode("65816", 0x67, 2) },
            { new Instruction(Sixty502DotNetParser.RTL, Implied     ), new Opcode("65816", 0x6b) },
            { new Instruction(Sixty502DotNetParser.ADC, Long        ), new Opcode("65816", 0x6f, 4) },
            { new Instruction(Sixty502DotNetParser.ADC, IndS        ), new Opcode("65816", 0x73, 2) },
            { new Instruction(Sixty502DotNetParser.ADC, DirY        ), new Opcode("65816", 0x77, 2) },
            { new Instruction(Sixty502DotNetParser.TDC, Implied     ), new Opcode("65816", 0x7b) },
            { new Instruction(Sixty502DotNetParser.ADC, LongX       ), new Opcode("65816", 0x7f, 4) },
            { new Instruction(Sixty502DotNetParser.BRL, RelativeAbs ), new Opcode("65816", 0x82, 3) },
            { new Instruction(Sixty502DotNetParser.STA, ZeroPageS   ), new Opcode("65816", 0x83, 2) },
            { new Instruction(Sixty502DotNetParser.STA, Dir         ), new Opcode("65816", 0x87, 2) },
            { new Instruction(Sixty502DotNetParser.PHB, Implied     ), new Opcode("65816", 0x8b) },
            { new Instruction(Sixty502DotNetParser.STA, Long        ), new Opcode("65816", 0x8f, 4) },
            { new Instruction(Sixty502DotNetParser.STA, IndS        ), new Opcode("65816", 0x93, 2) },
            { new Instruction(Sixty502DotNetParser.STA, DirY        ), new Opcode("65816", 0x97, 2) },
            { new Instruction(Sixty502DotNetParser.TXY, Implied     ), new Opcode("65816", 0x9b) },
            { new Instruction(Sixty502DotNetParser.STA, LongX       ), new Opcode("65816", 0x9f, 4) },
            { new Instruction(Sixty502DotNetParser.LDA, ZeroPageS   ), new Opcode("65816", 0xa3, 2) },
            { new Instruction(Sixty502DotNetParser.LDA, Dir         ), new Opcode("65816", 0xa7, 2) },
            { new Instruction(Sixty502DotNetParser.PLB, Implied     ), new Opcode("65816", 0xab) },
            { new Instruction(Sixty502DotNetParser.LDA, Long        ), new Opcode("65816", 0xaf, 4) },
            { new Instruction(Sixty502DotNetParser.LDA, IndS        ), new Opcode("65816", 0xb3, 2) },
            { new Instruction(Sixty502DotNetParser.LDA, DirY        ), new Opcode("65816", 0xb7, 2) },
            { new Instruction(Sixty502DotNetParser.TYX, Implied     ), new Opcode("65816", 0xbb) },
            { new Instruction(Sixty502DotNetParser.LDA, LongX       ), new Opcode("65816", 0xbf, 4) },
            { new Instruction(Sixty502DotNetParser.REP, Immediate   ), new Opcode("65816", 0xc2, 2) },
            { new Instruction(Sixty502DotNetParser.CMP, ZeroPageS   ), new Opcode("65816", 0xc3, 2) },
            { new Instruction(Sixty502DotNetParser.CMP, Dir         ), new Opcode("65816", 0xc7, 2) },
            { new Instruction(Sixty502DotNetParser.CMP, Long        ), new Opcode("65816", 0xcf, 4) },
            { new Instruction(Sixty502DotNetParser.CMP, IndS        ), new Opcode("65816", 0xd3, 2) },
            { new Instruction(Sixty502DotNetParser.PEI, IndZp       ), new Opcode("65816", 0xd4, 2) },
            { new Instruction(Sixty502DotNetParser.CMP, DirY        ), new Opcode("65816", 0xd7, 2) },
            { new Instruction(Sixty502DotNetParser.JMP, DirAbs      ), new Opcode("65816", 0xdc, 3) },
            { new Instruction(Sixty502DotNetParser.CMP, LongX       ), new Opcode("65816", 0xdf, 4) },
            { new Instruction(Sixty502DotNetParser.SEP, Immediate   ), new Opcode("65816", 0xe2, 2) },
            { new Instruction(Sixty502DotNetParser.SBC, ZeroPageS   ), new Opcode("65816", 0xe3, 2) },
            { new Instruction(Sixty502DotNetParser.SBC, Dir         ), new Opcode("65816", 0xe7, 2) },
            { new Instruction(Sixty502DotNetParser.XBA, Implied     ), new Opcode("65816", 0xeb) },
            { new Instruction(Sixty502DotNetParser.SBC, Long        ), new Opcode("65816", 0xef, 4) },
            { new Instruction(Sixty502DotNetParser.SBC, IndS        ), new Opcode("65816", 0xf3, 2) },
            { new Instruction(Sixty502DotNetParser.PEA, ImmAbs      ), new Opcode("65816", 0xf4, 3) },
            { new Instruction(Sixty502DotNetParser.PEA, Absolute    ), new Opcode("65816", 0xf4, 3) },
            { new Instruction(Sixty502DotNetParser.XCE, Implied     ), new Opcode("65816", 0xfb) },
            { new Instruction(Sixty502DotNetParser.JSR, IndAbsX     ), new Opcode("65816", 0xfc, 3) },
            { new Instruction(Sixty502DotNetParser.SBC, LongX       ), new Opcode("65816", 0xff, 4) }
        };

        private static readonly Dictionary<Instruction, Opcode> s_65c02 = new()
        {
            { new Instruction(Sixty502DotNetParser.TSB, ZeroPage    ), new Opcode("65C02", 0x04, 2) },
            { new Instruction(Sixty502DotNetParser.TSB, Absolute    ), new Opcode("65C02", 0x0c, 3) },
            { new Instruction(Sixty502DotNetParser.ORA, IndZp       ), new Opcode("65C02", 0x12, 2) },
            { new Instruction(Sixty502DotNetParser.TRB, ZeroPage    ), new Opcode("65C02", 0x14, 2) },
            { new Instruction(Sixty502DotNetParser.INC, Implied     ), new Opcode("65C02", 0x1a) },
            { new Instruction(Sixty502DotNetParser.TRB, Absolute    ), new Opcode("65C02", 0x1c, 3) },
            { new Instruction(Sixty502DotNetParser.AND, IndZp       ), new Opcode("65C02", 0x32, 2) },
            { new Instruction(Sixty502DotNetParser.BIT, ZeroPageX   ), new Opcode("65C02", 0x34, 2) },
            { new Instruction(Sixty502DotNetParser.DEC, Implied     ), new Opcode("65C02", 0x3a) },
            { new Instruction(Sixty502DotNetParser.BIT, AbsoluteX   ), new Opcode("65C02", 0x3c, 3) },
            { new Instruction(Sixty502DotNetParser.EOR, IndZp       ), new Opcode("65C02", 0x52, 2) },
            { new Instruction(Sixty502DotNetParser.PHY, Implied     ), new Opcode("65C02", 0x5a) },
            { new Instruction(Sixty502DotNetParser.STZ, ZeroPage    ), new Opcode("65C02", 0x64, 2) },
            { new Instruction(Sixty502DotNetParser.ADC, IndZp       ), new Opcode("65C02", 0x72, 2) },
            { new Instruction(Sixty502DotNetParser.STZ, ZeroPageX   ), new Opcode("65C02", 0x74, 2) },
            { new Instruction(Sixty502DotNetParser.PLY, Implied     ), new Opcode("65C02", 0x7a) },
            { new Instruction(Sixty502DotNetParser.JMP, IndAbsX     ), new Opcode("65C02", 0x7c, 3) },
            { new Instruction(Sixty502DotNetParser.BRA, Relative    ), new Opcode("65C02", 0x80, 2) },
            { new Instruction(Sixty502DotNetParser.BIT, Immediate   ), new Opcode("65C02", 0x89, 2) },
            { new Instruction(Sixty502DotNetParser.STA, IndZp       ), new Opcode("65C02", 0x92, 2) },
            { new Instruction(Sixty502DotNetParser.STZ, Absolute    ), new Opcode("65C02", 0x9c, 3) },
            { new Instruction(Sixty502DotNetParser.STZ, AbsoluteX   ), new Opcode("65C02", 0x9e, 3) },
            { new Instruction(Sixty502DotNetParser.LDA, IndZp       ), new Opcode("65C02", 0xb2, 2) },
            { new Instruction(Sixty502DotNetParser.CMP, IndZp       ), new Opcode("65C02", 0xd2, 2) },
            { new Instruction(Sixty502DotNetParser.PHX, Implied     ), new Opcode("65C02", 0xda) },
            { new Instruction(Sixty502DotNetParser.SBC, IndZp       ), new Opcode("65C02", 0xf2, 2) },
            { new Instruction(Sixty502DotNetParser.PLX, Implied     ), new Opcode("65C02", 0xfa) }
        };

        private static readonly Dictionary<Instruction, Opcode> s_65ce02 = new()
        {
            { new Instruction(Sixty502DotNetParser.CLE, Implied     ), new Opcode("65CE02", 0x02) },
            { new Instruction(Sixty502DotNetParser.SEE, Implied     ), new Opcode("65CE02", 0x03) },
            { new Instruction(Sixty502DotNetParser.TSY, Implied     ), new Opcode("65CE02", 0x0b) },
            { new Instruction(Sixty502DotNetParser.ORA, IndZ        ), new Opcode("65CE02", 0x12, 2) },
            { new Instruction(Sixty502DotNetParser.BPL, RelativeAbs ), new Opcode("65CE02", 0x13, 3) },
            { new Instruction(Sixty502DotNetParser.INZ, Implied     ), new Opcode("65CE02", 0x1b) },
            { new Instruction(Sixty502DotNetParser.JSR, IndAbs      ), new Opcode("65CE02", 0x22, 3) },
            { new Instruction(Sixty502DotNetParser.JSR, IndAbsX     ), new Opcode("65CE02", 0x23, 3) },
            { new Instruction(Sixty502DotNetParser.TYS, Implied     ), new Opcode("65CE02", 0x2b) },
            { new Instruction(Sixty502DotNetParser.AND, IndZ        ), new Opcode("65CE02", 0x32, 2) },
            { new Instruction(Sixty502DotNetParser.BMI, RelativeAbs ), new Opcode("65CE02", 0x33, 3) },
            { new Instruction(Sixty502DotNetParser.DEZ, Implied     ), new Opcode("65CE02", 0x3b) },
            { new Instruction(Sixty502DotNetParser.NEG, Implied     ), new Opcode("65CE02", 0x42) },
            { new Instruction(Sixty502DotNetParser.ASR, Implied     ), new Opcode("65CE02", 0x43) },
            { new Instruction(Sixty502DotNetParser.ASR, ZeroPage    ), new Opcode("65CE02", 0x44, 2) },
            { new Instruction(Sixty502DotNetParser.TAZ, Implied     ), new Opcode("65CE02", 0x4b) },
            { new Instruction(Sixty502DotNetParser.EOR, IndZ        ), new Opcode("65CE02", 0x52, 2) },
            { new Instruction(Sixty502DotNetParser.BVC, RelativeAbs ), new Opcode("65CE02", 0x53, 3) },
            { new Instruction(Sixty502DotNetParser.ASR, ZeroPageX   ), new Opcode("65CE02", 0x54, 2) },
            { new Instruction(Sixty502DotNetParser.TAB, Implied     ), new Opcode("65CE02", 0x5b) },
            { new Instruction(Sixty502DotNetParser.RTS, Immediate   ), new Opcode("65CE02", 0x62, 2) },
            { new Instruction(Sixty502DotNetParser.RTN, Implied     ), new Opcode("65CE02", 0x63) },
            { new Instruction(Sixty502DotNetParser.BSR, Absolute    ), new Opcode("65CE02", 0x63, 3) },
            { new Instruction(Sixty502DotNetParser.TZA, Implied     ), new Opcode("65CE02", 0x6b) },
            { new Instruction(Sixty502DotNetParser.ADC, IndZ        ), new Opcode("65CE02", 0x72, 2) },
            { new Instruction(Sixty502DotNetParser.BVS, RelativeAbs ), new Opcode("65CE02", 0x73, 3) },
            { new Instruction(Sixty502DotNetParser.TBA, Implied     ), new Opcode("65CE02", 0x7b) },
            { new Instruction(Sixty502DotNetParser.STA, IndSp       ), new Opcode("65CE02", 0x82, 2) },
            { new Instruction(Sixty502DotNetParser.BRA, RelativeAbs ), new Opcode("65CE02", 0x83, 3) },
            { new Instruction(Sixty502DotNetParser.STY, AbsoluteX   ), new Opcode("65CE02", 0x8b, 3) },
            { new Instruction(Sixty502DotNetParser.STA, IndZ        ), new Opcode("65CE02", 0x92, 2) },
            { new Instruction(Sixty502DotNetParser.BCC, RelativeAbs ), new Opcode("65CE02", 0x93, 3) },
            { new Instruction(Sixty502DotNetParser.BLT, RelativeAbs ), new Opcode("65CE02", 0x93, 3) },
            { new Instruction(Sixty502DotNetParser.STX, AbsoluteY   ), new Opcode("65CE02", 0x9b, 3) },
            { new Instruction(Sixty502DotNetParser.LDZ, Immediate   ), new Opcode("65CE02", 0xa3, 2) },
            { new Instruction(Sixty502DotNetParser.LDZ, Absolute    ), new Opcode("65CE02", 0xab, 3) },
            { new Instruction(Sixty502DotNetParser.LDA, IndZ        ), new Opcode("65CE02", 0xb2, 2) },
            { new Instruction(Sixty502DotNetParser.BCS, RelativeAbs ), new Opcode("65CE02", 0xb3, 3) },
            { new Instruction(Sixty502DotNetParser.BGE, RelativeAbs ), new Opcode("65CE02", 0xb3, 3) },
            { new Instruction(Sixty502DotNetParser.LDZ, AbsoluteX   ), new Opcode("65CE02", 0xbb, 3) },
            { new Instruction(Sixty502DotNetParser.CPZ, Immediate   ), new Opcode("65CE02", 0xc2, 2) },
            { new Instruction(Sixty502DotNetParser.DEW, ZeroPage    ), new Opcode("65CE02", 0xc3, 2) },
            { new Instruction(Sixty502DotNetParser.ASW, Absolute    ), new Opcode("65CE02", 0xcb, 3) },
            { new Instruction(Sixty502DotNetParser.CMP, IndZ        ), new Opcode("65CE02", 0xd2, 2) },
            { new Instruction(Sixty502DotNetParser.BNE, RelativeAbs ), new Opcode("65CE02", 0xd3, 3) },
            { new Instruction(Sixty502DotNetParser.CPZ, ZeroPage    ), new Opcode("65CE02", 0xd4, 2) },
            { new Instruction(Sixty502DotNetParser.PHZ, Implied     ), new Opcode("65CE02", 0xdb) },
            { new Instruction(Sixty502DotNetParser.CPZ, Absolute    ), new Opcode("65CE02", 0xdc, 3) },
            { new Instruction(Sixty502DotNetParser.LDA, IndSp       ), new Opcode("65CE02", 0xe2, 2) },
            { new Instruction(Sixty502DotNetParser.INW, Absolute    ), new Opcode("65CE02", 0xe3, 3) },
            { new Instruction(Sixty502DotNetParser.ROW, Absolute    ), new Opcode("65CE02", 0xeb, 3) },
            { new Instruction(Sixty502DotNetParser.SBC, IndZ        ), new Opcode("65CE02", 0xf2, 2) },
            { new Instruction(Sixty502DotNetParser.BEQ, RelativeAbs ), new Opcode("65CE02", 0xf3, 3) },
            { new Instruction(Sixty502DotNetParser.PHW, ImmAbs      ), new Opcode("65CE02", 0xf4, 3) },
            { new Instruction(Sixty502DotNetParser.PLZ, Implied     ), new Opcode("65CE02", 0xfb) },
            { new Instruction(Sixty502DotNetParser.PHW, Absolute    ), new Opcode("65CE02", 0xfc, 3) }
        };

        private static readonly Dictionary<Instruction, Opcode> s_c64dtv2 = new()
        {
            { new Instruction(Sixty502DotNetParser.BRA, Relative    ), new Opcode("c64dtv2", 0x12, 2) },
            { new Instruction(Sixty502DotNetParser.SAC, Immediate   ), new Opcode("c64dtv2", 0x32, 2) },
            { new Instruction(Sixty502DotNetParser.SIR, Immediate   ), new Opcode("c64dtv2", 0x42, 2) }
        };

        private static readonly Dictionary<Instruction, Opcode> s_huC6280 = new()
        {
            { new Instruction(Sixty502DotNetParser.SXY, Implied     ), new Opcode("HuC6280", 0x03) },
            { new Instruction(Sixty502DotNetParser.ORA, IndAbs      ), new Opcode("HuC6280", 0x12, 3) },
            { new Instruction(Sixty502DotNetParser.ST1, Immediate   ), new Opcode("HuC6280", 0x13, 2) },
            { new Instruction(Sixty502DotNetParser.SAX, Implied     ), new Opcode("HuC6280", 0x23) },
            { new Instruction(Sixty502DotNetParser.ST2, Immediate   ), new Opcode("HuC6280", 0x23, 2) },
            { new Instruction(Sixty502DotNetParser.AND, IndAbs      ), new Opcode("HuC6280", 0x32, 3) },
            { new Instruction(Sixty502DotNetParser.SAY, Implied     ), new Opcode("HuC6280", 0x43) },
            { new Instruction(Sixty502DotNetParser.TMA, Immediate   ), new Opcode("HuC6280", 0x43, 2) },
            { new Instruction(Sixty502DotNetParser.EOR, IndAbs      ), new Opcode("HuC6280", 0x52, 3) },
            { new Instruction(Sixty502DotNetParser.TAM, Immediate   ), new Opcode("HuC6280", 0x53, 2) },
            { new Instruction(Sixty502DotNetParser.CSL, Implied     ), new Opcode("HuC6280", 0x54) },
            { new Instruction(Sixty502DotNetParser.CLA, Implied     ), new Opcode("HuC6280", 0x62) },
            { new Instruction(Sixty502DotNetParser.ADC, IndAbs      ), new Opcode("HuC6280", 0x72, 3) },
            { new Instruction(Sixty502DotNetParser.TII, ThreeOpAbs  ), new Opcode("HuC6280", 0x73, 7) },
            { new Instruction(Sixty502DotNetParser.CLX, Implied     ), new Opcode("HuC6280", 0x82) },
            { new Instruction(Sixty502DotNetParser.TST, TestBitZp   ), new Opcode("HuC6280", 0x83, 3) },
            { new Instruction(Sixty502DotNetParser.STA, IndAbs      ), new Opcode("HuC6280", 0x92, 3) },
            { new Instruction(Sixty502DotNetParser.TST, TestBitZpX  ), new Opcode("HuC6280", 0x93, 3) },
            { new Instruction(Sixty502DotNetParser.TST, TestBitAbs  ), new Opcode("HuC6280", 0xa3, 4) },
            { new Instruction(Sixty502DotNetParser.LDA, IndAbs      ), new Opcode("HuC6280", 0xb2, 3) },
            { new Instruction(Sixty502DotNetParser.TST, TestBitAbsX ), new Opcode("HuC6280", 0xb3, 4) },
            { new Instruction(Sixty502DotNetParser.CLY, Implied     ), new Opcode("HuC6280", 0xc2) },
            { new Instruction(Sixty502DotNetParser.TDD, ThreeOpAbs  ), new Opcode("HuC6280", 0xc3, 7) },
            { new Instruction(Sixty502DotNetParser.CMP, IndAbs      ), new Opcode("HuC6280", 0xd2, 3) },
            { new Instruction(Sixty502DotNetParser.TIN, ThreeOpAbs  ), new Opcode("HuC6280", 0xd3, 7) },
            { new Instruction(Sixty502DotNetParser.CSH, Implied     ), new Opcode("HuC6280", 0xd4) },
            { new Instruction(Sixty502DotNetParser.TIA, ThreeOpAbs  ), new Opcode("HuC6280", 0xe3, 7) },
            { new Instruction(Sixty502DotNetParser.SBC, IndAbs      ), new Opcode("HuC6280", 0xf2, 3) },
            { new Instruction(Sixty502DotNetParser.TAI, ThreeOpAbs  ), new Opcode("HuC6280", 0xf3, 7) },
            { new Instruction(Sixty502DotNetParser.SET, Implied     ), new Opcode("HuC6280", 0xf4) }
        };

        private static readonly Dictionary<Instruction, Opcode> s_m65 = new()
        {
            { new Instruction(Sixty502DotNetParser.ORA, DirZ        ), new Opcode("m65", 0x12ea, 3) },
            { new Instruction(Sixty502DotNetParser.AND, DirZ        ), new Opcode("m65", 0x32ea, 3) },
            { new Instruction(Sixty502DotNetParser.EOR, DirZ        ), new Opcode("m65", 0x52ea, 3) },
            { new Instruction(Sixty502DotNetParser.ADC, DirZ        ), new Opcode("m65", 0x72ea, 3) },
            { new Instruction(Sixty502DotNetParser.STA, DirZ        ), new Opcode("m65", 0x92ea, 3) },
            { new Instruction(Sixty502DotNetParser.LDA, DirZ        ), new Opcode("m65", 0xb2ea, 3) },
            { new Instruction(Sixty502DotNetParser.CMP, DirZ        ), new Opcode("m65", 0xd2ea, 3) },
            { new Instruction(Sixty502DotNetParser.SBC, DirZ        ), new Opcode("m65", 0xf2ea, 3) },
            { new Instruction(Sixty502DotNetParser.ORQ, ZeroPage    ), new Opcode("m65", 0x054242, 4) },
            { new Instruction(Sixty502DotNetParser.ASLQ, ZeroPage   ), new Opcode("m65", 0x064242, 4) },
            { new Instruction(Sixty502DotNetParser.ASLQ, Implied    ), new Opcode("m65", 0x0a4242, 3) },
            { new Instruction(Sixty502DotNetParser.ORQ, Absolute    ), new Opcode("m65", 0x0d4242, 5) },
            { new Instruction(Sixty502DotNetParser.ASLQ, Absolute   ), new Opcode("m65", 0x0f4242, 5) },
            { new Instruction(Sixty502DotNetParser.ORQ, IndZp       ), new Opcode("m65", 0x124242, 4) },
            { new Instruction(Sixty502DotNetParser.ASLQ, ZeroPageX  ), new Opcode("m65", 0x164242, 4) },
            { new Instruction(Sixty502DotNetParser.INQ, Implied     ), new Opcode("m65", 0x1a4242, 3) },
            { new Instruction(Sixty502DotNetParser.ASLQ, AbsoluteX  ), new Opcode("m65", 0x1e4242, 5) },
            { new Instruction(Sixty502DotNetParser.BITQ, ZeroPage   ), new Opcode("m65", 0x244242, 4) },
            { new Instruction(Sixty502DotNetParser.ANDQ, ZeroPage   ), new Opcode("m65", 0x254242, 4) },
            { new Instruction(Sixty502DotNetParser.ROLQ, ZeroPage   ), new Opcode("m65", 0x264242, 4) },
            { new Instruction(Sixty502DotNetParser.ROLQ, Implied    ), new Opcode("m65", 0x2a4242, 3) },
            { new Instruction(Sixty502DotNetParser.BITQ, Absolute   ), new Opcode("m65", 0x2c4242, 5) },
            { new Instruction(Sixty502DotNetParser.ANDQ, Absolute   ), new Opcode("m65", 0x2d4242, 5) },
            { new Instruction(Sixty502DotNetParser.ROLQ, Absolute   ), new Opcode("m65", 0x2e4242, 5) },
            { new Instruction(Sixty502DotNetParser.ANDQ, IndZp      ), new Opcode("m65", 0x324242, 4) },
            { new Instruction(Sixty502DotNetParser.DEQ, Implied     ), new Opcode("m65", 0x3a4242, 3) },
            { new Instruction(Sixty502DotNetParser.ROLQ, AbsoluteX  ), new Opcode("m65", 0x3e4242, 5) },
            { new Instruction(Sixty502DotNetParser.ASRQ, Implied    ), new Opcode("m65", 0x434242, 3) },
            { new Instruction(Sixty502DotNetParser.ASRQ, ZeroPage   ), new Opcode("m65", 0x444242, 4) },
            { new Instruction(Sixty502DotNetParser.EORQ, ZeroPage   ), new Opcode("m65", 0x454242, 4) },
            { new Instruction(Sixty502DotNetParser.LSRQ, ZeroPage   ), new Opcode("m65", 0x464242, 4) },
            { new Instruction(Sixty502DotNetParser.LSRQ, Implied    ), new Opcode("m65", 0x4a4242, 3) },
            { new Instruction(Sixty502DotNetParser.EORQ, Absolute   ), new Opcode("m65", 0x4d4242, 5) },
            { new Instruction(Sixty502DotNetParser.LSRQ, Absolute   ), new Opcode("m65", 0x4e4242, 5) },
            { new Instruction(Sixty502DotNetParser.EORQ, IndZp      ), new Opcode("m65", 0x524242, 4) },
            { new Instruction(Sixty502DotNetParser.ASRQ, ZeroPageX  ), new Opcode("m65", 0x544242, 4) },
            { new Instruction(Sixty502DotNetParser.LSRQ, ZeroPageX  ), new Opcode("m65", 0x564242, 4) },
            { new Instruction(Sixty502DotNetParser.LSRQ, AbsoluteX  ), new Opcode("m65", 0x5e4242, 5) },
            { new Instruction(Sixty502DotNetParser.ADCQ, ZeroPage   ), new Opcode("m65", 0x654242, 4) },
            { new Instruction(Sixty502DotNetParser.RORQ, ZeroPage   ), new Opcode("m65", 0x664242, 4) },
            { new Instruction(Sixty502DotNetParser.RORQ, Implied    ), new Opcode("m65", 0x6a4242, 3) },
            { new Instruction(Sixty502DotNetParser.ADCQ, Absolute   ), new Opcode("m65", 0x6d4242, 5) },
            { new Instruction(Sixty502DotNetParser.RORQ, Absolute   ), new Opcode("m65", 0x6e4242, 5) },
            { new Instruction(Sixty502DotNetParser.ADCQ, IndZp      ), new Opcode("m65", 0x724242, 4) },
            { new Instruction(Sixty502DotNetParser.RORQ, ZeroPageX  ), new Opcode("m65", 0x764242, 4) },
            { new Instruction(Sixty502DotNetParser.RORQ, AbsoluteX  ), new Opcode("m65", 0x7e4242, 5) },
            { new Instruction(Sixty502DotNetParser.STQ, ZeroPage    ), new Opcode("m65", 0x854242, 4) },
            { new Instruction(Sixty502DotNetParser.STQ, Absolute    ), new Opcode("m65", 0x8d4242, 5) },
            { new Instruction(Sixty502DotNetParser.STQ, IndZp       ), new Opcode("m65", 0x924242, 4) },
            { new Instruction(Sixty502DotNetParser.LDQ, ZeroPage    ), new Opcode("m65", 0xa54242, 4) },
            { new Instruction(Sixty502DotNetParser.LDQ, Absolute    ), new Opcode("m65", 0xad4242, 5) },
            { new Instruction(Sixty502DotNetParser.LDQ, IndY        ), new Opcode("m65", 0xb14242, 4) },
            { new Instruction(Sixty502DotNetParser.LDQ, IndZp       ), new Opcode("m65", 0xb24242, 4) },
            { new Instruction(Sixty502DotNetParser.LDQ, ZeroPageX   ), new Opcode("m65", 0xb54242, 4) },
            { new Instruction(Sixty502DotNetParser.LDQ, AbsoluteY   ), new Opcode("m65", 0xb94242, 5) },
            { new Instruction(Sixty502DotNetParser.LDQ, AbsoluteX   ), new Opcode("m65", 0xbd4242, 5) },
            { new Instruction(Sixty502DotNetParser.CPQ, ZeroPage    ), new Opcode("m65", 0xc54242, 4) },
            { new Instruction(Sixty502DotNetParser.DEQ, ZeroPage    ), new Opcode("m65", 0xc64242, 4) },
            { new Instruction(Sixty502DotNetParser.CPQ, Absolute    ), new Opcode("m65", 0xcd4242, 5) },
            { new Instruction(Sixty502DotNetParser.DEQ, Absolute    ), new Opcode("m65", 0xce4242, 5) },
            { new Instruction(Sixty502DotNetParser.CPQ, IndZp       ), new Opcode("m65", 0xd24242, 4) },
            { new Instruction(Sixty502DotNetParser.DEQ, ZeroPageX   ), new Opcode("m65", 0xd64242, 4) },
            { new Instruction(Sixty502DotNetParser.DEQ, AbsoluteX   ), new Opcode("m65", 0xde4242, 5) },
            { new Instruction(Sixty502DotNetParser.LDQ, IndS        ), new Opcode("m65", 0xe24242, 4) },
            { new Instruction(Sixty502DotNetParser.SBCQ, ZeroPage   ), new Opcode("m65", 0xe54242, 4) },
            { new Instruction(Sixty502DotNetParser.INQ, ZeroPage    ), new Opcode("m65", 0xe64242, 4) },
            { new Instruction(Sixty502DotNetParser.SBCQ, Absolute   ), new Opcode("m65", 0xed4242, 5) },
            { new Instruction(Sixty502DotNetParser.INQ, Absolute    ), new Opcode("m65", 0xee4242, 5) },
            { new Instruction(Sixty502DotNetParser.SBCQ, IndZp      ), new Opcode("m65", 0xf24242, 4) },
            { new Instruction(Sixty502DotNetParser.INQ, ZeroPageX   ), new Opcode("m65", 0xf64242, 4) },
            { new Instruction(Sixty502DotNetParser.INQ, AbsoluteX   ), new Opcode("m65", 0xfe4242, 5) },
            { new Instruction(Sixty502DotNetParser.ORQ, Dir         ), new Opcode("m65", 0x12ea4242, 5) },
            { new Instruction(Sixty502DotNetParser.ANDQ, Dir        ), new Opcode("m65", 0x32ea4242, 5) },
            { new Instruction(Sixty502DotNetParser.EORQ, Dir        ), new Opcode("m65", 0x52ea4242, 5) },
            { new Instruction(Sixty502DotNetParser.ADCQ, Dir        ), new Opcode("m65", 0x72ea4242, 5) },
            { new Instruction(Sixty502DotNetParser.STQ, Dir         ), new Opcode("m65", -1830141374, 5) },
            { new Instruction(Sixty502DotNetParser.LDQ, Dir         ), new Opcode("m65", -1293270462, 5) },
            { new Instruction(Sixty502DotNetParser.CPQ, Dir         ), new Opcode("m65", -756399550, 5) },
            { new Instruction(Sixty502DotNetParser.SBCQ, Dir        ), new Opcode("m65", -219528638, 5) }
        };

        private static readonly Dictionary<Instruction, Opcode> s_r65c02 = new()
        {
            { new Instruction(Sixty502DotNetParser.RMB, Zp0         ), new Opcode("R65C02", 0x07, 2) },
            { new Instruction(Sixty502DotNetParser.BBR, ThreeOpRel0 ), new Opcode("R65C02", 0x0f, 3) },
            { new Instruction(Sixty502DotNetParser.RMB, Zp1         ), new Opcode("R65C02", 0x17, 2) },
            { new Instruction(Sixty502DotNetParser.BBR, ThreeOpRel1 ), new Opcode("R65C02", 0x1f, 3) },
            { new Instruction(Sixty502DotNetParser.RMB, Zp2         ), new Opcode("R65C02", 0x27, 2) },
            { new Instruction(Sixty502DotNetParser.BBR, ThreeOpRel2 ), new Opcode("R65C02", 0x2f, 3) },
            { new Instruction(Sixty502DotNetParser.RMB, Zp3         ), new Opcode("R65C02", 0x37, 2) },
            { new Instruction(Sixty502DotNetParser.BBR, ThreeOpRel3 ), new Opcode("R65C02", 0x3f, 3) },
            { new Instruction(Sixty502DotNetParser.RMB, Zp4         ), new Opcode("R65C02", 0x47, 2) },
            { new Instruction(Sixty502DotNetParser.BBR, ThreeOpRel4 ), new Opcode("R65C02", 0x4f, 3) },
            { new Instruction(Sixty502DotNetParser.RMB, Zp5         ), new Opcode("R65C02", 0x57, 2) },
            { new Instruction(Sixty502DotNetParser.BBR, ThreeOpRel5 ), new Opcode("R65C02", 0x5f, 3) },
            { new Instruction(Sixty502DotNetParser.RMB, Zp6         ), new Opcode("R65C02", 0x67, 2) },
            { new Instruction(Sixty502DotNetParser.BBR, ThreeOpRel6 ), new Opcode("R65C02", 0x6f, 3) },
            { new Instruction(Sixty502DotNetParser.RMB, Zp7         ), new Opcode("R65C02", 0x77, 2) },
            { new Instruction(Sixty502DotNetParser.BBR, ThreeOpRel7 ), new Opcode("R65C02", 0x7f, 3) },
            { new Instruction(Sixty502DotNetParser.SMB, Zp0         ), new Opcode("R65C02", 0x87, 2) },
            { new Instruction(Sixty502DotNetParser.BBS, ThreeOpRel0 ), new Opcode("R65C02", 0x8f, 3) },
            { new Instruction(Sixty502DotNetParser.SMB, Zp1         ), new Opcode("R65C02", 0x97, 2) },
            { new Instruction(Sixty502DotNetParser.BBS, ThreeOpRel1 ), new Opcode("R65C02", 0x9f, 3) },
            { new Instruction(Sixty502DotNetParser.SMB, Zp2         ), new Opcode("R65C02", 0xa7, 2) },
            { new Instruction(Sixty502DotNetParser.BBS, ThreeOpRel2 ), new Opcode("R65C02", 0xaf, 3) },
            { new Instruction(Sixty502DotNetParser.SMB, Zp3         ), new Opcode("R65C02", 0xb7, 2) },
            { new Instruction(Sixty502DotNetParser.BBS, ThreeOpRel3 ), new Opcode("R65C02", 0xbf, 3) },
            { new Instruction(Sixty502DotNetParser.SMB, Zp4         ), new Opcode("R65C02", 0xc7, 2) },
            { new Instruction(Sixty502DotNetParser.BBS, ThreeOpRel4 ), new Opcode("R65C02", 0xcf, 3) },
            { new Instruction(Sixty502DotNetParser.SMB, Zp5         ), new Opcode("R65C02", 0xd7, 2) },
            { new Instruction(Sixty502DotNetParser.BBS, ThreeOpRel5 ), new Opcode("R65C02", 0xdf, 3) },
            { new Instruction(Sixty502DotNetParser.SMB, Zp6         ), new Opcode("R65C02", 0xe7, 2) },
            { new Instruction(Sixty502DotNetParser.BBS, ThreeOpRel6 ), new Opcode("R65C02", 0xef, 3) },
            { new Instruction(Sixty502DotNetParser.SMB, Zp7         ), new Opcode("R65C02", 0xf7, 2) },
            { new Instruction(Sixty502DotNetParser.BBS, ThreeOpRel7 ), new Opcode("R65C02", 0xff, 3) }
        };

        private static readonly Dictionary<Instruction, Opcode> s_w65c02 = new()
        {
            { new Instruction(Sixty502DotNetParser.STP, Implied     ), new Opcode("W65C02", 0xdb) },
            { new Instruction(Sixty502DotNetParser.WAI, Implied     ), new Opcode("W65C02", 0xcb) }
        };

        private static readonly Dictionary<string, int> s_6502Mnemonics = new()
        {
            { ".dp", Sixty502DotNetLexer.Dp  },
            { "a"  , Sixty502DotNetLexer.A   },
            { "adc", Sixty502DotNetLexer.ADC },
            { "and", Sixty502DotNetLexer.AND },
            { "asl", Sixty502DotNetLexer.ASL },
            { "bcc", Sixty502DotNetLexer.BCC },
            { "bcs", Sixty502DotNetLexer.BCS },
            { "beq", Sixty502DotNetLexer.BEQ },
            { "bit", Sixty502DotNetLexer.BIT },
            { "bmi", Sixty502DotNetLexer.BMI },
            { "bne", Sixty502DotNetLexer.BNE },
            { "bpl", Sixty502DotNetLexer.BPL },
            { "brk", Sixty502DotNetLexer.BRK },
            { "bvc", Sixty502DotNetLexer.BVC },
            { "bvs", Sixty502DotNetLexer.BVS },
            { "clc", Sixty502DotNetLexer.CLC },
            { "cld", Sixty502DotNetLexer.CLD },
            { "cli", Sixty502DotNetLexer.CLI },
            { "clv", Sixty502DotNetLexer.CLV },
            { "cmp", Sixty502DotNetLexer.CMP },
            { "cpx", Sixty502DotNetLexer.CPX },
            { "cpy", Sixty502DotNetLexer.CPY },
            { "dec", Sixty502DotNetLexer.DEC },
            { "dex", Sixty502DotNetLexer.DEX },
            { "dey", Sixty502DotNetLexer.DEY },
            { "eor", Sixty502DotNetLexer.EOR },
            { "inc", Sixty502DotNetLexer.INC },
            { "inx", Sixty502DotNetLexer.INX },
            { "iny", Sixty502DotNetLexer.INY },
            { "jcc", Sixty502DotNetLexer.JCC },
            { "jcs", Sixty502DotNetLexer.JCS },
            { "jeq", Sixty502DotNetLexer.JEQ },
            { "jmi", Sixty502DotNetLexer.JMI },
            { "jne", Sixty502DotNetLexer.JNE },
            { "jpl", Sixty502DotNetLexer.JPL },
            { "jmp", Sixty502DotNetLexer.JMP },
            { "jsr", Sixty502DotNetLexer.JSR },
            { "jvc", Sixty502DotNetLexer.JVC },
            { "jvs", Sixty502DotNetLexer.JVS },
            { "lda", Sixty502DotNetLexer.LDA },
            { "ldx", Sixty502DotNetLexer.LDX },
            { "ldy", Sixty502DotNetLexer.LDY },
            { "lsr", Sixty502DotNetLexer.LSR },
            { "nop", Sixty502DotNetLexer.NOP },
            { "ora", Sixty502DotNetLexer.ORA },
            { "pha", Sixty502DotNetLexer.PHA },
            { "php", Sixty502DotNetLexer.PHP },
            { "pla", Sixty502DotNetLexer.PLA },
            { "plp", Sixty502DotNetLexer.PLP },
            { "rol", Sixty502DotNetLexer.ROL },
            { "ror", Sixty502DotNetLexer.ROR },
            { "rti", Sixty502DotNetLexer.RTI },
            { "rts", Sixty502DotNetLexer.RTS },
            { "sbc", Sixty502DotNetLexer.SBC },
            { "sec", Sixty502DotNetLexer.SEC },
            { "sed", Sixty502DotNetLexer.SED },
            { "sei", Sixty502DotNetLexer.SEI },
            { "sta", Sixty502DotNetLexer.STA },
            { "stx", Sixty502DotNetLexer.STX },
            { "sty", Sixty502DotNetLexer.STY },
            { "tax", Sixty502DotNetLexer.TAX },
            { "tay", Sixty502DotNetLexer.TAY },
            { "tsx", Sixty502DotNetLexer.TSX },
            { "txa", Sixty502DotNetLexer.TXA },
            { "txs", Sixty502DotNetLexer.TXS },
            { "tya", Sixty502DotNetLexer.TYA },
            { "x"  , Sixty502DotNetLexer.X   },
            { "y"  , Sixty502DotNetLexer.Y   }
        };

        private readonly static Dictionary<string, int> s_6502iMnemonics = new()
        {
            { "anc", Sixty502DotNetLexer.ANC },
            { "ane", Sixty502DotNetLexer.ANE },
            { "arr", Sixty502DotNetLexer.ARR },
            { "asr", Sixty502DotNetLexer.ASR },
            { "dcp", Sixty502DotNetLexer.DCP },
            { "dop", Sixty502DotNetLexer.DOP },
            { "isb", Sixty502DotNetLexer.ISB },
            { "jam", Sixty502DotNetLexer.JAM },
            { "las", Sixty502DotNetLexer.LAS },
            { "lax", Sixty502DotNetLexer.LAX },
            { "rla", Sixty502DotNetLexer.RLA },
            { "rra", Sixty502DotNetLexer.RRA },
            { "sax", Sixty502DotNetLexer.SAX },
            { "sha", Sixty502DotNetLexer.SHA },
            { "shx", Sixty502DotNetLexer.SHX },
            { "shy", Sixty502DotNetLexer.SHY },
            { "slo", Sixty502DotNetLexer.SLO },
            { "sre", Sixty502DotNetLexer.SRE },
            { "stp", Sixty502DotNetLexer.STP },
            { "tas", Sixty502DotNetLexer.TAS },
            { "top", Sixty502DotNetLexer.TOP }
        };

        private readonly static Dictionary<string, int> s_65816Mnemonics = new()
        {
            { "brl", Sixty502DotNetLexer.BRL },
            { "cop", Sixty502DotNetLexer.COP },
            { "jml", Sixty502DotNetLexer.JML },
            { "jsl", Sixty502DotNetLexer.JSL },
            { "mvn", Sixty502DotNetLexer.MVN },
            { "mvp", Sixty502DotNetLexer.MVP },
            { "pea", Sixty502DotNetLexer.PEA },
            { "pei", Sixty502DotNetLexer.PEI },
            { "per", Sixty502DotNetLexer.PER },
            { "phb", Sixty502DotNetLexer.PHB },
            { "phd", Sixty502DotNetLexer.PHD },
            { "phk", Sixty502DotNetLexer.PHK },
            { "plb", Sixty502DotNetLexer.PLB },
            { "pld", Sixty502DotNetLexer.PLD },
            { "rep", Sixty502DotNetLexer.REP },
            { "rtl", Sixty502DotNetLexer.RTL },
            { "s",   Sixty502DotNetLexer.S   },
            { "sep", Sixty502DotNetLexer.SEP },
            { "tcd", Sixty502DotNetLexer.TCD },
            { "tcs", Sixty502DotNetLexer.TCS },
            { "tdc", Sixty502DotNetLexer.TDC },
            { "tsc", Sixty502DotNetLexer.TSC },
            { "txy", Sixty502DotNetLexer.TXY },
            { "tyx", Sixty502DotNetLexer.TYX },
            { "wdm", Sixty502DotNetLexer.WDM },
            { "xba", Sixty502DotNetLexer.XBA },
            { "xce", Sixty502DotNetLexer.XCE },
            { "z",   Sixty502DotNetLexer.Z   }
        };

        private readonly static Dictionary<string, int> s_65c02Mnemonics = new()
        {
            { "bra", Sixty502DotNetLexer.BRA },
            { "phx", Sixty502DotNetLexer.PHX },
            { "phy", Sixty502DotNetLexer.PHY },
            { "plx", Sixty502DotNetLexer.PLX },
            { "stz", Sixty502DotNetLexer.STZ },
            { "trb", Sixty502DotNetLexer.TRB },
            { "tsb", Sixty502DotNetLexer.TSB }
        };

        private readonly static Dictionary<string, int> s_65ce02Mnemonics = new()
        {
            { "asw", Sixty502DotNetLexer.ASW },
            { "bge", Sixty502DotNetLexer.BGE },
            { "blt", Sixty502DotNetLexer.BLT },
            { "bsr", Sixty502DotNetLexer.BSR },
            { "cle", Sixty502DotNetLexer.CLE },
            { "cpz", Sixty502DotNetLexer.CPZ },
            { "dez", Sixty502DotNetLexer.DEZ },
            { "dew", Sixty502DotNetLexer.DEW },
            { "inw", Sixty502DotNetLexer.INW },
            { "inz", Sixty502DotNetLexer.INZ },
            { "ldz", Sixty502DotNetLexer.LDZ },
            { "phw", Sixty502DotNetLexer.PHZ },
            { "plz", Sixty502DotNetLexer.PLZ },
            { "row", Sixty502DotNetLexer.ROW },
            { "rtn", Sixty502DotNetLexer.RTN },
            { "see", Sixty502DotNetLexer.SEE },
            { "tab", Sixty502DotNetLexer.TAB },
            { "taz", Sixty502DotNetLexer.TAZ },
            { "tba", Sixty502DotNetLexer.TBA },
            { "tsy", Sixty502DotNetLexer.TSY },
            { "tys", Sixty502DotNetLexer.TYS },
            { "tza", Sixty502DotNetLexer.TZA },
            { "sp",  Sixty502DotNetLexer.SP },
            { "z",   Sixty502DotNetLexer.Z }
        };

        private readonly static Dictionary<string, int> s_huc6280Mnemonics = new()
        {
            { "cla", Sixty502DotNetLexer.CLA },
            { "clx", Sixty502DotNetLexer.CLX },
            { "cly", Sixty502DotNetLexer.CLY },
            { "csh", Sixty502DotNetLexer.CSH },
            { "csl", Sixty502DotNetLexer.CSL },
            { "say", Sixty502DotNetLexer.SAY },
            { "st1", Sixty502DotNetLexer.ST1 },
            { "st2", Sixty502DotNetLexer.ST2 },
            { "sxy", Sixty502DotNetLexer.SXY },
            { "tai", Sixty502DotNetLexer.TAI },
            { "tam", Sixty502DotNetLexer.TAM },
            { "tdd", Sixty502DotNetLexer.TDD },
            { "tia", Sixty502DotNetLexer.TIA },
            { "tii", Sixty502DotNetLexer.TII },
            { "tin", Sixty502DotNetLexer.TIN },
            { "tma", Sixty502DotNetLexer.TMA },
            { "tst", Sixty502DotNetLexer.TST }
        };

        private readonly static Dictionary<string, int> s_m65Mnemonics = new()
        {
            { "adcq", Sixty502DotNetLexer.ADCQ },
            { "andq", Sixty502DotNetLexer.ANDQ },
            { "aslq", Sixty502DotNetLexer.ASLQ },
            { "asrq", Sixty502DotNetLexer.ASRQ },
            { "bitq", Sixty502DotNetLexer.BITQ },
            { "cpq", Sixty502DotNetLexer.CPQ },
            { "deq", Sixty502DotNetLexer.DEQ },
            { "eorq", Sixty502DotNetLexer.EORQ },
            { "inq", Sixty502DotNetLexer.INQ },
            { "ldq", Sixty502DotNetLexer.LDQ },
            { "lsrq", Sixty502DotNetLexer.LSRQ },
            { "orq", Sixty502DotNetLexer.ORQ },
            { "rolq", Sixty502DotNetLexer.ROLQ },
            { "rorq", Sixty502DotNetLexer.RORQ },
            { "sbcq", Sixty502DotNetLexer.SBCQ },
            { "stq", Sixty502DotNetLexer.STQ }
        };

        private readonly static Dictionary<string, int> s_r65c02Mnemonics = new()
        {
            { "bbr", Sixty502DotNetLexer.BBR },
            { "bbs", Sixty502DotNetLexer.BBS },
            { "rmb", Sixty502DotNetLexer.RMB },
            { "smb", Sixty502DotNetLexer.SMB }
        };

        private readonly static HashSet<int> s_branches16 = new()
        {
            Sixty502DotNetParser.BGE,
            Sixty502DotNetParser.BLT,
            Sixty502DotNetParser.BRL,
            Sixty502DotNetParser.PER
        };

        private readonly static Dictionary<int, int> s_pseudoToRel = new()
        {
            { Sixty502DotNetParser.JCC, Sixty502DotNetParser.BCC },
            { Sixty502DotNetParser.JCS, Sixty502DotNetParser.BCS },
            { Sixty502DotNetParser.JEQ, Sixty502DotNetParser.BEQ },
            { Sixty502DotNetParser.JMI, Sixty502DotNetParser.BMI },
            { Sixty502DotNetParser.JNE, Sixty502DotNetParser.BNE },
            { Sixty502DotNetParser.JPL, Sixty502DotNetParser.BPL },
            { Sixty502DotNetParser.JVC, Sixty502DotNetParser.BVC },
            { Sixty502DotNetParser.JVS, Sixty502DotNetParser.BVS }
        };

        private readonly static Dictionary<int, int> s_pseudoConv = new()
        {
            { Sixty502DotNetParser.JCC, Sixty502DotNetParser.BCS },
            { Sixty502DotNetParser.JCS, Sixty502DotNetParser.BCC },
            { Sixty502DotNetParser.JEQ, Sixty502DotNetParser.BNE },
            { Sixty502DotNetParser.JMI, Sixty502DotNetParser.BPL },
            { Sixty502DotNetParser.JNE, Sixty502DotNetParser.BEQ },
            { Sixty502DotNetParser.JPL, Sixty502DotNetParser.BMI },
            { Sixty502DotNetParser.JVC, Sixty502DotNetParser.BVS },
            { Sixty502DotNetParser.JVS, Sixty502DotNetParser.BVC }
        };

        private readonly static Dictionary<int, string> s_pseudoRelText = new()
        {
            { Sixty502DotNetParser.JCC, "bcc" },
            { Sixty502DotNetParser.JCS, "bcs" },
            { Sixty502DotNetParser.JEQ, "beq" },
            { Sixty502DotNetParser.JMI, "bmi" },
            { Sixty502DotNetParser.JNE, "bne" },
            { Sixty502DotNetParser.JPL, "bpl" },
            { Sixty502DotNetParser.JVC, "bvc" },
            { Sixty502DotNetParser.JVS, "bvs" }
        };

        private readonly static Dictionary<int, string> s_pseudoConvText = new()
        {
            { Sixty502DotNetParser.JCC, "bcs" },
            { Sixty502DotNetParser.JCS, "bcc" },
            { Sixty502DotNetParser.JEQ, "bne"},
            { Sixty502DotNetParser.JMI, "bpl" },
            { Sixty502DotNetParser.JNE, "beq" },
            { Sixty502DotNetParser.JPL, "bmi" },
            { Sixty502DotNetParser.JVC, "bvs" },
            { Sixty502DotNetParser.JVS, "bvc" }
        };

        private readonly static HashSet<int> s_immediateA = new()
        {
            Sixty502DotNetParser.ADC, Sixty502DotNetParser.AND,
            Sixty502DotNetParser.CMP, Sixty502DotNetParser.EOR,
            Sixty502DotNetParser.LDA, Sixty502DotNetParser.ORA,
            Sixty502DotNetParser.SBC
        };

        private readonly static HashSet<int> s_immediateX = new()
        {
            Sixty502DotNetParser.CPX, Sixty502DotNetParser.CPY,
            Sixty502DotNetParser.LDX, Sixty502DotNetParser.LDY
        };

        protected override IDictionary<Instruction, Opcode> Set { get; set; }
    }
}
