//-----------------------------------------------------------------------------
// Copyright (c) 2017-2022 informedcitizenry <informedcitizenry@gmail.com>
//
// Licensed under the MIT license. See LICENSE for full license information.
// 
//-----------------------------------------------------------------------------

using System.Collections.Generic;

namespace Sixty502DotNet
{
    /// <summary>
    /// A class responsible for assembly of m680x source.
    /// </summary>
    public partial class M680x : MotorolaBase
    {
        private readonly static Dictionary<Instruction, Opcode> s_m6800 = new()
        {
            { new Instruction(Sixty502DotNetParser.NOP,  Implied),      new Opcode("m6800",    0x01) },
            { new Instruction(Sixty502DotNetParser.TAP,  Implied),      new Opcode("m6800",    0x06) },
            { new Instruction(Sixty502DotNetParser.TPA,  Implied),      new Opcode("m6800",    0x07) },
            { new Instruction(Sixty502DotNetParser.INX,  Implied),      new Opcode("m6800",    0x08) },
            { new Instruction(Sixty502DotNetParser.DEX,  Implied),      new Opcode("m6800",    0x09) },
            { new Instruction(Sixty502DotNetParser.CLV,  Implied),      new Opcode("m6800",    0x0a) },
            { new Instruction(Sixty502DotNetParser.SEV,  Implied),      new Opcode("m6800",    0x0b) },
            { new Instruction(Sixty502DotNetParser.CLC,  Implied),      new Opcode("m6800",    0x0c) },
            { new Instruction(Sixty502DotNetParser.SEC,  Implied),      new Opcode("m6800",    0x0d) },
            { new Instruction(Sixty502DotNetParser.CLI,  Implied),      new Opcode("m6800",    0x0e) },
            { new Instruction(Sixty502DotNetParser.SEI,  Implied),      new Opcode("m6800",    0x0f) },
            { new Instruction(Sixty502DotNetParser.SBA,  Implied),      new Opcode("m6800",    0x10) },
            { new Instruction(Sixty502DotNetParser.CBA,  Implied),      new Opcode("m6800",    0x11) },
            { new Instruction(Sixty502DotNetParser.TAB,  Implied),      new Opcode("m6800",    0x16) },
            { new Instruction(Sixty502DotNetParser.TBA,  Implied),      new Opcode("m6800",    0x17) },
            { new Instruction(Sixty502DotNetParser.DAA,  Implied),      new Opcode("m6800",    0x19) },
            { new Instruction(Sixty502DotNetParser.ABA,  Implied),      new Opcode("m6800",    0x1b) },
            { new Instruction(Sixty502DotNetParser.BRA,  Relative),     new Opcode("m6800",    0x20, 2) },
            { new Instruction(Sixty502DotNetParser.BHI,  Relative),     new Opcode("m6800",    0x22, 2) },
            { new Instruction(Sixty502DotNetParser.BLS,  Relative),     new Opcode("m6800",    0x23, 2) },
            { new Instruction(Sixty502DotNetParser.BCC,  Relative),     new Opcode("m6800",    0x24, 2) },
            { new Instruction(Sixty502DotNetParser.BCS,  Relative),     new Opcode("m6800",    0x25, 2) },
            { new Instruction(Sixty502DotNetParser.BNE,  Relative),     new Opcode("m6800",    0x26, 2) },
            { new Instruction(Sixty502DotNetParser.BEQ,  Relative),     new Opcode("m6800",    0x27, 2) },
            { new Instruction(Sixty502DotNetParser.BVC,  Relative),     new Opcode("m6800",    0x28, 2) },
            { new Instruction(Sixty502DotNetParser.BVS,  Relative),     new Opcode("m6800",    0x29, 2) },
            { new Instruction(Sixty502DotNetParser.BPL,  Relative),     new Opcode("m6800",    0x2a, 2) },
            { new Instruction(Sixty502DotNetParser.BMI,  Relative),     new Opcode("m6800",    0x2b, 2) },
            { new Instruction(Sixty502DotNetParser.BGE,  Relative),     new Opcode("m6800",    0x2c, 2) },
            { new Instruction(Sixty502DotNetParser.BLT,  Relative),     new Opcode("m6800",    0x2d, 2) },
            { new Instruction(Sixty502DotNetParser.BGT,  Relative),     new Opcode("m6800",    0x2e, 2) },
            { new Instruction(Sixty502DotNetParser.BLE,  Relative),     new Opcode("m6800",    0x2f, 2) },
            { new Instruction(Sixty502DotNetParser.TSX,  Implied),      new Opcode("m6800",    0x30) },
            { new Instruction(Sixty502DotNetParser.INS,  Implied),      new Opcode("m6800",    0x31) },
            { new Instruction(Sixty502DotNetParser.PULA, Implied),      new Opcode("m6800",    0x32) },
            { new Instruction(Sixty502DotNetParser.PULB, Implied),      new Opcode("m6800",    0x33) },
            { new Instruction(Sixty502DotNetParser.DES,  Implied),      new Opcode("m6800",    0x34) },
            { new Instruction(Sixty502DotNetParser.TXS,  Implied),      new Opcode("m6800",    0x35) },
            { new Instruction(Sixty502DotNetParser.PSHA, Implied),      new Opcode("m6800",    0x36) },
            { new Instruction(Sixty502DotNetParser.PSHB, Implied),      new Opcode("m6800",    0x37) },
            { new Instruction(Sixty502DotNetParser.RTS,  Implied),      new Opcode("m6800",    0x39) },
            { new Instruction(Sixty502DotNetParser.RTI,  Implied),      new Opcode("m6800",    0x3b) },
            { new Instruction(Sixty502DotNetParser.WAI,  Implied),      new Opcode("m6800",    0x3e) },
            { new Instruction(Sixty502DotNetParser.SWI,  Implied),      new Opcode("m6800",    0x3f) },
            { new Instruction(Sixty502DotNetParser.NEGA, Implied),      new Opcode("m6800",    0x40) },
            { new Instruction(Sixty502DotNetParser.COMA, Implied),      new Opcode("m6800",    0x43) },
            { new Instruction(Sixty502DotNetParser.LSRA, Implied),      new Opcode("m6800",    0x44) },
            { new Instruction(Sixty502DotNetParser.RORA, Implied),      new Opcode("m6800",    0x46) },
            { new Instruction(Sixty502DotNetParser.ASRA, Implied),      new Opcode("m6800",    0x47) },
            { new Instruction(Sixty502DotNetParser.ASLA, Implied),      new Opcode("m6800",    0x48) },
            { new Instruction(Sixty502DotNetParser.ROLA, Implied),      new Opcode("m6800",    0x49) },
            { new Instruction(Sixty502DotNetParser.DECA, Implied),      new Opcode("m6800",    0x4a) },
            { new Instruction(Sixty502DotNetParser.INCA, Implied),      new Opcode("m6800",    0x4c) },
            { new Instruction(Sixty502DotNetParser.TSTA, Implied),      new Opcode("m6800",    0x4d) },
            { new Instruction(Sixty502DotNetParser.CLRA, Implied),      new Opcode("m6800",    0x4f) },
            { new Instruction(Sixty502DotNetParser.NEGB, Implied),      new Opcode("m6800",    0x50) },
            { new Instruction(Sixty502DotNetParser.COMB, Implied),      new Opcode("m6800",    0x53) },
            { new Instruction(Sixty502DotNetParser.LSRB, Implied),      new Opcode("m6800",    0x54) },
            { new Instruction(Sixty502DotNetParser.RORB, Implied),      new Opcode("m6800",    0x56) },
            { new Instruction(Sixty502DotNetParser.ASRB, Implied),      new Opcode("m6800",    0x57) },
            { new Instruction(Sixty502DotNetParser.ASLB, Implied),      new Opcode("m6800",    0x58) },
            { new Instruction(Sixty502DotNetParser.ROLB, Implied),      new Opcode("m6800",    0x59) },
            { new Instruction(Sixty502DotNetParser.DECB, Implied),      new Opcode("m6800",    0x5a) },
            { new Instruction(Sixty502DotNetParser.INCB, Implied),      new Opcode("m6800",    0x5c) },
            { new Instruction(Sixty502DotNetParser.TSTB, Implied),      new Opcode("m6800",    0x5d) },
            { new Instruction(Sixty502DotNetParser.CLRB, Implied),      new Opcode("m6800",    0x5f) },
            { new Instruction(Sixty502DotNetParser.NEG,  ZeroPageX),    new Opcode("m6800",    0x60, 2) },
            { new Instruction(Sixty502DotNetParser.COM,  ZeroPageX),    new Opcode("m6800",    0x63, 2) },
            { new Instruction(Sixty502DotNetParser.LSR,  ZeroPageX),    new Opcode("m6800",    0x64, 2) },
            { new Instruction(Sixty502DotNetParser.ROR,  ZeroPageX),    new Opcode("m6800",    0x66, 2) },
            { new Instruction(Sixty502DotNetParser.ASR,  ZeroPageX),    new Opcode("m6800",    0x67, 2) },
            { new Instruction(Sixty502DotNetParser.ASL,  ZeroPageX),    new Opcode("m6800",    0x68, 2) },
            { new Instruction(Sixty502DotNetParser.ROL,  ZeroPageX),    new Opcode("m6800",    0x69, 2) },
            { new Instruction(Sixty502DotNetParser.DEC,  ZeroPageX),    new Opcode("m6800",    0x6a, 2) },
            { new Instruction(Sixty502DotNetParser.INC,  ZeroPageX),    new Opcode("m6800",    0x6c, 2) },
            { new Instruction(Sixty502DotNetParser.TST,  ZeroPageX),    new Opcode("m6800",    0x6d, 2) },
            { new Instruction(Sixty502DotNetParser.JMP,  ZeroPageX),    new Opcode("m6800",    0x6e, 2) },
            { new Instruction(Sixty502DotNetParser.CLR,  ZeroPageX),    new Opcode("m6800",    0x6f, 2) },
            { new Instruction(Sixty502DotNetParser.NEG,  Absolute),     new Opcode("m6800",    0x70, 3) },
            { new Instruction(Sixty502DotNetParser.COM,  Absolute),     new Opcode("m6800",    0x73, 3) },
            { new Instruction(Sixty502DotNetParser.LSR,  Absolute),     new Opcode("m6800",    0x74, 3) },
            { new Instruction(Sixty502DotNetParser.ROR,  Absolute),     new Opcode("m6800",    0x76, 3) },
            { new Instruction(Sixty502DotNetParser.ASR,  Absolute),     new Opcode("m6800",    0x77, 3) },
            { new Instruction(Sixty502DotNetParser.ASL,  Absolute),     new Opcode("m6800",    0x78, 3) },
            { new Instruction(Sixty502DotNetParser.ROL,  Absolute),     new Opcode("m6800",    0x79, 3) },
            { new Instruction(Sixty502DotNetParser.DEC,  Absolute),     new Opcode("m6800",    0x7a, 3) },
            { new Instruction(Sixty502DotNetParser.INC,  Absolute),     new Opcode("m6800",    0x7c, 3) },
            { new Instruction(Sixty502DotNetParser.TST,  Absolute),     new Opcode("m6800",    0x7d, 3) },
            { new Instruction(Sixty502DotNetParser.JMP,  Absolute),     new Opcode("m6800",    0x7e, 3) },
            { new Instruction(Sixty502DotNetParser.CLR,  Absolute),     new Opcode("m6800",    0x7f, 3) },
            { new Instruction(Sixty502DotNetParser.SUBA, Immediate),    new Opcode("m6800",    0x80, 2) },
            { new Instruction(Sixty502DotNetParser.CMPA, Immediate),    new Opcode("m6800",    0x81, 2) },
            { new Instruction(Sixty502DotNetParser.SBCA, Immediate),    new Opcode("m6800",    0x82, 2) },
            { new Instruction(Sixty502DotNetParser.ANDA, Immediate),    new Opcode("m6800",    0x84, 2) },
            { new Instruction(Sixty502DotNetParser.BITA, Immediate),    new Opcode("m6800",    0x85, 2) },
            { new Instruction(Sixty502DotNetParser.LDAA, Immediate),    new Opcode("m6800",    0x86, 2) },
            { new Instruction(Sixty502DotNetParser.EORA, Immediate),    new Opcode("m6800",    0x88, 2) },
            { new Instruction(Sixty502DotNetParser.ADCA, Immediate),    new Opcode("m6800",    0x89, 2) },
            { new Instruction(Sixty502DotNetParser.ORAA, Immediate),    new Opcode("m6800",    0x8a, 2) },
            { new Instruction(Sixty502DotNetParser.ADDA, Immediate),    new Opcode("m6800",    0x8b, 2) },
            { new Instruction(Sixty502DotNetParser.CPXA, Immediate),    new Opcode("m6800",    0x8c, 2) },
            { new Instruction(Sixty502DotNetParser.BSR,  Relative),     new Opcode("m6800",    0x8d, 2) },
            { new Instruction(Sixty502DotNetParser.LDS,  ImmAbs),       new Opcode("m6800",    0x8e, 3) },
            { new Instruction(Sixty502DotNetParser.SUBA, ZeroPage),     new Opcode("m6800",    0x90, 2) },
            { new Instruction(Sixty502DotNetParser.CMPA, ZeroPage),     new Opcode("m6800",    0x91, 2) },
            { new Instruction(Sixty502DotNetParser.SBCA, ZeroPage),     new Opcode("m6800",    0x92, 2) },
            { new Instruction(Sixty502DotNetParser.ANDA, ZeroPage),     new Opcode("m6800",    0x94, 2) },
            { new Instruction(Sixty502DotNetParser.BITA, ZeroPage),     new Opcode("m6800",    0x95, 2) },
            { new Instruction(Sixty502DotNetParser.LDAA, ZeroPage),     new Opcode("m6800",    0x96, 2) },
            { new Instruction(Sixty502DotNetParser.STAA, ZeroPage),     new Opcode("m6800",    0x97, 2) },
            { new Instruction(Sixty502DotNetParser.EORA, ZeroPage),     new Opcode("m6800",    0x98, 2) },
            { new Instruction(Sixty502DotNetParser.ADCA, ZeroPage),     new Opcode("m6800",    0x99, 2) },
            { new Instruction(Sixty502DotNetParser.ORAA, ZeroPage),     new Opcode("m6800",    0x9a, 2) },
            { new Instruction(Sixty502DotNetParser.ADDA, ZeroPage),     new Opcode("m6800",    0x9b, 2) },
            { new Instruction(Sixty502DotNetParser.CPXA, ZeroPage),     new Opcode("m6800",    0x9c, 2) },
            { new Instruction(Sixty502DotNetParser.LDS,  ZeroPage),     new Opcode("m6800",    0x9e, 2) },
            { new Instruction(Sixty502DotNetParser.STS,  ZeroPage),     new Opcode("m6800",    0x9f, 2) },
            { new Instruction(Sixty502DotNetParser.SUBA, ZeroPageX),    new Opcode("m6800",    0xa0, 2) },
            { new Instruction(Sixty502DotNetParser.CMPA, ZeroPageX),    new Opcode("m6800",    0xa1, 2) },
            { new Instruction(Sixty502DotNetParser.SBCA, ZeroPageX),    new Opcode("m6800",    0xa2, 2) },
            { new Instruction(Sixty502DotNetParser.ANDA, ZeroPageX),    new Opcode("m6800",    0xa4, 2) },
            { new Instruction(Sixty502DotNetParser.BITA, ZeroPageX),    new Opcode("m6800",    0xa5, 2) },
            { new Instruction(Sixty502DotNetParser.LDAA, ZeroPageX),    new Opcode("m6800",    0xa6, 2) },
            { new Instruction(Sixty502DotNetParser.STAA, ZeroPageX),    new Opcode("m6800",    0xa7, 2) },
            { new Instruction(Sixty502DotNetParser.EORA, ZeroPageX),    new Opcode("m6800",    0xa8, 2) },
            { new Instruction(Sixty502DotNetParser.ADCA, ZeroPageX),    new Opcode("m6800",    0xa9, 2) },
            { new Instruction(Sixty502DotNetParser.ORAA, ZeroPageX),    new Opcode("m6800",    0xaa, 2) },
            { new Instruction(Sixty502DotNetParser.ADDA, ZeroPageX),    new Opcode("m6800",    0xab, 2) },
            { new Instruction(Sixty502DotNetParser.CPXA, ZeroPageX),    new Opcode("m6800",    0xac, 2) },
            { new Instruction(Sixty502DotNetParser.JSR,  ZeroPageX),    new Opcode("m6800",    0xad, 2) },
            { new Instruction(Sixty502DotNetParser.LDS,  ZeroPageX),    new Opcode("m6800",    0xae, 2) },
            { new Instruction(Sixty502DotNetParser.STS,  ZeroPageX),    new Opcode("m6800",    0xaf, 2) },
            { new Instruction(Sixty502DotNetParser.SUBA, Absolute),     new Opcode("m6800",    0xb0, 3) },
            { new Instruction(Sixty502DotNetParser.CMPA, Absolute),     new Opcode("m6800",    0xb1, 3) },
            { new Instruction(Sixty502DotNetParser.SBCA, Absolute),     new Opcode("m6800",    0xb2, 3) },
            { new Instruction(Sixty502DotNetParser.ANDA, Absolute),     new Opcode("m6800",    0xb4, 3) },
            { new Instruction(Sixty502DotNetParser.BITA, Absolute),     new Opcode("m6800",    0xb5, 3) },
            { new Instruction(Sixty502DotNetParser.LDAA, Absolute),     new Opcode("m6800",    0xb6, 3) },
            { new Instruction(Sixty502DotNetParser.STAA, Absolute),     new Opcode("m6800",    0xb7, 3) },
            { new Instruction(Sixty502DotNetParser.EORA, Absolute),     new Opcode("m6800",    0xb8, 3) },
            { new Instruction(Sixty502DotNetParser.ADCA, Absolute),     new Opcode("m6800",    0xb9, 3) },
            { new Instruction(Sixty502DotNetParser.ORAA, Absolute),     new Opcode("m6800",    0xba, 3) },
            { new Instruction(Sixty502DotNetParser.ADDA, Absolute),     new Opcode("m6800",    0xbb, 3) },
            { new Instruction(Sixty502DotNetParser.CPXA, Absolute),     new Opcode("m6800",    0xbc, 3) },
            { new Instruction(Sixty502DotNetParser.JSR,  Absolute),     new Opcode("m6800",    0xbd, 3) },
            { new Instruction(Sixty502DotNetParser.LDS,  Absolute),     new Opcode("m6800",    0xbe, 3) },
            { new Instruction(Sixty502DotNetParser.STS,  Absolute),     new Opcode("m6800",    0xbf, 3) },
            { new Instruction(Sixty502DotNetParser.SUBB, Immediate),    new Opcode("m6800",    0xc0, 2) },
            { new Instruction(Sixty502DotNetParser.CMPB, Immediate),    new Opcode("m6800",    0xc1, 2) },
            { new Instruction(Sixty502DotNetParser.SBCB, Immediate),    new Opcode("m6800",    0xc2, 2) },
            { new Instruction(Sixty502DotNetParser.ANDB, Immediate),    new Opcode("m6800",    0xc4, 2) },
            { new Instruction(Sixty502DotNetParser.BITB, Immediate),    new Opcode("m6800",    0xc5, 2) },
            { new Instruction(Sixty502DotNetParser.LDAB, Immediate),    new Opcode("m6800",    0xc6, 2) },
            { new Instruction(Sixty502DotNetParser.STAA, Immediate),    new Opcode("m6800",    0xc7, 2) },
            { new Instruction(Sixty502DotNetParser.EORB, Immediate),    new Opcode("m6800",    0xc8, 2) },
            { new Instruction(Sixty502DotNetParser.ADCB, Immediate),    new Opcode("m6800",    0xc9, 2) },
            { new Instruction(Sixty502DotNetParser.ORAB, Immediate),    new Opcode("m6800",    0xca, 2) },
            { new Instruction(Sixty502DotNetParser.ADDB, Immediate),    new Opcode("m6800",    0xcb, 2) },
            { new Instruction(Sixty502DotNetParser.LDX,  ImmAbs),       new Opcode("m6800",    0xce, 3) },
            { new Instruction(Sixty502DotNetParser.SUBB, ZeroPage),     new Opcode("m6800",    0xd0, 2) },
            { new Instruction(Sixty502DotNetParser.CMPB, ZeroPage),     new Opcode("m6800",    0xd1, 2) },
            { new Instruction(Sixty502DotNetParser.SBCB, ZeroPage),     new Opcode("m6800",    0xd2, 2) },
            { new Instruction(Sixty502DotNetParser.ANDB, ZeroPage),     new Opcode("m6800",    0xd4, 2) },
            { new Instruction(Sixty502DotNetParser.BITB, ZeroPage),     new Opcode("m6800",    0xd5, 2) },
            { new Instruction(Sixty502DotNetParser.LDAB, ZeroPage),     new Opcode("m6800",    0xd6, 2) },
            { new Instruction(Sixty502DotNetParser.STAB, ZeroPage),     new Opcode("m6800",    0xd7, 2) },
            { new Instruction(Sixty502DotNetParser.EORB, ZeroPage),     new Opcode("m6800",    0xd8, 2) },
            { new Instruction(Sixty502DotNetParser.ADCB, ZeroPage),     new Opcode("m6800",    0xd9, 2) },
            { new Instruction(Sixty502DotNetParser.ORAB, ZeroPage),     new Opcode("m6800",    0xda, 2) },
            { new Instruction(Sixty502DotNetParser.ADDB, ZeroPage),     new Opcode("m6800",    0xdb, 2) },
            { new Instruction(Sixty502DotNetParser.LDX,  ZeroPage),     new Opcode("m6800",    0xde, 2) },
            { new Instruction(Sixty502DotNetParser.STX,  ZeroPage),     new Opcode("m6800",    0xdf, 2) },
            { new Instruction(Sixty502DotNetParser.SUBB, ZeroPageX),    new Opcode("m6800",    0xe0, 2) },
            { new Instruction(Sixty502DotNetParser.CMPB, ZeroPageX),    new Opcode("m6800",    0xe1, 2) },
            { new Instruction(Sixty502DotNetParser.SBCB, ZeroPageX),    new Opcode("m6800",    0xe2, 2) },
            { new Instruction(Sixty502DotNetParser.ANDB, ZeroPageX),    new Opcode("m6800",    0xe4, 2) },
            { new Instruction(Sixty502DotNetParser.BITB, ZeroPageX),    new Opcode("m6800",    0xe5, 2) },
            { new Instruction(Sixty502DotNetParser.LDAB, ZeroPageX),    new Opcode("m6800",    0xe6, 2) },
            { new Instruction(Sixty502DotNetParser.STAB, ZeroPageX),    new Opcode("m6800",    0xe7, 2) },
            { new Instruction(Sixty502DotNetParser.EORB, ZeroPageX),    new Opcode("m6800",    0xe8, 2) },
            { new Instruction(Sixty502DotNetParser.ADCB, ZeroPageX),    new Opcode("m6800",    0xe9, 2) },
            { new Instruction(Sixty502DotNetParser.ORAB, ZeroPageX),    new Opcode("m6800",    0xea, 2) },
            { new Instruction(Sixty502DotNetParser.ADDB, ZeroPageX),    new Opcode("m6800",    0xeb, 2) },
            { new Instruction(Sixty502DotNetParser.LDX,  ZeroPageX),    new Opcode("m6800",    0xee, 2) },
            { new Instruction(Sixty502DotNetParser.STX,  ZeroPageX),    new Opcode("m6800",    0xef, 2) },
            { new Instruction(Sixty502DotNetParser.SUBB, Absolute),     new Opcode("m6800",    0xf0, 3) },
            { new Instruction(Sixty502DotNetParser.CMPB, Absolute),     new Opcode("m6800",    0xf1, 3) },
            { new Instruction(Sixty502DotNetParser.SBCB, Absolute),     new Opcode("m6800",    0xf2, 3) },
            { new Instruction(Sixty502DotNetParser.ANDB, Absolute),     new Opcode("m6800",    0xf4, 3) },
            { new Instruction(Sixty502DotNetParser.BITB, Absolute),     new Opcode("m6800",    0xf5, 3) },
            { new Instruction(Sixty502DotNetParser.LDAB, Absolute),     new Opcode("m6800",    0xf6, 3) },
            { new Instruction(Sixty502DotNetParser.STAB, Absolute),     new Opcode("m6800",    0xf7, 3) },
            { new Instruction(Sixty502DotNetParser.EORB, Absolute),     new Opcode("m6800",    0xf8, 3) },
            { new Instruction(Sixty502DotNetParser.ADCB, Absolute),     new Opcode("m6800",    0xf9, 3) },
            { new Instruction(Sixty502DotNetParser.ORAB, Absolute),     new Opcode("m6800",    0xfa, 3) },
            { new Instruction(Sixty502DotNetParser.ADDB, Absolute),     new Opcode("m6800",    0xfb, 3) },
            { new Instruction(Sixty502DotNetParser.LDX,  Absolute),     new Opcode("m6800",    0xfe, 3) },
            { new Instruction(Sixty502DotNetParser.STX,  Absolute),     new Opcode("m6800",    0xff, 3) },
        };

        private static readonly Dictionary<Instruction, Opcode> s_m6809 = new()
        {
            { new Instruction(Sixty502DotNetParser.NEG,  ZeroPage),     new Opcode("m6809",    0x00, 2) },
            { new Instruction(Sixty502DotNetParser.COM,  ZeroPage),     new Opcode("m6809",    0x03, 2) },
            { new Instruction(Sixty502DotNetParser.LSR,  ZeroPage),     new Opcode("m6809",    0x04, 2) },
            { new Instruction(Sixty502DotNetParser.ROR,  ZeroPage),     new Opcode("m6809",    0x06, 2) },
            { new Instruction(Sixty502DotNetParser.ASR,  ZeroPage),     new Opcode("m6809",    0x07, 2) },
            { new Instruction(Sixty502DotNetParser.ASL,  ZeroPage),     new Opcode("m6809",    0x08, 2) },
            { new Instruction(Sixty502DotNetParser.LSL,  ZeroPage),     new Opcode("m6809",    0x08, 2) },
            { new Instruction(Sixty502DotNetParser.ROL,  ZeroPage),     new Opcode("m6809",    0x09, 2) },
            { new Instruction(Sixty502DotNetParser.DEC,  ZeroPage),     new Opcode("m6809",    0x0a, 2) },
            { new Instruction(Sixty502DotNetParser.INC,  ZeroPage),     new Opcode("m6809",    0x0c, 2) },
            { new Instruction(Sixty502DotNetParser.TST,  ZeroPage),     new Opcode("m6809",    0x0d, 2) },
            { new Instruction(Sixty502DotNetParser.JMP,  ZeroPage),     new Opcode("m6809",    0x0e, 2) },
            { new Instruction(Sixty502DotNetParser.CLR,  ZeroPage),     new Opcode("m6809",    0x0f, 2) },
            { new Instruction(Sixty502DotNetParser.NOP,  Implied),      new Opcode("m6809",    0x12) },
            { new Instruction(Sixty502DotNetParser.SYNC, Implied),      new Opcode("m6809",    0x13) },
            { new Instruction(Sixty502DotNetParser.LBRA, RelativeAbs),  new Opcode("m6809",    0x16, 3) },
            { new Instruction(Sixty502DotNetParser.LBSR, RelativeAbs),  new Opcode("m6809",    0x17, 3) },
            { new Instruction(Sixty502DotNetParser.DAA,  Implied),      new Opcode("m6809",    0x19) },
            { new Instruction(Sixty502DotNetParser.ORCC, Immediate),    new Opcode("m6809",    0x1a, 2) },
            { new Instruction(Sixty502DotNetParser.ANDCC,Immediate),    new Opcode("m6809",    0x1c, 2) },
            { new Instruction(Sixty502DotNetParser.SEX,  Implied),      new Opcode("m6809",    0x1d) },
            { new Instruction(Sixty502DotNetParser.EXG,  ZeroPage),     new Opcode("m6809",    0x1e, 2) },
            { new Instruction(Sixty502DotNetParser.TFR,  ZeroPage),     new Opcode("m6809",    0x1f, 2) },
            { new Instruction(Sixty502DotNetParser.BRA,  Relative),     new Opcode("m6809",    0x20, 2) },
            { new Instruction(Sixty502DotNetParser.BRN,  Relative),     new Opcode("m6809",    0x21, 2) },
            { new Instruction(Sixty502DotNetParser.BHI,  Relative),     new Opcode("m6809",    0x22, 2) },
            { new Instruction(Sixty502DotNetParser.BLS,  Relative),     new Opcode("m6809",    0x23, 2) },
            { new Instruction(Sixty502DotNetParser.BCC,  Relative),     new Opcode("m6809",    0x24, 2) },
            { new Instruction(Sixty502DotNetParser.BHS,  Relative),     new Opcode("m6809",    0x24, 2) },
            { new Instruction(Sixty502DotNetParser.BCS,  Relative),     new Opcode("m6809",    0x25, 2) },
            { new Instruction(Sixty502DotNetParser.BLO,  Relative),     new Opcode("m6809",    0x25, 2) },
            { new Instruction(Sixty502DotNetParser.BNE,  Relative),     new Opcode("m6809",    0x26, 2) },
            { new Instruction(Sixty502DotNetParser.BEQ,  Relative),     new Opcode("m6809",    0x27, 2) },
            { new Instruction(Sixty502DotNetParser.BVC,  Relative),     new Opcode("m6809",    0x28, 2) },
            { new Instruction(Sixty502DotNetParser.BVS,  Relative),     new Opcode("m6809",    0x29, 2) },
            { new Instruction(Sixty502DotNetParser.BPL,  Relative),     new Opcode("m6809",    0x2a, 2) },
            { new Instruction(Sixty502DotNetParser.BMI,  Relative),     new Opcode("m6809",    0x2b, 2) },
            { new Instruction(Sixty502DotNetParser.BGE,  Relative),     new Opcode("m6809",    0x2c, 2) },
            { new Instruction(Sixty502DotNetParser.BLT,  Relative),     new Opcode("m6809",    0x2d, 2) },
            { new Instruction(Sixty502DotNetParser.BGT,  Relative),     new Opcode("m6809",    0x2e, 2) },
            { new Instruction(Sixty502DotNetParser.BLE,  Relative),     new Opcode("m6809",    0x2f, 2) },
            { new Instruction(Sixty502DotNetParser.LEAX, IndexedX),     new Opcode("m6809",    0x30, 2) },
            { new Instruction(Sixty502DotNetParser.LEAY, IndexedX),     new Opcode("m6809",    0x31, 2) },
            { new Instruction(Sixty502DotNetParser.LEAS, IndexedX),     new Opcode("m6809",    0x32, 2) },
            { new Instruction(Sixty502DotNetParser.LEAU, IndexedX),     new Opcode("m6809",    0x33, 2) },
            { new Instruction(Sixty502DotNetParser.PSHS, ZeroPage),     new Opcode("m6809",    0x34, 2) },
            { new Instruction(Sixty502DotNetParser.PULS, ZeroPage),     new Opcode("m6809",    0x35, 2) },
            { new Instruction(Sixty502DotNetParser.PSHU, ZeroPage),     new Opcode("m6809",    0x36, 2) },
            { new Instruction(Sixty502DotNetParser.PULU, ZeroPage),     new Opcode("m6809",    0x37, 2) },
            { new Instruction(Sixty502DotNetParser.RTS,  Implied),      new Opcode("m6809",    0x39) },
            { new Instruction(Sixty502DotNetParser.ABX,  Implied),      new Opcode("m6809",    0x3a) },
            { new Instruction(Sixty502DotNetParser.RTI,  Implied),      new Opcode("m6809",    0x3b) },
            { new Instruction(Sixty502DotNetParser.CWAI, Implied),      new Opcode("m6809",    0x3c) },
            { new Instruction(Sixty502DotNetParser.MUL,  Implied),      new Opcode("m6809",    0x3d) },
            { new Instruction(Sixty502DotNetParser.SWI,  Implied),      new Opcode("m6809",    0x3f) },
            { new Instruction(Sixty502DotNetParser.NEGA, Implied),      new Opcode("m6809",    0x40) },
            { new Instruction(Sixty502DotNetParser.COMA, Implied),      new Opcode("m6809",    0x43) },
            { new Instruction(Sixty502DotNetParser.LSRA, Implied),      new Opcode("m6809",    0x44) },
            { new Instruction(Sixty502DotNetParser.RORA, Implied),      new Opcode("m6809",    0x46) },
            { new Instruction(Sixty502DotNetParser.ASRA, Implied),      new Opcode("m6809",    0x47) },
            { new Instruction(Sixty502DotNetParser.ASLA, Implied),      new Opcode("m6809",    0x48) },
            { new Instruction(Sixty502DotNetParser.LSLA, Implied),      new Opcode("m6809",    0x48) },
            { new Instruction(Sixty502DotNetParser.ROLA, Implied),      new Opcode("m6809",    0x49) },
            { new Instruction(Sixty502DotNetParser.DECA, Implied),      new Opcode("m6809",    0x4a) },
            { new Instruction(Sixty502DotNetParser.INCA, Implied),      new Opcode("m6809",    0x4c) },
            { new Instruction(Sixty502DotNetParser.TSTA, Implied),      new Opcode("m6809",    0x4d) },
            { new Instruction(Sixty502DotNetParser.CLRA, Implied),      new Opcode("m6809",    0x4f) },
            { new Instruction(Sixty502DotNetParser.NEGB, Implied),      new Opcode("m6809",    0x50) },
            { new Instruction(Sixty502DotNetParser.COMB, Implied),      new Opcode("m6809",    0x53) },
            { new Instruction(Sixty502DotNetParser.LSRB, Implied),      new Opcode("m6809",    0x54) },
            { new Instruction(Sixty502DotNetParser.RORB, Implied),      new Opcode("m6809",    0x56) },
            { new Instruction(Sixty502DotNetParser.ASRB, Implied),      new Opcode("m6809",    0x57) },
            { new Instruction(Sixty502DotNetParser.ASLB, Implied),      new Opcode("m6809",    0x58) },
            { new Instruction(Sixty502DotNetParser.LSLB, Implied),      new Opcode("m6809",    0x58) },
            { new Instruction(Sixty502DotNetParser.ROLB, Implied),      new Opcode("m6809",    0x59) },
            { new Instruction(Sixty502DotNetParser.DECB, Implied),      new Opcode("m6809",    0x5a) },
            { new Instruction(Sixty502DotNetParser.INCB, Implied),      new Opcode("m6809",    0x5c) },
            { new Instruction(Sixty502DotNetParser.TSTB, Implied),      new Opcode("m6809",    0x5d) },
            { new Instruction(Sixty502DotNetParser.CLRB, Implied),      new Opcode("m6809",    0x5f) },
            { new Instruction(Sixty502DotNetParser.NEG,  IndexedX),     new Opcode("m6809",    0x60, 2) },
            { new Instruction(Sixty502DotNetParser.COM,  IndexedX),     new Opcode("m6809",    0x63, 2) },
            { new Instruction(Sixty502DotNetParser.LSR,  IndexedX),     new Opcode("m6809",    0x64, 2) },
            { new Instruction(Sixty502DotNetParser.ROR,  IndexedX),     new Opcode("m6809",    0x66, 2) },
            { new Instruction(Sixty502DotNetParser.ASR,  IndexedX),     new Opcode("m6809",    0x67, 2) },
            { new Instruction(Sixty502DotNetParser.ASL,  IndexedX),     new Opcode("m6809",    0x68, 2) },
            { new Instruction(Sixty502DotNetParser.LSL,  IndexedX),     new Opcode("m6809",    0x68, 2) },
            { new Instruction(Sixty502DotNetParser.ROL,  IndexedX),     new Opcode("m6809",    0x69, 2) },
            { new Instruction(Sixty502DotNetParser.DEC,  IndexedX),     new Opcode("m6809",    0x6a, 2) },
            { new Instruction(Sixty502DotNetParser.INC,  IndexedX),     new Opcode("m6809",    0x6c, 2) },
            { new Instruction(Sixty502DotNetParser.TST,  IndexedX),     new Opcode("m6809",    0x6d, 2) },
            { new Instruction(Sixty502DotNetParser.JMP,  IndexedX),     new Opcode("m6809",    0x6e, 2) },
            { new Instruction(Sixty502DotNetParser.CLR,  IndexedX),     new Opcode("m6809",    0x6f, 2) },
            { new Instruction(Sixty502DotNetParser.NEG,  Absolute),     new Opcode("m6809",    0x70, 3) },
            { new Instruction(Sixty502DotNetParser.COM,  Absolute),     new Opcode("m6809",    0x73, 3) },
            { new Instruction(Sixty502DotNetParser.LSR,  Absolute),     new Opcode("m6809",    0x74, 3) },
            { new Instruction(Sixty502DotNetParser.ROR,  Absolute),     new Opcode("m6809",    0x76, 3) },
            { new Instruction(Sixty502DotNetParser.ASR,  Absolute),     new Opcode("m6809",    0x77, 3) },
            { new Instruction(Sixty502DotNetParser.ASL,  Absolute),     new Opcode("m6809",    0x78, 3) },
            { new Instruction(Sixty502DotNetParser.LSL,  Absolute),     new Opcode("m6809",    0x78, 3) },
            { new Instruction(Sixty502DotNetParser.ROL,  Absolute),     new Opcode("m6809",    0x79, 3) },
            { new Instruction(Sixty502DotNetParser.DEC,  Absolute),     new Opcode("m6809",    0x7a, 3) },
            { new Instruction(Sixty502DotNetParser.INC,  Absolute),     new Opcode("m6809",    0x7c, 3) },
            { new Instruction(Sixty502DotNetParser.TST,  Absolute),     new Opcode("m6809",    0x7d, 3) },
            { new Instruction(Sixty502DotNetParser.JMP,  Absolute),     new Opcode("m6809",    0x7e, 3) },
            { new Instruction(Sixty502DotNetParser.CLR,  Absolute),     new Opcode("m6809",    0x7f, 3) },
            { new Instruction(Sixty502DotNetParser.SUBA, Immediate),    new Opcode("m6809",    0x80, 2) },
            { new Instruction(Sixty502DotNetParser.CMPA, Immediate),    new Opcode("m6809",    0x81, 2) },
            { new Instruction(Sixty502DotNetParser.SBCA, Immediate),    new Opcode("m6809",    0x82, 2) },
            { new Instruction(Sixty502DotNetParser.SUBD, ImmAbs),       new Opcode("m6809",    0x83, 3) },
            { new Instruction(Sixty502DotNetParser.ANDA, Immediate),    new Opcode("m6809",    0x84, 2) },
            { new Instruction(Sixty502DotNetParser.BITA, Immediate),    new Opcode("m6809",    0x85, 2) },
            { new Instruction(Sixty502DotNetParser.LDA,  Immediate),    new Opcode("m6809",    0x86, 2) },
            { new Instruction(Sixty502DotNetParser.EORA, Immediate),    new Opcode("m6809",    0x88, 2) },
            { new Instruction(Sixty502DotNetParser.ADCA, Immediate),    new Opcode("m6809",    0x89, 2) },
            { new Instruction(Sixty502DotNetParser.ORAA, Immediate),    new Opcode("m6809",    0x8a, 2) },
            { new Instruction(Sixty502DotNetParser.ADDA, Immediate),    new Opcode("m6809",    0x8b, 2) },
            { new Instruction(Sixty502DotNetParser.CMPX, ImmAbs),       new Opcode("m6809",    0x8c, 3) },
            { new Instruction(Sixty502DotNetParser.BSR,  Relative),     new Opcode("m6809",    0x8d, 2) },
            { new Instruction(Sixty502DotNetParser.LDX,  ImmAbs),       new Opcode("m6809",    0x8e, 3) },
            { new Instruction(Sixty502DotNetParser.SUBA, ZeroPage),     new Opcode("m6809",    0x90, 2) },
            { new Instruction(Sixty502DotNetParser.CMPA, ZeroPage),     new Opcode("m6809",    0x91, 2) },
            { new Instruction(Sixty502DotNetParser.SBCA, ZeroPage),     new Opcode("m6809",    0x92, 2) },
            { new Instruction(Sixty502DotNetParser.SUBD, ZeroPage),     new Opcode("m6809",    0x93, 2) },
            { new Instruction(Sixty502DotNetParser.ANDA, ZeroPage),     new Opcode("m6809",    0x94, 2) },
            { new Instruction(Sixty502DotNetParser.BITA, ZeroPage),     new Opcode("m6809",    0x95, 2) },
            { new Instruction(Sixty502DotNetParser.LDA,  ZeroPage),     new Opcode("m6809",    0x96, 2) },
            { new Instruction(Sixty502DotNetParser.STA,  ZeroPage),     new Opcode("m6809",    0x97, 2) },
            { new Instruction(Sixty502DotNetParser.EORA, ZeroPage),     new Opcode("m6809",    0x98, 2) },
            { new Instruction(Sixty502DotNetParser.ADCA, ZeroPage),     new Opcode("m6809",    0x99, 2) },
            { new Instruction(Sixty502DotNetParser.ORA,  ZeroPage),     new Opcode("m6809",    0x9a, 2) },
            { new Instruction(Sixty502DotNetParser.ADDA, ZeroPage),     new Opcode("m6809",    0x9b, 2) },
            { new Instruction(Sixty502DotNetParser.CMPX, ZeroPage),     new Opcode("m6809",    0x9c, 2) },
            { new Instruction(Sixty502DotNetParser.JSR,  ZeroPage),     new Opcode("m6809",    0x9d, 2) },
            { new Instruction(Sixty502DotNetParser.LDX,  ZeroPage),     new Opcode("m6809",    0x9e, 2) },
            { new Instruction(Sixty502DotNetParser.STX,  ZeroPage),     new Opcode("m6809",    0x9f, 2) },
            { new Instruction(Sixty502DotNetParser.SUBA, IndexedX),     new Opcode("m6809",    0xa0, 2) },
            { new Instruction(Sixty502DotNetParser.CMPA, IndexedX),     new Opcode("m6809",    0xa1, 2) },
            { new Instruction(Sixty502DotNetParser.SBCA, IndexedX),     new Opcode("m6809",    0xa2, 2) },
            { new Instruction(Sixty502DotNetParser.SUBD, IndexedX),     new Opcode("m6809",    0xa3, 2) },
            { new Instruction(Sixty502DotNetParser.ANDA, IndexedX),     new Opcode("m6809",    0xa4, 2) },
            { new Instruction(Sixty502DotNetParser.BITA, IndexedX),     new Opcode("m6809",    0xa5, 2) },
            { new Instruction(Sixty502DotNetParser.LDA,  IndexedX),     new Opcode("m6809",    0xa6, 2) },
            { new Instruction(Sixty502DotNetParser.STA,  IndexedX),     new Opcode("m6809",    0xa7, 2) },
            { new Instruction(Sixty502DotNetParser.EORA, IndexedX),     new Opcode("m6809",    0xa8, 2) },
            { new Instruction(Sixty502DotNetParser.ADCA, IndexedX),     new Opcode("m6809",    0xa9, 2) },
            { new Instruction(Sixty502DotNetParser.ORA,  IndexedX),     new Opcode("m6809",    0xaa, 2) },
            { new Instruction(Sixty502DotNetParser.ADDA, IndexedX),     new Opcode("m6809",    0xab, 2) },
            { new Instruction(Sixty502DotNetParser.CMPX, IndexedX),     new Opcode("m6809",    0xac, 2) },
            { new Instruction(Sixty502DotNetParser.JSR,  IndexedX),     new Opcode("m6809",    0xad, 2) },
            { new Instruction(Sixty502DotNetParser.LDX,  IndexedX),     new Opcode("m6809",    0xae, 2) },
            { new Instruction(Sixty502DotNetParser.STX,  IndexedX),     new Opcode("m6809",    0xaf, 2) },
            { new Instruction(Sixty502DotNetParser.SUBA, Absolute),     new Opcode("m6809",    0xb0, 3) },
            { new Instruction(Sixty502DotNetParser.CMPA, Absolute),     new Opcode("m6809",    0xb1, 3) },
            { new Instruction(Sixty502DotNetParser.SBCA, Absolute),     new Opcode("m6809",    0xb2, 3) },
            { new Instruction(Sixty502DotNetParser.SUBD, Absolute),     new Opcode("m6809",    0xb3, 3) },
            { new Instruction(Sixty502DotNetParser.ANDA, Absolute),     new Opcode("m6809",    0xb4, 3) },
            { new Instruction(Sixty502DotNetParser.BITA, Absolute),     new Opcode("m6809",    0xb5, 3) },
            { new Instruction(Sixty502DotNetParser.LDA,  Absolute),     new Opcode("m6809",    0xb6, 3) },
            { new Instruction(Sixty502DotNetParser.STA,  Absolute),     new Opcode("m6809",    0xb7, 3) },
            { new Instruction(Sixty502DotNetParser.EORA, Absolute),     new Opcode("m6809",    0xb8, 3) },
            { new Instruction(Sixty502DotNetParser.ADCA, Absolute),     new Opcode("m6809",    0xb9, 3) },
            { new Instruction(Sixty502DotNetParser.ORA,  Absolute),     new Opcode("m6809",    0xba, 3) },
            { new Instruction(Sixty502DotNetParser.ADDA, Absolute),     new Opcode("m6809",    0xbb, 3) },
            { new Instruction(Sixty502DotNetParser.CPXA, Absolute),     new Opcode("m6809",    0xbc, 3) },
            { new Instruction(Sixty502DotNetParser.JSR,  Absolute),     new Opcode("m6809",    0xbd, 3) },
            { new Instruction(Sixty502DotNetParser.LDX,  Absolute),     new Opcode("m6809",    0xbe, 3) },
            { new Instruction(Sixty502DotNetParser.STX,  Absolute),     new Opcode("m6809",    0xbf, 3) },
            { new Instruction(Sixty502DotNetParser.SUBB, Immediate),    new Opcode("m6809",    0xc0, 2) },
            { new Instruction(Sixty502DotNetParser.CMPB, Immediate),    new Opcode("m6809",    0xc1, 2) },
            { new Instruction(Sixty502DotNetParser.SBCB, Immediate),    new Opcode("m6809",    0xc2, 2) },
            { new Instruction(Sixty502DotNetParser.ADDD, ImmAbs),       new Opcode("m6809",    0xc3, 3) },
            { new Instruction(Sixty502DotNetParser.ANDB, Immediate),    new Opcode("m6809",    0xc4, 2) },
            { new Instruction(Sixty502DotNetParser.BITB, Immediate),    new Opcode("m6809",    0xc5, 2) },
            { new Instruction(Sixty502DotNetParser.LDB,  Immediate),    new Opcode("m6809",    0xc6, 2) },
            { new Instruction(Sixty502DotNetParser.EORB, Immediate),    new Opcode("m6809",    0xc8, 2) },
            { new Instruction(Sixty502DotNetParser.ADCB, Immediate),    new Opcode("m6809",    0xc9, 2) },
            { new Instruction(Sixty502DotNetParser.ORB,  Immediate),    new Opcode("m6809",    0xca, 2) },
            { new Instruction(Sixty502DotNetParser.ADDB, Immediate),    new Opcode("m6809",    0xcb, 2) },
            { new Instruction(Sixty502DotNetParser.LDD,  ImmAbs),       new Opcode("m6809",    0xcc, 3) },
            { new Instruction(Sixty502DotNetParser.LDU,  ImmAbs),       new Opcode("m6809",    0xce, 3) },
            { new Instruction(Sixty502DotNetParser.SUBB, ZeroPage),     new Opcode("m6809",    0xd0, 2) },
            { new Instruction(Sixty502DotNetParser.CMPB, ZeroPage),     new Opcode("m6809",    0xd1, 2) },
            { new Instruction(Sixty502DotNetParser.SBCB, ZeroPage),     new Opcode("m6809",    0xd2, 2) },
            { new Instruction(Sixty502DotNetParser.ADDD, ZeroPage),     new Opcode("m6809",    0xd3, 2) },
            { new Instruction(Sixty502DotNetParser.ANDB, ZeroPage),     new Opcode("m6809",    0xd4, 2) },
            { new Instruction(Sixty502DotNetParser.BITB, ZeroPage),     new Opcode("m6809",    0xd5, 2) },
            { new Instruction(Sixty502DotNetParser.LDB,  ZeroPage),     new Opcode("m6809",    0xd6, 2) },
            { new Instruction(Sixty502DotNetParser.STB,  ZeroPage),     new Opcode("m6809",    0xd7, 2) },
            { new Instruction(Sixty502DotNetParser.EORB, ZeroPage),     new Opcode("m6809",    0xd8, 2) },
            { new Instruction(Sixty502DotNetParser.ADCB, ZeroPage),     new Opcode("m6809",    0xd9, 2) },
            { new Instruction(Sixty502DotNetParser.ORB,  ZeroPage),     new Opcode("m6809",    0xda, 2) },
            { new Instruction(Sixty502DotNetParser.ADDB, ZeroPage),     new Opcode("m6809",    0xdb, 2) },
            { new Instruction(Sixty502DotNetParser.LDD,  ZeroPage),     new Opcode("m6809",    0xdc, 2) },
            { new Instruction(Sixty502DotNetParser.STD,  ZeroPage),     new Opcode("m6809",    0xdd, 2) },
            { new Instruction(Sixty502DotNetParser.LDU,  ZeroPage),     new Opcode("m6809",    0xde, 2) },
            { new Instruction(Sixty502DotNetParser.STU,  ZeroPage),     new Opcode("m6809",    0xdf, 2) },
            { new Instruction(Sixty502DotNetParser.SUBB, IndexedX),     new Opcode("m6809",    0xe0, 2) },
            { new Instruction(Sixty502DotNetParser.CMPB, IndexedX),     new Opcode("m6809",    0xe1, 2) },
            { new Instruction(Sixty502DotNetParser.SBCB, IndexedX),     new Opcode("m6809",    0xe2, 2) },
            { new Instruction(Sixty502DotNetParser.ADDD, IndexedX),     new Opcode("m6809",    0xe3, 2) },
            { new Instruction(Sixty502DotNetParser.ANDB, IndexedX),     new Opcode("m6809",    0xe4, 2) },
            { new Instruction(Sixty502DotNetParser.BITB, IndexedX),     new Opcode("m6809",    0xe5, 2) },
            { new Instruction(Sixty502DotNetParser.LDB,  IndexedX),     new Opcode("m6809",    0xe6, 2) },
            { new Instruction(Sixty502DotNetParser.STB,  IndexedX),     new Opcode("m6809",    0xe7, 2) },
            { new Instruction(Sixty502DotNetParser.EORB, IndexedX),     new Opcode("m6809",    0xe8, 2) },
            { new Instruction(Sixty502DotNetParser.ADCB, IndexedX),     new Opcode("m6809",    0xe9, 2) },
            { new Instruction(Sixty502DotNetParser.ORB,  IndexedX),     new Opcode("m6809",    0xea, 2) },
            { new Instruction(Sixty502DotNetParser.ADDB, IndexedX),     new Opcode("m6809",    0xeb, 2) },
            { new Instruction(Sixty502DotNetParser.LDD,  IndexedX),     new Opcode("m6809",    0xec, 2) },
            { new Instruction(Sixty502DotNetParser.STD,  IndexedX),     new Opcode("m6809",    0xed, 2) },
            { new Instruction(Sixty502DotNetParser.LDU,  IndexedX),     new Opcode("m6809",    0xee, 2) },
            { new Instruction(Sixty502DotNetParser.STU,  IndexedX),     new Opcode("m6809",    0xef, 2) },
            { new Instruction(Sixty502DotNetParser.SUBB, Absolute),     new Opcode("m6809",    0xf0, 3) },
            { new Instruction(Sixty502DotNetParser.CMPB, Absolute),     new Opcode("m6809",    0xf1, 3) },
            { new Instruction(Sixty502DotNetParser.SBCB, Absolute),     new Opcode("m6809",    0xf2, 3) },
            { new Instruction(Sixty502DotNetParser.ADDD, Absolute),     new Opcode("m6809",    0xf2, 3) },
            { new Instruction(Sixty502DotNetParser.ANDB, Absolute),     new Opcode("m6809",    0xf4, 3) },
            { new Instruction(Sixty502DotNetParser.BITB, Absolute),     new Opcode("m6809",    0xf5, 3) },
            { new Instruction(Sixty502DotNetParser.LDB,  Absolute),     new Opcode("m6809",    0xf6, 3) },
            { new Instruction(Sixty502DotNetParser.STB,  Absolute),     new Opcode("m6809",    0xf7, 3) },
            { new Instruction(Sixty502DotNetParser.EORB, Absolute),     new Opcode("m6809",    0xf8, 3) },
            { new Instruction(Sixty502DotNetParser.ADCB, Absolute),     new Opcode("m6809",    0xf9, 3) },
            { new Instruction(Sixty502DotNetParser.ORB,  Absolute),     new Opcode("m6809",    0xfa, 3) },
            { new Instruction(Sixty502DotNetParser.ADDB, Absolute),     new Opcode("m6809",    0xfb, 3) },
            { new Instruction(Sixty502DotNetParser.LDD,  Absolute),     new Opcode("m6809",    0xfc, 3) },
            { new Instruction(Sixty502DotNetParser.STD,  Absolute),     new Opcode("m6809",    0xfd, 3) },
            { new Instruction(Sixty502DotNetParser.LDU,  Absolute),     new Opcode("m6809",    0xfe, 3) },
            { new Instruction(Sixty502DotNetParser.STU,  Absolute),     new Opcode("m6809",    0xff, 3) },
            { new Instruction(Sixty502DotNetParser.LBRN, RelativeAbs),  new Opcode("m6809",  0x1021, 4) },
            { new Instruction(Sixty502DotNetParser.LBHI, RelativeAbs),  new Opcode("m6809",  0x1022, 4) },
            { new Instruction(Sixty502DotNetParser.LBLS, RelativeAbs),  new Opcode("m6809",  0x1023, 4) },
            { new Instruction(Sixty502DotNetParser.LBCC, RelativeAbs),  new Opcode("m6809",  0x1024, 4) },
            { new Instruction(Sixty502DotNetParser.LBHS, RelativeAbs),  new Opcode("m6809",  0x1024, 4) },
            { new Instruction(Sixty502DotNetParser.LBCS, RelativeAbs),  new Opcode("m6809",  0x1025, 4) },
            { new Instruction(Sixty502DotNetParser.LBLO, RelativeAbs),  new Opcode("m6809",  0x1025, 4) },
            { new Instruction(Sixty502DotNetParser.LBNE, RelativeAbs),  new Opcode("m6809",  0x1026, 4) },
            { new Instruction(Sixty502DotNetParser.LBEQ, RelativeAbs),  new Opcode("m6809",  0x1027, 4) },
            { new Instruction(Sixty502DotNetParser.LBVC, RelativeAbs),  new Opcode("m6809",  0x1028, 4) },
            { new Instruction(Sixty502DotNetParser.LBVS, RelativeAbs),  new Opcode("m6809",  0x1029, 4) },
            { new Instruction(Sixty502DotNetParser.LBPL, RelativeAbs),  new Opcode("m6809",  0x102a, 4) },
            { new Instruction(Sixty502DotNetParser.LBMI, RelativeAbs),  new Opcode("m6809",  0x102b, 4) },
            { new Instruction(Sixty502DotNetParser.LBGE, RelativeAbs),  new Opcode("m6809",  0x102c, 4) },
            { new Instruction(Sixty502DotNetParser.LBLT, RelativeAbs),  new Opcode("m6809",  0x102d, 4) },
            { new Instruction(Sixty502DotNetParser.LBGT, RelativeAbs),  new Opcode("m6809",  0x102e, 4) },
            { new Instruction(Sixty502DotNetParser.LBLE, RelativeAbs),  new Opcode("m6809",  0x102f, 4) },
            { new Instruction(Sixty502DotNetParser.SWI2, Implied),      new Opcode("m6809",  0x103f, 2) },
            { new Instruction(Sixty502DotNetParser.CMPD, ImmAbs),       new Opcode("m6809",  0x1083, 4) },
            { new Instruction(Sixty502DotNetParser.CMPY, ImmAbs),       new Opcode("m6809",  0x108c, 4) },
            { new Instruction(Sixty502DotNetParser.LDY,  ImmAbs),       new Opcode("m6809",  0x108e, 4) },
            { new Instruction(Sixty502DotNetParser.CMPD, ZeroPage),     new Opcode("m6809",  0x1093, 3) },
            { new Instruction(Sixty502DotNetParser.CMPY, ZeroPage),     new Opcode("m6809",  0x109c, 3) },
            { new Instruction(Sixty502DotNetParser.LDY,  ZeroPage),     new Opcode("m6809",  0x109e, 3) },
            { new Instruction(Sixty502DotNetParser.STY,  ZeroPage),     new Opcode("m6809",  0x109f, 3) },
            { new Instruction(Sixty502DotNetParser.CMPD, IndexedX),     new Opcode("m6809",  0x10a3, 3) },
            { new Instruction(Sixty502DotNetParser.CMPY, IndexedX),     new Opcode("m6809",  0x10ac, 3) },
            { new Instruction(Sixty502DotNetParser.LDY,  IndexedX),     new Opcode("m6809",  0x10ae, 3) },
            { new Instruction(Sixty502DotNetParser.STY,  IndexedX),     new Opcode("m6809",  0x10af, 3) },
            { new Instruction(Sixty502DotNetParser.CMPD, Absolute),     new Opcode("m6809",  0x10b3, 4) },
            { new Instruction(Sixty502DotNetParser.CMPY, Absolute),     new Opcode("m6809",  0x10bc, 4) },
            { new Instruction(Sixty502DotNetParser.LDY,  Absolute),     new Opcode("m6809",  0x10be, 4) },
            { new Instruction(Sixty502DotNetParser.STY,  Absolute),     new Opcode("m6809",  0x10bf, 4) },
            { new Instruction(Sixty502DotNetParser.LDS,  ImmAbs),       new Opcode("m6809",  0x10ce, 4) },
            { new Instruction(Sixty502DotNetParser.LDS,  ZeroPage),     new Opcode("m6809",  0x10de, 3) },
            { new Instruction(Sixty502DotNetParser.STS,  ZeroPage),     new Opcode("m6809",  0x10df, 3) },
            { new Instruction(Sixty502DotNetParser.LDS,  IndexedX),     new Opcode("m6809",  0x10ee, 3) },
            { new Instruction(Sixty502DotNetParser.STS,  IndexedX),     new Opcode("m6809",  0x10ef, 3) },
            { new Instruction(Sixty502DotNetParser.LDS,  Absolute),     new Opcode("m6809",  0x10fe, 4) },
            { new Instruction(Sixty502DotNetParser.STS,  Absolute),     new Opcode("m6809",  0x10ff, 4) },
            { new Instruction(Sixty502DotNetParser.SWI3, Implied),      new Opcode("m6809",  0x113f, 2) },
            { new Instruction(Sixty502DotNetParser.CMPU, ImmAbs),       new Opcode("m6809",  0x1183, 4) },
            { new Instruction(Sixty502DotNetParser.CMPS, ImmAbs),       new Opcode("m6809",  0x118c, 4) },
            { new Instruction(Sixty502DotNetParser.CMPU, ZeroPage),     new Opcode("m6809",  0x1193, 3) },
            { new Instruction(Sixty502DotNetParser.CMPS, ZeroPage),     new Opcode("m6809",  0x119c, 3) },
            { new Instruction(Sixty502DotNetParser.CMPU, IndexedX),     new Opcode("m6809",  0x11a3, 3) },
            { new Instruction(Sixty502DotNetParser.CMPS, IndexedX),     new Opcode("m6809",  0x11ac, 3) },
            { new Instruction(Sixty502DotNetParser.CMPU, Absolute),     new Opcode("m6809",  0x11b3, 4) },
            { new Instruction(Sixty502DotNetParser.CMPS, Absolute),     new Opcode("m6809",  0x11bc, 4) }
        };

        private static readonly Dictionary<string, int> s_m6800Mnemonics = new()
        {
            { "aba",    Sixty502DotNetLexer.ABA },
            { "adca",   Sixty502DotNetLexer.ADCA },
            { "adcb",   Sixty502DotNetLexer.ADCB },
            { "adda",   Sixty502DotNetLexer.ADDA },
            { "addb",   Sixty502DotNetLexer.ADDB },
            { "anda",   Sixty502DotNetLexer.ANDA },
            { "andb",   Sixty502DotNetLexer.ANDB },
            { "asl",    Sixty502DotNetLexer.ASL },
            { "asla",   Sixty502DotNetLexer.ASLA },
            { "aslb",   Sixty502DotNetLexer.ASLB },
            { "asr",    Sixty502DotNetLexer.ASR },
            { "asra",   Sixty502DotNetLexer.ASRA },
            { "asrb",   Sixty502DotNetLexer.ASRB },
            { "bcc",    Sixty502DotNetLexer.BCC },
            { "bcs",    Sixty502DotNetLexer.BCS },
            { "beq",    Sixty502DotNetLexer.BEQ },
            { "bge",    Sixty502DotNetLexer.BGE },
            { "bgt",    Sixty502DotNetLexer.BGT },
            { "bhi",    Sixty502DotNetLexer.BHI },
            { "bita",   Sixty502DotNetLexer.BITA },
            { "bitb",   Sixty502DotNetLexer.BITB },
            { "ble",    Sixty502DotNetLexer.BLE },
            { "bls",    Sixty502DotNetLexer.BLS },
            { "blt",    Sixty502DotNetLexer.BLT },
            { "bmi",    Sixty502DotNetLexer.BMI },
            { "bne",    Sixty502DotNetLexer.BNE },
            { "bpl",    Sixty502DotNetLexer.BPL },
            { "bra",    Sixty502DotNetLexer.BRA },
            { "bsr",    Sixty502DotNetLexer.BSR },
            { "bvc",    Sixty502DotNetLexer.BVC },
            { "bvs",    Sixty502DotNetLexer.BVS },
            { "cba",    Sixty502DotNetLexer.CBA },
            { "clc",    Sixty502DotNetLexer.CLC },
            { "cli",    Sixty502DotNetLexer.CLI },
            { "clr",    Sixty502DotNetLexer.CLR },
            { "clra",   Sixty502DotNetLexer.CLRA },
            { "clrb",   Sixty502DotNetLexer.CLRB },
            { "clv",    Sixty502DotNetLexer.CLV },
            { "cmpa",   Sixty502DotNetLexer.CMPA },
            { "cmpb",   Sixty502DotNetLexer.CMPB },
            { "com",    Sixty502DotNetLexer.COM },
            { "coma",   Sixty502DotNetLexer.COMA },
            { "comb",   Sixty502DotNetLexer.COMB },
            { "cpxa",   Sixty502DotNetLexer.CPXA },
            { "daa",    Sixty502DotNetLexer.DAA },
            { "dec",    Sixty502DotNetLexer.DEC },
            { "deca",   Sixty502DotNetLexer.DECA },
            { "decb",   Sixty502DotNetLexer.DECB },
            { "des",    Sixty502DotNetLexer.DES },
            { "dex",    Sixty502DotNetLexer.DEX },
            { "eora",   Sixty502DotNetLexer.EORA },
            { "eorb",   Sixty502DotNetLexer.EORB },
            { "inc",    Sixty502DotNetLexer.INC },
            { "inca",   Sixty502DotNetLexer.INCA },
            { "incb",   Sixty502DotNetLexer.INCB },
            { "ins",    Sixty502DotNetLexer.INS },
            { "inx",    Sixty502DotNetLexer.INX },
            { "jmp",    Sixty502DotNetLexer.JMP },
            { "jsr",    Sixty502DotNetLexer.JSR },
            { "ldaa",   Sixty502DotNetLexer.LDAA },
            { "ldab",   Sixty502DotNetLexer.LDAB },
            { "lds",    Sixty502DotNetLexer.LDS },
            { "ldx",    Sixty502DotNetLexer.LDX },
            { "lsr",    Sixty502DotNetLexer.LSR },
            { "lsra",   Sixty502DotNetLexer.LSRA },
            { "lsrb",   Sixty502DotNetLexer.LSRB },
            { "neg",    Sixty502DotNetLexer.NEG },
            { "nega",   Sixty502DotNetLexer.NEGA },
            { "negb",   Sixty502DotNetLexer.NEGB },
            { "nop",    Sixty502DotNetLexer.NOP },
            { "oraa",   Sixty502DotNetLexer.ORAA },
            { "orab",   Sixty502DotNetLexer.ORAB },
            { "psha",   Sixty502DotNetLexer.PSHA },
            { "pshb",   Sixty502DotNetLexer.PSHB },
            { "pula",   Sixty502DotNetLexer.PULA },
            { "pulb",   Sixty502DotNetLexer.PULB },
            { "rol",    Sixty502DotNetLexer.ROL },
            { "rola",   Sixty502DotNetLexer.ROLA },
            { "rolb",   Sixty502DotNetLexer.ROLB },
            { "ror",    Sixty502DotNetLexer.ROR },
            { "rora",   Sixty502DotNetLexer.RORA },
            { "rorb",   Sixty502DotNetLexer.RORB },
            { "rti",    Sixty502DotNetLexer.RTI },
            { "rts",    Sixty502DotNetLexer.RTS },
            { "sba",    Sixty502DotNetLexer.SBA },
            { "sbca",   Sixty502DotNetLexer.SBCA },
            { "sbcb",   Sixty502DotNetLexer.SBCB },
            { "sec",    Sixty502DotNetLexer.SEC },
            { "sei",    Sixty502DotNetLexer.SEI },
            { "sev",    Sixty502DotNetLexer.SEV },
            { "staa",   Sixty502DotNetLexer.STAA },
            { "stab",   Sixty502DotNetLexer.STAB },
            { "sts",    Sixty502DotNetLexer.STS },
            { "stx",    Sixty502DotNetLexer.STX },
            { "suba",   Sixty502DotNetLexer.SUBA },
            { "subb",   Sixty502DotNetLexer.SUBB },
            { "swi",    Sixty502DotNetLexer.SWI },
            { "tab",    Sixty502DotNetLexer.TAB },
            { "tap",    Sixty502DotNetLexer.TAP },
            { "tba",    Sixty502DotNetLexer.TBA },
            { "tpa",    Sixty502DotNetLexer.TPA },
            { "tst",    Sixty502DotNetLexer.TST },
            { "tsta",   Sixty502DotNetLexer.TSTA },
            { "tstb",   Sixty502DotNetLexer.TSTB },
            { "tsx",    Sixty502DotNetLexer.TSX },
            { "txs",    Sixty502DotNetLexer.TXS },
            { "wai",    Sixty502DotNetLexer.WAI },
            { "x",      Sixty502DotNetLexer.X }    
        };

        private static readonly Dictionary<string, int> s_m6809Mnemonics = new()
        {
            { ".dp",    Sixty502DotNetLexer.Dp  },
            { "a",      Sixty502DotNetLexer.A   },
            { "abx",    Sixty502DotNetLexer.ABX },
            { "adca",   Sixty502DotNetLexer.ADCA },
            { "adcb",   Sixty502DotNetLexer.ADCB },
            { "adda",   Sixty502DotNetLexer.ADDA },
            { "addb",   Sixty502DotNetLexer.ADDB },
            { "addd",   Sixty502DotNetLexer.ADDD },
            { "anda",   Sixty502DotNetLexer.ANDA },
            { "andb",   Sixty502DotNetLexer.ANDB },
            { "andcc",  Sixty502DotNetLexer.ANDCC },
            { "asl",    Sixty502DotNetLexer.ASL },
            { "asla",   Sixty502DotNetLexer.ASLA },
            { "aslb",   Sixty502DotNetLexer.ASLB },
            { "asr",    Sixty502DotNetLexer.ASR },
            { "asra",   Sixty502DotNetLexer.ASRA },
            { "asrb",   Sixty502DotNetLexer.ASRB },
            { "b",      Sixty502DotNetLexer.B },
            { "bcc",    Sixty502DotNetLexer.BCC },
            { "bcs",    Sixty502DotNetLexer.BCS },
            { "beq",    Sixty502DotNetLexer.BEQ },
            { "bge",    Sixty502DotNetLexer.BGE },
            { "bgt",    Sixty502DotNetLexer.BGT },
            { "bhi",    Sixty502DotNetLexer.BHI },
            { "bhs",    Sixty502DotNetLexer.BHS },
            { "bita",   Sixty502DotNetLexer.BITA },
            { "bitb",   Sixty502DotNetLexer.BITB },
            { "ble",    Sixty502DotNetLexer.BLE },
            { "blo",    Sixty502DotNetLexer.BLO },
            { "bls",    Sixty502DotNetLexer.BLS },
            { "blt",    Sixty502DotNetLexer.BLT },
            { "bmi",    Sixty502DotNetLexer.BMI },
            { "bne",    Sixty502DotNetLexer.BNE },
            { "bpl",    Sixty502DotNetLexer.BPL },
            { "bra",    Sixty502DotNetLexer.BRA },
            { "brn",    Sixty502DotNetLexer.BRN },
            { "bsr",    Sixty502DotNetLexer.BSR },
            { "bvc",    Sixty502DotNetLexer.BVC },
            { "bvs",    Sixty502DotNetLexer.BVS },
            { "cc",     Sixty502DotNetLexer.CC },
            { "clr",    Sixty502DotNetLexer.CLR },
            { "clra",   Sixty502DotNetLexer.CLRA },
            { "clrb",   Sixty502DotNetLexer.CLRB },
            { "cmpa",   Sixty502DotNetLexer.CMPA },
            { "cmpb",   Sixty502DotNetLexer.CMPB },
            { "cmpd",   Sixty502DotNetLexer.CMPD },
            { "cmps",   Sixty502DotNetLexer.CMPS },
            { "cmpu",   Sixty502DotNetLexer.CMPU },
            { "cmpx",   Sixty502DotNetLexer.CMPX },
            { "cmpy",   Sixty502DotNetLexer.CMPY },
            { "com",    Sixty502DotNetLexer.COM },
            { "coma",   Sixty502DotNetLexer.COMA },
            { "comb",   Sixty502DotNetLexer.COMB },
            { "cpxa",   Sixty502DotNetLexer.CPXA },
            { "cwai",   Sixty502DotNetLexer.CWAI },
            { "d",      Sixty502DotNetLexer.D },
            { "daa",    Sixty502DotNetLexer.DAA },
            { "dec",    Sixty502DotNetLexer.DEC },
            { "deca",   Sixty502DotNetLexer.DECA },
            { "decb",   Sixty502DotNetLexer.DECB },
            { "dp",     Sixty502DotNetLexer.DP },
            { "eora",   Sixty502DotNetLexer.EORA },
            { "eorb",   Sixty502DotNetLexer.EORB },
            { "exg",    Sixty502DotNetLexer.EXG },
            { "inc",    Sixty502DotNetLexer.INC },
            { "inca",   Sixty502DotNetLexer.INCA },
            { "incb",   Sixty502DotNetLexer.INCB },
            { "jmp",    Sixty502DotNetLexer.JMP },
            { "jsr",    Sixty502DotNetLexer.JSR },
            { "lbcc",   Sixty502DotNetLexer.LBCC },
            { "lbcs",   Sixty502DotNetLexer.LBCS },
            { "lbeq",   Sixty502DotNetLexer.LBEQ },
            { "lbge",   Sixty502DotNetLexer.LBGE },
            { "lbgt",   Sixty502DotNetLexer.LBGT },
            { "lbhi",   Sixty502DotNetLexer.LBHI },
            { "lbhs",   Sixty502DotNetLexer.LBHS },
            { "lble",   Sixty502DotNetLexer.LBLE },
            { "lblo",   Sixty502DotNetLexer.LBLO },
            { "lbls",   Sixty502DotNetLexer.LBLS },
            { "lblt",   Sixty502DotNetLexer.LBLT },
            { "lbmi",   Sixty502DotNetLexer.LBMI },
            { "lbne",   Sixty502DotNetLexer.LBNE },
            { "lbpl",   Sixty502DotNetLexer.LBPL },
            { "lbra",   Sixty502DotNetLexer.LBRA },
            { "lbrn",   Sixty502DotNetLexer.LBRN },
            { "lbsr",   Sixty502DotNetLexer.LBSR },
            { "lbvc",   Sixty502DotNetLexer.LBVC },
            { "lbvs",   Sixty502DotNetLexer.LBVS },
            { "lda",    Sixty502DotNetLexer.LDA },
            { "ldb",    Sixty502DotNetLexer.LDB },
            { "ldd",    Sixty502DotNetLexer.LDD },
            { "lds",    Sixty502DotNetLexer.LDS },
            { "ldu",    Sixty502DotNetLexer.LDU },
            { "ldx",    Sixty502DotNetLexer.LDX },
            { "ldy",    Sixty502DotNetLexer.LDY },
            { "leas",   Sixty502DotNetLexer.LEAS },
            { "leau",   Sixty502DotNetLexer.LEAU },
            { "leax",   Sixty502DotNetLexer.LEAX },
            { "leay",   Sixty502DotNetLexer.LEAY },
            { "lsl",    Sixty502DotNetLexer.LSL },
            { "lsla",   Sixty502DotNetLexer.LSLA },
            { "lslb",   Sixty502DotNetLexer.LSLB },
            { "lsr",    Sixty502DotNetLexer.LSR },
            { "lsra",   Sixty502DotNetLexer.LSRA },
            { "lsrb",   Sixty502DotNetLexer.LSRB },
            { "mul",    Sixty502DotNetLexer.MUL },
            { "neg",    Sixty502DotNetLexer.NEG },
            { "nega",   Sixty502DotNetLexer.NEGA },
            { "negb",   Sixty502DotNetLexer.NEGB },
            { "nop",    Sixty502DotNetLexer.NOP },
            { "ora",    Sixty502DotNetLexer.ORA },
            { "oraa",   Sixty502DotNetLexer.ORAA },
            { "orb",    Sixty502DotNetLexer.ORB },
            { "orcc",   Sixty502DotNetLexer.ORCC },
            { "pc",     Sixty502DotNetLexer.PC },
            { "pcr",    Sixty502DotNetLexer.PCR },
            { "pshs",   Sixty502DotNetLexer.PSHS },
            { "pshu",   Sixty502DotNetLexer.PSHU },
            { "puls",   Sixty502DotNetLexer.PULS },
            { "pulu",   Sixty502DotNetLexer.PULU },
            { "rol",    Sixty502DotNetLexer.ROL },
            { "rola",   Sixty502DotNetLexer.ROLA },
            { "rolb",   Sixty502DotNetLexer.ROLB },
            { "ror",    Sixty502DotNetLexer.ROR },
            { "rora",   Sixty502DotNetLexer.RORA },
            { "rorb",   Sixty502DotNetLexer.RORB },
            { "rti",    Sixty502DotNetLexer.RTI },
            { "rts",    Sixty502DotNetLexer.RTS },
            { "s",      Sixty502DotNetLexer.S },    
            { "sbca",   Sixty502DotNetLexer.SBCA },
            { "sbcb",   Sixty502DotNetLexer.SBCB },
            { "sex",    Sixty502DotNetLexer.SEX },
            { "sta",    Sixty502DotNetLexer.STA },
            { "stb",    Sixty502DotNetLexer.STB },
            { "std",    Sixty502DotNetLexer.STD },
            { "sts",    Sixty502DotNetLexer.STS },
            { "stu",    Sixty502DotNetLexer.STU },
            { "stx",    Sixty502DotNetLexer.STX },
            { "sty",    Sixty502DotNetLexer.STY },
            { "suba",   Sixty502DotNetLexer.SUBA },
            { "subb",   Sixty502DotNetLexer.SUBB },
            { "subd",   Sixty502DotNetLexer.SUBD },
            { "swi",    Sixty502DotNetLexer.SWI },
            { "swi2",   Sixty502DotNetLexer.SWI2 },
            { "swi3",   Sixty502DotNetLexer.SWI3 },
            { "sync",   Sixty502DotNetLexer.SYNC },
            { "tfr",    Sixty502DotNetLexer.TFR },
            { "tst",    Sixty502DotNetLexer.TST },
            { "tsta",   Sixty502DotNetLexer.TSTA },
            { "tstb",   Sixty502DotNetLexer.TSTB },
            { "u",      Sixty502DotNetLexer.U },
            { "x",      Sixty502DotNetLexer.X },
            { "y",      Sixty502DotNetLexer.Y }
        };

        private readonly static HashSet<int> s_pushPullMnemonics = new()
        {
            Sixty502DotNetParser.PSHS, Sixty502DotNetParser.PSHU,
            Sixty502DotNetParser.PULS, Sixty502DotNetParser.PULU,
            Sixty502DotNetParser.TFR, Sixty502DotNetParser.EXG
        };

        private readonly static HashSet<int> s_accumulatorRegs = new()
        {
            Sixty502DotNetParser.A, Sixty502DotNetParser.B, Sixty502DotNetParser.D
        };

        private readonly static HashSet<int> s_indexRegs = new()
        {
            Sixty502DotNetParser.S, Sixty502DotNetParser.U, Sixty502DotNetParser.X, Sixty502DotNetParser.Y
        };

        private readonly static HashSet<int> s_pushPullRegs = new()
        {
            Sixty502DotNetParser.A, Sixty502DotNetParser.B, Sixty502DotNetParser.CC,
            Sixty502DotNetParser.D, Sixty502DotNetParser.DP, Sixty502DotNetParser.PC,
            Sixty502DotNetParser.S, Sixty502DotNetParser.U, Sixty502DotNetParser.X,
            Sixty502DotNetParser.Y
        };

        private readonly static HashSet<int> s_longBranches = new()
        {
            Sixty502DotNetParser.LBCC,
            Sixty502DotNetParser.LBCS,
            Sixty502DotNetParser.LBEQ,
            Sixty502DotNetParser.LBGE,
            Sixty502DotNetParser.LBGT,
            Sixty502DotNetParser.LBHI,
            Sixty502DotNetParser.LBHS,
            Sixty502DotNetParser.LBLE,
            Sixty502DotNetParser.LBLO,
            Sixty502DotNetParser.LBLS,
            Sixty502DotNetParser.LBLT,
            Sixty502DotNetParser.LBMI,
            Sixty502DotNetParser.LBNE,
            Sixty502DotNetParser.LBPL,
            Sixty502DotNetParser.LBRA,
            Sixty502DotNetParser.LBRN,
            Sixty502DotNetParser.LBSR,
            Sixty502DotNetParser.LBVC,
            Sixty502DotNetParser.LBVS
        };

        private readonly Dictionary<string, byte> _exchangeModes;

        private readonly Dictionary<string, byte> _pushPullModes;

        protected override IDictionary<Instruction, Opcode> Set { get ; set ; }
    }
}
