// Copyright (c) 2026 informedcitizenry
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// ReSharper disable IdentifierTypo
// ReSharper disable StringLiteralTypo

using Sixty502DotNet.Shared.Eval.Scope;

namespace Sixty502DotNet.Shared.Lex;


public enum TokenType : uint
{
    Eof,
    Newline,
    Comma,
    Colon,
    ColonEq,
    OpenParen,
    CloseParen,
    OpenBrace,
    CloseBrace,
    OpenBracket,
    CloseBracket,
    Pound,
    Tilde,
    Dot,
    DotDot,
    QuestionMark,
    DollarDollar,
    Star,
    StarEq,
    Slash,
    SlashEq,
    Percent,
    PercentEq,
    Plus,
    PlusEq,
    Minus,
    MinusEq,
    Shl,
    ShlEq,
    Shr,
    ShrEq,
    Ashr,
    AshrEq,
    Lt,
    Le,
    Gt,
    Ge,
    Spaceship,
    Eq,
    Arrow,
    EqEq,
    EqEqEq,
    Bang,
    BangEq,
    BangEqEq,
    BitwiseAnd,
    AndEq,
    AndAnd,
    Caret,
    CaretEq,
    CaretCaret,
    BitwiseOr,
    OrEq,
    OrOr,
    Ident,
    False,
    True,
    AltBinLiteral,
    CharLiteral,
    IntLiteral,
    FloatLiteral,
    StringLiteral,
    AtaScreenStringLiteral,
    CbmScreenStringLiteral,
    PetsciiStringLiteral,
    Utf8StringLiteral,
    Utf16StringLiteral,
    Utf32StringLiteral,
    InterpolationStart,
    InterpolationEnd,
    MacroArg,
    NamedArg,
    VarArg,
    Unrecognized,
    
    /*x80/x86 opcode stuff */
    Byte,
    Dword,
    N8,
    N16,
    Ptr,
    Qword,
    Tbyte,
    Word,
    
    /*registers */
    A,
    Af,
    Ah,
    Al,
    Ax,
    B,
    Bh,
    Bl,
    Bc,
    Bp,
    Bx,
    C,
    CcReg,
    Ch,
    Cl,
    Cs,
    Cx,
    D,
    Dh,
    Di,
    Dl,
    De,
    Dp,
    Ds,
    Dx,
    E,
    Es,
    H,
    Hl,
    I,
    Ix,
    Ixh,
    Ixl,
    Iy,
    Iyh,
    Iyl,
    L,
    M,
    Nc,
    Nz,
    P,
    Pc,
    Pcr,
    Pe,
    Po,
    Psw,
    R,
    S,
    ShadowAf,
    Si,
    Sp,
    Ss,
    St,
    St0Reg,
    St1Reg,
    St2Reg,
    St3Reg,
    St4Reg,
    St5Reg,
    St6Reg,
    St7Reg,
    U,
    X,
    Y,
    Z,
    
    /* st(n) 8087 registers */
    StParen0Reg,
    StParen1Reg,
    StParen2Reg,
    StParen3Reg,
    StParen4Reg,
    StParen5Reg,
    StParen6Reg,
    StParen7Reg,
    
    CaseKw,
    DefaultKw,
    
    /*block statement delimiters */
    
    ElseKw,
    ElseifKw,
    ElseifdefKw,
    ElseifndefKw,
    EndblockKw,
    EndenumKw,
    EndfunctionKw,
    EndifKw,
    EndmacroKw,
    EndnamespaceKw,
    EndpageKw,
    EndprocKw,
    EndrepeatKw,
    EndswitchKw,
    EndwhileKw,
    NextKw,
    WhiletrueKw,

    /*preprocessing directives */
    BincludeKw,
    IncludeKw,
    MacroName,
    MacroKw,
    
    /*labeled block statement directives */
    EnumKw,
    FunctionKw,
    BlockKw,
    ProcKw,
    
    /*constant assignment operators */
    EquKw,
    GlobalKw,
    
    /*block statement and declarative statements */
    DoKw,
    ForKw,
    ForeachKw,
    IfKw,
    IfdefKw,
    IfndefKw,
    NamespaceKw,
    PageKw,
    RepeatKw,
    StructKw,
    SwitchKw,
    UnionKw,
    WhileKw,
    
    /*asm control directives */
    AlignKw,
    AssertKw,
    AutoKw,
    BankKw,
    BinaryKw,
    BreakKw,
    ContinueKw,
    CpuKw,
    EorKw,
    DpKw,
    MapKw,
    DsectionKw,
    EchoKw,
    EncodingKw,
    EndKw,
    EndrelocateKw,
    ErrorKw,
    ErrorifKw,
    FillKw,
    ForcepassKw,
    FormatKw,
    GotoKw,
    ImportKw,
    InitmemKw,
    InvokeKw,
    LetKw,
    M8Kw,
    M16Kw,
    Mx8Kw,
    Mx16Kw,
    ManualKw,
    OrgKw,
    ProffKw,
    PronKw,
    PseudoPcKw,
    RealPcKw,
    RelocateKw,
    ReturnKw,
    SectionKw,
    StringifyKw,
    UnmapKw,
    WarnKw,
    WarnifKw,
    X8Kw,
    X16Kw,

    /*data commands/pseudo-ops */
    AddrKw,
    BankBytesKw,
    BstringKw,
    ByteKw,
    CbmfltKw,
    CbmfltpKw,
    CharKw,
    CstringKw,
    DintKw,
    DoubleKw,
    DwordKw,
    HibytesKw,
    HiwordsKw,
    HstringKw,
    LintKw,
    LobytesKw,
    LongKw,
    LowordsKw,
    LstringKw,
    NstringKw,
    PstringKw,
    QwordKw,
    RtaKw,
    SbyteKw,
    ShortKw,
    SintKw,
    StringKw,
    TbyteKw,
    WordKw,

    /*6502 mnemonics */
    Adc,
    And,
    Asl,
    Bcc,
    Bcs,
    Beq,
    Bit,
    Bmi,
    Bne,
    Bpl,
    Brk,
    Bvc,
    Bvs,
    Clc,
    Cld,
    Cli,
    Clv,
    Cmp,
    Cpx,
    Cpy,
    Dec,
    Dex,
    Dey,
    Eor,
    Inc,
    Inx,
    Iny,
    Jcc,
    Jcs,
    Jeq,
    Jmi,
    Jmp,
    Jne,
    Jpl,
    Jsr,
    Jvc,
    Jvs,
    Lda,
    Ldx,
    Ldy,
    Lsr,
    Nop,
    Ora,
    Pha,
    Php,
    Pla,
    Plp,
    Rol,
    Ror,
    Rti,
    Rts,
    Sbc,
    Sec,
    Sed,
    Sei,
    Sta,
    Stx,
    Sty,
    Tax,
    Tay,
    Tsx,
    Txa,
    Txs,
    Tya,

    /*6502i mnemonics */
    Anc,
    Ane,
    Arr,
    Asr,
    Dcp,
    Dop,
    Isb,
    Jam,
    Las,
    Lax,
    Rla,
    Rra,
    Sax,
    Sha,
    Shx,
    Shy,
    Slo,
    Sre,
    Stp,
    Tas,
    Top,
    
    /*C64dtv mnemonics */
    Gra,
    Sac,
    Sir,

    /*65816 mnemonics */
    Brl,
    Cop,
    Jml,
    Jsl,
    Mvn,
    Mvp,
    Pea,
    Pei,
    Per,
    Phb,
    Phd,
    Phk,
    Plb,
    Pld,
    Rep,
    Rtl,
    Sep,
    Tcd,
    Tcs,
    Tdc,
    Tsc,
    Txy,
    Tyx,
    Wdm,
    Xba,
    Xce,

    /*65C02 mnemonics */
    Bbr,
    Bbs,
    Bra,
    Phx,
    Phy,
    Plx,
    Ply,
    Rmb,
    Smb,
    Stz,
    Trb,
    Tsb,

    /*65CE02 mnemonics */
    Asw,
    Bge,
    Blt,
    Bsr,
    Cle,
    Cpz,
    Dez,
    Dew,
    Eom,
    Inw,
    Inz,
    Ldz,
    Map,
    Neg,
    Phw,
    Phz,
    Plz,
    Row,
    Rtn,
    See,
    Tab,
    Taz,
    Tba,
    Tsy,
    Tys,
    Tza,

    /*gb80 mnemonics */
    Ccf,
    Cp,
    Cpl,
    Daa,
    Di80,
    Ei,
    Halt,
    Jp,
    Jr,
    Ld,
    Ldd,
    Ldi,
    Or,
    Pop,
    Push,
    Res,
    Ret,
    Reti,
    Rl,
    Rlc,
    Rlca,
    Rr,
    Rrc,
    Rrca,
    Rst,
    Scf,
    Set,
    Sla,
    Sra,
    Srl,
    Stop,
    Sub,
    Swap,
    Xor,

    /*HuC6280 mnemonics */
    Cla,
    Clx,
    Cly,
    Csh,
    Csl,
    Say,
    St1,
    St2,
    Sxy,
    Tai,
    Tam,
    Tdd,
    Tia,
    Tii,
    Tin,
    Tma,
    Tst,

    /*i8080 mnemonics */
    Aci,
    Add,
    Adi,
    Ana,
    Ani,
    Call,
    Cc,
    Cm,
    Cma,
    Cmc,
    Cnc,
    Cnz,
    Cpe,
    Cpi,
    Cpo,
    Cz,
    Dad,
    Dcr,
    Dcx,
    Hlt,
    In,
    Inr,
    Jc,
    Jm,
    Jnc,
    Jnz,
    Jpe,
    Jpo,
    Jz,
    Ldax,
    Lhld,
    Lxi,
    Mov,
    Mvi,
    Ori,
    Out,
    Pchl,
    Ral,
    Rar,
    Rc,
    Rm,
    Rnc,
    Rnz,
    Rp,
    Rpe,
    Rpo,
    Rz,
    Sbb,
    Sbi,
    Shld,
    Sphl,
    Stax,
    Stc,
    Sui,
    Xchg,
    Xra,
    Xri,
    Xthl,

    /*m65 mnemonics */
    Adcq,
    Andq,
    Aslq,
    Asrq,
    Bitq,
    Cpq,
    Deq,
    Eorq,
    Inq,
    Ldq,
    Lsrq,
    Orq,
    Rolq,
    Rorq,
    Sbcq,
    Stq,

    /*m6800 keywords */
    Aba,
    Adca,
    Adcb,
    Adda,
    Addb,
    Anda,
    Andb,
    Asla,
    Aslb,
    Asra,
    Asrb,
    Bgt,
    Bhi,
    Bita,
    Bitb,
    Ble,
    Bls,
    Cba,
    Clr,
    Clra,
    Clrb,
    Cmpa,
    Cmpb,
    Com,
    Coma,
    Comb,
    Cpxa,
    Deca,
    Decb,
    Des,
    Eora,
    Eorb,
    Inca,
    Incb,
    Ins,
    Ldaa,
    Ldab,
    Lds,
    Lsra,
    Lsrb,
    Nega,
    Negb,
    Oraa,
    Orab,
    Psha,
    Pshb,
    Pula,
    Pulb,
    Rola,
    Rolb,
    Rora,
    Rorb,
    Sba,
    Sbca,
    Sbcb,
    Sev,
    Staa,
    Stab,
    Sts,
    Suba,
    Subb,
    Swi,
    Tap,
    Tpa,
    Tsta,
    Tstb,
    Wai,

    /*m6809 mnemonics */
    Abx,
    Addd,
    Andcc,
    Bhs,
    Blo,
    Brn,
    Cmpd,
    Cmps,
    Cmpu,
    Cmpx,
    Cmpy,
    Cwai,
    Exg,
    Lbcc,
    Lbcs,
    Lbeq,
    Lbge,
    Lbgt,
    Lbhi,
    Lbhs,
    Lble,
    Lblo,
    Lbls,
    Lblt,
    Lbmi,
    Lbne,
    Lbpl,
    Lbra,
    Lbrn,
    Lbsr,
    Lbvc,
    Lbvs,
    Ldb,
    Ldu,
    Leas,
    Leau,
    Leax,
    Leay,
    Lsl,
    Lsla,
    Lslb,
    Mul,
    Orb,
    Orcc,
    Pshs,
    Pshu,
    Puls,
    Pulu,
    Sex,
    Stb,
    Std,
    Stu,
    Subd,
    Swi2,
    Swi3,
    Sync,
    Tfr,
    Tfradp,
    Tfrbdp,

    /*z80 mnemonics */
    Cpd,
    Cpdr,
    Cpir,
    Djnz,
    Ex,
    Exx,
    Im,
    Ind,
    Indr,
    Ini,
    Inir,
    Lddr,
    Ldir,
    Otdr,
    Otir,
    Outd,
    Outi,
    Retn,
    Rld,
    Rrd,
    Sll,
    
    /* i8086 mnemonics */
    Aaa,
    Aad,
    Aam,
    Aas,
    Cbw,
    Cmpsb,
    Cmpsw,
    Cwd,
    Das,
    Div,
    Esc,
    F2Xm1,
    Fadd,
    Faddp,
    Fabs,
    Fbld,
    Fbstp,
    Fchs,
    Fclex,
    Fcom,
    Fcomp,
    Fcompp,
    Fcos,
    Fdecstp,
    Fdisi,
    Fdiv,
    Fdivp,
    Fdivr,
    Fdivrp,
    Feni,
    Ffree,
    Fiadd,
    Ficom,
    Ficomp,
    Fidiv,
    Fidivr,
    Fild,
    Fimul,
    Fincstp,
    Finit,
    Fist,
    Fistp,
    Fisub,
    Fisubr,
    Fld,
    Fld1,
    Fldcw,
    Fldenv,
    Fldl2E,
    Fldl2T,
    Fldlg2,
    Fldln2,
    Fldpi,
    Fldz,
    Fmul,
    Fmulp,
    Fnclex,
    Fndisi,
    Fneni,
    Fninit,
    Fnop,
    Fnsave,
    Fnstcw,
    Fnstenv,
    Fnstsw,
    Fpatan,
    Fprem,
    Frndint,
    Fptan,
    Frstor,
    Fsave,
    Fscale,
    Fsin,
    Fsqrt,
    Fst,
    Fstcw,
    Fstenv,
    Fstp,
    Fstsw,
    Fsub,
    Fsubp,
    Fsubr,
    Fsubrp,
    Ftst,
    Fxch,
    Fxtract,
    Fwait,
    Fxam,
    Fyl2X,
    Fyl2Xp1,
    Idiv,
    Imul,
    Insb,
    Insw,
    Int,
    Int3,
    Into,
    Iret,
    Ja,
    Jae,
    Jb,
    Jbe,
    Jcxz,
    Je,
    Jg,
    Jge,
    Jl,
    Jle,
    Jmpf,
    Jmps,
    Jna,
    Jnae,
    Jnb,
    Jnbe,
    Jng,
    Jnge,
    Jnl,
    Jnle,
    Jno,
    Jnp,
    Jns,
    Jo,
    Js,
    Lahf,
    Lea,
    Leave,
    Les,
    Lock,
    Lods,
    Lodsb,
    Lodsw,
    Loop,
    Loope,
    Loopne,
    Loopnz,
    Loopz,
    Movs,
    Movsb,
    Movsw,
    Not,
    Outs,
    Outsb,
    Outsw,
    Popa,
    Popf,
    Pusha,
    Pushf,
    Repe,
    Repne,
    Repnz,
    Repz,
    Rcl,
    Rcr,
    Retf,
    Sahf,
    Sal,
    Salc,
    Sar,
    Scas,
    Scasb,
    Scasw,
    ShlMnem,
    ShrMnem,
    Sti,
    Stos,
    Stosb,
    Stosw,
    Test,
    Wait,
    Xlat,
    Xlatb
}

public static class TokenTypeExtensions
{
    extension(TokenType tokenType)
    {
        public TokenType GetDelimiter()
        {
            return tokenType switch
            {
                TokenType.BlockKw => TokenType.EndblockKw,
                TokenType.DoKw => TokenType.WhiletrueKw,
                TokenType.ElseKw or
                TokenType.IfKw => TokenType.EndifKw,
                TokenType.ForKw or TokenType.ForeachKw => TokenType.NextKw,
                TokenType.FunctionKw => TokenType.EndfunctionKw,
                TokenType.NamespaceKw => TokenType.EndnamespaceKw,
                TokenType.PageKw => TokenType.EndpageKw,
                TokenType.ProcKw => TokenType.EndprocKw,
                TokenType.RepeatKw => TokenType.EndrepeatKw,
                TokenType.SwitchKw => TokenType.EndswitchKw,
                TokenType.WhileKw => TokenType.EndwhileKw,
                _ => tokenType
            };
        }

        public string Stringified()
        {
            return tokenType switch
            {
                TokenType.Eof => "end of file",
                TokenType.Newline => "newline",
                TokenType.Comma => "`,`",
                TokenType.Colon => "`:`",
                TokenType.ColonEq => "`:=`",
                TokenType.OpenParen => "`(`",
                TokenType.CloseParen => "`)`",
                TokenType.OpenBrace => "`{`",
                TokenType.CloseBrace => "`}`",
                TokenType.OpenBracket => "`[`",
                TokenType.CloseBracket => "`]`",
                TokenType.Pound => "`#`",
                TokenType.Tilde => "`~`",
                TokenType.Dot => "`.`",
                TokenType.DotDot => "`..`",
                TokenType.DollarDollar => "$$",
                TokenType.QuestionMark => "`?`",
                TokenType.Star => "`*`",
                TokenType.StarEq => "`*=`",
                TokenType.Slash => "`/`",
                TokenType.SlashEq => "`/=`",
                TokenType.Percent => "`%`",
                TokenType.PercentEq => "`%=`",
                TokenType.Plus => "`+`",
                TokenType.PlusEq => "`+=`",
                TokenType.Minus => "`-`",
                TokenType.MinusEq => "`-=`",
                TokenType.Shl => "`<<`",
                TokenType.ShlEq => "`<<=`",
                TokenType.Shr => "`>>`",
                TokenType.ShrEq => "`>>=`",
                TokenType.Ashr => "`>>>`",
                TokenType.AshrEq => "`>>>=`",
                TokenType.Lt => "`<`",
                TokenType.Le => "`<=`",
                TokenType.Gt => "`>`",
                TokenType.Ge => "`>=`",
                TokenType.Spaceship => "`<=>`",
                TokenType.Eq => "`=`",
                TokenType.Arrow => "`=>`",
                TokenType.EqEq => "`==`",
                TokenType.EqEqEq => "`===`",
                TokenType.Bang => "`!`",
                TokenType.BangEq => "`!=`",
                TokenType.BangEqEq => "`!==`",
                TokenType.BitwiseAnd => "`&`",
                TokenType.AndEq => "`&=`",
                TokenType.AndAnd => "`&&`",
                TokenType.Caret => "`^`",
                TokenType.CaretEq => "`^=`",
                TokenType.CaretCaret => "`^^`",
                TokenType.BitwiseOr => "`|`",
                TokenType.OrEq => "`|=`",
                TokenType.OrOr => "`||`",
                TokenType.Ident => "identifier",
                TokenType.False => "`false`",
                TokenType.True => "`true`",
                TokenType.CharLiteral => "char literal",
                TokenType.AltBinLiteral or
                TokenType.IntLiteral => "integer literal",
                TokenType.FloatLiteral => "floating point literal",
                TokenType.StringLiteral or
                TokenType.AtaScreenStringLiteral or
                TokenType.CbmScreenStringLiteral or
                TokenType.PetsciiStringLiteral or
                TokenType.Utf8StringLiteral or
                TokenType.Utf16StringLiteral or
                TokenType.Utf32StringLiteral or
                TokenType.InterpolationStart or
                TokenType.InterpolationEnd => "string literal",
                TokenType.MacroArg or
                TokenType.NamedArg or
                TokenType.VarArg => "macro argument",
                TokenType.Unrecognized => "unrecognized token",
                TokenType.A => "`a`",
                TokenType.Af => "`af`",
                TokenType.Ah => "`ah`",
                TokenType.Al => "`al`",
                TokenType.Ax => "`ax`",
                TokenType.B => "`b`",
                TokenType.Bc => "`bc`",
                TokenType.Bh => "`bh`",
                TokenType.Bl => "`bl`",
                TokenType.Bp => "`bp`",
                TokenType.Bx => "`bx`",
                TokenType.Byte => "`BYTE`",
                TokenType.C => "`c`",
                TokenType.CcReg => "`cc`",
                TokenType.Ch => "`ch`",
                TokenType.Cl => "`cl`",
                TokenType.Cs => "`cs`",
                TokenType.Cx => "`cx`",
                TokenType.D => "`d`",
                TokenType.De => "`de`",
                TokenType.Dh => "`dh`",
                TokenType.Di => "`di`",
                TokenType.Dl => "`dl`",
                TokenType.Dp => "`dp`",
                TokenType.Ds => "`ds`",
                TokenType.Dword => "`DWORD`",
                TokenType.Dx => "`dx`",
                TokenType.E => "`e`",
                TokenType.Es => "`es`",
                TokenType.Esc => "`esc`",
                TokenType.H => "`h`",
                TokenType.Hl => "`hl`",
                TokenType.I => "`i`",
                TokenType.Ix => "`ix`",
                TokenType.Ixh => "`ixh`",
                TokenType.Ixl => "`ixl`",
                TokenType.Iy => "`iy`",
                TokenType.Iyh => "`iyh`",
                TokenType.Iyl => "`iyl`",
                TokenType.L => "`l`",
                TokenType.M => "`m`",
                TokenType.Nc => "`nc`",
                TokenType.Nz => "`nz`",
                TokenType.Pc => "`pc`",
                TokenType.Pcr => "`pcr`",
                TokenType.Pe => "`pe`",
                TokenType.Po => "`po`",
                TokenType.Ptr => "`PTR`",
                TokenType.Qword => "`QWORD`",
                TokenType.R => "`r`",
                TokenType.S => "`s`",
                TokenType.ShadowAf => "`af'`",
                TokenType.Sp => "`sp`",
                TokenType.Ss => "`ss`",
                TokenType.St => "`st`",
                TokenType.St0Reg => "`st0`",
                TokenType.St1Reg => "`st1`",
                TokenType.St2Reg => "`st2`",
                TokenType.St3Reg => "`st3`",
                TokenType.St4Reg => "`st4`",
                TokenType.St5Reg => "`st5`",
                TokenType.St6Reg => "`st6`",
                TokenType.St7Reg => "`st7`",
                TokenType.StParen0Reg => "`st(0)`",
                TokenType.StParen1Reg => "`st(1)`",
                TokenType.StParen2Reg => "`st(2)`",
                TokenType.StParen3Reg => "`st(3)`",
                TokenType.StParen4Reg => "`st(4)`",
                TokenType.StParen5Reg => "`st(5)`",
                TokenType.StParen6Reg => "`st(6)`",
                TokenType.StParen7Reg => "`st(7)`",
                TokenType.Tbyte => "`TBYTE`",
                TokenType.U => "`u`",
                TokenType.Word => "`WORD`",
                TokenType.X => "`x`",
                TokenType.Y => "`y`",
                TokenType.Z => "`z`",
                TokenType.CaseKw => "`.case`",
                TokenType.DefaultKw => "`.default`",
                TokenType.ElseKw => "`.else`",
                TokenType.ElseifKw => "`.elseif`",
                TokenType.ElseifdefKw => "`.elseifdef`",
                TokenType.ElseifndefKw => "`.elseifndef`",
                TokenType.EndblockKw => "`.endblock`",
                TokenType.EndenumKw => "`.endenum`",
                TokenType.EndfunctionKw => "`.endfunction`",
                TokenType.EndifKw => "`.endif`",
                TokenType.EndmacroKw => "`.endmacro`",
                TokenType.EndnamespaceKw => "`.endnamespace`",
                TokenType.EndpageKw => "`.endpage`",
                TokenType.EndprocKw => "`.endproc`",
                TokenType.EndrepeatKw => "`.endrepeat`",
                TokenType.EndswitchKw => "`.endswitch`",
                TokenType.EndwhileKw => "`.endwhile`",
                TokenType.NextKw => "`.next`",
                TokenType.WhiletrueKw => "`.whiletrue`",
                TokenType.AlignKw => "`.align`",
                TokenType.AssertKw => "`.assert`",
                TokenType.AutoKw => "`.auto`",
                TokenType.BankKw => "`.bank`",
                TokenType.BinaryKw => "`.binary`",
                TokenType.BincludeKw => "`.binclude`",
                TokenType.BreakKw => "`.break`",
                TokenType.ContinueKw => "`.continue`",
                TokenType.CpuKw => "`.cpu`",
                TokenType.EorKw => "`.eor`",
                TokenType.DpKw => "`.dp`",
                TokenType.MapKw => "`.map`",
                TokenType.DsectionKw => "`.dsection`",
                TokenType.EchoKw => "`.echo`",
                TokenType.EncodingKw => "`.encoding`",
                TokenType.EndKw => "`.end`",
                TokenType.EndrelocateKw => "`.endrelocate`",
                TokenType.EquKw => "`.equ`",
                TokenType.ErrorKw => "`.error`",
                TokenType.ErrorifKw => "`.errorif`",
                TokenType.FillKw => "`.fill`",
                TokenType.ForcepassKw => "`.forcepass`",
                TokenType.FormatKw => "`.format`",
                TokenType.GlobalKw => "`.global`",
                TokenType.GotoKw => "`.goto`",
                TokenType.ImportKw => "`.import`",
                TokenType.IncludeKw => "`.include`",
                TokenType.InitmemKw => "`.initmem`",
                TokenType.InvokeKw => "`.invoke`",
                TokenType.LetKw => "`.let`",
                TokenType.M8Kw => "`.m8`",
                TokenType.M16Kw => "`.m16`",
                TokenType.Mx8Kw => "`.mx8`",
                TokenType.Mx16Kw => "`.mx16`",
                TokenType.ManualKw => "`.manual`",
                TokenType.OrgKw => "`.org`",
                TokenType.ProffKw => "`.proff`",
                TokenType.PronKw => "`.pron`",
                TokenType.PseudoPcKw => "`.pseudopc`",
                TokenType.RealPcKw => "`.realpc`",
                TokenType.RelocateKw => "`.relocate`",
                TokenType.ReturnKw => "`.return`",
                TokenType.SectionKw => "`.section`",
                TokenType.StringifyKw => "`.stringify`",
                TokenType.Tfradp => "`.tfradp`",
                TokenType.Tfrbdp => "`.tfrbdp`",
                TokenType.UnmapKw => "`.unmap`",
                TokenType.WarnKw => "`.warn`",
                TokenType.WarnifKw => "`.warnif`",
                TokenType.X8Kw => "`.x8`",
                TokenType.X16Kw => "`.x16`",
                TokenType.BlockKw => "`.block`",
                TokenType.DoKw => "`.do`",
                TokenType.EnumKw => "`.enum`",
                TokenType.ForKw => "`.for`",
                TokenType.ForeachKw => "`.foreach`",
                TokenType.FunctionKw => "`.function`",
                TokenType.IfKw => "`.if`",
                TokenType.IfdefKw => "`ifdef`",
                TokenType.IfndefKw => "`.ifndef`",
                TokenType.MacroKw => "`.macro`",
                TokenType.MacroName => "`.macroname`",
                TokenType.NamespaceKw => "`.namespace`",
                TokenType.PageKw => "`.page`",
                TokenType.ProcKw => "`.proc`",
                TokenType.RepeatKw => "`.repeat`",
                TokenType.StructKw => "`.struct`",
                TokenType.SwitchKw => "`.switch`",
                TokenType.UnionKw => "`.union`",
                TokenType.WhileKw => "`.while`",
                TokenType.AddrKw => "`.addr`",
                TokenType.BankBytesKw => "`.bankbytes`",
                TokenType.BstringKw => "`.bstring`",
                TokenType.ByteKw => "`.byte`",
                TokenType.CbmfltKw => "`.cbmflt`",
                TokenType.CbmfltpKw => "`.cbmfltp`",
                TokenType.CharKw => "`.char`",
                TokenType.CstringKw => "`.cstring`",
                TokenType.DintKw => "`.dint`",
                TokenType.DoubleKw => "`.double`",
                TokenType.DwordKw => "`.dword`",
                TokenType.HibytesKw => "`.hibytes`",
                TokenType.HiwordsKw => "`.hiwords`",
                TokenType.HstringKw => "`.hstring`",
                TokenType.LintKw => "`.lint`",
                TokenType.LobytesKw => "`.lobytes`",
                TokenType.LongKw => "`.long`",
                TokenType.LowordsKw => "`.lowords`",
                TokenType.LstringKw => "`.lstring`",
                TokenType.NstringKw => "`.nstring`",
                TokenType.PstringKw => "`.pstring`",
                TokenType.QwordKw => "`.qword`",
                TokenType.RtaKw => "`.rta`",
                TokenType.SbyteKw => "`.sbyte`",
                TokenType.ShortKw => "`.short`",
                TokenType.SintKw => "`.sint`",
                TokenType.StringKw => "`.string`",
                TokenType.TbyteKw => "`.tbyte`",
                TokenType.WordKw => "`.word`",
                TokenType.Sac => "`sac`",
                TokenType.Sir => "`sir`",
                TokenType.Adc => "`adc`",
                TokenType.And => "`and`",
                TokenType.Asl => "`asl`",
                TokenType.Bcc => "`bcc`",
                TokenType.Bcs => "`bcs`",
                TokenType.Beq => "`beq`",
                TokenType.Bit => "`bit`",
                TokenType.Bmi => "`bmi`",
                TokenType.Bne => "`bne`",
                TokenType.Bpl => "`bpl`",
                TokenType.Brk => "`brk`",
                TokenType.Bvc => "`bvc`",
                TokenType.Bvs => "`bvs`",
                TokenType.Clc => "`clc`",
                TokenType.Cld => "`cld`",
                TokenType.Cli => "`cli`",
                TokenType.Clv => "`clv`",
                TokenType.Cmp => "`cmp`",
                TokenType.Cpx => "`cpx`",
                TokenType.Cpy => "`cpy`",
                TokenType.Dec => "`dec`",
                TokenType.Dex => "`dex`",
                TokenType.Dey => "`dey`",
                TokenType.Eor => "`eor`",
                TokenType.Inc => "`inc`",
                TokenType.Inx => "`inx`",
                TokenType.Iny => "`iny`",
                TokenType.Jcc => "`jcc`",
                TokenType.Jcs => "`jcs`",
                TokenType.Jeq => "`jeq`",
                TokenType.Jmi => "`jmi`",
                TokenType.Jmp => "`jmp`",
                TokenType.Jne => "`jne`",
                TokenType.Jpl => "`jpl`",
                TokenType.Jsr => "`jsr`",
                TokenType.Jvc => "`jvc`",
                TokenType.Jvs => "`jvs`",
                TokenType.Lda => "`lda`",
                TokenType.Ldx => "`ldx`",
                TokenType.Ldy => "`ldy`",
                TokenType.Lsr => "`lsr`",
                TokenType.Nop => "`nop`",
                TokenType.Ora => "`ora`",
                TokenType.Pha => "`pha`",
                TokenType.Php => "`php`",
                TokenType.Pla => "`pla`",
                TokenType.Plp => "`plp`",
                TokenType.Rol => "`rol`",
                TokenType.Ror => "`ror`",
                TokenType.Rti => "`rti`",
                TokenType.Rts => "`rts`",
                TokenType.Sbc => "`sbc`",
                TokenType.Sec => "`sec`",
                TokenType.Sed => "`sed`",
                TokenType.Sei => "`sei`",
                TokenType.Sta => "`sta`",
                TokenType.Stx => "`stx`",
                TokenType.Sty => "`sty`",
                TokenType.Tax => "`tax`",
                TokenType.Tay => "`tay`",
                TokenType.Tsx => "`tsx`",
                TokenType.Txa => "`txa`",
                TokenType.Txs => "`txs`",
                TokenType.Tya => "`tya`",
                TokenType.Anc => "`anc`",
                TokenType.Ane => "`ane`",
                TokenType.Arr => "`arr`",
                TokenType.Asr => "`asr`",
                TokenType.Dcp => "`dcp`",
                TokenType.Dop => "`dop`",
                TokenType.Gra => "`gra`",
                TokenType.Isb => "`isb`",
                TokenType.Jam => "`jam`",
                TokenType.Las => "`las`",
                TokenType.Lax => "`lax`",
                TokenType.Rla => "`rla`",
                TokenType.Rra => "`rra`",
                TokenType.Sax => "`sax`",
                TokenType.Sha => "`sha`",
                TokenType.Shx => "`shx`",
                TokenType.Shy => "`shy`",
                TokenType.Slo => "`slo`",
                TokenType.Sre => "`sre`",
                TokenType.Stp => "`stp`",
                TokenType.Tas => "`tas`",
                TokenType.Top => "`top`",
                TokenType.Brl => "`brl`",
                TokenType.Cop => "`cop`",
                TokenType.Jml => "`jml`",
                TokenType.Jsl => "`jsl`",
                TokenType.Mvn => "`mvn`",
                TokenType.Mvp => "`mvp`",
                TokenType.Pea => "`pea`",
                TokenType.Pei => "`pei`",
                TokenType.Per => "`per`",
                TokenType.Phb => "`phb`",
                TokenType.Phd => "`phd`",
                TokenType.Phk => "`phk`",
                TokenType.Plb => "`plb`",
                TokenType.Pld => "`pld`",
                TokenType.Rep => "`rep`",
                TokenType.Rtl => "`rtl`",
                TokenType.Sep => "`sep`",
                TokenType.Tcd => "`tcd`",
                TokenType.Tcs => "`tcs`",
                TokenType.Tdc => "`tdc`",
                TokenType.Tsc => "`tsc`",
                TokenType.Txy => "`txy`",
                TokenType.Tyx => "`tyx`",
                TokenType.Wdm => "`wdm`",
                TokenType.Xba => "`xba`",
                TokenType.Xce => "`xce`",
                TokenType.Bbr => "`bbr`",
                TokenType.Bbs => "`bbs`",
                TokenType.Bra => "`bra`",
                TokenType.Phx => "`phx`",
                TokenType.Phy => "`phy`",
                TokenType.Plx => "`plx`",
                TokenType.Ply => "`ply`",
                TokenType.Rmb => "`rmb`",
                TokenType.Smb => "`smb`",
                TokenType.Stz => "`stz`",
                TokenType.Trb => "`trb`",
                TokenType.Tsb => "`tsb`",
                TokenType.Asw => "`asw`",
                TokenType.Bge => "`bge`",
                TokenType.Blt => "`blt`",
                TokenType.Bsr => "`bsr`",
                TokenType.Cle => "`cle`",
                TokenType.Cpz => "`cpz`",
                TokenType.Dez => "`dez`",
                TokenType.Dew => "`dew`",
                TokenType.Eom => "`eom`",
                TokenType.Inw => "`inw`",
                TokenType.Inz => "`inz`",
                TokenType.Ldz => "`ldz`",
                TokenType.Map => "`map`",
                TokenType.Neg => "`neg`",
                TokenType.Phw => "`phw`",
                TokenType.Phz => "`phz`",
                TokenType.Plz => "`plz`",
                TokenType.Row => "`row`",
                TokenType.Rtn => "`rtn`",
                TokenType.See => "`see`",
                TokenType.Tab => "`tab`",
                TokenType.Taz => "`taz`",
                TokenType.Tba => "`tba`",
                TokenType.Tsy => "`tsy`",
                TokenType.Tys => "`tys`",
                TokenType.Tza => "`tza`",
                TokenType.Cp => "`cp`",
                TokenType.Cpl => "`cpl`",
                TokenType.Daa => "`daa`",
                TokenType.Di80 => "`di`",
                TokenType.Ei => "`ei`",
                TokenType.Halt => "`halt`",
                TokenType.Jp => "`jp`",
                TokenType.Jr => "`jr`",
                TokenType.Ld => "`ld`",
                TokenType.Ldd => "`ldd`",
                TokenType.Ldi => "`ldi`",
                TokenType.Or => "`or`",
                TokenType.Pop => "`pop`",
                TokenType.Push => "`push`",
                TokenType.Res => "`res`",
                TokenType.Ret => "`ret`",
                TokenType.Reti => "`reti`",
                TokenType.Rl => "`rl`",
                TokenType.Rlc => "`rlc`",
                TokenType.Rlca => "`rlca`",
                TokenType.Rr => "`rr`",
                TokenType.Rrc => "`rrc`",
                TokenType.Rrca => "`rrca`",
                TokenType.Rst => "`rst`",
                TokenType.Scf => "`scf`",
                TokenType.Set => "`set`",
                TokenType.Sla => "`sla`",
                TokenType.Sra => "`sra`",
                TokenType.Srl => "`srl`",
                TokenType.Stop => "`stop`",
                TokenType.Sub => "`sub`",
                TokenType.Swap => "`swap`",
                TokenType.Xor => "`xor`",
                TokenType.Cla => "`cla`",
                TokenType.Clx => "`clx`",
                TokenType.Cly => "`cly`",
                TokenType.Csh => "`csh`",
                TokenType.Csl => "`csl`",
                TokenType.Say => "`say`",
                TokenType.St1 => "`st1`",
                TokenType.St2 => "`st2`",
                TokenType.Sxy => "`sxy`",
                TokenType.Tai => "`tai`",
                TokenType.Tam => "`tam`",
                TokenType.Tdd => "`tdd`",
                TokenType.Tia => "`tia`",
                TokenType.Tii => "`tii`",
                TokenType.Tin => "`tin`",
                TokenType.Tma => "`tma`",
                TokenType.Tst => "`tst`",
                TokenType.Aci => "`aci`",
                TokenType.Add => "`add`",
                TokenType.Adi => "`adi`",
                TokenType.Ana => "`ana`",
                TokenType.Ani => "`ani`",
                TokenType.Call => "`call`",
                TokenType.Cc => "`cc`",
                TokenType.Cm => "`cm`",
                TokenType.Cma => "`cma`",
                TokenType.Cmc => "`cmc`",
                TokenType.Cnc => "`cnc`",
                TokenType.Cnz => "`cnz`",
                TokenType.Cpe => "`cpe`",
                TokenType.Cpi => "`cpi`",
                TokenType.Cpo => "`cpo`",
                TokenType.Cz => "`cz`",
                TokenType.Dad => "`dad`",
                TokenType.Dcr => "`dcr`",
                TokenType.Dcx => "`dcx`",
                TokenType.Hlt => "`hlt`",
                TokenType.In => "`in`",
                TokenType.Inr => "`inr`",
                TokenType.Jc => "`jc`",
                TokenType.Jm => "`jm`",
                TokenType.Jnc => "`jnc`",
                TokenType.Jnz => "`jnz`",
                TokenType.Jpe => "`jpe`",
                TokenType.Jpo => "`jpo`",
                TokenType.Jz => "`jz`",
                TokenType.Ldax => "`ldax`",
                TokenType.Lhld => "`lhld`",
                TokenType.Lxi => "`lxi`",
                TokenType.Mov => "`mov`",
                TokenType.Mvi => "`mvi`",
                TokenType.Ori => "`ori`",
                TokenType.Out => "`out`",
                TokenType.Pchl => "`pchl`",
                TokenType.Psw => "`psw`",
                TokenType.Ral => "`ral`",
                TokenType.Rar => "`rar`",
                TokenType.Rc => "`rc`",
                TokenType.Rm => "`rm`",
                TokenType.Rnc => "`rnc`",
                TokenType.Rnz => "`rnz`",
                TokenType.Rp => "`rp`",
                TokenType.Rpe => "`rpe`",
                TokenType.Rpo => "`rpo`",
                TokenType.Rz => "`rz`",
                TokenType.Sbb => "`sbb`",
                TokenType.Sbi => "`sbi`",
                TokenType.Shld => "`shld`",
                TokenType.Sphl => "`sphl`",
                TokenType.Stax => "`stax`",
                TokenType.Stc => "`stc`",
                TokenType.Sui => "`sui`",
                TokenType.Xchg => "`xchg`",
                TokenType.Xra => "`xra`",
                TokenType.Xri => "`xri`",
                TokenType.Xthl => "`xthl`",
                TokenType.Adcq => "`adcq`",
                TokenType.Andq => "`andq`",
                TokenType.Aslq => "`aslq`",
                TokenType.Asrq => "`asrq`",
                TokenType.Bitq => "`bitq`",
                TokenType.Cpq => "`cpq`",
                TokenType.Deq => "`deq`",
                TokenType.Eorq => "`eorq`",
                TokenType.Inq => "`inq`",
                TokenType.Ldq => "`ldq`",
                TokenType.Lsrq => "`lsrq`",
                TokenType.Orq => "`orq`",
                TokenType.Rolq => "`rolq`",
                TokenType.Rorq => "`rorq`",
                TokenType.Sbcq => "`sbcq`",
                TokenType.Stq => "`stq`",
                TokenType.Aba => "`aba`",
                TokenType.Adca => "`adca`",
                TokenType.Adcb => "`adcb`",
                TokenType.Adda => "`adda`",
                TokenType.Addb => "`addb`",
                TokenType.Anda => "`anda`",
                TokenType.Andb => "`andb`",
                TokenType.Asla => "`asla`",
                TokenType.Aslb => "`aslb`",
                TokenType.Asra => "`asra`",
                TokenType.Asrb => "`asrb`",
                TokenType.Bgt => "`bgt`",
                TokenType.Bhi => "`bhi`",
                TokenType.Bita => "`bita`",
                TokenType.Bitb => "`bitb`",
                TokenType.Ble => "`ble`",
                TokenType.Bls => "`bls`",
                TokenType.Cba => "`cba`",
                TokenType.Clr => "`clr`",
                TokenType.Clra => "`clra`",
                TokenType.Clrb => "`clrb`",
                TokenType.Cmpa => "`cmpa`",
                TokenType.Cmpb => "`cmpb`",
                TokenType.Com => "`com`",
                TokenType.Coma => "`coma`",
                TokenType.Comb => "`comb`",
                TokenType.Cpxa => "`cpxa`",
                TokenType.Deca => "`deca`",
                TokenType.Decb => "`decb`",
                TokenType.Des => "`des`",
                TokenType.Eora => "`eora`",
                TokenType.Eorb => "`eorb`",
                TokenType.Inca => "`inca`",
                TokenType.Incb => "`incb`",
                TokenType.Ins => "`ins`",
                TokenType.Ldaa => "`ldaa`",
                TokenType.Ldab => "`ldab`",
                TokenType.Lds => "`lds`",
                TokenType.Lsra => "`lsra`",
                TokenType.Lsrb => "`lsrb`",
                TokenType.Nega => "`nega`",
                TokenType.Negb => "`negb`",
                TokenType.Oraa => "`oraa`",
                TokenType.Orab => "`orab`",
                TokenType.Psha => "`psha`",
                TokenType.Pshb => "`pshb`",
                TokenType.Pula => "`pula`",
                TokenType.Pulb => "`pulb`",
                TokenType.Rola => "`rola`",
                TokenType.Rolb => "`rolb`",
                TokenType.Rora => "`rora`",
                TokenType.Rorb => "`rorb`",
                TokenType.Sba => "`sba`",
                TokenType.Sbca => "`sbca`",
                TokenType.Sbcb => "`sbcb`",
                TokenType.Sev => "`sev`",
                TokenType.Staa => "`staa`",
                TokenType.Stab => "`stab`",
                TokenType.Sts => "`sts`",
                TokenType.Suba => "`suba`",
                TokenType.Subb => "`subb`",
                TokenType.Swi => "`swi`",
                TokenType.Tap => "`tap`",
                TokenType.Tpa => "`tpa`",
                TokenType.Tsta => "`tsta`",
                TokenType.Tstb => "`tstb`",
                TokenType.Wai => "`wai`",
                TokenType.Abx => "`abx`",
                TokenType.Addd => "`addd`",
                TokenType.Andcc => "`andcc`",
                TokenType.Bhs => "`bhs`",
                TokenType.Blo => "`blo`",
                TokenType.Brn => "`brn`",
                TokenType.Cmpd => "`cmpd`",
                TokenType.Cmps => "`cmps`",
                TokenType.Cmpu => "`cmpu`",
                TokenType.Cmpx => "`cmpx`",
                TokenType.Cmpy => "`cmpy`",
                TokenType.Cwai => "`cwai`",
                TokenType.Exg => "`exg`",
                TokenType.Lbcc => "`lbcc`",
                TokenType.Lbcs => "`lbcs`",
                TokenType.Lbeq => "`lbeq`",
                TokenType.Lbge => "`lbge`",
                TokenType.Lbgt => "`lbgt`",
                TokenType.Lbhi => "`lbhi`",
                TokenType.Lbhs => "`lbhs`",
                TokenType.Lble => "`lble`",
                TokenType.Lblo => "`lblo`",
                TokenType.Lbls => "`lbls`",
                TokenType.Lblt => "`lblt`",
                TokenType.Lbmi => "`lbmi`",
                TokenType.Lbne => "`lbne`",
                TokenType.Lbpl => "`lbpl`",
                TokenType.Lbra => "`lbra`",
                TokenType.Lbrn => "`lbrn`",
                TokenType.Lbsr => "`lbsr`",
                TokenType.Lbvc => "`lbvc`",
                TokenType.Lbvs => "`lbvs`",
                TokenType.Ldb => "`ldb`",
                TokenType.Ldu => "`ldu`",
                TokenType.Leas => "`leas`",
                TokenType.Leau => "`leau`",
                TokenType.Leax => "`leax`",
                TokenType.Leay => "`leay`",
                TokenType.Lsl => "`lsl`",
                TokenType.Lsla => "`lsla`",
                TokenType.Lslb => "`lslb`",
                TokenType.Mul => "`mul`",
                TokenType.Orb => "`orb`",
                TokenType.Orcc => "`orcc`",
                TokenType.Pshs => "`pshs`",
                TokenType.Pshu => "`pshu`",
                TokenType.Puls => "`puls`",
                TokenType.Pulu => "`pulu`",
                TokenType.Sex => "`sex`",
                TokenType.Stb => "`stb`",
                TokenType.Std => "`std`",
                TokenType.Stu => "`stu`",
                TokenType.Subd => "`subd`",
                TokenType.Swi2 => "`swi2`",
                TokenType.Swi3 => "`swi3`",
                TokenType.Sync => "`sync`",
                TokenType.Tfr => "`tfr`",
                TokenType.Cpd => "`cpd`",
                TokenType.Cpdr => "`cpdr`",
                TokenType.Cpir => "`cpir`",
                TokenType.Djnz => "`djnz`",
                TokenType.Ex => "`ex`",
                TokenType.Exx => "`exx`",
                TokenType.Im => "`im`",
                TokenType.Ind => "`ind`",
                TokenType.Indr => "`indr`",
                TokenType.Ini => "`ini`",
                TokenType.Inir => "`inir`",
                TokenType.Lddr => "`lddr`",
                TokenType.Ldir => "`ldir`",
                TokenType.Otdr => "`otdr`",
                TokenType.Otir => "`otir`",
                TokenType.Outd => "`outd`",
                TokenType.Outi => "`outi`",
                TokenType.Retn => "`retn`",
                TokenType.Rld => "`rld`",
                TokenType.Rrd => "`rrd`",
                TokenType.Sll => "`sll`",
                TokenType.Aaa => "`aaa`",
                TokenType.Aad => "`aad`",
                TokenType.Aam => "`aam`",
                TokenType.Aas => "`aas`",
                TokenType.Cbw => "`cbw`",
                TokenType.Cmpsb => "`cmpsb`",
                TokenType.Cmpsw => "`cmpsw`",
                TokenType.Cwd => "`cwd`",
                TokenType.Das => "`das`",
                TokenType.Div => "`div`",
                TokenType.F2Xm1 => "`f2xm1`",
                TokenType.Fadd => "`fadd`",
                TokenType.Faddp => "`faddp`",
                TokenType.Fabs => "`fabs`",
                TokenType.Fbld => "`fbld`",
                TokenType.Fbstp => "`fbstp`",
                TokenType.Fchs => "`fchs`",
                TokenType.Fclex => "`fclex`",
                TokenType.Fcom => "`fcom`",
                TokenType.Fcomp => "`fcomp`",
                TokenType.Fcompp => "`fcompp`",
                TokenType.Fcos => "`fcos`",
                TokenType.Fdecstp => "`fdecstp`",
                TokenType.Fdisi => "`fdisi`",
                TokenType.Fdiv => "`fdiv`",
                TokenType.Fdivp => "`fdivp`",
                TokenType.Fdivr => "`fdvir`",
                TokenType.Fdivrp => "`fdivrp`",
                TokenType.Feni => "`feni`",
                TokenType.Ffree => "`ffree`",
                TokenType.Fiadd => "`fiadd`",
                TokenType.Ficom => "`ficom`",
                TokenType.Ficomp => "`ficmp`",
                TokenType.Fidiv => "`fidiv`",
                TokenType.Fidivr => "`fidivr`",
                TokenType.Fild => "`fild`",
                TokenType.Fimul => "`fimul`",
                TokenType.Fincstp => "`fincstp`",
                TokenType.Finit => "`finit`",
                TokenType.Fist => "`fist`",
                TokenType.Fistp => "`fistp`",
                TokenType.Fisub => "`fisub`",
                TokenType.Fisubr => "`fisubr`",
                TokenType.Fld => "`fld`",
                TokenType.Fld1 => "`fld1`",
                TokenType.Fldcw => "`fldcw`",
                TokenType.Fldenv => "`fldenv`",
                TokenType.Fldl2E => "`fldl2e`",
                TokenType.Fldl2T => "`fldl2t`",
                TokenType.Fldlg2 => "`fldlg2`",
                TokenType.Fldln2 => "`fldln2`",
                TokenType.Fldpi => "`fldpi`",
                TokenType.Fldz => "`fldz`",
                TokenType.Fmul => "`fmul`",
                TokenType.Fmulp => "`fmulp`",
                TokenType.Fnclex => "`fnclex`",
                TokenType.Fndisi => "`fndisi`",
                TokenType.Fneni => "`fneni`",
                TokenType.Fninit => "`fninit`",
                TokenType.Fnop => "`fnop`",
                TokenType.Fnsave => "`fnsave`",
                TokenType.Fnstcw => "`fnstcw`",
                TokenType.Fnstenv => "`fnstenv`",
                TokenType.Fnstsw => "`fnstsw`",
                TokenType.Fpatan => "`fpatan`",
                TokenType.Fprem => "`fprem`",
                TokenType.Frndint => "`frndint`",
                TokenType.Fptan => "`fptan`",
                TokenType.Frstor => "`frstor`",
                TokenType.Fsave => "`fsave`",
                TokenType.Fscale => "`fscale`",
                TokenType.Fsin => "`fsin`",
                TokenType.Fsqrt => "`fsqrt`",
                TokenType.Fst => "`fst`",
                TokenType.Fstcw => "`fstcw`",
                TokenType.Fstenv => "`fstenv`",
                TokenType.Fstp => "`fstp`",
                TokenType.Fstsw => "`fstsw`",
                TokenType.Fsub => "`fsub`",
                TokenType.Fsubp => "`fsubp`",
                TokenType.Fsubr => "`fsubr`",
                TokenType.Fsubrp => "`fsubrp`",
                TokenType.Ftst => "`ftst`",
                TokenType.Fxch => "`fxch`",
                TokenType.Fxtract => "`fxtract`",
                TokenType.Fwait => "`fwait`",
                TokenType.Fxam => "`fxam`",
                TokenType.Fyl2X => "`fyl2x`",
                TokenType.Fyl2Xp1 => "`fyl2xp1`",
                TokenType.Idiv => "`idiv`",
                TokenType.Imul => "`imul`",
                TokenType.Insb => "`insb`",
                TokenType.Insw => "`insw`",
                TokenType.Int => "`int`",
                TokenType.Int3 => "`int3`",
                TokenType.Into => "`into`",
                TokenType.Iret => "`iret`",
                TokenType.Jo => "`jo`",
                TokenType.Jno => "`jno`",
                TokenType.Jb => "`jb`",
                TokenType.Jnae => "`jnae`",
                TokenType.Jnb => "`jnb`",
                TokenType.Jae => "`jae`",
                TokenType.Je => "`je`",
                TokenType.Jbe => "`jbe`",
                TokenType.Jcxz => "`jcxz`",
                TokenType.Jna => "`jna`",
                TokenType.Jnbe => "`jnbe`",
                TokenType.Ja => "`ja`",
                TokenType.Js => "`js`",
                TokenType.Jns => "`jns`",
                TokenType.Jnp => "`jnp`",
                TokenType.Jl => "`jl`",
                TokenType.Jnge => "`jnge`",
                TokenType.Jnl => "`jnl`",
                TokenType.Jge => "`jge`",
                TokenType.Jle => "`jle`",
                TokenType.Jmpf => "`jmpf`",
                TokenType.Jmps => "`jmps`",
                TokenType.Jng => "`jng`",
                TokenType.Jnle => "`jnle`",
                TokenType.Jg => "`jg`",
                TokenType.Lahf => "`lahf`",
                TokenType.Lea => "`lea`",
                TokenType.Leave => "`leave`",
                TokenType.Les => "`les`",
                TokenType.Lock => "`lock`",
                TokenType.Lods => "`lods`",
                TokenType.Lodsb => "`lodsb`",
                TokenType.Lodsw => "`lodsw`",
                TokenType.Loop => "`loop`",
                TokenType.Loope => "`loope`",
                TokenType.Loopne => "`loopne`",
                TokenType.Loopnz => "`loopnz`",
                TokenType.Loopz => "`loopz`",
                TokenType.Movs => "`movs`",
                TokenType.Movsb => "`movsb`",
                TokenType.Movsw => "`movsw`",
                TokenType.Not => "`not`",
                TokenType.Outs => "`outs`",
                TokenType.Outsb => "`outsb`",
                TokenType.Outsw => "`outsw`",
                TokenType.Popa => "`popa`",
                TokenType.Popf => "`popf`",
                TokenType.Pusha => "`pusha`",
                TokenType.Pushf => "`pushf`",
                TokenType.Rcl => "`rcl`",
                TokenType.Rcr => "`rcr`",
                TokenType.Repe => "`repe`",
                TokenType.Repne => "`repne`",
                TokenType.Repnz => "`repnz`",
                TokenType.Repz => "`repz`",
                TokenType.Retf => "`retf`",
                TokenType.Sahf => "`sahf`",
                TokenType.Sal => "`sal`",
                TokenType.Salc => "`salc`",
                TokenType.Sar => "`sar`",
                TokenType.Scas => "`scas`",
                TokenType.Scasb => "`scasb`",
                TokenType.Scasw => "`scasw`",
                TokenType.ShlMnem => "`shl`",
                TokenType.ShrMnem => "`shr`",
                TokenType.Sti => "`sti`",
                TokenType.Stos => "`stos`",
                TokenType.Stosb => "`stosb`",
                TokenType.Stosw => "`stosw`",
                TokenType.Test => "`test`",
                TokenType.Wait => "`wait`",
                TokenType.Xlat => "`xlat`",
                TokenType.Xlatb => "`xlatb`",
                _ => throw new ArgumentOutOfRangeException(nameof(tokenType), tokenType, null)
            };
        }
        
        public bool IsIntOperator()
        {
            return tokenType switch
            {
                TokenType.Percent or
                TokenType.Shl or 
                TokenType.Shr or 
                TokenType.Ashr or 
                TokenType.BitwiseAnd or 
                TokenType.Caret or 
                TokenType.BitwiseOr => true,
                _ => false
            };
        }

        public bool IsStringLiteral()
        {
            return tokenType switch
            {
                TokenType.AtaScreenStringLiteral or
                TokenType.CbmScreenStringLiteral or
                TokenType.InterpolationStart or 
                TokenType.InterpolationEnd or
                TokenType.StringLiteral or
                TokenType.PetsciiStringLiteral or
                TokenType.Utf8StringLiteral or 
                TokenType.Utf16StringLiteral or 
                TokenType.Utf32StringLiteral => true,
                _ => false
            };
        }

        public bool IsVarAssignment()
        {
            return tokenType switch
            {
                TokenType.ColonEq or 
                TokenType.EquKw or
                TokenType.GlobalKw or
                TokenType.OrEq or 
                TokenType.CaretEq or 
                TokenType.AndEq or 
                TokenType.AshrEq or 
                TokenType.ShrEq or 
                TokenType.ShlEq or 
                TokenType.PlusEq or 
                TokenType.MinusEq or 
                TokenType.StarEq or 
                TokenType.PercentEq or 
                TokenType.SlashEq => true,
                _ => false
            };
        }

        public bool IsAssignment() 
            => tokenType == TokenType.Eq || tokenType.IsVarAssignment();

        private bool IsExpression()
            => tokenType.IsIdent() || 
               tokenType.IsRegister() ||
               tokenType.IsStringLiteral() ||
               tokenType is 
                   TokenType.AltBinLiteral or
                   TokenType.CharLiteral or 
                   TokenType.False or 
                   TokenType.FloatLiteral or 
                   TokenType.IntLiteral or
                   TokenType.True;

        public bool BeginsExpression()
            => tokenType.IsExpression() ||
               tokenType is
                   TokenType.OpenBrace or
                   TokenType.OpenBracket or
                   TokenType.OpenParen;
        
        public bool EndsExpression()
            => tokenType.IsExpression() ||
                tokenType is
                   TokenType.CloseBrace or 
                   TokenType.CloseBracket or 
                   TokenType.CloseParen;
        
        public bool IsIdent() 
            => tokenType == TokenType.Ident || 
               tokenType.IsRegister() || 
               tokenType.IsI86PtrType() ||
               tokenType == TokenType.Ptr;

        public bool Is8087Opcode()
            => tokenType is >= TokenType.F2Xm1 and <= TokenType.Fyl2Xp1;
        
        public bool IsRegister() => tokenType is >= TokenType.A and <= TokenType.Z;

        public bool IsExtraDirective()
            => tokenType is >= TokenType.CaseKw and < TokenType.BincludeKw;
        
        public bool IsFieldType()
            => tokenType is TokenType.ByteKw or 
                TokenType.CharKw or 
                TokenType.DintKw or 
                TokenType.DoubleKw or
                TokenType.DwordKw or  
                TokenType.LintKw or 
                TokenType.LongKw or  
                TokenType.QwordKw or
                TokenType.ShortKw or 
                TokenType.SintKw or 
                TokenType.StringKw or 
                TokenType.TbyteKw or
                TokenType.WordKw;

        public bool IsI86Segment()
            => tokenType is TokenType.Cs or TokenType.Ds or TokenType.Es or TokenType.Ss;

        public bool IsI86Base()
            => tokenType is TokenType.Bx or TokenType.Bp;

        public bool IsI86Index()
            => tokenType is TokenType.Di or TokenType.Si;

        public bool IsI86PtrType()
            => tokenType is TokenType.Byte or 
                TokenType.Dword or 
                TokenType.Qword or
                TokenType.Tbyte or
                TokenType.Word;

        public bool IsStParenReg()
            => tokenType is >= TokenType.StParen0Reg and <= TokenType.StParen7Reg;

        public TokenType FromStParen()
            => tokenType switch
            {
                TokenType.StParen0Reg => TokenType.St0Reg,
                TokenType.StParen1Reg => TokenType.St1Reg,
                TokenType.StParen2Reg => TokenType.St2Reg,
                TokenType.StParen3Reg => TokenType.St3Reg,
                TokenType.StParen4Reg => TokenType.St4Reg,
                TokenType.StParen5Reg => TokenType.St5Reg,
                TokenType.StParen6Reg => TokenType.St6Reg,
                TokenType.StParen7Reg => TokenType.St7Reg,
                _ => tokenType
            };

        /*public FieldType ToFieldType()
            => tokenType switch
            {
                TokenType.ByteKw => FieldType.Byte,
                TokenType.CharKw => FieldType.Char,
                TokenType.DintKw => FieldType.Dint,
                TokenType.DoubleKw => FieldType.Float,
                TokenType.DwordKw => FieldType.Dword,
                TokenType.LintKw => FieldType.Lint,
                TokenType.LongKw => FieldType.Long,
                TokenType.QwordKw => FieldType.Qword,
                TokenType.ShortKw => FieldType.Short,
                TokenType.StringKw => FieldType.String,
                TokenType.TbyteKw => FieldType.Tbyte,
                TokenType.WordKw => FieldType.Word,
                _ => FieldType.Unknown
            };*/

        public int PtrSize()
            => tokenType switch
            {
                TokenType.Byte => 1,
                TokenType.Word => 2,
                TokenType.Dword => 4,
                TokenType.Qword => 8,
                TokenType.Tbyte => 10,
                _ => 0
            };
    }
}
