//-----------------------------------------------------------------------------
// Copyright (c) 2017-2021 informedcitizenry <informedcitizenry@gmail.com>
//
// Licensed under the MIT license. See LICENSE for full license information.
// 
//-----------------------------------------------------------------------------

using System.Collections.Generic;

namespace Core6502DotNet.m65xx
{
    /// <summary>
    /// A line assembler that will assemble into 6502 instructions.
    /// </summary>
    public sealed partial class Asm6502 : MotorolaBase
    {

        #region Members
    
        bool _m16, _x16;
        bool _autoOn;
        static readonly Dictionary<(string Mnem, Modes Mode), CpuInstruction> s_opcodes6502 = 
            new Dictionary<(string Mnem, Modes Mode), CpuInstruction>()
        {
            { ("brk", Modes.Implied     ), new CpuInstruction( "6502",    0x00) },
            { ("ora", Modes.IndX        ), new CpuInstruction( "6502",    0x01, 2) },
            { ("ora", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x05, 2) },
            { ("asl", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x06, 2) },
            { ("php", Modes.Implied     ), new CpuInstruction( "6502",    0x08) },
            { ("ora", Modes.Immediate   ), new CpuInstruction( "6502",    0x09, 2) },
            { ("asl", Modes.Implied     ), new CpuInstruction( "6502",    0x0a) },
            { ("ora", Modes.Absolute    ), new CpuInstruction( "6502",    0x0d, 3) },
            { ("asl", Modes.Absolute    ), new CpuInstruction( "6502",    0x0e, 3) },
            { ("bpl", Modes.Relative    ), new CpuInstruction( "6502",    0x10, 2) },
            { ("ora", Modes.IndY        ), new CpuInstruction( "6502",    0x11, 2) },
            { ("ora", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x15, 2) },
            { ("asl", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x16, 2) },
            { ("clc", Modes.Implied     ), new CpuInstruction( "6502",    0x18) },
            { ("ora", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0x19, 3) },
            { ("ora", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x1d, 3) },
            { ("asl", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x1e, 3) },
            { ("jsr", Modes.Absolute    ), new CpuInstruction( "6502",    0x20, 3) },
            { ("and", Modes.IndX        ), new CpuInstruction( "6502",    0x21, 2) },
            { ("bit", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x24, 2) },
            { ("and", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x25, 2) },
            { ("rol", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x26, 2) },
            { ("plp", Modes.Implied     ), new CpuInstruction( "6502",    0x28) },
            { ("and", Modes.Immediate   ), new CpuInstruction( "6502",    0x29, 2) },
            { ("rol", Modes.Implied     ), new CpuInstruction( "6502",    0x2a) },
            { ("bit", Modes.Absolute    ), new CpuInstruction( "6502",    0x2c, 3) },
            { ("and", Modes.Absolute    ), new CpuInstruction( "6502",    0x2d, 3) },
            { ("rol", Modes.Absolute    ), new CpuInstruction( "6502",    0x2e, 3) },
            { ("bmi", Modes.Relative    ), new CpuInstruction( "6502",    0x30, 2) },
            { ("and", Modes.IndY        ), new CpuInstruction( "6502",    0x31, 2) },
            { ("and", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x35, 2) },
            { ("rol", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x36, 2) },
            { ("sec", Modes.Implied     ), new CpuInstruction( "6502",    0x38) },
            { ("and", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0x39, 3) },
            { ("and", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x3d, 3) },
            { ("rol", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x3e, 3) },
            { ("rti", Modes.Implied     ), new CpuInstruction( "6502",    0x40) },
            { ("eor", Modes.IndX        ), new CpuInstruction( "6502",    0x41, 2) },
            { ("eor", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x45, 2) },
            { ("lsr", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x46, 2) },
            { ("pha", Modes.Implied     ), new CpuInstruction( "6502",    0x48) },
            { ("eor", Modes.Immediate   ), new CpuInstruction( "6502",    0x49, 2) },
            { ("lsr", Modes.Implied     ), new CpuInstruction( "6502",    0x4a) },
            { ("jmp", Modes.Absolute    ), new CpuInstruction( "6502",    0x4c, 3) },
            { ("eor", Modes.Absolute    ), new CpuInstruction( "6502",    0x4d, 3) },
            { ("lsr", Modes.Absolute    ), new CpuInstruction( "6502",    0x4e, 3) },
            { ("bvc", Modes.Relative    ), new CpuInstruction( "6502",    0x50, 2) },
            { ("eor", Modes.IndY        ), new CpuInstruction( "6502",    0x51, 2) },
            { ("eor", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x55, 2) },
            { ("lsr", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x56, 2) },
            { ("cli", Modes.Implied     ), new CpuInstruction( "6502",    0x58) },
            { ("eor", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0x59, 3) },
            { ("eor", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x5d, 3) },
            { ("lsr", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x5e, 3) },
            { ("rts", Modes.Implied     ), new CpuInstruction( "6502",    0x60) },
            { ("adc", Modes.IndX        ), new CpuInstruction( "6502",    0x61, 2) },
            { ("adc", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x65, 2) },
            { ("ror", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x66, 2) },
            { ("pla", Modes.Implied     ), new CpuInstruction( "6502",    0x68) },
            { ("adc", Modes.Immediate   ), new CpuInstruction( "6502",    0x69, 2) },
            { ("ror", Modes.Implied     ), new CpuInstruction( "6502",    0x6a) },
            { ("jmp", Modes.IndAbs      ), new CpuInstruction( "6502",    0x6c, 3) },
            { ("adc", Modes.Absolute    ), new CpuInstruction( "6502",    0x6d, 3) },
            { ("ror", Modes.Absolute    ), new CpuInstruction( "6502",    0x6e, 3) },
            { ("bvs", Modes.Relative    ), new CpuInstruction( "6502",    0x70, 2) },
            { ("adc", Modes.IndY        ), new CpuInstruction( "6502",    0x71, 2) },
            { ("adc", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x75, 2) },
            { ("ror", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x76, 2) },
            { ("sei", Modes.Implied     ), new CpuInstruction( "6502",    0x78) },
            { ("adc", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0x79, 3) },
            { ("adc", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x7d, 3) },
            { ("ror", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x7e, 3) },
            { ("sta", Modes.IndX        ), new CpuInstruction( "6502",    0x81, 2) },
            { ("sty", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x84, 2) },
            { ("sta", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x85, 2) },
            { ("stx", Modes.ZeroPage    ), new CpuInstruction( "6502",    0x86, 2) },
            { ("dey", Modes.Implied     ), new CpuInstruction( "6502",    0x88) },
            { ("txa", Modes.Implied     ), new CpuInstruction( "6502",    0x8a) },
            { ("sty", Modes.Absolute    ), new CpuInstruction( "6502",    0x8c, 3) },
            { ("sta", Modes.Absolute    ), new CpuInstruction( "6502",    0x8d, 3) },
            { ("stx", Modes.Absolute    ), new CpuInstruction( "6502",    0x8e, 3) },
            { ("bcc", Modes.Relative    ), new CpuInstruction( "6502",    0x90, 2) },
            { ("sta", Modes.IndY        ), new CpuInstruction( "6502",    0x91, 2) },
            { ("sty", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x94, 2) },
            { ("sta", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0x95, 2) },
            { ("stx", Modes.ZeroPageY   ), new CpuInstruction( "6502",    0x96, 2) },
            { ("tya", Modes.Implied     ), new CpuInstruction( "6502",    0x98) },
            { ("sta", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0x99, 3) },
            { ("txs", Modes.Implied     ), new CpuInstruction( "6502",    0x9a) },
            { ("sta", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0x9d, 3) },
            { ("ldy", Modes.Immediate   ), new CpuInstruction( "6502",    0xa0, 2) },
            { ("lda", Modes.IndX        ), new CpuInstruction( "6502",    0xa1, 2) },
            { ("ldx", Modes.Immediate   ), new CpuInstruction( "6502",    0xa2, 2) },
            { ("ldy", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xa4, 2) },
            { ("lda", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xa5, 2) },
            { ("ldx", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xa6, 2) },
            { ("tay", Modes.Implied     ), new CpuInstruction( "6502",    0xa8) },
            { ("lda", Modes.Immediate   ), new CpuInstruction( "6502",    0xa9, 2) },
            { ("tax", Modes.Implied     ), new CpuInstruction( "6502",    0xaa) },
            { ("ldy", Modes.Absolute    ), new CpuInstruction( "6502",    0xac, 3) },
            { ("lda", Modes.Absolute    ), new CpuInstruction( "6502",    0xad, 3) },
            { ("ldx", Modes.Absolute    ), new CpuInstruction( "6502",    0xae, 3) },
            { ("bcs", Modes.Relative    ), new CpuInstruction( "6502",    0xb0, 2) },
            { ("lda", Modes.IndY        ), new CpuInstruction( "6502",    0xb1, 2) },
            { ("ldy", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0xb4, 2) },
            { ("lda", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0xb5, 2) },
            { ("ldx", Modes.ZeroPageY   ), new CpuInstruction( "6502",    0xb6, 2) },
            { ("clv", Modes.Implied     ), new CpuInstruction( "6502",    0xb8) },
            { ("lda", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0xb9, 3) },
            { ("tsx", Modes.Implied     ), new CpuInstruction( "6502",    0xba) },
            { ("ldy", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0xbc, 3) },
            { ("lda", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0xbd, 3) },
            { ("ldx", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0xbe, 3) },
            { ("cpy", Modes.Immediate   ), new CpuInstruction( "6502",    0xc0, 2) },
            { ("cmp", Modes.IndX        ), new CpuInstruction( "6502",    0xc1, 2) },
            { ("cpy", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xc4, 2) },
            { ("cmp", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xc5, 2) },
            { ("dec", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xc6, 2) },
            { ("iny", Modes.Implied     ), new CpuInstruction( "6502",    0xc8) },
            { ("cmp", Modes.Immediate   ), new CpuInstruction( "6502",    0xc9, 2) },
            { ("dex", Modes.Implied     ), new CpuInstruction( "6502",    0xca) },
            { ("cpy", Modes.Absolute    ), new CpuInstruction( "6502",    0xcc, 3) },
            { ("cmp", Modes.Absolute    ), new CpuInstruction( "6502",    0xcd, 3) },
            { ("dec", Modes.Absolute    ), new CpuInstruction( "6502",    0xce, 3) },
            { ("bne", Modes.Relative    ), new CpuInstruction( "6502",    0xd0, 2) },
            { ("cmp", Modes.IndY        ), new CpuInstruction( "6502",    0xd1, 2) },
            { ("cmp", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0xd5, 2) },
            { ("dec", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0xd6, 2) },
            { ("cld", Modes.Implied     ), new CpuInstruction( "6502",    0xd8) },
            { ("cmp", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0xd9, 3) },
            { ("cmp", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0xdd, 3) },
            { ("dec", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0xde, 3) },
            { ("cpx", Modes.Immediate   ), new CpuInstruction( "6502",    0xe0, 2) },
            { ("sbc", Modes.IndX        ), new CpuInstruction( "6502",    0xe1, 2) },
            { ("cpx", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xe4, 2) },
            { ("sbc", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xe5, 2) },
            { ("inc", Modes.ZeroPage    ), new CpuInstruction( "6502",    0xe6, 2) },
            { ("inx", Modes.Implied     ), new CpuInstruction( "6502",    0xe8) },
            { ("sbc", Modes.Immediate   ), new CpuInstruction( "6502",    0xe9, 2) },
            { ("nop", Modes.Implied     ), new CpuInstruction( "6502",    0xea) },
            { ("cpx", Modes.Absolute    ), new CpuInstruction( "6502",    0xec, 3) },
            { ("sbc", Modes.Absolute    ), new CpuInstruction( "6502",    0xed, 3) },
            { ("inc", Modes.Absolute    ), new CpuInstruction( "6502",    0xee, 3) },
            { ("beq", Modes.Relative    ), new CpuInstruction( "6502",    0xf0, 2) },
            { ("sbc", Modes.IndY        ), new CpuInstruction( "6502",    0xf1, 2) },
            { ("sbc", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0xf5, 2) },
            { ("inc", Modes.ZeroPageX   ), new CpuInstruction( "6502",    0xf6, 2) },
            { ("sed", Modes.Implied     ), new CpuInstruction( "6502",    0xf8) },
            { ("sbc", Modes.AbsoluteY   ), new CpuInstruction( "6502",    0xf9, 3) },
            { ("sbc", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0xfd, 3) },
            { ("inc", Modes.AbsoluteX   ), new CpuInstruction( "6502",    0xfe, 3) },
        };
        static readonly Dictionary<(string Mnem, Modes Mode), CpuInstruction> s_opcodes65C02 = 
            new Dictionary<(string Mnem, Modes Mode), CpuInstruction>()
        {
            { ("tsb", Modes.ZeroPage    ), new CpuInstruction( "65C02",   0x04, 2) },
            { ("tsb", Modes.Absolute    ), new CpuInstruction( "65C02",   0x0c, 3) },
            { ("ora", Modes.IndZp       ), new CpuInstruction( "65C02",   0x12, 2) },
            { ("trb", Modes.ZeroPage    ), new CpuInstruction( "65C02",   0x14, 2) },
            { ("inc", Modes.Implied     ), new CpuInstruction( "65C02",   0x1a) },
            { ("trb", Modes.Absolute    ), new CpuInstruction( "65C02",   0x1c, 3) },
            { ("and", Modes.IndZp       ), new CpuInstruction( "65C02",   0x32, 2) },
            { ("bit", Modes.ZeroPageX   ), new CpuInstruction( "65C02",   0x34, 2) },
            { ("dec", Modes.Implied     ), new CpuInstruction( "65C02",   0x3a) },
            { ("bit", Modes.AbsoluteX   ), new CpuInstruction( "65C02",   0x3c, 3) },
            { ("eor", Modes.IndZp       ), new CpuInstruction( "65C02",   0x52, 2) },
            { ("phy", Modes.Implied     ), new CpuInstruction( "65C02",   0x5a) },
            { ("stz", Modes.ZeroPage    ), new CpuInstruction( "65C02",   0x64, 2) },
            { ("adc", Modes.IndZp       ), new CpuInstruction( "65C02",   0x72, 2) },
            { ("stz", Modes.ZeroPageX   ), new CpuInstruction( "65C02",   0x74, 2) },
            { ("ply", Modes.Implied     ), new CpuInstruction( "65C02",   0x7a) },
            { ("jmp", Modes.IndAbsX     ), new CpuInstruction( "65C02",   0x7c, 3) },
            { ("bra", Modes.Relative    ), new CpuInstruction( "65C02",   0x80, 2) },
            { ("bit", Modes.Immediate   ), new CpuInstruction( "65C02",   0x89, 2) },
            { ("sta", Modes.IndZp       ), new CpuInstruction( "65C02",   0x92, 2) },
            { ("stz", Modes.Absolute    ), new CpuInstruction( "65C02",   0x9c, 3) },
            { ("stz", Modes.AbsoluteX   ), new CpuInstruction( "65C02",   0x9e, 3) },
            { ("lda", Modes.IndZp       ), new CpuInstruction( "65C02",   0xb2, 2) },
            { ("cmp", Modes.IndZp       ), new CpuInstruction( "65C02",   0xd2, 2) },
            { ("phx", Modes.Implied     ), new CpuInstruction( "65C02",   0xda) },
            { ("sbc", Modes.IndZp       ), new CpuInstruction( "65C02",   0xf2, 2) },
            { ("plx", Modes.Implied     ), new CpuInstruction( "65C02",   0xfa) },
        };
        static readonly Dictionary<(string Mnem, Modes Mode), CpuInstruction> s_opcodesW65C02 = 
            new Dictionary<(string Mnem, Modes Mode), CpuInstruction>()
        {
            { ("wai", Modes.Implied     ), new CpuInstruction( "W65C02",  0xcb) },
            { ("stp", Modes.Implied     ), new CpuInstruction( "W65C02",  0xdb) }
        };
        static readonly Dictionary<(string Mnem, Modes Mode), CpuInstruction> s_opcodesR65C02 = 
            new Dictionary<(string Mnem, Modes Mode), CpuInstruction>()
        {
            { ("rmb", Modes.Zp0         ), new CpuInstruction( "R65C02",  0x07, 2) },
            { ("bbr", Modes.ThreeOpRel0 ), new CpuInstruction( "R65C02",  0x0f, 3) },
            { ("rmb", Modes.Zp1         ), new CpuInstruction( "R65C02",  0x17, 2) },
            { ("bbr", Modes.ThreeOpRel1 ), new CpuInstruction( "R65C02",  0x1f, 3) },
            { ("rmb", Modes.Zp2         ), new CpuInstruction( "R65C02",  0x27, 2) },
            { ("bbr", Modes.ThreeOpRel2 ), new CpuInstruction( "R65C02",  0x2f, 3) },
            { ("rmb", Modes.Zp3         ), new CpuInstruction( "R65C02",  0x37, 2) },
            { ("bbr", Modes.ThreeOpRel3 ), new CpuInstruction( "R65C02",  0x3f, 3) },
            { ("rmb", Modes.Zp4         ), new CpuInstruction( "R65C02",  0x47, 2) },
            { ("bbr", Modes.ThreeOpRel4 ), new CpuInstruction( "R65C02",  0x4f, 3) },
            { ("rmb", Modes.Zp5         ), new CpuInstruction( "R65C02",  0x57, 2) },
            { ("bbr", Modes.ThreeOpRel5 ), new CpuInstruction( "R65C02",  0x5f, 3) },
            { ("rmb", Modes.Zp6         ), new CpuInstruction( "R65C02",  0x67, 2) },
            { ("bbr", Modes.ThreeOpRel6 ), new CpuInstruction( "R65C02",  0x6f, 3) },
            { ("rmb", Modes.Zp7         ), new CpuInstruction( "R65C02",  0x77, 2) },
            { ("bbr", Modes.ThreeOpRel7 ), new CpuInstruction( "R65C02",  0x7f, 3) },
            { ("smb", Modes.Zp0         ), new CpuInstruction( "R65C02",  0x87, 2) },
            { ("bbs", Modes.ThreeOpRel0 ), new CpuInstruction( "R65C02",  0x8f, 3) },
            { ("smb", Modes.Zp1         ), new CpuInstruction( "R65C02",  0x97, 2) },
            { ("bbs", Modes.ThreeOpRel1 ), new CpuInstruction( "R65C02",  0x9f, 3) },
            { ("smb", Modes.Zp2         ), new CpuInstruction( "R65C02",  0xa7, 2) },
            { ("bbs", Modes.ThreeOpRel2 ), new CpuInstruction( "R65C02",  0xaf, 3) },
            { ("smb", Modes.Zp3         ), new CpuInstruction( "R65C02",  0xb7, 2) },
            { ("bbs", Modes.ThreeOpRel3 ), new CpuInstruction( "R65C02",  0xbf, 3) },
            { ("smb", Modes.Zp4         ), new CpuInstruction( "R65C02",  0xc7, 2) },
            { ("bbs", Modes.ThreeOpRel4 ), new CpuInstruction( "R65C02",  0xcf, 3) },
            { ("smb", Modes.Zp5         ), new CpuInstruction( "R65C02",  0xd7, 2) },
            { ("bbs", Modes.ThreeOpRel5 ), new CpuInstruction( "R65C02",  0xdf, 3) },
            { ("smb", Modes.Zp6         ), new CpuInstruction( "R65C02",  0xe7, 2) },
            { ("bbs", Modes.ThreeOpRel6 ), new CpuInstruction( "R65C02",  0xef, 3) },
            { ("smb", Modes.Zp7         ), new CpuInstruction( "R65C02",  0xf7, 2) },
            { ("bbs", Modes.ThreeOpRel7 ), new CpuInstruction( "R65C02",  0xff, 3) },
        };
        static readonly Dictionary<(string Mnem, Modes Mode), CpuInstruction> s_opcodesHuC6280 = 
            new Dictionary<(string Mnem, Modes Mode), CpuInstruction>()
        {
            { ("sxy", Modes.Implied     ), new CpuInstruction( "HuC6280", 0x03) },
            { ("ora", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0x12, 3) },
            { ("st1", Modes.Immediate   ), new CpuInstruction( "HuC6280", 0x13, 2) },
            { ("sax", Modes.Implied     ), new CpuInstruction( "HuC6280", 0x23) },
            { ("st2", Modes.Immediate   ), new CpuInstruction( "HuC6280", 0x23, 2) },
            { ("and", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0x32, 3) },
            { ("say", Modes.Implied     ), new CpuInstruction( "HuC6280", 0x43) },
            { ("tma", Modes.Immediate   ), new CpuInstruction( "HuC6280", 0x43, 2) },
            { ("eor", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0x52, 3) },
            { ("tam", Modes.Immediate   ), new CpuInstruction( "HuC6280", 0x53, 2) },
            { ("csl", Modes.Implied     ), new CpuInstruction( "HuC6280", 0x54) },
            { ("cla", Modes.Implied     ), new CpuInstruction( "HuC6280", 0x62) },
            { ("adc", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0x72, 3) },
            { ("tii", Modes.ThreeOpAbs  ), new CpuInstruction( "HuC6280", 0x73, 7) },
            { ("clx", Modes.Implied     ), new CpuInstruction( "HuC6280", 0x82) },
            { ("tst", Modes.TestBitZp   ), new CpuInstruction( "HuC6280", 0x83, 3) },
            { ("sta", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0x92, 3) },
            { ("tst", Modes.TestBitZpX  ), new CpuInstruction( "HuC6280", 0x93, 3) },
            { ("tst", Modes.TestBitAbs  ), new CpuInstruction( "HuC6280", 0xa3, 4) },
            { ("lda", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0xb2, 3) },
            { ("tst", Modes.TestBitAbsX ), new CpuInstruction( "HuC6280", 0xb3, 4) },
            { ("cly", Modes.Implied     ), new CpuInstruction( "HuC6280", 0xc2) },
            { ("tdd", Modes.ThreeOpAbs  ), new CpuInstruction( "HuC6280", 0xc3, 7) },
            { ("cmp", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0xd2, 3) },
            { ("tin", Modes.ThreeOpAbs  ), new CpuInstruction( "HuC6280", 0xd3, 7) },
            { ("csh", Modes.Implied     ), new CpuInstruction( "HuC6280", 0xd4) },
            { ("tia", Modes.ThreeOpAbs  ), new CpuInstruction( "HuC6280", 0xe3, 7) },
            { ("sbc", Modes.IndAbs      ), new CpuInstruction( "HuC6280", 0xf2, 3) },
            { ("tai", Modes.ThreeOpAbs  ), new CpuInstruction( "HuC6280", 0xf3, 7) },
            { ("set", Modes.Implied     ), new CpuInstruction( "HuC6280", 0xf4) }
        };
        static readonly Dictionary<(string Mnem, Modes Mode), CpuInstruction> s_opcodes65CE02 = 
            new Dictionary<(string Mnem, Modes Mode), CpuInstruction>()
        {
            { ("cle", Modes.Implied     ), new CpuInstruction( "65CE02",  0x02) },
            { ("see", Modes.Implied     ), new CpuInstruction( "65CE02",  0x03) },
            { ("tsy", Modes.Implied     ), new CpuInstruction( "65CE02",  0x0b) },
            { ("ora", Modes.IndZ        ), new CpuInstruction( "65CE02",  0x12, 2) },
            { ("bpl", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0x13, 3) },
            { ("inz", Modes.Implied     ), new CpuInstruction( "65CE02",  0x1b) },
            { ("jsr", Modes.IndAbs      ), new CpuInstruction( "65CE02",  0x22, 3) },
            { ("jsr", Modes.IndAbsX     ), new CpuInstruction( "65CE02",  0x23, 3) },
            { ("tys", Modes.Implied     ), new CpuInstruction( "65CE02",  0x2b) },
            { ("and", Modes.IndZ        ), new CpuInstruction( "65CE02",  0x32, 2) },
            { ("bmi", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0x33, 3) },
            { ("dez", Modes.Implied     ), new CpuInstruction( "65CE02",  0x3b) },
            { ("neg", Modes.Implied     ), new CpuInstruction( "65CE02",  0x42) },
            { ("asr", Modes.Implied     ), new CpuInstruction( "65CE02",  0x43) },
            { ("asr", Modes.ZeroPage    ), new CpuInstruction( "65CE02",  0x44, 2) },
            { ("taz", Modes.Implied     ), new CpuInstruction( "65CE02",  0x4b) },
            { ("eor", Modes.IndZ        ), new CpuInstruction( "65CE02",  0x52, 2) },
            { ("bvc", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0x53, 3) },
            { ("asr", Modes.ZeroPageX   ), new CpuInstruction( "65CE02",  0x54, 2) },
            { ("tab", Modes.Implied     ), new CpuInstruction( "65CE02",  0x5b) },
            { ("rts", Modes.Immediate   ), new CpuInstruction( "65CE02",  0x62, 2) },
            { ("rtn", Modes.Implied     ), new CpuInstruction( "65CE02",  0x63) },
            { ("bsr", Modes.Absolute    ), new CpuInstruction( "65CE02",  0x63, 3) },
            { ("tza", Modes.Implied     ), new CpuInstruction( "65CE02",  0x6b) },
            { ("adc", Modes.IndZ        ), new CpuInstruction( "65CE02",  0x72, 2) },
            { ("bvs", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0x73, 3) },
            { ("tba", Modes.Implied     ), new CpuInstruction( "65CE02",  0x7b) },
            { ("sta", Modes.IndSp       ), new CpuInstruction( "65CE02",  0x82, 2) },
            { ("bra", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0x83, 3) },
            { ("sty", Modes.AbsoluteX   ), new CpuInstruction( "65CE02",  0x8b, 3) },
            { ("sta", Modes.IndZ        ), new CpuInstruction( "65CE02",  0x92, 2) },
            { ("bcc", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0x93, 3) },
            { ("blt", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0x93, 3) },
            { ("stx", Modes.AbsoluteY   ), new CpuInstruction( "65CE02",  0x9b, 3) },
            { ("ldz", Modes.Immediate   ), new CpuInstruction( "65CE02",  0xa3, 2) },
            { ("ldz", Modes.Absolute    ), new CpuInstruction( "65CE02",  0xab, 3) },
            { ("lda", Modes.IndZ        ), new CpuInstruction( "65CE02",  0xb2, 2) },
            { ("bcs", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0xb3, 3) },
            { ("bge", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0xb3, 3) },
            { ("ldz", Modes.AbsoluteX   ), new CpuInstruction( "65CE02",  0xbb, 3) },
            { ("cpz", Modes.Immediate   ), new CpuInstruction( "65CE02",  0xc2, 2) },
            { ("dew", Modes.ZeroPage    ), new CpuInstruction( "65CE02",  0xc3, 2) },
            { ("asw", Modes.Absolute    ), new CpuInstruction( "65CE02",  0xcb, 3) },
            { ("cmp", Modes.IndZ        ), new CpuInstruction( "65CE02",  0xd2, 2) },
            { ("bne", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0xd3, 3) },
            { ("cpz", Modes.ZeroPage    ), new CpuInstruction( "65CE02",  0xd4, 2) },
            { ("phz", Modes.Implied     ), new CpuInstruction( "65CE02",  0xdb) },
            { ("cpz", Modes.Absolute    ), new CpuInstruction( "65CE02",  0xdc, 3) },
            { ("lda", Modes.IndSp       ), new CpuInstruction( "65CE02",  0xe2, 2) },
            { ("inw", Modes.Absolute    ), new CpuInstruction( "65CE02",  0xe3, 3) },
            { ("row", Modes.Absolute    ), new CpuInstruction( "65CE02",  0xeb, 3) },
            { ("sbc", Modes.IndZ        ), new CpuInstruction( "65CE02",  0xf2, 2) },
            { ("beq", Modes.RelativeAbs ), new CpuInstruction( "65CE02",  0xf3, 3) },
            { ("phw", Modes.ImmAbs      ), new CpuInstruction( "65CE02",  0xf4, 3) },
            { ("plz", Modes.Implied     ), new CpuInstruction( "65CE02",  0xfb) },
            { ("phw", Modes.Absolute    ), new CpuInstruction( "65CE02",  0xfc, 3) }
        };
        static readonly Dictionary<(string Mnem, Modes Mode), CpuInstruction> s_opcodes45GS02 =
            new Dictionary<(string Mnem, Modes Mode), CpuInstruction>()
        {
            { ("map", Modes.Implied     ), new CpuInstruction( "45GS02",    0x5c) },
            { ("eom", Modes.Implied     ), new CpuInstruction( "45GS02",    0xea) }
        };
        static readonly Dictionary<(string Mnem, Modes Mode), CpuInstruction> s_opcodesm65 =
            new Dictionary<(string Mnem, Modes Mode), CpuInstruction>()
        {
            { ("ora",  Modes.DirZ       ), new CpuInstruction( "m65",  0x12ea,     3) },
            { ("and",  Modes.DirZ       ), new CpuInstruction( "m65",  0x32ea,     3) },
            { ("eor",  Modes.DirZ       ), new CpuInstruction( "m65",  0x52ea,     3) },
            { ("adc",  Modes.DirZ       ), new CpuInstruction( "m65",  0x72ea,     3) },
            { ("sta",  Modes.DirZ       ), new CpuInstruction( "m65",  0x92ea,     3) },
            { ("lda",  Modes.DirZ       ), new CpuInstruction( "m65",  0xb2ea,     3) },
            { ("cmp",  Modes.DirZ       ), new CpuInstruction( "m65",  0xd2ea,     3) },
            { ("sbc",  Modes.DirZ       ), new CpuInstruction( "m65",  0xf2ea,     3) },
            { ("orq",  Modes.ZeroPage   ), new CpuInstruction( "m65",  0x054242,   4) },
            { ("aslq", Modes.ZeroPage   ), new CpuInstruction( "m65",  0x064242,   4) },
            { ("aslq", Modes.Implied    ), new CpuInstruction( "m65",  0x0a4242,   3) },
            { ("orq",  Modes.Absolute   ), new CpuInstruction( "m65",  0x0d4242,   5) },
            { ("aslq", Modes.Absolute   ), new CpuInstruction( "m65",  0x0f4242,   5) },
            { ("orq",  Modes.IndZp      ), new CpuInstruction( "m65",  0x124242,   4) },
            { ("aslq", Modes.ZeroPageX  ), new CpuInstruction( "m65",  0x164242,   4) },
            { ("inq",  Modes.Implied    ), new CpuInstruction( "m65",  0x1a4242,   3) },
            { ("aslq", Modes.AbsoluteX  ), new CpuInstruction( "m65",  0x1e4242,   5) },
            { ("bitq", Modes.ZeroPage   ), new CpuInstruction( "m65",  0x244242,   4) },
            { ("andq", Modes.ZeroPage   ), new CpuInstruction( "m65",  0x254242,   4) },
            { ("rolq", Modes.ZeroPage   ), new CpuInstruction( "m65",  0x264242,   4) },
            { ("rolq", Modes.Implied    ), new CpuInstruction( "m65",  0x2a4242,   3) },
            { ("bitq", Modes.Absolute   ), new CpuInstruction( "m65",  0x2c4242,   5) },
            { ("andq", Modes.Absolute   ), new CpuInstruction( "m65",  0x2d4242,   5) },
            { ("rolq", Modes.Absolute   ), new CpuInstruction( "m65",  0x2e4242,   5) },
            { ("andq", Modes.IndZp      ), new CpuInstruction( "m65",  0x324242,   4) },
            { ("deq",  Modes.Implied    ), new CpuInstruction( "m65",  0x3a4242,   3) },
            { ("rolq", Modes.AbsoluteX  ), new CpuInstruction( "m65",  0x3e4242,   5) },
            { ("asrq", Modes.Implied    ), new CpuInstruction( "m65",  0x434242,   3) },
            { ("asrq", Modes.ZeroPage   ), new CpuInstruction( "m65",  0x444242,   4) },
            { ("eorq", Modes.ZeroPage   ), new CpuInstruction( "m65",  0x454242,   4) },
            { ("lsrq", Modes.ZeroPage   ), new CpuInstruction( "m65",  0x464242,   4) },
            { ("lsrq", Modes.Implied    ), new CpuInstruction( "m65",  0x4a4242,   3) },
            { ("eorq", Modes.Absolute   ), new CpuInstruction( "m65",  0x4d4242,   5) },
            { ("lsrq", Modes.Absolute   ), new CpuInstruction( "m65",  0x4e4242,   5) },
            { ("eorq", Modes.IndZp      ), new CpuInstruction( "m65",  0x524242,   4) },
            { ("asrq", Modes.ZeroPageX  ), new CpuInstruction( "m65",  0x544242,   4) },
            { ("lsrq", Modes.ZeroPageX  ), new CpuInstruction( "m65",  0x564242,   4) },
            { ("lsrq", Modes.AbsoluteX  ), new CpuInstruction( "m65",  0x5e4242,   5) },
            { ("adcq", Modes.ZeroPage   ), new CpuInstruction( "m65",  0x654242,   4) },
            { ("rorq", Modes.ZeroPage   ), new CpuInstruction( "m65",  0x664242,   4) },
            { ("rorq", Modes.Implied    ), new CpuInstruction( "m65",  0x6a4242,   3) },
            { ("adcq", Modes.Absolute   ), new CpuInstruction( "m65",  0x6d4242,   5) },
            { ("rorq", Modes.Absolute   ), new CpuInstruction( "m65",  0x6e4242,   5) },
            { ("adcq", Modes.IndZp      ), new CpuInstruction( "m65",  0x724242,   4) },
            { ("rorq", Modes.ZeroPageX  ), new CpuInstruction( "m65",  0x764242,   4) },
            { ("rorq", Modes.AbsoluteX  ), new CpuInstruction( "m65",  0x7e4242,   5) },
            { ("stq",  Modes.ZeroPage   ), new CpuInstruction( "m65",  0x854242,   4) },
            { ("stq",  Modes.Absolute   ), new CpuInstruction( "m65",  0x8d4242,   5) },
            { ("stq",  Modes.IndZp      ), new CpuInstruction( "m65",  0x924242,   4) },
            { ("ldq",  Modes.ZeroPage   ), new CpuInstruction( "m65",  0xa54242,   4) },
            { ("ldq",  Modes.Absolute   ), new CpuInstruction( "m65",  0xad4242,   5) },
            { ("ldq",  Modes.IndY       ), new CpuInstruction( "m65",  0xb14242,   4) },
            { ("ldq",  Modes.IndZp      ), new CpuInstruction( "m65",  0xb24242,   4) },
            { ("ldq",  Modes.ZeroPageX  ), new CpuInstruction( "m65",  0xb54242,   4) },
            { ("ldq",  Modes.AbsoluteY  ), new CpuInstruction( "m65",  0xb94242,   5) },
            { ("ldq",  Modes.AbsoluteX  ), new CpuInstruction( "m65",  0xbd4242,   5) },
            { ("cpq",  Modes.ZeroPage   ), new CpuInstruction( "m65",  0xc54242,   4) },
            { ("deq",  Modes.ZeroPage   ), new CpuInstruction( "m65",  0xc64242,   4) },
            { ("cpq",  Modes.Absolute   ), new CpuInstruction( "m65",  0xcd4242,   5) },
            { ("deq",  Modes.Absolute   ), new CpuInstruction( "m65",  0xce4242,   5) },
            { ("cpq",  Modes.IndZp      ), new CpuInstruction( "m65",  0xd24242,   4) },
            { ("deq",  Modes.ZeroPageX  ), new CpuInstruction( "m65",  0xd64242,   4) },
            { ("deq",  Modes.AbsoluteX  ), new CpuInstruction( "m65",  0xde4242,   5) },
            { ("ldq",  Modes.IndS       ), new CpuInstruction( "m65",  0xe24242,   4) },
            { ("sbcq", Modes.ZeroPage   ), new CpuInstruction( "m65",  0xe54242,   4) },
            { ("inq",  Modes.ZeroPage   ), new CpuInstruction( "m65",  0xe64242,   4) },
            { ("sbcq", Modes.Absolute   ), new CpuInstruction( "m65",  0xed4242,   5) },
            { ("inq",  Modes.Absolute   ), new CpuInstruction( "m65",  0xee4242,   5) },
            { ("sbcq", Modes.IndZp      ), new CpuInstruction( "m65",  0xf24242,   4) },
            { ("inq",  Modes.ZeroPageX  ), new CpuInstruction( "m65",  0xf64242,   4) },
            { ("inq",  Modes.AbsoluteX  ), new CpuInstruction( "m65",  0xfe4242,   5) },
            { ("orq",  Modes.Dir        ), new CpuInstruction( "m65",  0x12ea4242, 5) },
            { ("andq", Modes.Dir        ), new CpuInstruction( "m65",  0x32ea4242, 5) },
            { ("eorq", Modes.Dir        ), new CpuInstruction( "m65",  0x52ea4242, 5) },
            { ("adcq", Modes.Dir        ), new CpuInstruction( "m65",  0x72ea4242, 5) },
            { ("stq",  Modes.Dir        ), new CpuInstruction( "m65",  0x92ea4242, 5) },
            { ("ldq",  Modes.Dir        ), new CpuInstruction( "m65",  0xb2ea4242, 5) },
            { ("cpq",  Modes.Dir        ), new CpuInstruction( "m65",  0xd2ea4242, 5) },
            { ("sbcq", Modes.Dir        ), new CpuInstruction( "m65",  0xf2ea4242, 5) }
        };
        static readonly Dictionary<(string Mnem, Modes Mode), CpuInstruction> s_opcodes65816 = 
            new Dictionary<(string Mnem, Modes Mode), CpuInstruction>()
        {
            { ("cop", Modes.Immediate   ), new CpuInstruction( "65816",   0x02, 2) },
            { ("ora", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0x03, 2) },
            { ("ora", Modes.Dir         ), new CpuInstruction( "65816",   0x07, 2) },
            { ("phd", Modes.Implied     ), new CpuInstruction( "65816",   0x0b) },
            { ("ora", Modes.Long        ), new CpuInstruction( "65816",   0x0f, 4) },
            { ("ora", Modes.IndS        ), new CpuInstruction( "65816",   0x13, 2) },
            { ("ora", Modes.DirY        ), new CpuInstruction( "65816",   0x17, 2) },
            { ("tcs", Modes.Implied     ), new CpuInstruction( "65816",   0x1b) },
            { ("ora", Modes.LongX       ), new CpuInstruction( "65816",   0x1f, 4) },
            { ("jsl", Modes.Long        ), new CpuInstruction( "65816",   0x22, 4) },
            { ("jsr", Modes.Long        ), new CpuInstruction( "65816",   0x22, 4) },
            { ("and", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0x23, 2) },
            { ("and", Modes.Dir         ), new CpuInstruction( "65816",   0x27, 2) },
            { ("pld", Modes.Implied     ), new CpuInstruction( "65816",   0x2b) },
            { ("and", Modes.Long        ), new CpuInstruction( "65816",   0x2f, 4) },
            { ("and", Modes.IndS        ), new CpuInstruction( "65816",   0x33, 2) },
            { ("and", Modes.DirY        ), new CpuInstruction( "65816",   0x37, 2) },
            { ("tsc", Modes.Implied     ), new CpuInstruction( "65816",   0x3b) },
            { ("and", Modes.LongX       ), new CpuInstruction( "65816",   0x3f, 4) },
            { ("wdm", Modes.Implied     ), new CpuInstruction( "65816",   0x42) },
            { ("eor", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0x43, 2) },
            { ("mvp", Modes.TwoOperand  ), new CpuInstruction( "65816",   0x44, 3) },
            { ("eor", Modes.Dir         ), new CpuInstruction( "65816",   0x47, 2) },
            { ("phk", Modes.Implied     ), new CpuInstruction( "65816",   0x4b) },
            { ("eor", Modes.Long        ), new CpuInstruction( "65816",   0x4f, 4) },
            { ("eor", Modes.IndS        ), new CpuInstruction( "65816",   0x53, 2) },
            { ("mvn", Modes.TwoOperand  ), new CpuInstruction( "65816",   0x54, 3) },
            { ("eor", Modes.DirY        ), new CpuInstruction( "65816",   0x57, 2) },
            { ("tcd", Modes.Implied     ), new CpuInstruction( "65816",   0x5b) },
            { ("jml", Modes.Long        ), new CpuInstruction( "65816",   0x5c, 4) },
            { ("jmp", Modes.Long        ), new CpuInstruction( "65816",   0x5c, 4) },
            { ("eor", Modes.LongX       ), new CpuInstruction( "65816",   0x5f, 4) },
            { ("per", Modes.RelativeAbs ), new CpuInstruction( "65816",   0x62, 3) },
            { ("adc", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0x63, 2) },
            { ("adc", Modes.Dir         ), new CpuInstruction( "65816",   0x67, 2) },
            { ("rtl", Modes.Implied     ), new CpuInstruction( "65816",   0x6b) },
            { ("adc", Modes.Long        ), new CpuInstruction( "65816",   0x6f, 4) },
            { ("adc", Modes.IndS        ), new CpuInstruction( "65816",   0x73, 2) },
            { ("adc", Modes.DirY        ), new CpuInstruction( "65816",   0x77, 2) },
            { ("tdc", Modes.Implied     ), new CpuInstruction( "65816",   0x7b) },
            { ("adc", Modes.LongX       ), new CpuInstruction( "65816",   0x7f, 4) },
            { ("brl", Modes.RelativeAbs ), new CpuInstruction( "65816",   0x82, 3) },
            { ("sta", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0x83, 2) },
            { ("sta", Modes.Dir         ), new CpuInstruction( "65816",   0x87, 2) },
            { ("phb", Modes.Implied     ), new CpuInstruction( "65816",   0x8b) },
            { ("sta", Modes.Long        ), new CpuInstruction( "65816",   0x8f, 4) },
            { ("sta", Modes.IndS        ), new CpuInstruction( "65816",   0x93, 2) },
            { ("sta", Modes.DirY        ), new CpuInstruction( "65816",   0x97, 2) },
            { ("txy", Modes.Implied     ), new CpuInstruction( "65816",   0x9b) },
            { ("sta", Modes.LongX       ), new CpuInstruction( "65816",   0x9f, 4) },
            { ("lda", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0xa3, 2) },
            { ("lda", Modes.Dir         ), new CpuInstruction( "65816",   0xa7, 2) },
            { ("plb", Modes.Implied     ), new CpuInstruction( "65816",   0xab) },
            { ("lda", Modes.Long        ), new CpuInstruction( "65816",   0xaf, 4) },
            { ("lda", Modes.IndS        ), new CpuInstruction( "65816",   0xb3, 2) },
            { ("lda", Modes.DirY        ), new CpuInstruction( "65816",   0xb7, 2) },
            { ("tyx", Modes.Implied     ), new CpuInstruction( "65816",   0xbb) },
            { ("lda", Modes.LongX       ), new CpuInstruction( "65816",   0xbf, 4) },
            { ("rep", Modes.Immediate   ), new CpuInstruction( "65816",   0xc2, 2) },
            { ("cmp", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0xc3, 2) },
            { ("cmp", Modes.Dir         ), new CpuInstruction( "65816",   0xc7, 2) },
            { ("cmp", Modes.Long        ), new CpuInstruction( "65816",   0xcf, 4) },
            { ("cmp", Modes.IndS        ), new CpuInstruction( "65816",   0xd3, 2) },
            { ("pei", Modes.IndZp       ), new CpuInstruction( "65816",   0xd4, 2) },
            { ("cmp", Modes.DirY        ), new CpuInstruction( "65816",   0xd7, 2) },
            { ("jmp", Modes.DirAbs      ), new CpuInstruction( "65816",   0xdc, 3) },
            { ("cmp", Modes.LongX       ), new CpuInstruction( "65816",   0xdf, 4) },
            { ("sep", Modes.Immediate   ), new CpuInstruction( "65816",   0xe2, 2) },
            { ("sbc", Modes.ZeroPageS   ), new CpuInstruction( "65816",   0xe3, 2) },
            { ("sbc", Modes.Dir         ), new CpuInstruction( "65816",   0xe7, 2) },
            { ("xba", Modes.Implied     ), new CpuInstruction( "65816",   0xeb) },
            { ("sbc", Modes.Long        ), new CpuInstruction( "65816",   0xef, 4) },
            { ("sbc", Modes.IndS        ), new CpuInstruction( "65816",   0xf3, 2) },
            { ("pea", Modes.ImmAbs      ), new CpuInstruction( "65816",   0xf4, 3) },
            { ("pea", Modes.Absolute    ), new CpuInstruction( "65816",   0xf4, 3) }, // both are acceptable
            { ("sbc", Modes.DirY        ), new CpuInstruction( "65816",   0xf7, 2) },
            { ("xce", Modes.Implied     ), new CpuInstruction( "65816",   0xfb) },
            { ("jsr", Modes.IndAbsX     ), new CpuInstruction( "65816",   0xfc, 3) },
            { ("sbc", Modes.LongX       ), new CpuInstruction( "65816",   0xff, 4) },
        };
        static readonly Dictionary<(string Mnem, Modes Mode), CpuInstruction> s_opcodes6502i = 
            new Dictionary<(string Mnem, Modes Mode), CpuInstruction>()
        {
            { ("jam", Modes.Implied     ), new CpuInstruction( "6502i",   0x03) },
            { ("slo", Modes.IndX        ), new CpuInstruction( "6502i",   0x03, 2) },
            { ("dop", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0x04, 2) },
            { ("slo", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0x07, 2) },
            { ("top", Modes.Implied     ), new CpuInstruction( "6502i",   0x0c) },
            { ("top", Modes.Absolute    ), new CpuInstruction( "6502i",   0x0c, 3) },
            { ("slo", Modes.Absolute    ), new CpuInstruction( "6502i",   0x0f, 3) },
            { ("stp", Modes.Implied     ), new CpuInstruction( "6502i",   0x13) },
            { ("slo", Modes.IndY        ), new CpuInstruction( "6502i",   0x13, 2) },
            { ("dop", Modes.ZeroPageX   ), new CpuInstruction( "6502i",   0x14, 2) },
            { ("slo", Modes.ZeroPageX   ), new CpuInstruction( "6502i",   0x17, 2) },
            { ("slo", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0x1b, 3) },
            { ("slo", Modes.AbsoluteX   ), new CpuInstruction( "6502i",   0x1f, 3) },
            { ("rla", Modes.IndX        ), new CpuInstruction( "6502i",   0x23, 2) },
            { ("rla", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0x27, 2) },
            { ("anc", Modes.Immediate   ), new CpuInstruction( "6502i",   0x2b, 2) },
            { ("rla", Modes.Absolute    ), new CpuInstruction( "6502i",   0x2f, 3) },
            { ("rla", Modes.IndY        ), new CpuInstruction( "6502i",   0x33, 2) },
            { ("rla", Modes.ZeroPageX   ), new CpuInstruction( "6502i",   0x37, 2) },
            { ("rla", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0x3b, 3) },
            { ("rla", Modes.AbsoluteX   ), new CpuInstruction( "6502i",   0x3f, 3) },
            { ("sre", Modes.IndX        ), new CpuInstruction( "6502i",   0x43, 2) },
            { ("sre", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0x47, 2) },
            { ("asr", Modes.Immediate   ), new CpuInstruction( "6502i",   0x4b, 2) },
            { ("sre", Modes.Absolute    ), new CpuInstruction( "6502i",   0x4f, 3) },
            { ("sre", Modes.IndY        ), new CpuInstruction( "6502i",   0x53, 2) },
            { ("sre", Modes.ZeroPageX   ), new CpuInstruction( "6502i",   0x57, 2) },
            { ("sre", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0x5b, 3) },
            { ("sre", Modes.AbsoluteX   ), new CpuInstruction( "6502i",   0x5f, 3) },
            { ("rra", Modes.IndX        ), new CpuInstruction( "6502i",   0x63, 2) },
            { ("rra", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0x67, 2) },
            { ("arr", Modes.Immediate   ), new CpuInstruction( "6502i",   0x6b, 2) },
            { ("rra", Modes.Absolute    ), new CpuInstruction( "6502i",   0x6f, 3) },
            { ("rra", Modes.IndY        ), new CpuInstruction( "6502i",   0x73, 2) },
            { ("rra", Modes.ZeroPageX   ), new CpuInstruction( "6502i",   0x77, 2) },
            { ("rra", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0x7b, 3) },
            { ("rra", Modes.AbsoluteX   ), new CpuInstruction( "6502i",   0x7f, 3) },
            { ("dop", Modes.Implied     ), new CpuInstruction( "6502i",   0x80) },
            { ("dop", Modes.Immediate   ), new CpuInstruction( "6502i",   0x80, 2) },
            { ("sax", Modes.IndX        ), new CpuInstruction( "6502i",   0x83, 2) },
            { ("sax", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0x87, 2) },
            { ("ane", Modes.Immediate   ), new CpuInstruction( "6502i",   0x8b, 2) },
            { ("sax", Modes.Absolute    ), new CpuInstruction( "6502i",   0x8f, 3) },
            { ("sha", Modes.IndY        ), new CpuInstruction( "6502i",   0x93, 2) },
            { ("sax", Modes.ZeroPageY   ), new CpuInstruction( "6502i",   0x97, 2) },
            { ("tas", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0x9b, 3) },
            { ("shy", Modes.AbsoluteX   ), new CpuInstruction( "6502i",   0x9c, 3) },
            { ("shx", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0x9e, 3) },
            { ("sha", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0x9f, 3) },
            { ("lax", Modes.IndX        ), new CpuInstruction( "6502i",   0xa3, 2) },
            { ("lax", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0xa7, 2) },
            { ("lax", Modes.Absolute    ), new CpuInstruction( "6502i",   0xaf, 3) },
            { ("lax", Modes.IndY        ), new CpuInstruction( "6502i",   0xb3, 2) },
            { ("lax", Modes.ZeroPageY   ), new CpuInstruction( "6502i",   0xb7, 2) },
            { ("las", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0xbb, 3) },
            { ("lax", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0xbf, 3) },
            { ("dcp", Modes.IndX        ), new CpuInstruction( "6502i",   0xc3, 2) },
            { ("dcp", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0xc7, 2) },
            { ("sax", Modes.Immediate   ), new CpuInstruction( "6502i",   0xcb, 2) },
            { ("dcp", Modes.Absolute    ), new CpuInstruction( "6502i",   0xcf, 3) },
            { ("dcp", Modes.IndY        ), new CpuInstruction( "6502i",   0xd3, 2) },
            { ("dcp", Modes.ZeroPageX   ), new CpuInstruction( "6502i",   0xd7, 2) },
            { ("dcp", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0xdb, 3) },
            { ("dcp", Modes.AbsoluteX   ), new CpuInstruction( "6502i",   0xdf, 3) },
            { ("isb", Modes.IndX        ), new CpuInstruction( "6502i",   0xe3, 2) },
            { ("isb", Modes.ZeroPage    ), new CpuInstruction( "6502i",   0xe7, 2) },
            { ("isb", Modes.Absolute    ), new CpuInstruction( "6502i",   0xef, 3) },
            { ("isb", Modes.IndY        ), new CpuInstruction( "6502i",   0xf3, 2) },
            { ("isb", Modes.ZeroPageX   ), new CpuInstruction( "6502i",   0xf7, 2) },
            { ("isb", Modes.AbsoluteY   ), new CpuInstruction( "6502i",   0xfb, 3) },
            { ("isb", Modes.AbsoluteX   ), new CpuInstruction( "6502i",   0xff, 3) },
        };

        static readonly Dictionary<(string Mnem, Modes Mode), CpuInstruction> s_opcodesC64dtv2 =
            new Dictionary<(string Mnem, Modes Mode), CpuInstruction>()
        {
            { ("bra", Modes.Relative    ), new CpuInstruction( "c64dtv2", 0x12, 2) },
            { ("sac", Modes.Immediate   ), new CpuInstruction( "c64dtv2", 0x32, 2) },
            { ("sir", Modes.Immediate   ), new CpuInstruction( "c64dtv2", 0x42, 2) }
        };

        static readonly IReadOnlyDictionary<StringView, string> s_pseudoBranchTranslations =
            new Dictionary<StringView, string>
        {
            { "jcc", "bcs" },
            { "jcs", "bcc" },
            { "jeq", "bne" },
            { "jmi", "bpl" },
            { "jne", "beq" },
            { "jvc", "bvs" },
            { "jvs", "bvc" }
        };

        #endregion

        #region Properties

        /// <summary>
        /// Gets an array of the 65xx-based CPUs whose mnemonics this assembler recognizes.
        /// </summary>
        /// <value>The supported CPUs.</value>
        public static string[] SupportedCPUs { get; } =
        {
            "6502",
            "6502i",
            "65C02",
            "c64dtv2",
            "HuC6280",
            "R65C02",
            "65CE02",
            "45GS02",
            "m65",
            "65816",
            "65CS02"
        };

        #endregion

    }
}