// Copyright (c) 2026 informedcitizenry
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

using Sixty502DotNet.Shared.Lex;
using System.Text;

namespace Sixty502DotNet.Shared.Parse.Ast;

public sealed class Operand : Ast
{
    public Operand(OperandType type, Token firstToken)
    {
        Type = type;
        LeftToken = firstToken;
        if (type == OperandType.Implied)
        {
            RightToken = firstToken;
        }
    }

    public override string? ToString()
    {
        if (Type == OperandType.RegisterList)
        {
            var sb = new StringBuilder(Registers[0].Text.ToString());
            for (var i = 1; i < sb.Length; i++)
            {
                sb.Append($", {Registers[i].Text}");
            }
            return sb.ToString();
        }

        return Type switch
        {
            OperandType.AutoDecrement => $",-{Registers[0].Text}",
            OperandType.AutoDecrement2 => $",--{Registers[0].Text}",
            OperandType.AutoIncrement => $",{Registers[0].Text}+",
            OperandType.AutoIncrement2 => $",{Registers[0].Text}++",
            OperandType.Address when CoercedSize == 3 => $"[24] {Expressions[0]}",
            OperandType.Address when CoercedSize == 2 => $"[16] {Expressions[0]}",
            OperandType.Address when CoercedSize == 1 => $"[8] {Expressions[0]}",
            OperandType.Address => Expressions[0].ToString(),
            OperandType.GbAccumulatorHlDecrement => "a, (hl-)",
            OperandType.GbAccumulatorHlIncrement => "a, (hl+)",
            OperandType.GbHlDecrementAccumulator => "(hl-), a",
            OperandType.GbHlIncrementAccumulator => "(hl+), a",
            OperandType.GbImmediateIndirect => $"a, ({Expressions[0]}+{Expressions[1]})",
            OperandType.GbImmediateIndirectIndexed => $"a, ({Expressions[0]}+c)",
            OperandType.GbIndirect => $"({Expressions[0]}+{Expressions[1]}), a",
            OperandType.GbIndirectIndexed => $"({Expressions[0]}+c), a",
            OperandType.GbStackOffset => $"hl, sp+{Expressions[0]}",
            OperandType.Immediate when CoercedSize == 2 => $"[16] #{Expressions[0]}",
            OperandType.Immediate when CoercedSize == 1 => $"[8] #{Expressions[0]}",
            OperandType.Immediate => $"#{Expressions[0]}",
            OperandType.Immediate80 => $"{Registers[0].Text}, {Expressions[0]}",
            OperandType.ImmediateBranch when CoercedSize == 2 => $"[16] #{Expressions[0]}, {Expressions[1]}",
            OperandType.ImmediateBranch when CoercedSize == 1  => $"[8] #{Expressions[0]}, {Expressions[1]}",
            OperandType.ImmediateBranch => $"{Expressions[0]}, {Expressions[1]}",
            OperandType.ImmediateBranchIndexed when CoercedSize == 2 => $"[16] #{Expressions[0]}, {Expressions[1]}, x",
            OperandType.ImmediateBranchIndexed when CoercedSize == 1 => $"[8] #{Expressions[0]}, {Expressions[1]}, x",
            OperandType.ImmediateBranchIndexed => $"{Expressions[0]}, {Expressions[1]}, x",
            OperandType.Implied => string.Empty,
            OperandType.Indexed when CoercedSize == 3 => $"[24] {Expressions[0]}, {Registers[0].Text}",
            OperandType.Indexed when CoercedSize == 2 => $"[16] {Expressions[0]}, {Registers[0].Text}",
            OperandType.Indexed when CoercedSize == 1 => $"[8] {Expressions[0]}, {Registers[0].Text}",
            OperandType.Indexed => $"{Expressions[0]}, {Registers[0].Text}",
            OperandType.Indexed80 => $"({Registers[0].Text}+{Expressions[0]})",
            OperandType.Indexed80Bit => $"{Expressions[0]}, ({Registers[0].Text}, {Expressions[1]})",
            OperandType.IndexedIndirect when CoercedSize == 2 => $"[16] ({Expressions[0]}, {Registers[0].Text})",
            OperandType.IndexedIndirect when CoercedSize == 1 => $"[8] ({Expressions[0]}, {Registers[0].Text})",
            OperandType.IndexedIndirect => $"({Expressions[0]}, {Registers[0].Text})",
            OperandType.IndexedIndirect6809 => $"[{Expressions[0]}, {Registers[0].Text}]",
            OperandType.IndexedIndirectIndexed => $"({Expressions[0]}, {Registers[0].Text}), {Registers[1].Text}",
            OperandType.Indirect when CoercedSize == 2 => $"[16] ({Expressions[0]})",
            OperandType.Indirect when CoercedSize == 1 => $"[8] ({Expressions[0]})",
            OperandType.Indirect => $"({Expressions[0]})",
            OperandType.IndirectAutoDecrement => $"[, --{Registers[0].Text}]",
            OperandType.IndirectAutoIncrement => $"[, {Registers[0].Text}++]",
            OperandType.IndirectHlBit => $"{Expressions[0]}, (hl)",
            OperandType.IndirectIndexed => $"({Expressions[0]}), {Registers[0].Text}",
            OperandType.IndirectIndexed80Bit =>
                $"{Expressions[0]}, ({Registers[0].Text}+{Expressions[1]}), {Registers[1].Text}",
            OperandType.IndirectLong when CoercedSize == 2 => $"WORD PTR [{Expressions[0]}]",
            OperandType.IndirectLong when CoercedSize == 1 => $"BYTE PTR [{Expressions[0]}]",
            OperandType.IndirectLong => $"[{Expressions[0]}]",
            OperandType.IndirectRegister => $"({Registers[0].Text})",
            OperandType.IndirectRegisterImmediate => $"({Registers[0].Text}), {Expressions[0]}",
            OperandType.IndirectRegisterOffset => $"[,{Registers[0].Text}]",
            OperandType.IndirectRegisterRegister => $"({Registers[0].Text}), {Registers[1].Text}",
            OperandType.IndirectRegisterRegister6809 => $"[{Registers[0].Text}, {Registers[1].Text}]",
            OperandType.Register => Registers[0].Text.ToString(),
            OperandType.RegisterIndirect => $"{Registers[0].Text}, ({Expressions[0]})",
            OperandType.RegisterIndirectIndexed80 => $"{Registers[0].Text}, ({Registers[1].Text}+{Expressions[0]})",
            OperandType.RegisterIndirectRegister => $"{Registers[0].Text}, ({Registers[1].Text})",
            OperandType.RegisterOffset => $",{Registers[0].Text}",
            OperandType.RegisterRegister => $"{Registers[0].Text}, {Registers[1].Text}",
            OperandType.ThreeExpression => $"{Expressions[0]}, {Expressions[1]}, {Expressions[2]}",
            OperandType.TwoExpression => $"{Expressions[0]}, {Expressions[1]}",
            OperandType.IndirectRegister86 when CoercedSize == 10 => $"TBYTE PTR [{Registers[0].Text}]",
            OperandType.IndirectRegister86 when CoercedSize == 8 => $"QWORD PTR [{Registers[0].Text}]",
            OperandType.IndirectRegister86 when CoercedSize == 4 => $"DWORD PTR [{Registers[0].Text}]",
            OperandType.IndirectRegister86 when CoercedSize == 2 => $"WORD PTR [{Registers[0].Text}]",
            OperandType.IndirectRegister86 when CoercedSize == 1 => $"BYTE PTR [{Registers[0].Text}]",
            OperandType.IndirectRegister86 => $"[{Registers[0].Text}]",
            OperandType.BaseDisplacement when CoercedSize == 10 => $"TBYTE PTR [{Registers[0].Text}+{Expressions[0]}]",
            OperandType.BaseDisplacement when CoercedSize == 8 => $"QWORD PTR [{Registers[0].Text}+{Expressions[0]}]",
            OperandType.BaseDisplacement when CoercedSize == 4 => $"DWORD PTR [{Registers[0].Text}+{Expressions[0]}]",
            OperandType.BaseDisplacement when CoercedSize == 2 => $"WORD PTR [{Registers[0].Text}+{Expressions[0]}]",
            OperandType.BaseDisplacement when CoercedSize == 1 => $"BYTE PTR [{Registers[0].Text}+{Expressions[0]}]",
            OperandType.BaseDisplacement => $"[{Registers[0].Text}+{Expressions[0]}]",
            OperandType.BaseIndex when CoercedSize == 10 => $"TBYTE PTR [{Registers[0].Text}+{Registers[1].Text}]",
            OperandType.BaseIndex when CoercedSize == 8 => $"QWORD PTR [{Registers[0].Text}+{Registers[1].Text}]",
            OperandType.BaseIndex when CoercedSize == 4 => $"DWORD PTR [{Registers[0].Text}+{Registers[1].Text}]",
            OperandType.BaseIndex when CoercedSize == 2 => $"WORD PTR [{Registers[0].Text}+{Registers[1].Text}]",
            OperandType.BaseIndex when CoercedSize == 1 => $"BYTE PTR [{Registers[0].Text}+{Registers[1].Text}]",
            OperandType.BaseIndex => $"[{Registers[0].Text}+{Registers[1].Text}]",
            OperandType.BaseIndexDisplacement when CoercedSize == 10 => $"TBYTE PTR [{Registers[0].Text}+{Registers[1].Text}+{Expressions[0]}]",
            OperandType.BaseIndexDisplacement when CoercedSize == 8 => $"QWORD PTR [{Registers[0].Text}+{Registers[1].Text}+{Expressions[0]}]",
            OperandType.BaseIndexDisplacement when CoercedSize == 4 => $"DWORD PTR [{Registers[0].Text}+{Registers[1].Text}+{Expressions[0]}]",
            OperandType.BaseIndexDisplacement when CoercedSize == 2 => $"WORD PTR [{Registers[0].Text}+{Registers[1].Text}+{Expressions[0]}]",
            OperandType.BaseIndexDisplacement when CoercedSize == 1 => $"BYTE PTR [{Registers[0].Text}+{Registers[1].Text}+{Expressions[0]}]",
            OperandType.BaseIndexDisplacement => $"[{Registers[0].Text}+{Registers[1].Text}+{Expressions[0]}]",
            OperandType.BaseIndexRegister when CoercedSize == 10 => $"TBYTE PTR [{Registers[0].Text}+{Registers[1].Text}], {Registers[2].Text}",
            OperandType.BaseIndexRegister when CoercedSize == 8 => $"QWORD PTR [{Registers[0].Text}+{Registers[1].Text}], {Registers[2].Text}",
            OperandType.BaseIndexRegister when CoercedSize == 4 => $"DWORD PTR [{Registers[0].Text}+{Registers[1].Text}], {Registers[2].Text}",
            OperandType.BaseIndexRegister when CoercedSize == 2 => $"WORD PTR [{Registers[0].Text}+{Registers[1].Text}], {Registers[2].Text}",
            OperandType.BaseIndexRegister when CoercedSize == 1 => $"BYTE PTR [{Registers[0].Text}+{Registers[1].Text}], {Registers[2].Text}",
            OperandType.BaseIndexRegister => $"[{Registers[0].Text}+{Registers[1].Text}], {Registers[2].Text}",
            OperandType.BaseDisplacementRegister when CoercedSize == 10 => $"TBYTE PTR [{Registers[0].Text}+{Expressions[0]}], {Registers[1].Text}",
            OperandType.BaseDisplacementRegister when CoercedSize == 8 => $"QWORD PTR [{Registers[0].Text}+{Expressions[0]}], {Registers[1].Text}",
            OperandType.BaseDisplacementRegister when CoercedSize == 4 => $"DWORD PTR [{Registers[0].Text}+{Expressions[0]}], {Registers[1].Text}",
            OperandType.BaseDisplacementRegister when CoercedSize == 2 => $"WORD PTR [{Registers[0].Text}+{Expressions[0]}], {Registers[1].Text}",
            OperandType.BaseDisplacementRegister when CoercedSize == 1 => $"BYTE PTR [{Registers[0].Text}+{Expressions[0]}], {Registers[1].Text}",
            OperandType.BaseDisplacementRegister => $"[{Registers[0].Text}+{Expressions[0]}], {Registers[1].Text}",
            OperandType.BaseIndexDisplacementRegister when CoercedSize == 10 => $"TBYTE PTR [{Registers[0].Text}+{Registers[1].Text}+{Expressions[0]}], {Registers[2].Text}",
            OperandType.BaseIndexDisplacementRegister when CoercedSize == 8 => $"QWORD PTR [{Registers[0].Text}+{Registers[1].Text}+{Expressions[0]}], {Registers[2].Text}",
            OperandType.BaseIndexDisplacementRegister when CoercedSize == 4 => $"DWORD PTR [{Registers[0].Text}+{Registers[1].Text}+{Expressions[0]}], {Registers[2].Text}",
            OperandType.BaseIndexDisplacementRegister when CoercedSize == 2 => $"WORD PTR [{Registers[0].Text}+{Registers[1].Text}+{Expressions[0]}], {Registers[2].Text}",
            OperandType.BaseIndexDisplacementRegister when CoercedSize == 1 => $"BYTE PTR [{Registers[0].Text}+{Registers[1].Text}+{Expressions[0]}], {Registers[2].Text}",
            OperandType.BaseIndexDisplacementRegister => $"[{Registers[0].Text}+{Registers[1].Text}+{Expressions[0]}], {Registers[2].Text}",
            OperandType.DirectRegister when CoercedSize == 10 => $"TBYTE PTR [{Expressions[0]}], {Registers[0].Text}",
            OperandType.DirectRegister when CoercedSize == 8 => $"QWORD PTR [{Expressions[0]}], {Registers[0].Text}",
            OperandType.DirectRegister when CoercedSize == 4 => $"DWORD PTR [{Expressions[0]}], {Registers[0].Text}",
            OperandType.DirectRegister when CoercedSize == 2 => $"WORD PTR [{Expressions[0]}], {Registers[0].Text}",
            OperandType.DirectRegister when CoercedSize == 1 => $"BYTE PTR [{Expressions[0]}], {Registers[0].Text}",
            OperandType.DirectRegister => $"[{Expressions[0]}], {Registers[0].Text}",
            OperandType.IndirectRegister86Register when CoercedSize == 10 => $"TBYTE PTR [{Registers[0].Text}], {Registers[1].Text}",
            OperandType.IndirectRegister86Register when CoercedSize == 8 => $"QWORD PTR [{Registers[0].Text}], {Registers[1].Text}",
            OperandType.IndirectRegister86Register when CoercedSize == 4 => $"DWORD PTR [{Registers[0].Text}], {Registers[1].Text}",
            OperandType.IndirectRegister86Register when CoercedSize == 2 => $"WORD PTR [{Registers[0].Text}], {Registers[1].Text}",
            OperandType.IndirectRegister86Register when CoercedSize == 1 => $"BYTE PTR [{Registers[0].Text}], {Registers[1].Text}",
            OperandType.IndirectRegister86Register => $"[{Registers[0].Text}], {Registers[1].Text}",
            OperandType.RegisterBaseDisplacement when CoercedSize == 10 => $"{Registers[0].Text}, TBYTE PTR [{Registers[0].Text}+{Expressions[0]}]",
            OperandType.RegisterBaseDisplacement when CoercedSize == 8 => $"{Registers[0].Text}, QWORD PTR [{Registers[0].Text}+{Expressions[0]}]",
            OperandType.RegisterBaseDisplacement when CoercedSize == 4 => $"{Registers[0].Text}, DWORD PTR [{Registers[0].Text}+{Expressions[0]}]",
            OperandType.RegisterBaseDisplacement when CoercedSize == 2 => $"{Registers[0].Text}, WORD PTR [{Registers[0].Text}+{Expressions[0]}]",
            OperandType.RegisterBaseDisplacement when CoercedSize == 1 => $"{Registers[0].Text}, BYTE PTR [{Registers[0].Text}+{Expressions[0]}]",
            OperandType.RegisterBaseDisplacement => $"{Registers[0].Text}, [{Registers[1].Text}+{Expressions[0]}]",
            OperandType.RegisterBaseIndex when CoercedSize == 10 => $"{Registers[0].Text}, TBYTE PTR [{Registers[1].Text}+{Registers[2].Text}]",
            OperandType.RegisterBaseIndex when CoercedSize == 8 => $"{Registers[0].Text}, QWORD PTR [{Registers[1].Text}+{Registers[2].Text}]",
            OperandType.RegisterBaseIndex when CoercedSize == 4 => $"{Registers[0].Text}, DWORD PTR [{Registers[1].Text}+{Registers[2].Text}]",
            OperandType.RegisterBaseIndex when CoercedSize == 2 => $"{Registers[0].Text}, WORD PTR [{Registers[1].Text}+{Registers[2].Text}]",
            OperandType.RegisterBaseIndex when CoercedSize == 1 => $"{Registers[0].Text}, BYTE PTR [{Registers[1].Text}+{Registers[2].Text}]",
            OperandType.RegisterBaseIndex => $"{Registers[0].Text}, [{Registers[1].Text}+{Registers[2].Text}]",
            OperandType.RegisterBaseIndexDisplacement when CoercedSize == 10 => $"{Registers[0].Text}, TBYTE PTR [{Registers[1].Text}+{Registers[2].Text}+{Expressions[0]}]",
            OperandType.RegisterBaseIndexDisplacement when CoercedSize == 8 => $"{Registers[0].Text}, QWORD PTR [{Registers[1].Text}+{Registers[2].Text}+{Expressions[0]}]",
            OperandType.RegisterBaseIndexDisplacement when CoercedSize == 4 => $"{Registers[0].Text}, DWORD PTR [{Registers[1].Text}+{Registers[2].Text}+{Expressions[0]}]",
            OperandType.RegisterBaseIndexDisplacement when CoercedSize == 2 => $"{Registers[0].Text}, WORD PTR [{Registers[1].Text}+{Registers[2].Text}+{Expressions[0]}]",
            OperandType.RegisterBaseIndexDisplacement when CoercedSize == 1 => $"{Registers[0].Text}, BYTE PTR [{Registers[1].Text}+{Registers[2].Text}+{Expressions[0]}]",
            OperandType.RegisterBaseIndexDisplacement => $"{Registers[0].Text}, [{Registers[1].Text}+{Registers[2].Text}+{Expressions[0]}]",
            OperandType.RegisterDirect when CoercedSize == 10 => $"{Registers[0].Text}, TBYTE PTR [{Expressions[0]}",
            OperandType.RegisterDirect when CoercedSize == 8 => $"{Registers[0].Text}, QWORD PTR [{Expressions[0]}",
            OperandType.RegisterDirect when CoercedSize == 4 => $"{Registers[0].Text}, DWORD PTR [{Expressions[0]}",
            OperandType.RegisterDirect when CoercedSize == 2 => $"{Registers[0].Text}, WORD PTR [{Expressions[0]}",
            OperandType.RegisterDirect when CoercedSize == 1 => $"{Registers[0].Text}, BYTE PTR [{Expressions[0]}",
            OperandType.RegisterDirect => $"{Registers[0].Text}, [{Expressions[0]}",
            OperandType.RegisterIndirectRegister86 when CoercedSize == 10 => $"{Registers[0].Text}, TBYTE PTR [{Registers[1].Text}]",
            OperandType.RegisterIndirectRegister86 when CoercedSize == 8 => $"{Registers[0].Text}, QWORD PTR [{Registers[1].Text}]",
            OperandType.RegisterIndirectRegister86 when CoercedSize == 4 => $"{Registers[0].Text}, DWORD PTR [{Registers[1].Text}]",
            OperandType.RegisterIndirectRegister86 when CoercedSize == 2 => $"{Registers[0].Text}, WORD PTR [{Registers[1].Text}]",
            OperandType.RegisterIndirectRegister86 when CoercedSize == 1 => $"{Registers[0].Text}, BYTE PTR [{Registers[1].Text}]",
            OperandType.RegisterIndirectRegister86 => $"{Registers[0].Text}, [{Registers[1].Text}]",
            OperandType.RegisterSegmentOverrideDirect when CoercedSize == 10 => $"{Registers[0].Text}, TBYTE PTR {Registers[1].Text}:[{Expressions[0]}]",
            OperandType.RegisterSegmentOverrideDirect when CoercedSize == 8 => $"{Registers[0].Text}, QWORD PTR {Registers[1].Text}:[{Expressions[0]}]",
            OperandType.RegisterSegmentOverrideDirect when CoercedSize == 4 => $"{Registers[0].Text}, DWORD PTR {Registers[1].Text}:[{Expressions[0]}]",
            OperandType.RegisterSegmentOverrideDirect when CoercedSize == 2 => $"{Registers[0].Text}, WORD PTR {Registers[1].Text}:[{Expressions[0]}]",
            OperandType.RegisterSegmentOverrideDirect when CoercedSize == 1 => $"{Registers[0].Text}, BYTE PTR {Registers[1].Text}:[{Expressions[0]}]",
            OperandType.RegisterSegmentOverrideDirect => $"{Registers[0].Text}, {Registers[1].Text}:[{Expressions[0]}]",
            OperandType.RegisterSegmentOverrideRegister when CoercedSize == 10 => $"{Registers[0].Text}, TBYTE PTR {Registers[1].Text}:[{Registers[2].Text}]",
            OperandType.RegisterSegmentOverrideRegister when CoercedSize == 8 => $"{Registers[0].Text}, QWORD PTR {Registers[1].Text}:[{Registers[2].Text}]",
            OperandType.RegisterSegmentOverrideRegister when CoercedSize == 4 => $"{Registers[0].Text}, DWORD PTR {Registers[1].Text}:[{Registers[2].Text}]",
            OperandType.RegisterSegmentOverrideRegister when CoercedSize == 2 => $"{Registers[0].Text}, WORD PTR {Registers[1].Text}:[{Registers[2].Text}]",
            OperandType.RegisterSegmentOverrideRegister when CoercedSize == 1 => $"{Registers[0].Text}, BYTE PTR {Registers[1].Text}:[{Registers[2].Text}]",
            OperandType.RegisterSegmentOverrideRegister => $"{Registers[0].Text}, {Registers[1].Text}:[{Registers[2].Text}]",
            OperandType.RegisterSegmentOverrideBaseIndex when CoercedSize == 10 => $"{Registers[0].Text}, TBYTE PTR {Registers[1].Text}:[{Registers[2].Text}+{Registers[3].Text}]",
            OperandType.RegisterSegmentOverrideBaseIndex when CoercedSize == 8 => $"{Registers[0].Text}, QWORD PTR {Registers[1].Text}:[{Registers[2].Text}+{Registers[3].Text}]",
            OperandType.RegisterSegmentOverrideBaseIndex when CoercedSize == 4 => $"{Registers[0].Text}, DWORD PTR {Registers[1].Text}:[{Registers[2].Text}+{Registers[3].Text}]",
            OperandType.RegisterSegmentOverrideBaseIndex when CoercedSize == 2 => $"{Registers[0].Text}, WORD PTR {Registers[1].Text}:[{Registers[2].Text}+{Registers[3].Text}]",
            OperandType.RegisterSegmentOverrideBaseIndex when CoercedSize == 1 => $"{Registers[0].Text}, BYTE PTR {Registers[1].Text}:[{Registers[2].Text}+{Registers[3].Text}]",
            OperandType.RegisterSegmentOverrideBaseIndex => $"{Registers[0].Text}, {Registers[1].Text}:[{Registers[2].Text}+{Registers[3].Text}]",
            OperandType.RegisterSegmentOverrideBaseDisplacement when CoercedSize == 10 => $"{Registers[0].Text}, TBYTE PTR {Registers[1].Text}:[{Registers[2].Text}+{Expressions[0]}]",
            OperandType.RegisterSegmentOverrideBaseDisplacement when CoercedSize == 8 => $"{Registers[0].Text}, QWORD PTR {Registers[1].Text}:[{Registers[2].Text}+{Expressions[0]}]",
            OperandType.RegisterSegmentOverrideBaseDisplacement when CoercedSize == 4 => $"{Registers[0].Text}, DWORD PTR {Registers[1].Text}:[{Registers[2].Text}+{Expressions[0]}]",
            OperandType.RegisterSegmentOverrideBaseDisplacement when CoercedSize == 2 => $"{Registers[0].Text}, WORD PTR {Registers[1].Text}:[{Registers[2].Text}+{Expressions[0]}]",
            OperandType.RegisterSegmentOverrideBaseDisplacement when CoercedSize == 1 => $"{Registers[0].Text}, BYTE PTR {Registers[1].Text}:[{Registers[2].Text}+{Expressions[0]}]",
            OperandType.RegisterSegmentOverrideBaseDisplacement => $"{Registers[0].Text}, {Registers[1].Text}:[{Registers[2].Text}+{Expressions[0]}]",
            OperandType.RegisterSegmentOverrideBaseIndexDisplacement when CoercedSize == 10 => $"{Registers[0].Text}, TBYTE PTR {Registers[1].Text}:[{Registers[2].Text}+{Registers[3].Text}+{Expressions[0]}]",
            OperandType.RegisterSegmentOverrideBaseIndexDisplacement when CoercedSize == 8 => $"{Registers[0].Text}, QWORD PTR {Registers[1].Text}:[{Registers[2].Text}+{Registers[3].Text}+{Expressions[0]}]",
            OperandType.RegisterSegmentOverrideBaseIndexDisplacement when CoercedSize == 4 => $"{Registers[0].Text}, DWORD PTR {Registers[1].Text}:[{Registers[2].Text}+{Registers[3].Text}+{Expressions[0]}]",
            OperandType.RegisterSegmentOverrideBaseIndexDisplacement when CoercedSize == 2 => $"{Registers[0].Text}, WORD PTR {Registers[1].Text}:[{Registers[2].Text}+{Registers[3].Text}+{Expressions[0]}]",
            OperandType.RegisterSegmentOverrideBaseIndexDisplacement when CoercedSize == 1 => $"{Registers[0].Text}, BYTE PTR {Registers[1].Text}:[{Registers[2].Text}+{Registers[3].Text}+{Expressions[0]}]",
            OperandType.RegisterSegmentOverrideBaseIndexDisplacement => $"{Registers[0].Text}, {Registers[1].Text}:[{Registers[2].Text}+{Registers[3].Text}+{Expressions[0]}]",
            OperandType.SegmentOverrideDirect when CoercedSize == 10 => $"TBYTE PTR {Registers[0].Text}:[{Expressions[0]}]",
            OperandType.SegmentOverrideDirect when CoercedSize == 8 => $"QWORD PTR {Registers[0].Text}:[{Expressions[0]}]",
            OperandType.SegmentOverrideDirect when CoercedSize == 4 => $"DWORD PTR {Registers[0].Text}:[{Expressions[0]}]",
            OperandType.SegmentOverrideDirect when CoercedSize == 2 => $"WORD PTR {Registers[0].Text}:[{Expressions[0]}]",
            OperandType.SegmentOverrideDirect when CoercedSize == 1 => $"BYTE PTR {Registers[0].Text}:[{Expressions[0]}]",
            OperandType.SegmentOverrideDirect => $"{Registers[0].Text}:[{Expressions[0]}]",
            OperandType.SegmentAbsoluteDirect => $"{Expressions[0]}:{Expressions[1]}",
            OperandType.SegmentOverrideDirectRegister when CoercedSize == 10 => $"TBYTE PTR {Registers[0].Text}:[{Expressions[0]}], {Registers[1].Text}",
            OperandType.SegmentOverrideDirectRegister when CoercedSize == 8 => $"QWORD PTR {Registers[0].Text}:[{Expressions[0]}], {Registers[1].Text}",
            OperandType.SegmentOverrideDirectRegister when CoercedSize == 4 => $"DWORD PTR {Registers[0].Text}:[{Expressions[0]}], {Registers[1].Text}",
            OperandType.SegmentOverrideDirectRegister when CoercedSize == 2 => $"WORD PTR {Registers[0].Text}:[{Expressions[0]}], {Registers[1].Text}",
            OperandType.SegmentOverrideDirectRegister when CoercedSize == 1 => $"BYTE PTR {Registers[0].Text}:[{Expressions[0]}], {Registers[1].Text}",
            OperandType.SegmentOverrideDirectRegister => $"{Registers[0].Text}:[{Expressions[0]}], {Registers[1].Text}",
            OperandType.SegmentOverrideBaseDisplacement when CoercedSize == 10 => $"TBYTE PTR {Registers[0].Text}:[{Registers[1].Text}+{Expressions[0]}]",
            OperandType.SegmentOverrideBaseDisplacement when CoercedSize == 8 => $"QWORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Expressions[0]}]",
            OperandType.SegmentOverrideBaseDisplacement when CoercedSize == 4 => $"DWORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Expressions[0]}]",
            OperandType.SegmentOverrideBaseDisplacement when CoercedSize == 2 => $"WORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Expressions[0]}]",
            OperandType.SegmentOverrideBaseDisplacement when CoercedSize == 1 => $"BYTE PTR {Registers[0].Text}:[{Registers[1].Text}+{Expressions[0]}]",
            OperandType.SegmentOverrideBaseDisplacement => $"{Registers[0].Text}:[{Registers[1].Text}+{Expressions[0]}]",
            OperandType.SegmentOverrideRegister when CoercedSize == 10 => $"TBYTE PTR {Registers[0].Text}:[{Registers[1].Text}]",
            OperandType.SegmentOverrideRegister when CoercedSize == 8 => $"QWORD PTR {Registers[0].Text}:[{Registers[1].Text}]",
            OperandType.SegmentOverrideRegister when CoercedSize == 4 => $"DWORD PTR {Registers[0].Text}:[{Registers[1].Text}]",
            OperandType.SegmentOverrideRegister when CoercedSize == 2 => $"WORD PTR {Registers[0].Text}:[{Registers[1].Text}]",
            OperandType.SegmentOverrideRegister when CoercedSize == 1 => $"BYTE PTR {Registers[0].Text}:[{Registers[1].Text}]",
            OperandType.SegmentOverrideRegister => $"{Registers[0].Text}:[{Registers[1].Text}]",
            OperandType.SegmentOverrideBaseIndexDisplacement when CoercedSize == 10 => $"TBYTE PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}+{Expressions[0]}]",
            OperandType.SegmentOverrideBaseIndexDisplacement when CoercedSize == 8 => $"QWORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}+{Expressions[0]}]",
            OperandType.SegmentOverrideBaseIndexDisplacement when CoercedSize == 4 => $"DWORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}+{Expressions[0]}]",
            OperandType.SegmentOverrideBaseIndexDisplacement when CoercedSize == 2 => $"WORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}+{Expressions[0]}]",
            OperandType.SegmentOverrideBaseIndexDisplacement when CoercedSize == 1 => $"BYTE PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}+{Expressions[0]}]",
            OperandType.SegmentOverrideBaseIndexDisplacement => $"{Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}+{Expressions[0]}]",
            OperandType.SegmentOverrideBaseIndex when CoercedSize == 10 => $"TBYTE PTR {Registers[0]}:[{Registers[1].Text}+{Registers[2].Text}]",
            OperandType.SegmentOverrideBaseIndex when CoercedSize == 8 => $"QWORD PTR {Registers[0]}:[{Registers[1].Text}+{Registers[2].Text}]",
            OperandType.SegmentOverrideBaseIndex when CoercedSize == 4 => $"DWORD PTR {Registers[0]}:[{Registers[1].Text}+{Registers[2].Text}]",
            OperandType.SegmentOverrideBaseIndex when CoercedSize == 2 => $"WORD PTR {Registers[0]}:[{Registers[1].Text}+{Registers[2].Text}]",
            OperandType.SegmentOverrideBaseIndex when CoercedSize == 1 => $"BYTE PTR {Registers[0]}:[{Registers[1].Text}+{Registers[2].Text}]",
            OperandType.SegmentOverrideBaseIndex => $"{Registers[0]}:[{Registers[1].Text}+{Registers[2].Text}]",
            OperandType.SegmentOverrideRegisterRegister when CoercedSize == 10 => $"TBYTE PTR {Registers[0].Text}:[{Registers[1].Text}], {Registers[2].Text}",
            OperandType.SegmentOverrideRegisterRegister when CoercedSize == 8 => $"QWORD PTR {Registers[0].Text}:[{Registers[1].Text}], {Registers[2].Text}",
            OperandType.SegmentOverrideRegisterRegister when CoercedSize == 4 => $"DWORD PTR {Registers[0].Text}:[{Registers[1].Text}], {Registers[2].Text}",
            OperandType.SegmentOverrideRegisterRegister when CoercedSize == 2 => $"WORD PTR {Registers[0].Text}:[{Registers[1].Text}], {Registers[2].Text}",
            OperandType.SegmentOverrideRegisterRegister when CoercedSize == 1 => $"BYTE PTR {Registers[0].Text}:[{Registers[1].Text}], {Registers[2].Text}",
            OperandType.SegmentOverrideRegisterRegister => $"{Registers[0].Text}:[{Registers[1].Text}], {Registers[2].Text}",
            OperandType.SegmentOverrideRegisterSegmentOverrideRegister when CoercedSize == 2 => $"WORD PTR {Registers[0].Text}:[{Registers[1].Text}], WORD PTR {Registers[2].Text}:[{Registers[3].Text}]",
            OperandType.SegmentOverrideRegisterSegmentOverrideRegister => $"BYTE PTR {Registers[0].Text}:[{Registers[1].Text}], BYTE PTR {Registers[2].Text}:[{Registers[3].Text}]",
            OperandType.SegmentOverrideBaseDisplacementRegister when CoercedSize == 10 => $"TBYTE PTR {Registers[0].Text}:[{Registers[1].Text}+{Expressions[0]}], {Registers[2].Text}",
            OperandType.SegmentOverrideBaseDisplacementRegister when CoercedSize == 8 => $"QWORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Expressions[0]}], {Registers[2].Text}",
            OperandType.SegmentOverrideBaseDisplacementRegister when CoercedSize == 4 => $"DWORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Expressions[0]}], {Registers[2].Text}",
            OperandType.SegmentOverrideBaseDisplacementRegister when CoercedSize == 2 => $"WORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Expressions[0]}], {Registers[2].Text}",
            OperandType.SegmentOverrideBaseDisplacementRegister when CoercedSize == 1 => $"BYTE PTR {Registers[0].Text}:[{Registers[1].Text}+{Expressions[0]}], {Registers[2].Text}",
            OperandType.SegmentOverrideBaseDisplacementRegister => $"{Registers[0].Text}:[{Registers[1].Text}+{Expressions[0]}], {Registers[2].Text}",
            OperandType.SegmentOverrideBaseIndexRegister when CoercedSize == 10 => $"TBYTE PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}], {Registers[3].Text}",
            OperandType.SegmentOverrideBaseIndexRegister when CoercedSize == 8 => $"QWORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}], {Registers[3].Text}",
            OperandType.SegmentOverrideBaseIndexRegister when CoercedSize == 4 => $"DWORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}], {Registers[3].Text}",
            OperandType.SegmentOverrideBaseIndexRegister when CoercedSize == 2 => $"WORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}], {Registers[3].Text}",
            OperandType.SegmentOverrideBaseIndexRegister when CoercedSize == 1 => $"BYTE PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}], {Registers[3].Text}",
            OperandType.SegmentOverrideBaseIndexRegister => $"{Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}], {Registers[3].Text}",
            OperandType.SegmentOverrideBaseIndexDisplacementRegister when CoercedSize == 10 => $"TBYTE PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}+{Expressions[0]}], {Registers[3].Text}",
            OperandType.SegmentOverrideBaseIndexDisplacementRegister when CoercedSize == 8 => $"QWORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}+{Expressions[0]}], {Registers[3].Text}",
            OperandType.SegmentOverrideBaseIndexDisplacementRegister when CoercedSize == 4 => $"DWORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}+{Expressions[0]}], {Registers[3].Text}",
            OperandType.SegmentOverrideBaseIndexDisplacementRegister when CoercedSize == 2 => $"WORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}+{Expressions[0]}], {Registers[3].Text}",
            OperandType.SegmentOverrideBaseIndexDisplacementRegister when CoercedSize == 1 => $"BYTE PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}+{Expressions[0]}], {Registers[3].Text}",
            OperandType.SegmentOverrideBaseIndexDisplacementRegister => $"{Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}+{Expressions[0]}], {Registers[3].Text}",
            OperandType.DirectImm when CoercedSize == 10 => $"TBYTE PTR [{Expressions[0]}], {Expressions[1]}",
            OperandType.DirectImm when CoercedSize == 8 => $"QWORD PTR [{Expressions[0]}], {Expressions[1]}",
            OperandType.DirectImm when CoercedSize == 4 => $"DWORD PTR [{Expressions[0]}], {Expressions[1]}",
            OperandType.DirectImm when CoercedSize == 2 => $"WORD PTR [{Expressions[0]}], {Expressions[1]}",
            OperandType.DirectImm => $"BYTE PTR [{Expressions[0]}], {Expressions[1]}",
            OperandType.IndirectRegister86Imm when CoercedSize == 10 => $"TBYTE PTR [{Registers[0].Text}], {Expressions[0]}",
            OperandType.IndirectRegister86Imm when CoercedSize == 8 => $"QWORD PTR [{Registers[0].Text}], {Expressions[0]}",
            OperandType.IndirectRegister86Imm when CoercedSize == 4 => $"DWORD PTR [{Registers[0].Text}], {Expressions[0]}",
            OperandType.IndirectRegister86Imm when CoercedSize == 2 => $"WORD PTR [{Registers[0].Text}], {Expressions[0]}",
            OperandType.IndirectRegister86Imm => $"BYTE PTR [{Registers[0].Text}], {Expressions[0]}",
            OperandType.BaseIndexImm when CoercedSize == 10 => $"TBYTE PTR [{Registers[0].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.BaseIndexImm when CoercedSize == 8 => $"QWORD PTR [{Registers[0].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.BaseIndexImm when CoercedSize == 4 => $"DWORD PTR [{Registers[0].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.BaseIndexImm when CoercedSize == 2 => $"WORD PTR [{Registers[0].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.BaseIndexImm => $"BYTE PTR [{Registers[0].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.BaseDisplacementImm when CoercedSize == 10 => $"TBYTE PTR [{Registers[0].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.BaseDisplacementImm when CoercedSize == 8 => $"QWORD PTR [{Registers[0].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.BaseDisplacementImm when CoercedSize == 4 => $"DWORD PTR [{Registers[0].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.BaseDisplacementImm when CoercedSize == 2 => $"WORD PTR [{Registers[0].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.BaseDisplacementImm => $"BYTE PTR [{Registers[0].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.BaseIndexDisplacementImm when CoercedSize == 10 => $"TBYTE PTR [{Registers[0].Text}+{Registers[1].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.BaseIndexDisplacementImm when CoercedSize == 8 => $"QWORD PTR [{Registers[0].Text}+{Registers[1].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.BaseIndexDisplacementImm when CoercedSize == 4 => $"DWORD PTR [{Registers[0].Text}+{Registers[1].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.BaseIndexDisplacementImm when CoercedSize == 2 => $"WORD PTR [{Registers[0].Text}+{Registers[1].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.BaseIndexDisplacementImm => $"BYTE PTR [{Registers[0].Text}+{Registers[1].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.SegmentOverrideDirectImm when CoercedSize == 10 => $"TBYTE PTR {Registers[0].Text}:[{Expressions[0]}, {Expressions[1]}",
            OperandType.SegmentOverrideDirectImm when CoercedSize == 8 => $"QWORD PTR {Registers[0].Text}:[{Expressions[0]}, {Expressions[1]}",
            OperandType.SegmentOverrideDirectImm when CoercedSize == 4 => $"DWORD PTR {Registers[0].Text}:[{Expressions[0]}, {Expressions[1]}",
            OperandType.SegmentOverrideDirectImm when CoercedSize == 2 => $"WORD PTR {Registers[0].Text}:[{Expressions[0]}, {Expressions[1]}",
            OperandType.SegmentOverrideDirectImm => $"BYTE PTR {Registers[0].Text}:[{Expressions[0]}, {Expressions[1]}",
            OperandType.SegmentOverrideRegisterImm when CoercedSize == 10 => $"TBYTE PTR {Registers[0].Text}:[{Registers[1].Text}], {Expressions[0]}",
            OperandType.SegmentOverrideRegisterImm when CoercedSize == 8 => $"QWORD PTR {Registers[0].Text}:[{Registers[1].Text}], {Expressions[0]}",
            OperandType.SegmentOverrideRegisterImm when CoercedSize == 4 => $"DWORD PTR {Registers[0].Text}:[{Registers[1].Text}], {Expressions[0]}",
            OperandType.SegmentOverrideRegisterImm when CoercedSize == 2 => $"WORD PTR {Registers[0].Text}:[{Registers[1].Text}], {Expressions[0]}",
            OperandType.SegmentOverrideRegisterImm => $"BYTE PTR {Registers[0].Text}:[{Registers[1].Text}], {Expressions[0]}",
            OperandType.SegmentOverrideBaseIndexImm when CoercedSize == 10 => $"TBYTE PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}], {Expressions[0]}",
            OperandType.SegmentOverrideBaseIndexImm when CoercedSize == 8 => $"QWORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}], {Expressions[0]}",
            OperandType.SegmentOverrideBaseIndexImm when CoercedSize == 4 => $"DWORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}], {Expressions[0]}",
            OperandType.SegmentOverrideBaseIndexImm when CoercedSize == 2 => $"WORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}], {Expressions[0]}",
            OperandType.SegmentOverrideBaseIndexImm => $"BYTE PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}], {Expressions[0]}",
            OperandType.SegmentOverrideBaseDisplacementImm when CoercedSize == 10 => $"TBYTE PTR {Registers[0].Text}:[{Registers[1].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.SegmentOverrideBaseDisplacementImm when CoercedSize == 8 => $"QWORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.SegmentOverrideBaseDisplacementImm when CoercedSize == 4 => $"DWORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.SegmentOverrideBaseDisplacementImm when CoercedSize == 2 => $"WORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.SegmentOverrideBaseDisplacementImm => $"BYTE PTR {Registers[0].Text}:[{Registers[1].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.SegmentOverrideBaseIndexDisplacementImm when CoercedSize == 10 => $"TBYTE PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.SegmentOverrideBaseIndexDisplacementImm when CoercedSize == 8 => $"QWORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.SegmentOverrideBaseIndexDisplacementImm when CoercedSize == 4 => $"DWORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.SegmentOverrideBaseIndexDisplacementImm when CoercedSize == 2 => $"WORD PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}+{Expressions[0]}], {Expressions[1]}",
            OperandType.SegmentOverrideBaseIndexDisplacementImm => $"BYTE PTR {Registers[0].Text}:[{Registers[1].Text}+{Registers[2].Text}+{Expressions[0]}], {Expressions[1]}",
            _ => string.Empty
        };
    }

    public int CoercedSize
    {
        get;
        init;
    }

    public OperandType Type { get; }
    
    public IList<Token> Registers { get; init; } = new List<Token>();
    
    public IList<Expression> Expressions { get; init; } = new List<Expression>();
}
