// Copyright (c) 2026 informedcitizenry
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

using Sixty502DotNet.Shared.Arch;
using Sixty502DotNet.Shared.Lex;
using System.Collections.Frozen;

namespace Sixty502DotNet.Shared.Encode;

using static EncodeUtil;

public static class PostByteFlags
{
    public const int Offset5Bit    = 0b0001_1111,
                        AutoInc1   = 0b1000_0000,
                        AutoInc2   = 0b1000_0001,
                        AutoDec1   = 0b1000_0010,
                        AutoDec2   = 0b1000_0011,
                        ZeroOffset = 0b1000_0100,
                        AccBOffset = 0b1000_0101,
                        AccAOffset = 0b1000_0110,
                        Offset8Bit = 0b1000_1000,
                        Offset16   = 0b1000_1001,
                        AccDOffset = 0b1000_1011,
                        Pc8BitOffs = 0b1000_1100,
                        Pc16Bit    = 0b1000_1101,
                        OffsetMask = 0b1000_1111,
                        Indirect   = 0b1001_0000,
                        Extended   = 0b1001_1111,
                        X          = 0b0000_0000,
                        Y          = 0b0010_0000,
                        U          = 0b0100_0000,
                        S          = 0b0110_0000,
                        IndexMask  = 0b0110_0000;
};

internal static partial class MotorolaEncoder
{
    private static readonly FrozenDictionary<TokenType, byte> s_exchangeModes 
        = new Dictionary<TokenType, byte>()
    {
        { TokenType.D,      0b0000 },
        { TokenType.X,      0b0001 },
        { TokenType.Y,      0b0010 },
        { TokenType.U,      0b0011 },
        { TokenType.S,      0b0100 },
        { TokenType.Pc,     0b0101 },
        { TokenType.A,      0b1000 },
        { TokenType.B,      0b1001 },
        { TokenType.CcReg,  0b1010 },
        { TokenType.Dp,     0b1011 },
        { TokenType.Tfradp, 0b10001011 },
        { TokenType.Tfrbdp, 0b10011011 },
    }.ToFrozenDictionary();
    
    private static readonly FrozenDictionary<TokenType, byte> s_pushPullModes 
        = new Dictionary<TokenType, byte>
    {
        { TokenType.Pc,     0b1000_0000 },
        { TokenType.S,      0b0100_0000 },
        { TokenType.U,      0b0100_0000 },
        { TokenType.Y,      0b0010_0000 },
        { TokenType.X,      0b0001_0000 },
        { TokenType.Dp,     0b0000_1000 },
        { TokenType.D,      0b0000_0110 },
        { TokenType.B,      0b0000_0100 },
        { TokenType.A,      0b0000_0010 },
        { TokenType.CcReg,  0b0000_0001 }
    }.ToFrozenDictionary();
    
    private static readonly  FrozenDictionary<TokenType, M6xxOpcode> s_m6800Opcodes 
        = new Dictionary<TokenType, M6xxOpcode>
    {
        //                                         Impl               Zp            Rel             Abs              Imm              ZpX             RelAbs              ImmAbs
        { TokenType.Asl,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x78,    Bad,   0x68,    Bad,    Bad) },
        { TokenType.Bcc,  new M6xxOpcode(    Bad,    Bad,   0x24,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bcs,  new M6xxOpcode(    Bad,    Bad,   0x25,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Beq,  new M6xxOpcode(    Bad,    Bad,   0x27,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bmi,  new M6xxOpcode(    Bad,    Bad,   0x2B,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bne,  new M6xxOpcode(    Bad,    Bad,   0x26,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bpl,  new M6xxOpcode(    Bad,    Bad,   0x2A,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bvc,  new M6xxOpcode(    Bad,    Bad,   0x28,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bvs,  new M6xxOpcode(    Bad,    Bad,   0x29,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Clc,  new M6xxOpcode(   0x0C,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Cli,  new M6xxOpcode(   0x0E,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Clv,  new M6xxOpcode(   0x0A,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Dec,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x7A,    Bad,   0x6A,    Bad,    Bad) },
        { TokenType.Dex,  new M6xxOpcode(   0x09,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Inc,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x7C,    Bad,   0x6C,    Bad,    Bad) },
        { TokenType.Inx,  new M6xxOpcode(   0x08,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Jmp,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x7E,    Bad,   0x6E,    Bad,    Bad) },
        { TokenType.Jsr,  new M6xxOpcode(    Bad,    Bad,    Bad,   0xBD,    Bad,   0xAD,    Bad,    Bad) },
        { TokenType.Ldx,  new M6xxOpcode(    Bad,   0xDE,    Bad,   0xFE,    Bad,   0xEE,    Bad,   0xCE) },
        { TokenType.Lsr,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x74,    Bad,   0x64,    Bad,    Bad) },
        { TokenType.Nop,  new M6xxOpcode(   0x01,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Rol,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x79,    Bad,   0x69,    Bad,    Bad) },
        { TokenType.Ror,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x76,    Bad,   0x66,    Bad,    Bad) },
        { TokenType.Rti,  new M6xxOpcode(   0x3B,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Rts,  new M6xxOpcode(   0x39,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Sec,  new M6xxOpcode(   0x0D,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Sei,  new M6xxOpcode(   0x0F,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Stx,  new M6xxOpcode(    Bad,   0xDF,    Bad,   0xFF,    Bad,   0xEF,    Bad,    Bad) },
        //                                     Impl      Zp     Rel     Abs     Imm     ZpX  RelAbs  ImmAbs
        { TokenType.Tsx,  new M6xxOpcode(   0x30,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Txs,  new M6xxOpcode(   0x35,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Asr,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x77,    Bad,   0x67,    Bad,    Bad) },
        { TokenType.Bra,  new M6xxOpcode(    Bad,    Bad,   0x20,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bge,  new M6xxOpcode(    Bad,    Bad,   0x2C,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Blt,  new M6xxOpcode(    Bad,    Bad,   0x2D,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bsr,  new M6xxOpcode(    Bad,    Bad,   0x8D,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Tab,  new M6xxOpcode(   0x16,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Tba,  new M6xxOpcode(   0x17,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Aba,  new M6xxOpcode(   0x1B,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Adca, new M6xxOpcode(    Bad,   0x99,    Bad,   0xB9,   0x89,   0xA9,    Bad,    Bad) },
        { TokenType.Adcb, new M6xxOpcode(    Bad,   0xD9,    Bad,   0xF9,   0xC9,   0xE9,    Bad,    Bad) },
        { TokenType.Adda, new M6xxOpcode(    Bad,   0x9B,    Bad,   0xBB,   0x8B,   0xAB,    Bad,    Bad) },
        { TokenType.Addb, new M6xxOpcode(    Bad,   0xDB,    Bad,   0xFB,   0xCB,   0xEB,    Bad,    Bad) },
        { TokenType.Anda, new M6xxOpcode(    Bad,   0x94,    Bad,   0xB4,   0x84,   0xA4,    Bad,    Bad) },
        { TokenType.Andb, new M6xxOpcode(    Bad,   0xD4,    Bad,   0xF4,   0xC4,   0xE4,    Bad,    Bad) },
        { TokenType.Asla, new M6xxOpcode(   0x48,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Aslb, new M6xxOpcode(   0x58,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Asra, new M6xxOpcode(   0x47,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Asrb, new M6xxOpcode(   0x57,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bgt,  new M6xxOpcode(    Bad,    Bad,   0x2E,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bhi,  new M6xxOpcode(    Bad,    Bad,   0x22,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bita, new M6xxOpcode(    Bad,   0x95,    Bad,   0xB5,   0x85,   0xA5,    Bad,    Bad) },
        { TokenType.Bitb, new M6xxOpcode(    Bad,   0xD5,    Bad,   0xF5,   0xC5,   0xE5,    Bad,    Bad) },
        { TokenType.Ble,  new M6xxOpcode(    Bad,    Bad,   0x2F,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bls,  new M6xxOpcode(    Bad,    Bad,   0x23,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Cba,  new M6xxOpcode(   0x11,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Clr,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x7F,    Bad,   0x6F,    Bad,    Bad) },
        //                                     Impl      Zp     Rel     Abs     Imm     ZpX  RelAbs  ImmAbs
        { TokenType.Clra, new M6xxOpcode(   0x4F,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Clrb, new M6xxOpcode(   0x5F,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Cmpa, new M6xxOpcode(    Bad,   0x91,    Bad,   0xB1,   0x81,   0xA1,    Bad,    Bad) },
        { TokenType.Cmpb, new M6xxOpcode(    Bad,   0xD1,    Bad,   0xF1,   0xC1,   0xE1,    Bad,    Bad) },
        { TokenType.Com,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x73,    Bad,   0x63,    Bad,    Bad) },
        { TokenType.Coma, new M6xxOpcode(   0x43,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Comb, new M6xxOpcode(   0x53,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Cpxa, new M6xxOpcode(    Bad,   0x9C,    Bad,   0xBC,   0x8C,   0xAC,    Bad,    Bad) },
        { TokenType.Deca, new M6xxOpcode(   0x4A,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Decb, new M6xxOpcode(   0x5A,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Des,  new M6xxOpcode(   0x34,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Eora, new M6xxOpcode(    Bad,   0x98,    Bad,   0xB8,   0x88,   0xA8,    Bad,    Bad) },
        { TokenType.Eorb, new M6xxOpcode(    Bad,   0xD8,    Bad,   0xF8,   0xC8,   0xE8,    Bad,    Bad) },
        { TokenType.Inca, new M6xxOpcode(   0x4C,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Incb, new M6xxOpcode(   0x5C,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Ins,  new M6xxOpcode(   0x31,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Ldaa, new M6xxOpcode(    Bad,   0x96,    Bad,   0xB6,   0x86,   0xA6,    Bad,    Bad) },
        { TokenType.Ldab, new M6xxOpcode(    Bad,   0xD6,    Bad,   0xF6,   0xC6,   0xE6,    Bad,    Bad) },
        { TokenType.Lds,  new M6xxOpcode(    Bad,   0x9E,    Bad,   0xBE,    Bad,   0xAE,    Bad,   0x8E) },
        { TokenType.Lsra, new M6xxOpcode(   0x44,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Lsrb, new M6xxOpcode(   0x54,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Nega, new M6xxOpcode(   0x40,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Negb, new M6xxOpcode(   0x50,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Oraa, new M6xxOpcode(    Bad,   0x9A,    Bad,   0xBA,   0x8A,   0xAA,    Bad,    Bad) },
        { TokenType.Orab, new M6xxOpcode(    Bad,   0xDA,    Bad,   0xFA,   0xCA,   0xEA,    Bad,    Bad) },
        { TokenType.Psha, new M6xxOpcode(   0x36,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Pshb, new M6xxOpcode(   0x37,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Pula, new M6xxOpcode(   0x32,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        //                                     Impl      Zp     Rel     Abs     Imm     ZpX  RelAbs  ImmAbs
        { TokenType.Pulb, new M6xxOpcode(   0x33,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Rola, new M6xxOpcode(   0x49,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Rolb, new M6xxOpcode(   0x59,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Rora, new M6xxOpcode(   0x46,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Rorb, new M6xxOpcode(   0x56,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Sba,  new M6xxOpcode(   0x10,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Sbca, new M6xxOpcode(    Bad,   0x92,    Bad,   0xB2,   0x82,   0xA2,    Bad,    Bad) },
        { TokenType.Sbcb, new M6xxOpcode(    Bad,   0xD2,    Bad,   0xF2,   0xC2,   0xE2,    Bad,    Bad) },
        { TokenType.Sev,  new M6xxOpcode(   0x0B,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Staa, new M6xxOpcode(    Bad,   0x97,    Bad,   0xB7,   0xC7,   0xA7,    Bad,    Bad) },
        { TokenType.Stab, new M6xxOpcode(    Bad,   0xD7,    Bad,   0xF7,    Bad,   0xE7,    Bad,    Bad) },
        { TokenType.Sts,  new M6xxOpcode(    Bad,   0x9F,    Bad,   0xBF,    Bad,   0xAF,    Bad,    Bad) },
        { TokenType.Suba, new M6xxOpcode(    Bad,   0x90,    Bad,   0xB0,   0x80,   0xA0,    Bad,    Bad) },
        { TokenType.Subb, new M6xxOpcode(    Bad,   0xD0,    Bad,   0xF0,   0xC0,   0xE0,    Bad,    Bad) },
        { TokenType.Swi,  new M6xxOpcode(   0x3F,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Tap,  new M6xxOpcode(   0x06,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Tpa,  new M6xxOpcode(   0x07,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Tsta, new M6xxOpcode(   0x4D,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Tstb, new M6xxOpcode(   0x5D,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Daa,  new M6xxOpcode(   0x19,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Neg,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x70,    Bad,   0x60,    Bad,    Bad) },
        { TokenType.Tst,  new M6xxOpcode(    Bad,    Bad,    Bad,   0x7D,    Bad,   0x6D,    Bad,    Bad) },
        { TokenType.Wai,  new M6xxOpcode(   0x3E,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
    }.ToFrozenDictionary();
    
    private static readonly  FrozenDictionary<TokenType, M6xxOpcode> s_m6809Opcodes 
        = new Dictionary<TokenType, M6xxOpcode>
    {
        //                                     Impl      Zp     Rel     Abs     Imm     ZpX  RelAbs  ImmAbs
        { TokenType.Asl,  new M6xxOpcode(    Bad,   0x08,    Bad,   0x78,    Bad,   0x68,    Bad,    Bad) },
        { TokenType.Bcc,  new M6xxOpcode(    Bad,    Bad,   0x24,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bcs,  new M6xxOpcode(    Bad,    Bad,   0x25,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Beq,  new M6xxOpcode(    Bad,    Bad,   0x27,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bmi,  new M6xxOpcode(    Bad,    Bad,   0x2B,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bne,  new M6xxOpcode(    Bad,    Bad,   0x26,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bpl,  new M6xxOpcode(    Bad,    Bad,   0x2A,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bvc,  new M6xxOpcode(    Bad,    Bad,   0x28,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bvs,  new M6xxOpcode(    Bad,    Bad,   0x29,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Dec,  new M6xxOpcode(    Bad,   0x0A,    Bad,   0x7A,    Bad,   0x6A,    Bad,    Bad) },
        { TokenType.Inc,  new M6xxOpcode(    Bad,   0x0C,    Bad,   0x7C,    Bad,   0x6C,    Bad,    Bad) },
        { TokenType.Jmp,  new M6xxOpcode(    Bad,   0x0E,    Bad,   0x7E,    Bad,   0x6E,    Bad,    Bad) },
        { TokenType.Jsr,  new M6xxOpcode(    Bad,   0x9D,    Bad,   0xBD,    Bad,   0xAD,    Bad,    Bad) },
        { TokenType.Lda,  new M6xxOpcode(    Bad,   0x96,    Bad,   0xB6,   0x86,   0xA6,    Bad,    Bad) },
        { TokenType.Ldx,  new M6xxOpcode(    Bad,   0x9E,    Bad,   0xBE,    Bad,   0xAE,    Bad,   0x8E) },
        { TokenType.Ldy,  new M6xxOpcode(    Bad, 0x109E,    Bad, 0x10BE,    Bad, 0x10AE,    Bad, 0x108E) },
        { TokenType.Lsr,  new M6xxOpcode(    Bad,   0x04,    Bad,   0x74,    Bad,   0x64,    Bad,    Bad) },
        { TokenType.Nop,  new M6xxOpcode(   0x12,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Ora,  new M6xxOpcode(    Bad,   0x9A,    Bad,   0xBA,   0x8A,   0xAA,    Bad,    Bad) },
        { TokenType.Rol,  new M6xxOpcode(    Bad,   0x09,    Bad,   0x79,    Bad,   0x69,    Bad,    Bad) },
        { TokenType.Ror,  new M6xxOpcode(    Bad,   0x06,    Bad,   0x76,    Bad,   0x66,    Bad,    Bad) },
        { TokenType.Rti,  new M6xxOpcode(   0x3B,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Rts,  new M6xxOpcode(   0x39,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Sta,  new M6xxOpcode(    Bad,   0x97,    Bad,   0xB7,    Bad,   0xA7,    Bad,    Bad) },
        { TokenType.Stx,  new M6xxOpcode(    Bad,   0x9F,    Bad,   0xBF,    Bad,   0xAF,    Bad,    Bad) },
        { TokenType.Sty,  new M6xxOpcode(    Bad, 0x109F,    Bad, 0x10BF,    Bad, 0x10AF,    Bad,    Bad) },
        //                                     Impl      Zp     Rel     Abs     Imm     ZpX  RelAbs  ImmAbs
        { TokenType.Asr,  new M6xxOpcode(    Bad,   0x07,    Bad,   0x77,    Bad,   0x67,    Bad,    Bad) },
        { TokenType.Bra,  new M6xxOpcode(    Bad,    Bad,   0x20,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bge,  new M6xxOpcode(    Bad,    Bad,   0x2C,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Blt,  new M6xxOpcode(    Bad,    Bad,   0x2D,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bsr,  new M6xxOpcode(    Bad,    Bad,   0x8D,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Adca, new M6xxOpcode(    Bad,   0x99,    Bad,   0xB9,   0x89,   0xA9,    Bad,    Bad) },
        { TokenType.Adcb, new M6xxOpcode(    Bad,   0xD9,    Bad,   0xF9,   0xC9,   0xE9,    Bad,    Bad) },
        { TokenType.Adda, new M6xxOpcode(    Bad,   0x9B,    Bad,   0xBB,   0x8B,   0xAB,    Bad,    Bad) },
        { TokenType.Addb, new M6xxOpcode(    Bad,   0xDB,    Bad,   0xFB,   0xCB,   0xEB,    Bad,    Bad) },
        { TokenType.Anda, new M6xxOpcode(    Bad,   0x94,    Bad,   0xB4,   0x84,   0xA4,    Bad,    Bad) },
        { TokenType.Andb, new M6xxOpcode(    Bad,   0xD4,    Bad,   0xF4,   0xC4,   0xE4,    Bad,    Bad) },
        { TokenType.Asla, new M6xxOpcode(   0x48,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Aslb, new M6xxOpcode(   0x58,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Asra, new M6xxOpcode(   0x47,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Asrb, new M6xxOpcode(   0x57,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bgt,  new M6xxOpcode(    Bad,    Bad,   0x2E,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bhi,  new M6xxOpcode(    Bad,    Bad,   0x22,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bita, new M6xxOpcode(    Bad,   0x95,    Bad,   0xB5,   0x85,   0xA5,    Bad,    Bad) },
        { TokenType.Bitb, new M6xxOpcode(    Bad,   0xD5,    Bad,   0xF5,   0xC5,   0xE5,    Bad,    Bad) },
        { TokenType.Ble,  new M6xxOpcode(    Bad,    Bad,   0x2F,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Bls,  new M6xxOpcode(    Bad,    Bad,   0x23,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Clr,  new M6xxOpcode(    Bad,   0x0F,    Bad,   0x7F,    Bad,   0x6F,    Bad,    Bad) },
        { TokenType.Clra, new M6xxOpcode(   0x4F,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Clrb, new M6xxOpcode(   0x5F,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Cmpa, new M6xxOpcode(    Bad,   0x91,    Bad,   0xB1,   0x81,   0xA1,    Bad,    Bad) },
        { TokenType.Cmpb, new M6xxOpcode(    Bad,   0xD1,    Bad,   0xF1,   0xC1,   0xE1,    Bad,    Bad) },
        { TokenType.Com,  new M6xxOpcode(    Bad,   0x03,    Bad,   0x73,    Bad,   0x63,    Bad,    Bad) },
        { TokenType.Coma, new M6xxOpcode(   0x43,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        //                                     Impl      Zp     Rel     Abs     Imm     ZpX  RelAbs  ImmAbs
        { TokenType.Comb, new M6xxOpcode(   0x53,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Cpxa, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Deca, new M6xxOpcode(   0x4A,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Decb, new M6xxOpcode(   0x5A,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Eora, new M6xxOpcode(    Bad,   0x98,    Bad,   0xB8,   0x88,   0xA8,    Bad,    Bad) },
        { TokenType.Eorb, new M6xxOpcode(    Bad,   0xD8,    Bad,   0xF8,   0xC8,   0xE8,    Bad,    Bad) },
        { TokenType.Inca, new M6xxOpcode(   0x4C,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Incb, new M6xxOpcode(   0x5C,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Lds,  new M6xxOpcode(    Bad, 0x10DE,    Bad, 0x10FE,    Bad, 0x10EE,    Bad, 0x10CE) },
        { TokenType.Lsra, new M6xxOpcode(   0x44,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Lsrb, new M6xxOpcode(   0x54,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Nega, new M6xxOpcode(   0x40,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Negb, new M6xxOpcode(   0x50,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Oraa, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Rola, new M6xxOpcode(   0x49,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Rolb, new M6xxOpcode(   0x59,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Rora, new M6xxOpcode(   0x46,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Rorb, new M6xxOpcode(   0x56,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Sbca, new M6xxOpcode(    Bad,   0x92,    Bad,   0xB2,   0x82,   0xA2,    Bad,    Bad) },
        { TokenType.Sbcb, new M6xxOpcode(    Bad,   0xD2,    Bad,   0xF2,   0xC2,   0xE2,    Bad,    Bad) },
        { TokenType.Sts,  new M6xxOpcode(    Bad, 0x10DF,    Bad, 0x10FF,    Bad, 0x10EF,    Bad,    Bad) },
        { TokenType.Suba, new M6xxOpcode(    Bad,   0x90,    Bad,   0xB0,   0x80,   0xA0,    Bad,    Bad) },
        { TokenType.Subb, new M6xxOpcode(    Bad,   0xD0,    Bad,   0xF0,   0xC0,   0xE0,    Bad,    Bad) },
        { TokenType.Swi,  new M6xxOpcode(   0x3F,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Tsta, new M6xxOpcode(   0x4D,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Tstb, new M6xxOpcode(   0x5D,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Abx,  new M6xxOpcode(   0x3A,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Addd, new M6xxOpcode(    Bad,   0xD3,    Bad,   0xF2,    Bad,   0xE3,    Bad,   0xC3) },
        //                                     Impl      Zp     Rel     Abs     Imm     ZpX  RelAbs  ImmAbs
        { TokenType.Andcc,new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,   0x1C,    Bad,    Bad,    Bad) },
        { TokenType.Bhs,  new M6xxOpcode(    Bad,    Bad,   0x24,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Blo,  new M6xxOpcode(    Bad,    Bad,   0x25,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Brn,  new M6xxOpcode(    Bad,    Bad,   0x21,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Cmpd, new M6xxOpcode(    Bad, 0x1093,    Bad, 0x10B3,    Bad, 0x10A3,    Bad, 0x1083) },
        { TokenType.Cmps, new M6xxOpcode(    Bad, 0x119C,    Bad, 0x11BC,    Bad, 0x11AC,    Bad, 0x118C) },
        { TokenType.Cmpu, new M6xxOpcode(    Bad, 0x1193,    Bad, 0x11B3,    Bad, 0x11A3,    Bad, 0x1183) },
        { TokenType.Cmpx, new M6xxOpcode(    Bad,   0x9C,    Bad,   0xBC,    Bad,   0xAC,    Bad,   0x8C) },
        { TokenType.Cmpy, new M6xxOpcode(    Bad, 0x109C,    Bad, 0x10BC,    Bad, 0x10AC,    Bad, 0x108C) },
        { TokenType.Cwai, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,   0x3C,    Bad,    Bad,    Bad) },
        { TokenType.Daa,  new M6xxOpcode(   0x19,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Exg,  new M6xxOpcode(    Bad,   0x1E,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Lbcc, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x1024,    Bad) },
        { TokenType.Lbcs, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x1025,    Bad) },
        { TokenType.Lbeq, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x1027,    Bad) },
        { TokenType.Lbge, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x102C,    Bad) },
        { TokenType.Lbgt, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x102E,    Bad) },
        { TokenType.Lbhi, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x1022,    Bad) },
        { TokenType.Lbhs, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x1024,    Bad) },
        { TokenType.Lble, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x102F,    Bad) },
        { TokenType.Lblo, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x1025,    Bad) },
        { TokenType.Lbls, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x1023,    Bad) },
        { TokenType.Lblt, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x102D,    Bad) },
        { TokenType.Lbmi, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x102B,    Bad) },
        { TokenType.Lbne, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x1026,    Bad) },
        { TokenType.Lbpl, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x102A,    Bad) },
        { TokenType.Lbra, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,   0x16,    Bad) },
        { TokenType.Lbrn, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x1021,    Bad) },
        //                                     Impl      Zp     Rel     Abs     Imm     ZpX  RelAbs  ImmAbs
        { TokenType.Lbsr, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,   0x17,    Bad) },
        { TokenType.Lbvc, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x1028,    Bad) },
        { TokenType.Lbvs, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,    Bad, 0x1029,    Bad) },
        { TokenType.Ldb,  new M6xxOpcode(    Bad,   0xD6,    Bad,   0xF6,   0xC6,   0xE6,    Bad,    Bad) },
        { TokenType.Ldd,  new M6xxOpcode(    Bad,   0xDC,    Bad,   0xFC,    Bad,   0xEC,    Bad,   0xCC) },
        { TokenType.Ldu,  new M6xxOpcode(    Bad,   0xDE,    Bad,   0xFE,    Bad,   0xEE,    Bad,   0xCE) },
        { TokenType.Leas, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,   0x32,    Bad,    Bad) },
        { TokenType.Leau, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,   0x33,    Bad,    Bad) },
        { TokenType.Leax, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,   0x30,    Bad,    Bad) },
        { TokenType.Leay, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,    Bad,   0x31,    Bad,    Bad) },
        { TokenType.Lsl,  new M6xxOpcode(    Bad,   0x08,    Bad,   0x78,    Bad,   0x68,    Bad,    Bad) },
        { TokenType.Lsla, new M6xxOpcode(   0x48,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Lslb, new M6xxOpcode(   0x58,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Mul,  new M6xxOpcode(   0x3D,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Neg,  new M6xxOpcode(    Bad,   0x00,    Bad,   0x70,    Bad,   0x60,    Bad,    Bad) },
        { TokenType.Orb,  new M6xxOpcode(    Bad,   0xDA,    Bad,   0xFA,   0xCA,   0xEA,    Bad,    Bad) },
        { TokenType.Orcc, new M6xxOpcode(    Bad,    Bad,    Bad,    Bad,   0x1A,    Bad,    Bad,    Bad) },
        { TokenType.Pshs, new M6xxOpcode(    Bad,   0x34,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Pshu, new M6xxOpcode(    Bad,   0x36,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Puls, new M6xxOpcode(    Bad,   0x35,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Pulu, new M6xxOpcode(    Bad,   0x37,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Sex,  new M6xxOpcode(   0x1D,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Stb,  new M6xxOpcode(    Bad,   0xD7,    Bad,   0xF7,    Bad,   0xE7,    Bad,    Bad) },
        { TokenType.Std,  new M6xxOpcode(    Bad,   0xDD,    Bad,   0xFD,    Bad,   0xED,    Bad,    Bad) },
        { TokenType.Stu,  new M6xxOpcode(    Bad,   0xDF,    Bad,   0xFF,    Bad,   0xEF,    Bad,    Bad) },
        { TokenType.Subd, new M6xxOpcode(    Bad,   0x93,    Bad,   0xB3,    Bad,   0xA3,    Bad,   0x83) },
        { TokenType.Swi2, new M6xxOpcode( 0x103F,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Swi3, new M6xxOpcode( 0x113F,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Sync, new M6xxOpcode(   0x13,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Tfr,  new M6xxOpcode(    Bad,   0x1F,    Bad,    Bad,    Bad,    Bad,    Bad,    Bad) },
        { TokenType.Tst,  new M6xxOpcode(    Bad,   0x0D,    Bad,   0x7D,    Bad,   0x6D,    Bad,    Bad) }
    }.ToFrozenDictionary();
    
    private static readonly int[] s_regOpcodes =
    [
        0x1e, 0x1f, 0x34, 0x35, 0x36, 0x37
    ];
    
    private static readonly FrozenSet<int> s_m6809IndexedCodes =
    [
        0x30,
        0x31,
        0x32,
        0x33,
        0x60,
        0x63,
        0x64,
        0x66,
        0x67,
        0x68,
        0x69,
        0x6a,
        0x6c,
        0x6d,
        0x6e,
        0x6f,
        0xa0,
        0xa1,
        0xa2,
        0xa3,
        0xa4,
        0xa5,
        0xa6,
        0xa7,
        0xa8,
        0xa9,
        0xaa,
        0xab,
        0xac,
        0xad,
        0xae,
        0xaf,
        0xe0,
        0xe1,
        0xe2,
        0xe3,
        0xe4,
        0xe5,
        0xe6,
        0xe7,
        0xe8,
        0xe9,
        0xea,
        0xeb,
        0xec,
        0xed,
        0xee,
        0xef,
        0x10a3,
        0x10ac,
        0x10ae,
        0x10af,
        0x10ee,
        0x10ef,
        0x11a3,
        0x11ac
    ];
    
    private static readonly FrozenDictionary<int, string> s_exchangeRegsLu 
        = new Dictionary<int, string>
    {
        { 0b0000, "d" },
        { 0b0001, "x" },
        { 0b0010, "y" },
        { 0b0011, "u" },
        { 0b0100, "s" },
        { 0b0101, "pc" },
        { 0b1000, "a" },
        { 0b1001, "b" },
        { 0b1010, "cc" },
        { 0b1011, "dp" }
    }.ToFrozenDictionary();

    private static readonly FrozenDictionary<int, string> s_pushPullRegsLu 
        = new Dictionary<int, string>
    {
        { 0b1000_0000, "pc" },
        { 0b0100_0000, "su" },
        { 0b0010_0000, "y" },
        { 0b0001_0000, "x" },
        { 0b0000_1000, "dp" },
        { 0b0000_0110, "d" },
        { 0b0000_0100, "b" },
        { 0b0000_0010, "a" },
        { 0b0000_0001, "cc" }
    }.ToFrozenDictionary();

    private static readonly FrozenDictionary<int, char> s_indexRegsReverseLu 
        = new Dictionary<int, char>
    {
        { 0b0_00_00000, 'x' },
        { 0b0_01_00000, 'y' },
        { 0b0_10_00000, 'u' },
        { 0b0_11_00000, 's' }
    }.ToFrozenDictionary();
    
    private static readonly  FrozenDictionary<int, DecodedInstruction> s_m6800Disassembly = new Dictionary<int, DecodedInstruction>
    {
        { 0x01, new DecodedInstruction("nop", 0x01) },
        { 0x06, new DecodedInstruction("tap", 0x06) },
        { 0x07, new DecodedInstruction("tpa", 0x07) },
        { 0x08, new DecodedInstruction("inx", 0x08) },
        { 0x09, new DecodedInstruction("dex", 0x09) },
        { 0x0a, new DecodedInstruction("clv", 0x0a) },
        { 0x0b, new DecodedInstruction("sev", 0x0b) },
        { 0x0c, new DecodedInstruction("clc", 0x0c) },
        { 0x0d, new DecodedInstruction("sec", 0x0d) },
        { 0x0e, new DecodedInstruction("cli", 0x0e) },
        { 0x0f, new DecodedInstruction("sei", 0x0f) },
        { 0x10, new DecodedInstruction("sba", 0x10) },
        { 0x11, new DecodedInstruction("cba", 0x11) },
        { 0x16, new DecodedInstruction("tab", 0x16) },
        { 0x17, new DecodedInstruction("tba", 0x17) },
        { 0x19, new DecodedInstruction("daa", 0x19) },
        { 0x1b, new DecodedInstruction("aba", 0x1b) },
        { 0x20, new DecodedInstruction("bra ${0:x4}", 0x20, 2, true) },
        { 0x22, new DecodedInstruction("bhi ${0:x4}", 0x22, 2, true) },
        { 0x23, new DecodedInstruction("bls ${0:x4}", 0x23, 2, true) },
        { 0x24, new DecodedInstruction("bcc ${0:x4}", 0x24, 2, true) },
        { 0x25, new DecodedInstruction("bcs ${0:x4}", 0x25, 2, true) },
        { 0x26, new DecodedInstruction("bne ${0:x4}", 0x26, 2, true) },
        { 0x27, new DecodedInstruction("beq ${0:x4}", 0x27, 2, true) },
        { 0x28, new DecodedInstruction("bvc ${0:x4}", 0x28, 2, true) },
        { 0x29, new DecodedInstruction("bvs ${0:x4}", 0x29, 2, true) },
        { 0x2a, new DecodedInstruction("bpl ${0:x4}", 0x2a, 2, true) },
        { 0x2b, new DecodedInstruction("bmi ${0:x4}", 0x2b, 2, true) },
        { 0x2c, new DecodedInstruction("bge ${0:x4}", 0x2c, 2, true) },
        { 0x2d, new DecodedInstruction("blt ${0:x4}", 0x2d, 2, true) },
        { 0x2e, new DecodedInstruction("bgt ${0:x4}", 0x2e, 2, true) },
        { 0x2f, new DecodedInstruction("ble ${0:x4}", 0x2f, 2, true) },
        { 0x30, new DecodedInstruction("tsx", 0x30) },
        { 0x31, new DecodedInstruction("ins", 0x31) },
        { 0x32, new DecodedInstruction("pula", 0x32) },
        { 0x33, new DecodedInstruction("pulb", 0x33) },
        { 0x34, new DecodedInstruction("des", 0x34) },
        { 0x35, new DecodedInstruction("txs", 0x35) },
        { 0x36, new DecodedInstruction("psha", 0x36) },
        { 0x37, new DecodedInstruction("pshb", 0x37) },
        { 0x39, new DecodedInstruction("rts", 0x39) },
        { 0x3b, new DecodedInstruction("rti", 0x3b) },
        { 0x3e, new DecodedInstruction("wai", 0x3e) },
        { 0x3f, new DecodedInstruction("swi", 0x3f) },
        { 0x40, new DecodedInstruction("nega", 0x40) },
        { 0x43, new DecodedInstruction("coma", 0x43) },
        { 0x44, new DecodedInstruction("lsra", 0x44) },
        { 0x46, new DecodedInstruction("rora", 0x46) },
        { 0x47, new DecodedInstruction("asra", 0x47) },
        { 0x48, new DecodedInstruction("asla", 0x48) },
        { 0x49, new DecodedInstruction("rola", 0x49) },
        { 0x4a, new DecodedInstruction("deca", 0x4a) },
        { 0x4c, new DecodedInstruction("inca", 0x4c) },
        { 0x4d, new DecodedInstruction("tsta", 0x4d) },
        { 0x4f, new DecodedInstruction("clra", 0x4f) },
        { 0x50, new DecodedInstruction("negb", 0x50) },
        { 0x53, new DecodedInstruction("comb", 0x53) },
        { 0x54, new DecodedInstruction("lsrb", 0x54) },
        { 0x56, new DecodedInstruction("rorb", 0x56) },
        { 0x57, new DecodedInstruction("asrb", 0x57) },
        { 0x58, new DecodedInstruction("aslb", 0x58) },
        { 0x59, new DecodedInstruction("rolb", 0x59) },
        { 0x5a, new DecodedInstruction("decb", 0x5a) },
        { 0x5c, new DecodedInstruction("incb", 0x5c) },
        { 0x5d, new DecodedInstruction("tstb", 0x5d) },
        { 0x5f, new DecodedInstruction("clrb", 0x5f) },
        { 0x60, new DecodedInstruction("neg ${0:x2},x", 0x60, 2) },
        { 0x63, new DecodedInstruction("com ${0:x2},x", 0x63, 2) },
        { 0x64, new DecodedInstruction("lsr ${0:x2},x", 0x64, 2) },
        { 0x66, new DecodedInstruction("ror ${0:x2},x", 0x66, 2) },
        { 0x67, new DecodedInstruction("asr ${0:x2},x", 0x67, 2) },
        { 0x68, new DecodedInstruction("asl ${0:x2},x", 0x68, 2) },
        { 0x69, new DecodedInstruction("rol ${0:x2},x", 0x69, 2) },
        { 0x6a, new DecodedInstruction("dec ${0:x2},x", 0x6a, 2) },
        { 0x6c, new DecodedInstruction("inc ${0:x2},x", 0x6c, 2) },
        { 0x6d, new DecodedInstruction("tst ${0:x2},x", 0x6d, 2) },
        { 0x6e, new DecodedInstruction("jmp ${0:x2},x", 0x6e, 2) },
        { 0x6f, new DecodedInstruction("clr ${0:x2},x", 0x6f, 2) },
        { 0x70, new DecodedInstruction("neg ${0:x4}", 0x70, 3) },
        { 0x73, new DecodedInstruction("com ${0:x4}", 0x73, 3) },
        { 0x74, new DecodedInstruction("lsr ${0:x4}", 0x74, 3) },
        { 0x76, new DecodedInstruction("ror ${0:x4}", 0x76, 3) },
        { 0x77, new DecodedInstruction("asr ${0:x4}", 0x77, 3) },
        { 0x78, new DecodedInstruction("asl ${0:x4}", 0x78, 3) },
        { 0x79, new DecodedInstruction("rol ${0:x4}", 0x79, 3) },
        { 0x7a, new DecodedInstruction("dec ${0:x4}", 0x7a, 3) },
        { 0x7c, new DecodedInstruction("inc ${0:x4}", 0x7c, 3) },
        { 0x7d, new DecodedInstruction("tst ${0:x4}", 0x7d, 3) },
        { 0x7e, new DecodedInstruction("jmp ${0:x4}", 0x7e, 3) },
        { 0x7f, new DecodedInstruction("clr ${0:x4}", 0x7f, 3) },
        { 0x80, new DecodedInstruction("suba #${0:x2}", 0x80, 2) },
        { 0x81, new DecodedInstruction("cmpa #${0:x2}", 0x81, 2) },
        { 0x82, new DecodedInstruction("sbca #${0:x2}", 0x82, 2) },
        { 0x84, new DecodedInstruction("anda #${0:x2}", 0x84, 2) },
        { 0x85, new DecodedInstruction("bita #${0:x2}", 0x85, 2) },
        { 0x86, new DecodedInstruction("ldaa #${0:x2}", 0x86, 2) },
        { 0x88, new DecodedInstruction("eora #${0:x2}", 0x88, 2) },
        { 0x89, new DecodedInstruction("adca #${0:x2}", 0x89, 2) },
        { 0x8a, new DecodedInstruction("oraa #${0:x2}", 0x8a, 2) },
        { 0x8b, new DecodedInstruction("adda #${0:x2}", 0x8b, 2) },
        { 0x8c, new DecodedInstruction("cpxa #${0:x2}", 0x8c, 2) },
        { 0x8d, new DecodedInstruction("bsr ${0:x4}", 0x8d, 2) },
        { 0x8e, new DecodedInstruction("lds #${0:x4}", 0x8e, 3) },
        { 0x90, new DecodedInstruction("suba ${0:x2}", 0x90, 2) },
        { 0x91, new DecodedInstruction("cmpa ${0:x2}", 0x91, 2) },
        { 0x92, new DecodedInstruction("sbca ${0:x2}", 0x92, 2) },
        { 0x94, new DecodedInstruction("anda ${0:x2}", 0x94, 2) },
        { 0x95, new DecodedInstruction("bita ${0:x2}", 0x95, 2) },
        { 0x96, new DecodedInstruction("ldaa ${0:x2}", 0x96, 2) },
        { 0x97, new DecodedInstruction("staa ${0:x2}", 0x97, 2) },
        { 0x98, new DecodedInstruction("eora ${0:x2}", 0x98, 2) },
        { 0x99, new DecodedInstruction("adca ${0:x2}", 0x99, 2) },
        { 0x9a, new DecodedInstruction("oraa ${0:x2}", 0x9a, 2) },
        { 0x9b, new DecodedInstruction("adda ${0:x2}", 0x9b, 2) },
        { 0x9c, new DecodedInstruction("cpxa ${0:x2}", 0x9c, 2) },
        { 0x9e, new DecodedInstruction("lds ${0:x2}", 0x9e, 2) },
        { 0x9f, new DecodedInstruction("sts ${0:x2}", 0x9f, 2) },
        { 0xa0, new DecodedInstruction("suba ${0:x2},x", 0xa0, 2) },
        { 0xa1, new DecodedInstruction("cmpa ${0:x2},x", 0xa1, 2) },
        { 0xa2, new DecodedInstruction("sbca ${0:x2},x", 0xa2, 2) },
        { 0xa4, new DecodedInstruction("anda ${0:x2},x", 0xa4, 2) },
        { 0xa5, new DecodedInstruction("bita ${0:x2},x", 0xa5, 2) },
        { 0xa6, new DecodedInstruction("ldaa ${0:x2},x", 0xa6, 2) },
        { 0xa7, new DecodedInstruction("staa ${0:x2},x", 0xa7, 2) },
        { 0xa8, new DecodedInstruction("eora ${0:x2},x", 0xa8, 2) },
        { 0xa9, new DecodedInstruction("adca ${0:x2},x", 0xa9, 2) },
        { 0xaa, new DecodedInstruction("oraa ${0:x2},x", 0xaa, 2) },
        { 0xab, new DecodedInstruction("adda ${0:x2},x", 0xab, 2) },
        { 0xac, new DecodedInstruction("cpxa ${0:x2},x", 0xac, 2) },
        { 0xad, new DecodedInstruction("jsr ${0:x2},x", 0xad, 2) },
        { 0xae, new DecodedInstruction("lds ${0:x2},x", 0xae, 2) },
        { 0xaf, new DecodedInstruction("sts ${0:x2},x", 0xaf, 2) },
        { 0xb0, new DecodedInstruction("suba ${0:x4}", 0xb0, 3) },
        { 0xb1, new DecodedInstruction("cmpa ${0:x4}", 0xb1, 3) },
        { 0xb2, new DecodedInstruction("sbca ${0:x4}", 0xb2, 3) },
        { 0xb4, new DecodedInstruction("anda ${0:x4}", 0xb4, 3) },
        { 0xb5, new DecodedInstruction("bita ${0:x4}", 0xb5, 3) },
        { 0xb6, new DecodedInstruction("ldaa ${0:x4}", 0xb6, 3) },
        { 0xb7, new DecodedInstruction("staa ${0:x4}", 0xb7, 3) },
        { 0xb8, new DecodedInstruction("eora ${0:x4}", 0xb8, 3) },
        { 0xb9, new DecodedInstruction("adca ${0:x4}", 0xb9, 3) },
        { 0xba, new DecodedInstruction("oraa ${0:x4}", 0xba, 3) },
        { 0xbb, new DecodedInstruction("adda ${0:x4}", 0xbb, 3) },
        { 0xbc, new DecodedInstruction("cpxa ${0:x4}", 0xbc, 3) },
        { 0xbd, new DecodedInstruction("jsr ${0:x4}", 0xbd, 3) },
        { 0xbe, new DecodedInstruction("lds ${0:x4}", 0xbe, 3) },
        { 0xbf, new DecodedInstruction("sts ${0:x4}", 0xbf, 3) },
        { 0xc0, new DecodedInstruction("subb #${0:x2}", 0xc0, 2) },
        { 0xc1, new DecodedInstruction("cmpb #${0:x2}", 0xc1, 2) },
        { 0xc2, new DecodedInstruction("sbcb #${0:x2}", 0xc2, 2) },
        { 0xc4, new DecodedInstruction("andb #${0:x2}", 0xc4, 2) },
        { 0xc5, new DecodedInstruction("bitb #${0:x2}", 0xc5, 2) },
        { 0xc6, new DecodedInstruction("ldab #${0:x2}", 0xc6, 2) },
        { 0xc7, new DecodedInstruction("staa #${0:x2}", 0xc7, 2) },
        { 0xc8, new DecodedInstruction("eorb #${0:x2}", 0xc8, 2) },
        { 0xc9, new DecodedInstruction("adcb #${0:x2}", 0xc9, 2) },
        { 0xca, new DecodedInstruction("orab #${0:x2}", 0xca, 2) },
        { 0xcb, new DecodedInstruction("addb #${0:x2}", 0xcb, 2) },
        { 0xce, new DecodedInstruction("ldx #${0:x4}", 0xce, 3) },
        { 0xd0, new DecodedInstruction("subb ${0:x2}", 0xd0, 2) },
        { 0xd1, new DecodedInstruction("cmpb ${0:x2}", 0xd1, 2) },
        { 0xd2, new DecodedInstruction("sbcb ${0:x2}", 0xd2, 2) },
        { 0xd4, new DecodedInstruction("andb ${0:x2}", 0xd4, 2) },
        { 0xd5, new DecodedInstruction("bitb ${0:x2}", 0xd5, 2) },
        { 0xd6, new DecodedInstruction("ldab ${0:x2}", 0xd6, 2) },
        { 0xd7, new DecodedInstruction("stab ${0:x2}", 0xd7, 2) },
        { 0xd8, new DecodedInstruction("eorb ${0:x2}", 0xd8, 2) },
        { 0xd9, new DecodedInstruction("adcb ${0:x2}", 0xd9, 2) },
        { 0xda, new DecodedInstruction("orab ${0:x2}", 0xda, 2) },
        { 0xdb, new DecodedInstruction("addb ${0:x2}", 0xdb, 2) },
        { 0xde, new DecodedInstruction("ldx ${0:x2}", 0xde, 2) },
        { 0xdf, new DecodedInstruction("stx ${0:x2}", 0xdf, 2) },
        { 0xe0, new DecodedInstruction("subb ${0:x2},x", 0xe0, 2) },
        { 0xe1, new DecodedInstruction("cmpb ${0:x2},x", 0xe1, 2) },
        { 0xe2, new DecodedInstruction("sbcb ${0:x2},x", 0xe2, 2) },
        { 0xe4, new DecodedInstruction("andb ${0:x2},x", 0xe4, 2) },
        { 0xe5, new DecodedInstruction("bitb ${0:x2},x", 0xe5, 2) },
        { 0xe6, new DecodedInstruction("ldab ${0:x2},x", 0xe6, 2) },
        { 0xe7, new DecodedInstruction("stab ${0:x2},x", 0xe7, 2) },
        { 0xe8, new DecodedInstruction("eorb ${0:x2},x", 0xe8, 2) },
        { 0xe9, new DecodedInstruction("adcb ${0:x2},x", 0xe9, 2) },
        { 0xea, new DecodedInstruction("orab ${0:x2},x", 0xea, 2) },
        { 0xeb, new DecodedInstruction("addb ${0:x2},x", 0xeb, 2) },
        { 0xee, new DecodedInstruction("ldx ${0:x2},x", 0xee, 2) },
        { 0xef, new DecodedInstruction("stx ${0:x2},x", 0xef, 2) },
        { 0xf0, new DecodedInstruction("subb ${0:x4}", 0xf0, 3) },
        { 0xf1, new DecodedInstruction("cmpb ${0:x4}", 0xf1, 3) },
        { 0xf2, new DecodedInstruction("sbcb ${0:x4}", 0xf2, 3) },
        { 0xf4, new DecodedInstruction("andb ${0:x4}", 0xf4, 3) },
        { 0xf5, new DecodedInstruction("bitb ${0:x4}", 0xf5, 3) },
        { 0xf6, new DecodedInstruction("ldab ${0:x4}", 0xf6, 3) },
        { 0xf7, new DecodedInstruction("stab ${0:x4}", 0xf7, 3) },
        { 0xf8, new DecodedInstruction("eorb ${0:x4}", 0xf8, 3) },
        { 0xf9, new DecodedInstruction("adcb ${0:x4}", 0xf9, 3) },
        { 0xfa, new DecodedInstruction("orab ${0:x4}", 0xfa, 3) },
        { 0xfb, new DecodedInstruction("addb ${0:x4}", 0xfb, 3) },
        { 0xfe, new DecodedInstruction("ldx ${0:x4}", 0xfe, 3) },
        { 0xff, new DecodedInstruction("stx ${0:x4}", 0xff, 3) },
    }.ToFrozenDictionary();
    
    private static readonly  FrozenDictionary<int, DecodedInstruction> s_m6809Disassembly = new Dictionary<int, DecodedInstruction>
    {
        { 0x00, new DecodedInstruction("neg ${0:x2}", 0x00, 2) },
        { 0x03, new DecodedInstruction("com ${0:x2}", 0x03, 2) },
        { 0x04, new DecodedInstruction("lsr ${0:x2}", 0x04, 2) },
        { 0x06, new DecodedInstruction("ror ${0:x2}", 0x06, 2) },
        { 0x07, new DecodedInstruction("asr ${0:x2}", 0x07, 2) },
        { 0x08, new DecodedInstruction("lsl ${0:x2}", 0x08, 2) },
        { 0x09, new DecodedInstruction("rol ${0:x2}", 0x09, 2) },
        { 0x0a, new DecodedInstruction("dec ${0:x2}", 0x0a, 2) },
        { 0x0c, new DecodedInstruction("inc ${0:x2}", 0x0c, 2) },
        { 0x0d, new DecodedInstruction("tst ${0:x2}", 0x0d, 2) },
        { 0x0e, new DecodedInstruction("jmp ${0:x2}", 0x0e, 2) },
        { 0x0f, new DecodedInstruction("clr ${0:x2}", 0x0f, 2) },
        { 0x1021, new DecodedInstruction("lbrn ${0:x4}", 0x1021, 4, true, true) },
        { 0x1022, new DecodedInstruction("lbhi ${0:x4}", 0x1022, 4, true, true) },
        { 0x1023, new DecodedInstruction("lbls ${0:x4}", 0x1023, 4, true, true) },
        { 0x1024, new DecodedInstruction("lbhs ${0:x4}", 0x1024, 4, true, true) },
        { 0x1025, new DecodedInstruction("lblo ${0:x4}", 0x1025, 4, true, true) },
        { 0x1026, new DecodedInstruction("lbne ${0:x4}", 0x1026, 4, true, true) },
        { 0x1027, new DecodedInstruction("lbeq ${0:x4}", 0x1027, 4, true, true) },
        { 0x1028, new DecodedInstruction("lbvc ${0:x4}", 0x1028, 4, true, true) },
        { 0x1029, new DecodedInstruction("lbvs ${0:x4}", 0x1029, 4, true, true) },
        { 0x102a, new DecodedInstruction("lbpl ${0:x4}", 0x102a, 4, true, true) },
        { 0x102b, new DecodedInstruction("lbmi ${0:x4}", 0x102b, 4, true, true) },
        { 0x102c, new DecodedInstruction("lbge ${0:x4}", 0x102c, 4, true, true) },
        { 0x102d, new DecodedInstruction("lblt ${0:x4}", 0x102d, 4, true, true) },
        { 0x102e, new DecodedInstruction("lbgt ${0:x4}", 0x102e, 4, true, true) },
        { 0x102f, new DecodedInstruction("lble ${0:x4}", 0x102f, 4, true, true) },
        { 0x103f, new DecodedInstruction("swi2", 0x103f, 2) },
        { 0x1083, new DecodedInstruction("cmpd #${0:x4}", 0x1083, 4) },
        { 0x108c, new DecodedInstruction("cmpy #${0:x4}", 0x108c, 4) },
        { 0x108e, new DecodedInstruction("ldy #${0:x4}", 0x108e, 4) },
        { 0x1093, new DecodedInstruction("cmpd ${0:x2}", 0x1093, 3) },
        { 0x109c, new DecodedInstruction("cmpy ${0:x2}", 0x109c, 3) },
        { 0x109e, new DecodedInstruction("ldy ${0:x2}", 0x109e, 3) },
        { 0x109f, new DecodedInstruction("sty ${0:x2}", 0x109f, 3) },
        { 0x10a3, new DecodedInstruction("cmpd", 0x10a3, 3) },
        { 0x10ac, new DecodedInstruction("cmpy", 0x10ac, 3) },
        { 0x10ae, new DecodedInstruction("ldy", 0x10ae, 3) },
        { 0x10af, new DecodedInstruction("sty", 0x10af, 3) },
        { 0x10b3, new DecodedInstruction("cmpd ${0:x4}", 0x10b3, 4) },
        { 0x10bc, new DecodedInstruction("cmpy ${0:x4}", 0x10bc, 4) },
        { 0x10be, new DecodedInstruction("ldy ${0:x4}", 0x10be, 4) },
        { 0x10bf, new DecodedInstruction("sty ${0:x4}", 0x10bf, 4) },
        { 0x10ce, new DecodedInstruction("lds #${0:x4}", 0x10ce, 4) },
        { 0x10de, new DecodedInstruction("lds ${0:x2}", 0x10de, 3) },
        { 0x10df, new DecodedInstruction("sts ${0:x2}", 0x10df, 3) },
        { 0x10ee, new DecodedInstruction("lds", 0x10ee, 3) },
        { 0x10ef, new DecodedInstruction("sts", 0x10ef, 3) },
        { 0x10fe, new DecodedInstruction("lds ${0:x4}", 0x10fe, 4) },
        { 0x10ff, new DecodedInstruction("sts ${0:x4}", 0x10ff, 4) },
        { 0x113f, new DecodedInstruction("swi3", 0x113f, 2) },
        { 0x1183, new DecodedInstruction("cmpu #${0:x4}", 0x1183, 4) },
        { 0x118c, new DecodedInstruction("cmps #${0:x4}", 0x118c, 4) },
        { 0x1193, new DecodedInstruction("cmpu ${0:x2}", 0x1193, 3) },
        { 0x119c, new DecodedInstruction("cmps ${0:x2}", 0x119c, 3) },
        { 0x11a3, new DecodedInstruction("cmpu", 0x11a3, 3) },
        { 0x11ac, new DecodedInstruction("cmps", 0x11ac, 3) },
        { 0x11b3, new DecodedInstruction("cmpu ${0:x4}", 0x11b3, 4) },
        { 0x11bc, new DecodedInstruction("cmps ${0:x4}", 0x11bc, 4) },
        { 0x12, new DecodedInstruction("nop", 0x12) },
        { 0x13, new DecodedInstruction("sync", 0x13) },
        { 0x16, new DecodedInstruction("lbra ${0:x4}", 0x16, 3, true, true) },
        { 0x17, new DecodedInstruction("lbsr ${0:x4}", 0x17, 3, true, true) },
        { 0x19, new DecodedInstruction("daa", 0x19) },
        { 0x1a, new DecodedInstruction("orcc #${0:x2}", 0x1a, 2) },
        { 0x1c, new DecodedInstruction("andcc #${0:x2}", 0x1c, 2) },
        { 0x1d, new DecodedInstruction("sex", 0x1d) },
        { 0x1e, new DecodedInstruction("exg", 0x1e, 2) },
        { 0x1f, new DecodedInstruction("tfr", 0x1f, 2) },
        { 0x20, new DecodedInstruction("bra ${0:x4}", 0x20, 2, true) },
        { 0x21, new DecodedInstruction("brn ${0:x4}", 0x21, 2, true) },
        { 0x22, new DecodedInstruction("bhi ${0:x4}", 0x22, 2, true) },
        { 0x23, new DecodedInstruction("bls ${0:x4}", 0x23, 2, true) },
        { 0x24, new DecodedInstruction("bhs ${0:x4}", 0x24, 2, true) },
        { 0x25, new DecodedInstruction("blo ${0:x4}", 0x25, 2, true) },
        { 0x26, new DecodedInstruction("bne ${0:x4}", 0x26, 2, true) },
        { 0x27, new DecodedInstruction("beq ${0:x4}", 0x27, 2, true) },
        { 0x28, new DecodedInstruction("bvc ${0:x4}", 0x28, 2, true) },
        { 0x29, new DecodedInstruction("bvs ${0:x4}", 0x29, 2, true) },
        { 0x2a, new DecodedInstruction("bpl ${0:x4}", 0x2a, 2, true) },
        { 0x2b, new DecodedInstruction("bmi ${0:x4}", 0x2b, 2, true) },
        { 0x2c, new DecodedInstruction("bge ${0:x4}", 0x2c, 2, true) },
        { 0x2d, new DecodedInstruction("blt ${0:x4}", 0x2d, 2, true) },
        { 0x2e, new DecodedInstruction("bgt ${0:x4}", 0x2e, 2, true) },
        { 0x2f, new DecodedInstruction("ble ${0:x4}", 0x2f, 2, true) },
        { 0x30, new DecodedInstruction("leax", 0x30, 2) },
        { 0x31, new DecodedInstruction("leay", 0x31, 2) },
        { 0x32, new DecodedInstruction("leas", 0x32, 2) },
        { 0x33, new DecodedInstruction("leau", 0x33, 2) },
        { 0x34, new DecodedInstruction("pshs", 0x34, 2) },
        { 0x35, new DecodedInstruction("puls", 0x35, 2) },
        { 0x36, new DecodedInstruction("pshu", 0x36, 2) },
        { 0x37, new DecodedInstruction("pulu", 0x37, 2) },
        { 0x39, new DecodedInstruction("rts", 0x39) },
        { 0x3a, new DecodedInstruction("abx", 0x3a) },
        { 0x3b, new DecodedInstruction("rti", 0x3b) },
        { 0x3c, new DecodedInstruction("cwai #${0:x2}", 0x3c, 2) },
        { 0x3d, new DecodedInstruction("mul", 0x3d) },
        { 0x3f, new DecodedInstruction("swi", 0x3f) },
        { 0x40, new DecodedInstruction("nega", 0x40) },
        { 0x43, new DecodedInstruction("coma", 0x43) },
        { 0x44, new DecodedInstruction("lsra", 0x44) },
        { 0x46, new DecodedInstruction("rora", 0x46) },
        { 0x47, new DecodedInstruction("asra", 0x47) },
        { 0x48, new DecodedInstruction("lsla", 0x48) },
        { 0x49, new DecodedInstruction("rola", 0x49) },
        { 0x4a, new DecodedInstruction("deca", 0x4a) },
        { 0x4c, new DecodedInstruction("inca", 0x4c) },
        { 0x4d, new DecodedInstruction("tsta", 0x4d) },
        { 0x4f, new DecodedInstruction("clra", 0x4f) },
        { 0x50, new DecodedInstruction("negb", 0x50) },
        { 0x53, new DecodedInstruction("comb", 0x53) },
        { 0x54, new DecodedInstruction("lsrb", 0x54) },
        { 0x56, new DecodedInstruction("rorb", 0x56) },
        { 0x57, new DecodedInstruction("asrb", 0x57) },
        { 0x58, new DecodedInstruction("aslb", 0x58) },
        { 0x59, new DecodedInstruction("rolb", 0x59) },
        { 0x5a, new DecodedInstruction("decb", 0x5a) },
        { 0x5c, new DecodedInstruction("incb", 0x5c) },
        { 0x5d, new DecodedInstruction("tstb", 0x5d) },
        { 0x5f, new DecodedInstruction("clrb", 0x5f) },
        { 0x60, new DecodedInstruction("neg", 0x60, 2) },
        { 0x63, new DecodedInstruction("com", 0x63, 2) },
        { 0x64, new DecodedInstruction("lsr", 0x64, 2) },
        { 0x66, new DecodedInstruction("ror", 0x66, 2) },
        { 0x67, new DecodedInstruction("asr", 0x67, 2) },
        { 0x68, new DecodedInstruction("lsl", 0x68, 2) },
        { 0x69, new DecodedInstruction("rol", 0x69, 2) },
        { 0x6a, new DecodedInstruction("dec", 0x6a, 2) },
        { 0x6c, new DecodedInstruction("inc", 0x6c, 2) },
        { 0x6d, new DecodedInstruction("tst", 0x6d, 2) },
        { 0x6e, new DecodedInstruction("jmp", 0x6e, 2) },
        { 0x6f, new DecodedInstruction("clr", 0x6f, 2) },
        { 0x70, new DecodedInstruction("neg ${0:x4}", 0x70, 3) },
        { 0x73, new DecodedInstruction("com ${0:x4}", 0x73, 3) },
        { 0x74, new DecodedInstruction("lsr ${0:x4}", 0x74, 3) },
        { 0x76, new DecodedInstruction("ror ${0:x4}", 0x76, 3) },
        { 0x77, new DecodedInstruction("asr ${0:x4}", 0x77, 3) },
        { 0x78, new DecodedInstruction("lsl ${0:x4}", 0x78, 3) },
        { 0x79, new DecodedInstruction("rol ${0:x4}", 0x79, 3) },
        { 0x7a, new DecodedInstruction("dec ${0:x4}", 0x7a, 3) },
        { 0x7c, new DecodedInstruction("inc ${0:x4}", 0x7c, 3) },
        { 0x7d, new DecodedInstruction("tst ${0:x4}", 0x7d, 3) },
        { 0x7e, new DecodedInstruction("jmp ${0:x4}", 0x7e, 3) },
        { 0x7f, new DecodedInstruction("clr ${0:x4}", 0x7f, 3) },
        { 0x80, new DecodedInstruction("suba #${0:x2}", 0x80, 2) },
        { 0x81, new DecodedInstruction("cmpa #${0:x2}", 0x81, 2) },
        { 0x82, new DecodedInstruction("sbca #${0:x2}", 0x82, 2) },
        { 0x83, new DecodedInstruction("subd #${0:x4}", 0x83, 3) },
        { 0x84, new DecodedInstruction("anda #${0:x2}", 0x84, 2) },
        { 0x85, new DecodedInstruction("bita #${0:x2}", 0x85, 2) },
        { 0x86, new DecodedInstruction("lda #${0:x2}", 0x86, 2) },
        { 0x88, new DecodedInstruction("eora #${0:x2}", 0x88, 2) },
        { 0x89, new DecodedInstruction("adca #${0:x2}", 0x89, 2) },
        { 0x8a, new DecodedInstruction("ora #${0:x2}", 0x8a, 2) },
        { 0x8b, new DecodedInstruction("adda #${0:x2}", 0x8b, 2) },
        { 0x8c, new DecodedInstruction("cmpx #${0:x4}", 0x8c, 3) },
        { 0x8d, new DecodedInstruction("bsr ${0:x4}", 0x8d, 2, true) },
        { 0x8e, new DecodedInstruction("ldx #${0:x4}", 0x8e, 3) },
        { 0x90, new DecodedInstruction("suba ${0:x2}", 0x90, 2) },
        { 0x91, new DecodedInstruction("cmpa ${0:x2}", 0x91, 2) },
        { 0x92, new DecodedInstruction("sbca ${0:x2}", 0x92, 2) },
        { 0x93, new DecodedInstruction("subd ${0:x2}", 0x93, 2) },
        { 0x94, new DecodedInstruction("anda ${0:x2}", 0x94, 2) },
        { 0x95, new DecodedInstruction("bita ${0:x2}", 0x95, 2) },
        { 0x96, new DecodedInstruction("lda ${0:x2}", 0x96, 2) },
        { 0x97, new DecodedInstruction("sta ${0:x2}", 0x97, 2) },
        { 0x98, new DecodedInstruction("eora ${0:x2}", 0x98, 2) },
        { 0x99, new DecodedInstruction("adca ${0:x2}", 0x99, 2) },
        { 0x9a, new DecodedInstruction("ora ${0:x2}", 0x9a, 2) },
        { 0x9b, new DecodedInstruction("adda ${0:x2}", 0x9b, 2) },
        { 0x9c, new DecodedInstruction("cmpx ${0:x2}", 0x9c, 2) },
        { 0x9d, new DecodedInstruction("jsr ${0:x2}", 0x9d, 2) },
        { 0x9e, new DecodedInstruction("ldx ${0:x2}", 0x9e, 2) },
        { 0x9f, new DecodedInstruction("stx ${0:x2}", 0x9f, 2) },
        { 0xa0, new DecodedInstruction("suba", 0xa0, 2) },
        { 0xa1, new DecodedInstruction("cmpa", 0xa1, 2) },
        { 0xa2, new DecodedInstruction("sbca", 0xa2, 2) },
        { 0xa3, new DecodedInstruction("subd", 0xa3, 2) },
        { 0xa4, new DecodedInstruction("anda", 0xa4, 2) },
        { 0xa5, new DecodedInstruction("bita", 0xa5, 2) },
        { 0xa6, new DecodedInstruction("lda", 0xa6, 2) },
        { 0xa7, new DecodedInstruction("sta", 0xa7, 2) },
        { 0xa8, new DecodedInstruction("eora", 0xa8, 2) },
        { 0xa9, new DecodedInstruction("adca", 0xa9, 2) },
        { 0xaa, new DecodedInstruction("ora", 0xaa, 2) },
        { 0xab, new DecodedInstruction("adda", 0xab, 2) },
        { 0xac, new DecodedInstruction("cmpx", 0xac, 2) },
        { 0xad, new DecodedInstruction("jsr", 0xad, 2) },
        { 0xae, new DecodedInstruction("ldx", 0xae, 2) },
        { 0xaf, new DecodedInstruction("stx", 0xaf, 2) },
        { 0xb0, new DecodedInstruction("suba ${0:x4}", 0xb0, 3) },
        { 0xb1, new DecodedInstruction("cmpa ${0:x4}", 0xb1, 3) },
        { 0xb2, new DecodedInstruction("sbca ${0:x4}", 0xb2, 3) },
        { 0xb3, new DecodedInstruction("subd ${0:x4}", 0xb3, 3) },
        { 0xb4, new DecodedInstruction("anda ${0:x4}", 0xb4, 3) },
        { 0xb5, new DecodedInstruction("bita ${0:x4}", 0xb5, 3) },
        { 0xb6, new DecodedInstruction("lda ${0:x4}", 0xb6, 3) },
        { 0xb7, new DecodedInstruction("sta ${0:x4}", 0xb7, 3) },
        { 0xb8, new DecodedInstruction("eora ${0:x4}", 0xb8, 3) },
        { 0xb9, new DecodedInstruction("adca ${0:x4}", 0xb9, 3) },
        { 0xba, new DecodedInstruction("ora ${0:x4}", 0xba, 3) },
        { 0xbb, new DecodedInstruction("adda ${0:x4}", 0xbb, 3) },
        { 0xbc, new DecodedInstruction("cmpx ${0:x4}", 0xbc, 3) },
        { 0xbd, new DecodedInstruction("jsr ${0:x4}", 0xbd, 3) },
        { 0xbe, new DecodedInstruction("ldx ${0:x4}", 0xbe, 3) },
        { 0xbf, new DecodedInstruction("stx ${0:x4}", 0xbf, 3) },
        { 0xc0, new DecodedInstruction("subb #${0:x2}", 0xc0, 2) },
        { 0xc1, new DecodedInstruction("cmpb #${0:x2}", 0xc1, 2) },
        { 0xc2, new DecodedInstruction("sbcb #${0:x2}", 0xc2, 2) },
        { 0xc3, new DecodedInstruction("addd #${0:x4}", 0xc3, 3) },
        { 0xc4, new DecodedInstruction("andb #${0:x2}", 0xc4, 2) },
        { 0xc5, new DecodedInstruction("bitb #${0:x2}", 0xc5, 2) },
        { 0xc6, new DecodedInstruction("ldb #${0:x2}", 0xc6, 2) },
        { 0xc8, new DecodedInstruction("eorb #${0:x2}", 0xc8, 2) },
        { 0xc9, new DecodedInstruction("adcb #${0:x2}", 0xc9, 2) },
        { 0xca, new DecodedInstruction("orb #${0:x2}", 0xca, 2) },
        { 0xcb, new DecodedInstruction("addb #${0:x2}", 0xcb, 2) },
        { 0xcc, new DecodedInstruction("ldd #${0:x4}", 0xcc, 3) },
        { 0xce, new DecodedInstruction("ldu #${0:x4}", 0xce, 3) },
        { 0xd0, new DecodedInstruction("subb ${0:x2}", 0xd0, 2) },
        { 0xd1, new DecodedInstruction("cmpb ${0:x2}", 0xd1, 2) },
        { 0xd2, new DecodedInstruction("sbcb ${0:x2}", 0xd2, 2) },
        { 0xd3, new DecodedInstruction("addd ${0:x2}", 0xd3, 2) },
        { 0xd4, new DecodedInstruction("andb ${0:x2}", 0xd4, 2) },
        { 0xd5, new DecodedInstruction("bitb ${0:x2}", 0xd5, 2) },
        { 0xd6, new DecodedInstruction("ldb ${0:x2}", 0xd6, 2) },
        { 0xd7, new DecodedInstruction("stb ${0:x2}", 0xd7, 2) },
        { 0xd8, new DecodedInstruction("eorb ${0:x2}", 0xd8, 2) },
        { 0xd9, new DecodedInstruction("adcb ${0:x2}", 0xd9, 2) },
        { 0xda, new DecodedInstruction("orb ${0:x2}", 0xda, 2) },
        { 0xdb, new DecodedInstruction("addb ${0:x2}", 0xdb, 2) },
        { 0xdc, new DecodedInstruction("ldd ${0:x2}", 0xdc, 2) },
        { 0xdd, new DecodedInstruction("std ${0:x2}", 0xdd, 2) },
        { 0xde, new DecodedInstruction("ldu ${0:x2}", 0xde, 2) },
        { 0xdf, new DecodedInstruction("stu ${0:x2}", 0xdf, 2) },
        { 0xe0, new DecodedInstruction("subb", 0xe0, 2) },
        { 0xe1, new DecodedInstruction("cmpb", 0xe1, 2) },
        { 0xe2, new DecodedInstruction("sbcb", 0xe2, 2) },
        { 0xe3, new DecodedInstruction("addd", 0xe3, 2) },
        { 0xe4, new DecodedInstruction("andb", 0xe4, 2) },
        { 0xe5, new DecodedInstruction("bitb", 0xe5, 2) },
        { 0xe6, new DecodedInstruction("ldb", 0xe6, 2) },
        { 0xe7, new DecodedInstruction("stb", 0xe7, 2) },
        { 0xe8, new DecodedInstruction("eorb", 0xe8, 2) },
        { 0xe9, new DecodedInstruction("adcb", 0xe9, 2) },
        { 0xea, new DecodedInstruction("orb", 0xea, 2) },
        { 0xeb, new DecodedInstruction("addb", 0xeb, 2) },
        { 0xec, new DecodedInstruction("ldd", 0xec, 2) },
        { 0xed, new DecodedInstruction("std", 0xed, 2) },
        { 0xee, new DecodedInstruction("ldu", 0xee, 2) },
        { 0xef, new DecodedInstruction("stu", 0xef, 2) },
        { 0xf0, new DecodedInstruction("subb ${0:x4}", 0xf0, 3) },
        { 0xf1, new DecodedInstruction("cmpb ${0:x4}", 0xf1, 3) },
        { 0xf2, new DecodedInstruction("addd ${0:x4}", 0xf2, 3) },
        { 0xf4, new DecodedInstruction("andb ${0:x4}", 0xf4, 3) },
        { 0xf5, new DecodedInstruction("bitb ${0:x4}", 0xf5, 3) },
        { 0xf6, new DecodedInstruction("ldb ${0:x4}", 0xf6, 3) },
        { 0xf7, new DecodedInstruction("stb ${0:x4}", 0xf7, 3) },
        { 0xf8, new DecodedInstruction("eorb ${0:x4}", 0xf8, 3) },
        { 0xf9, new DecodedInstruction("adcb ${0:x4}", 0xf9, 3) },
        { 0xfa, new DecodedInstruction("orb ${0:x4}", 0xfa, 3) },
        { 0xfb, new DecodedInstruction("addb ${0:x4}", 0xfb, 3) },
        { 0xfc, new DecodedInstruction("ldd ${0:x4}", 0xfc, 3) },
        { 0xfd, new DecodedInstruction("std ${0:x4}", 0xfd, 3) },
        { 0xfe, new DecodedInstruction("ldu ${0:x4}", 0xfe, 3) },
        { 0xff, new DecodedInstruction("stu ${0:x4}", 0xff, 3) },
    }.ToFrozenDictionary();
}