//-----------------------------------------------------------------------------
// Copyright (c) 2017-2019 informedcitizenry <informedcitizenry@gmail.com>
//
// Licensed under the MIT license. See LICENSE for full license information.
// 
//-----------------------------------------------------------------------------

using DotNetAsm;
using OpcodeTable = System.Collections.Generic.Dictionary<string, DotNetAsm.Instruction>;

namespace Asm6502.Net
{
    /// <summary>
    /// A line assembler that will assemble into 6502 instructions.
    /// </summary>
    public sealed partial class Asm6502 : AssemblerBase, ILineAssembler
    {
        #region Members

        readonly IAssemblyController _controller;

        string _cpu;

        bool _m16, _x16;

        OpcodeTable _filteredOpcodes;
        OpcodeTable _opcodes6502, _opcodes6502i;
        OpcodeTable _opcodes65C02, _opcodesR65C02, _opcodes65CE02, _opcodesHuC6280;
        OpcodeTable _opcodes65816;

        #endregion

        #region Methods

        void ConstructOpcodeTable()
        {
            _opcodes6502 = new OpcodeTable()
            {
                { "brk",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0x00 } },
                { "ora (${0:x2},x)",         new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x01 } },
                { "ora ${0:x2}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x05 } },
                { "asl ${0:x2}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x06 } },
                { "php",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0x08 } },
                { "ora #${0:x2}",            new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x09 } },
                { "asl",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0x0a } },
                { "ora ${0:x4}",             new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x0d } },
                { "asl ${0:x4}",             new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x0e } },
                { "bpl ${0:x4}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x10 } },
                { "ora (${0:x2}),y",         new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x11 } },
                { "ora ${0:x2},x",           new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x15 } },
                { "asl ${0:x2},x",           new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x16 } },
                { "clc",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0x18 } },
                { "ora ${0:x4},y",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x19 } },
                { "top ${0:x4},x",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x1c } },
                { "ora ${0:x4},x",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x1d } },
                { "asl ${0:x4},x",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x1e } },
                { "jsr ${0:x4}",             new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x20 } },
                { "and (${0:x2},x)",         new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x21 } },
                { "bit ${0:x2}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x24 } },
                { "and ${0:x2}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x25 } },
                { "rol ${0:x2}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x26 } },
                { "plp",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0x28 } },
                { "and #${0:x2}",            new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x29 } },
                { "rol",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0x2a } },
                { "bit ${0:x4}",             new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x2c } },
                { "and ${0:x4}",             new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x2d } },
                { "rol ${0:x4}",             new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x2e } },
                { "bmi ${0:x4}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x30 } },
                { "and (${0:x2}),y",         new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x31 } },
                { "and ${0:x2},x",           new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x35 } },
                { "rol ${0:x2},x",           new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x36 } },
                { "sec",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0x38 } },
                { "and ${0:x4},y",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x39 } },
                { "and ${0:x4},x",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x3d } },
                { "rol ${0:x4},x",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x3e } },
                { "rti",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0x40 } },
                { "eor (${0:x2},x)",         new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x41 } },
                { "eor ${0:x2}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x45 } },
                { "lsr ${0:x2}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x46 } },
                { "pha",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0x48 } },
                { "eor #${0:x2}",            new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x49 } },
                { "lsr",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0x4a } },
                { "jmp ${0:x4}",             new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x4c } },
                { "eor ${0:x4}",             new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x4d } },
                { "lsr ${0:x4}",             new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x4e } },
                { "bvc ${0:x4}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x50 } },
                { "eor (${0:x2}),y",         new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x51 } },
                { "eor ${0:x2},x",           new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x55 } },
                { "lsr ${0:x2},x",           new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x56 } },
                { "cli",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0x58 } },
                { "eor ${0:x4},y",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x59 } },
                { "eor ${0:x4},x",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x5d } },
                { "lsr ${0:x4},x",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x5e } },
                { "rts",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0x60 } },
                { "adc (${0:x2},x)",         new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x61 } },
                { "adc ${0:x2}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x65 } },
                { "ror ${0:x2}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x66 } },
                { "pla",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0x68 } },
                { "adc #${0:x2}",            new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x69 } },
                { "ror",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0x6a } },
                { "jmp (${0:x4})",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x6c } },
                { "adc ${0:x4}",             new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x6d } },
                { "ror ${0:x4}",             new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x6e } },
                { "bvs ${0:x4}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x70 } },
                { "adc (${0:x2}),y",         new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x71 } },
                { "adc ${0:x2},x",           new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x75 } },
                { "ror ${0:x2},x",           new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x76 } },
                { "sei",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0x78 } },
                { "adc ${0:x4},y",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x79 } },
                { "adc ${0:x4},x",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x7d } },
                { "ror ${0:x4},x",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x7e } },
                { "sta (${0:x2},x)",         new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x81 } },
                { "sty ${0:x2}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x84 } },
                { "sta ${0:x2}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x85 } },
                { "stx ${0:x2}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x86 } },
                { "dey",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0x88 } },
                { "txa",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0x8a } },
                { "sty ${0:x4}",             new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x8c } },
                { "sta ${0:x4}",             new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x8d } },
                { "stx ${0:x4}",             new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x8e } },
                { "bcc ${0:x4}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x90 } },
                { "sta (${0:x2}),y",         new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x91 } },
                { "sty ${0:x2},x",           new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x94 } },
                { "sta ${0:x2},x",           new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x95 } },
                { "stx ${0:x2},y",           new Instruction { CPU = "6502",    Size = 2,  Opcode = 0x96 } },
                { "tya",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0x98 } },
                { "sta ${0:x4},y",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x99 } },
                { "txs",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0x9a } },
                { "sta ${0:x4},x",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0x9d } },
                { "ldy #${0:x2}",            new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xa0 } },
                { "lda (${0:x2},x)",         new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xa1 } },
                { "ldx #${0:x2}",            new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xa2 } },
                { "ldy ${0:x2}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xa4 } },
                { "lda ${0:x2}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xa5 } },
                { "ldx ${0:x2}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xa6 } },
                { "tay",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0xa8 } },
                { "lda #${0:x2}",            new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xa9 } },
                { "tax",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0xaa } },
                { "ldy ${0:x4}",             new Instruction { CPU = "6502",    Size = 3,  Opcode = 0xac } },
                { "lda ${0:x4}",             new Instruction { CPU = "6502",    Size = 3,  Opcode = 0xad } },
                { "ldx ${0:x4}",             new Instruction { CPU = "6502",    Size = 3,  Opcode = 0xae } },
                { "bcs ${0:x4}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xb0 } },
                { "lda (${0:x2}),y",         new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xb1 } },
                { "ldy ${0:x2},x",           new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xb4 } },
                { "lda ${0:x2},x",           new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xb5 } },
                { "ldx ${0:x2},y",           new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xb6 } },
                { "clv",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0xb8 } },
                { "lda ${0:x4},y",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0xb9 } },
                { "tsx",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0xba } },
                { "ldy ${0:x4},x",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0xbc } },
                { "lda ${0:x4},x",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0xbd } },
                { "ldx ${0:x4},y",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0xbe } },
                { "cpy #${0:x2}",            new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xc0 } },
                { "cmp (${0:x2},x)",         new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xc1 } },
                { "cpy ${0:x2}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xc4 } },
                { "cmp ${0:x2}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xc5 } },
                { "dec ${0:x2}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xc6 } },
                { "iny",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0xc8 } },
                { "cmp #${0:x2}",            new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xc9 } },
                { "dex",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0xca } },
                { "cpy ${0:x4}",             new Instruction { CPU = "6502",    Size = 3,  Opcode = 0xcc } },
                { "cmp ${0:x4}",             new Instruction { CPU = "6502",    Size = 3,  Opcode = 0xcd } },
                { "dec ${0:x4}",             new Instruction { CPU = "6502",    Size = 3,  Opcode = 0xce } },
                { "bne ${0:x4}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xd0 } },
                { "cmp (${0:x2}),y",         new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xd1 } },
                { "cmp ${0:x2},x",           new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xd5 } },
                { "dec ${0:x2},x",           new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xd6 } },
                { "cld",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0xd8 } },
                { "cmp ${0:x4},y",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0xd9 } },
                { "cmp ${0:x4},x",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0xdd } },
                { "dec ${0:x4},x",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0xde } },
                { "cpx #${0:x2}",            new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xe0 } },
                { "sbc (${0:x2},x)",         new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xe1 } },
                { "cpx ${0:x2}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xe4 } },
                { "sbc ${0:x2}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xe5 } },
                { "inc ${0:x2}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xe6 } },
                { "inx",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0xe8 } },
                { "sbc #${0:x2}",            new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xe9 } },
                { "nop",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0xea } },
                { "cpx ${0:x4}",             new Instruction { CPU = "6502",    Size = 3,  Opcode = 0xec } },
                { "sbc ${0:x4}",             new Instruction { CPU = "6502",    Size = 3,  Opcode = 0xed } },
                { "inc ${0:x4}",             new Instruction { CPU = "6502",    Size = 3,  Opcode = 0xee } },
                { "beq ${0:x4}",             new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xf0 } },
                { "sbc (${0:x2}),y",         new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xf1 } },
                { "sbc ${0:x2},x",           new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xf5 } },
                { "inc ${0:x2},x",           new Instruction { CPU = "6502",    Size = 2,  Opcode = 0xf6 } },
                { "sed",                     new Instruction { CPU = "6502",    Size = 1,  Opcode = 0xf8 } },
                { "sbc ${0:x4},y",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0xf9 } },
                { "sbc ${0:x4},x",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0xfd } },
                { "inc ${0:x4},x",           new Instruction { CPU = "6502",    Size = 3,  Opcode = 0xfe } },
            };

            _opcodes65C02 = new OpcodeTable()
            {
                { "tsb ${0:x2}",             new Instruction { CPU = "65C02",   Size = 2,  Opcode = 0x04 } },
                { "tsb ${0:x4}",             new Instruction { CPU = "65C02",   Size = 3,  Opcode = 0x0c } },
                { "ora (${0:x2})",           new Instruction { CPU = "65C02",   Size = 2,  Opcode = 0x12 } },
                { "trb ${0:x2}",             new Instruction { CPU = "65C02",   Size = 2,  Opcode = 0x14 } },
                { "inc",                     new Instruction { CPU = "65C02",   Size = 1,  Opcode = 0x1a } },
                { "trb ${0:x4}",             new Instruction { CPU = "65C02",   Size = 3,  Opcode = 0x1c } },
                { "and (${0:x2})",           new Instruction { CPU = "65C02",   Size = 2,  Opcode = 0x32 } },
                { "bit ${0:x2},x",           new Instruction { CPU = "65C02",   Size = 2,  Opcode = 0x34 } },
                { "dec",                     new Instruction { CPU = "65C02",   Size = 1,  Opcode = 0x3a } },
                { "bit ${0:x4},x",           new Instruction { CPU = "65C02",   Size = 3,  Opcode = 0x3c } },
                { "eor (${0:x2})",           new Instruction { CPU = "65C02",   Size = 2,  Opcode = 0x52 } },
                { "phy",                     new Instruction { CPU = "65C02",   Size = 1,  Opcode = 0x5a } },
                { "stz ${0:x2}",             new Instruction { CPU = "65C02",   Size = 2,  Opcode = 0x64 } },
                { "adc (${0:x2})",           new Instruction { CPU = "65C02",   Size = 2,  Opcode = 0x72 } },
                { "stz ${0:x2},x",           new Instruction { CPU = "65C02",   Size = 2,  Opcode = 0x74 } },
                { "ply",                     new Instruction { CPU = "65C02",   Size = 1,  Opcode = 0x7a } },
                { "jmp (${0:x4},x)",         new Instruction { CPU = "65C02",   Size = 3,  Opcode = 0x7c } },
                { "bra ${0:x4}",             new Instruction { CPU = "65C02",   Size = 2,  Opcode = 0x80 } },
                { "bit #${0:x2}",            new Instruction { CPU = "65C02",   Size = 2,  Opcode = 0x89 } },
                { "sta (${0:x2})",           new Instruction { CPU = "65C02",   Size = 2,  Opcode = 0x92 } },
                { "stz ${0:x4}",             new Instruction { CPU = "65C02",   Size = 3,  Opcode = 0x9c } },
                { "stz ${0:x4},x",           new Instruction { CPU = "65C02",   Size = 3,  Opcode = 0x9e } },
                { "lda (${0:x2})",           new Instruction { CPU = "65C02",   Size = 2,  Opcode = 0xb2 } },
                { "cmp (${0:x2})",           new Instruction { CPU = "65C02",   Size = 2,  Opcode = 0xd2 } },
                { "phx",                     new Instruction { CPU = "65C02",   Size = 1,  Opcode = 0xda } },
                { "sbc (${0:x2})",           new Instruction { CPU = "65C02",   Size = 2,  Opcode = 0xf2 } },
                { "plx",                     new Instruction { CPU = "65C02",   Size = 1,  Opcode = 0xfa } },
            };

            _opcodesR65C02 = new OpcodeTable()
            {
                { "rmb 0,${0:x2}",           new Instruction { CPU = "R65C02",  Size = 2,  Opcode = 0x07 } },
                { "bbr 0,${0:x2},${1:x2}",   new Instruction { CPU = "R65C02",  Size = 3,  Opcode = 0x0f } },
                { "rmb 1,${0:x2}",           new Instruction { CPU = "R65C02",  Size = 2,  Opcode = 0x17 } },
                { "bbr 1,${0:x2},${1:x2}",   new Instruction { CPU = "R65C02",  Size = 3,  Opcode = 0x1f } },
                { "rmb 2,${0:x2}",           new Instruction { CPU = "R65C02",  Size = 2,  Opcode = 0x27 } },
                { "bbr 2,${0:x2},${1:x2}",   new Instruction { CPU = "R65C02",  Size = 3,  Opcode = 0x2f } },
                { "rmb 3,${0:x2}",           new Instruction { CPU = "R65C02",  Size = 2,  Opcode = 0x37 } },
                { "bbr 3,${0:x2},${1:x2}",   new Instruction { CPU = "R65C02",  Size = 3,  Opcode = 0x3f } },
                { "rmb 4,${0:x2}",           new Instruction { CPU = "R65C02",  Size = 2,  Opcode = 0x47 } },
                { "bbr 4,${0:x2},${1:x2}",   new Instruction { CPU = "R65C02",  Size = 3,  Opcode = 0x4f } },
                { "rmb 5,${0:x2}",           new Instruction { CPU = "R65C02",  Size = 2,  Opcode = 0x57 } },
                { "bbr 5,${0:x2},${1:x2}",   new Instruction { CPU = "R65C02",  Size = 3,  Opcode = 0x5f } },
                { "rmb 6,${0:x2}",           new Instruction { CPU = "R65C02",  Size = 2,  Opcode = 0x67 } },
                { "bbr 6,${0:x2},${1:x2}",   new Instruction { CPU = "R65C02",  Size = 3,  Opcode = 0x6f } },
                { "rmb 7,${0:x2}",           new Instruction { CPU = "R65C02",  Size = 2,  Opcode = 0x77 } },
                { "bbr 7,${0:x2},${1:x2}",   new Instruction { CPU = "R65C02",  Size = 3,  Opcode = 0x7f } },
                { "smb 0,${0:x2}",           new Instruction { CPU = "R65C02",  Size = 2,  Opcode = 0x87 } },
                { "bbs 0,${0:x2},${1:x2}",   new Instruction { CPU = "R65C02",  Size = 3,  Opcode = 0x8f } },
                { "smb 1,${0:x2}",           new Instruction { CPU = "R65C02",  Size = 2,  Opcode = 0x97 } },
                { "bbs 1,${0:x2},${1:x2}",   new Instruction { CPU = "R65C02",  Size = 3,  Opcode = 0x9f } },
                { "smb 2,${0:x2}",           new Instruction { CPU = "R65C02",  Size = 2,  Opcode = 0xa7 } },
                { "bbs 2,${0:x2},${1:x2}",   new Instruction { CPU = "R65C02",  Size = 3,  Opcode = 0xaf } },
                { "smb 3,${0:x2}",           new Instruction { CPU = "R65C02",  Size = 2,  Opcode = 0xb7 } },
                { "bbs 3,${0:x2},${1:x2}",   new Instruction { CPU = "R65C02",  Size = 3,  Opcode = 0xbf } },
                { "smb 4,${0:x2}",           new Instruction { CPU = "R65C02",  Size = 2,  Opcode = 0xc7 } },
                { "bbs 4,${0:x2},${1:x2}",   new Instruction { CPU = "R65C02",  Size = 3,  Opcode = 0xcf } },
                { "smb 5,${0:x2}",           new Instruction { CPU = "R65C02",  Size = 2,  Opcode = 0xd7 } },
                { "bbs 5,${0:x2},${1:x2}",   new Instruction { CPU = "R65C02",  Size = 3,  Opcode = 0xdf } },
                { "smb 6,${0:x2}",           new Instruction { CPU = "R65C02",  Size = 2,  Opcode = 0xe7 } },
                { "bbs 6,${0:x2},${1:x2}",   new Instruction { CPU = "R65C02",  Size = 3,  Opcode = 0xef } },
                { "smb 7,${0:x2}",           new Instruction { CPU = "R65C02",  Size = 2,  Opcode = 0xf7 } },
                { "bbs 7,${0:x2},${1:x2}",   new Instruction { CPU = "R65C02",  Size = 3,  Opcode = 0xff } },
            };

            _opcodesHuC6280 = new OpcodeTable()
            {
                { "sxy",                     new Instruction { CPU = "HuC6280", Size = 1,  Opcode = 0x02 } },
                { "ora (${0:x4})",           new Instruction { CPU = "HuC6280", Size = 3,  Opcode = 0x12 } },
                { "st1 #${0:x2}",            new Instruction { CPU = "HuC6280", Size = 2,  Opcode = 0x13 } },
                { "sax",                     new Instruction { CPU = "HuC6280", Size = 1,  Opcode = 0x22 } },
                { "st2 #${0:x2}",            new Instruction { CPU = "HuC6280", Size = 2,  Opcode = 0x23 } },
                { "and (${0:x4})",           new Instruction { CPU = "HuC6280", Size = 3,  Opcode = 0x32 } },
                { "say",                     new Instruction { CPU = "HuC6280", Size = 1,  Opcode = 0x42 } },
                { "tma #${0:x2}",            new Instruction { CPU = "HuC6280", Size = 2,  Opcode = 0x43 } },
                { "eor (${0:x4})",           new Instruction { CPU = "HuC6280", Size = 3,  Opcode = 0x52 } },
                { "tam #${0:x2}",            new Instruction { CPU = "HuC6280", Size = 2,  Opcode = 0x53 } },
                { "cla",                     new Instruction { CPU = "HuC6280", Size = 1,  Opcode = 0x62 } },
                { "adc (${0:x4})",           new Instruction { CPU = "HuC6280", Size = 3,  Opcode = 0x72 } },
                { "tii ${0:x4},${1:x4},${2:x4}",
                                             new Instruction { CPU = "HuC6280", Size = 7,  Opcode = 0x73 } },
                { "clx",                     new Instruction { CPU = "HuC6280", Size = 1,  Opcode = 0x82 } },
                { "tst #${0:x2},${1:x2}",    new Instruction { CPU = "HuC6280", Size = 3,  Opcode = 0x83 } },
                { "sta (${0:x4})",           new Instruction { CPU = "HuC6280", Size = 3,  Opcode = 0x92 } },
                { "tst #${0:x2},${1:x2},x",  new Instruction { CPU = "HuC6280", Size = 3,  Opcode = 0x93 } },
                { "tst #${0:x2},${1:x4}",    new Instruction { CPU = "HuC6280", Size = 4,  Opcode = 0xa3 } },
                { "lda (${0:x4})",           new Instruction { CPU = "HuC6280", Size = 3,  Opcode = 0xb2 } },
                { "tst #${0:x2},${1:x4},x",  new Instruction { CPU = "HuC6280", Size = 4,  Opcode = 0xb3 } },
                { "cly",                     new Instruction { CPU = "HuC6280", Size = 1,  Opcode = 0xc2 } },
                { "tdd ${0:x4},${1:x4},${2:x4}",
                                             new Instruction { CPU = "HuC6280", Size = 7,  Opcode = 0xc3 } },
                { "cmp (${0:x4})",           new Instruction { CPU = "HuC6280", Size = 3,  Opcode = 0xd2 } },
                { "tin ${0:x4},${1:x4},${2:x4}",
                                             new Instruction { CPU = "HuC6280", Size = 7,  Opcode = 0xd3 } },
                { "csh",                     new Instruction { CPU = "HuC6280", Size = 1,  Opcode = 0xd4 } },
                { "tia ${0:x4},${1:x4},${2:x4}",
                                             new Instruction { CPU = "HuC6280", Size = 7,  Opcode = 0xe3 } },
                { "sbc (${0:x4})",           new Instruction { CPU = "HuC6280", Size = 3,  Opcode = 0xf2 } },
                { "tai ${0:x4},${1:x4},${2:x4}",
                                             new Instruction { CPU = "HuC6280", Size = 7,  Opcode = 0xf3 } },
                { "set",                     new Instruction { CPU = "HuC6280", Size = 1,  Opcode = 0xf4 } }
            };

            _opcodes65CE02 = new OpcodeTable()
            {
                { "cle",                     new Instruction { CPU = "65CE02",  Size = 1,  Opcode = 0x02 } },
                { "see",                     new Instruction { CPU = "65CE02",  Size = 1,  Opcode = 0x03 } },
                { "tsy",                     new Instruction { CPU = "65CE02",  Size = 1,  Opcode = 0x0b } },
                { "ora (${0:x2}),z",         new Instruction { CPU = "65CE02",  Size = 2,  Opcode = 0x12 } },
                { "bpl ${0:x4}",             new Instruction { CPU = "65CE02",  Size = 3,  Opcode = 0x13 } },
                { "inz",                     new Instruction { CPU = "65CE02",  Size = 1,  Opcode = 0x1b } },
                { "jsr (${0:x4})",           new Instruction { CPU = "65CE02",  Size = 3,  Opcode = 0x22 } },
                { "jsr (${0:x4},x)",         new Instruction { CPU = "65CE02",  Size = 3,  Opcode = 0x23 } },
                { "tys",                     new Instruction { CPU = "65CE02",  Size = 1,  Opcode = 0x2b } },
                { "and (${0:x2}),z",         new Instruction { CPU = "65CE02",  Size = 2,  Opcode = 0x32 } },
                { "bmi ${0:x4}",             new Instruction { CPU = "65CE02",  Size = 3,  Opcode = 0x33 } },
                { "dez",                     new Instruction { CPU = "65CE02",  Size = 1,  Opcode = 0x3b } },
                { "neg",                     new Instruction { CPU = "65CE02",  Size = 1,  Opcode = 0x42 } },
                { "asr",                     new Instruction { CPU = "65CE02",  Size = 1,  Opcode = 0x43 } },
                { "asr ${0:x2}",             new Instruction { CPU = "65CE02",  Size = 2,  Opcode = 0x44 } },
                { "taz",                     new Instruction { CPU = "65CE02",  Size = 1,  Opcode = 0x4b } },
                { "eor (${0:x2}),z",         new Instruction { CPU = "65CE02",  Size = 2,  Opcode = 0x52 } },
                { "bvc ${0:x4}",             new Instruction { CPU = "65CE02",  Size = 3,  Opcode = 0x53 } },
                { "asr ${0:x2},x",           new Instruction { CPU = "65CE02",  Size = 2,  Opcode = 0x54 } },
                { "tab",                     new Instruction { CPU = "65CE02",  Size = 1,  Opcode = 0x5b } },
                { "map",                     new Instruction { CPU = "65CE02",  Size = 1,  Opcode = 0x5c } },
                { "rtn",                     new Instruction { CPU = "65CE02",  Size = 1,  Opcode = 0x62 } },
                { "bsr ${0:x4}",             new Instruction { CPU = "65CE02",  Size = 3,  Opcode = 0x63 } },
                { "tza",                     new Instruction { CPU = "65CE02",  Size = 1,  Opcode = 0x6b } },
                { "adc (${0:x2}),z",         new Instruction { CPU = "65CE02",  Size = 2,  Opcode = 0x72 } },
                { "bvs ${0:x4}",             new Instruction { CPU = "65CE02",  Size = 3,  Opcode = 0x73 } },
                { "tba",                     new Instruction { CPU = "65CE02",  Size = 1,  Opcode = 0x7b } },
                { "sta (${0:x2},sp),y",      new Instruction { CPU = "65CE02",  Size = 2,  Opcode = 0x82 } },
                { "bra ${0:x4}",             new Instruction { CPU = "65CE02",  Size = 3,  Opcode = 0x83 } },
                { "sty ${0:x4},x",           new Instruction { CPU = "65CE02",  Size = 3,  Opcode = 0x8b } },
                { "sta (${0:x2}),z",         new Instruction { CPU = "65CE02",  Size = 2,  Opcode = 0x92 } },
                { "bcc ${0:x4}",             new Instruction { CPU = "65CE02",  Size = 3,  Opcode = 0x93 } },
                { "blt ${0:x4}",             new Instruction { CPU = "65CE02",  Size = 3,  Opcode = 0x93 } },
                { "stx ${0:x4},y",           new Instruction { CPU = "65CE02",  Size = 3,  Opcode = 0x9b } },
                { "ldz #${0:x2}",            new Instruction { CPU = "65CE02",  Size = 2,  Opcode = 0xa3 } },
                { "ldz ${0:x4}",             new Instruction { CPU = "65CE02",  Size = 3,  Opcode = 0xab } },
                { "lda (${0:x2}),z",         new Instruction { CPU = "65CE02",  Size = 2,  Opcode = 0xb2 } },
                { "bcs ${0:x4}",             new Instruction { CPU = "65CE02",  Size = 3,  Opcode = 0xb3 } },
                { "bge ${0:x4}",             new Instruction { CPU = "65CE02",  Size = 3,  Opcode = 0xb3 } },
                { "ldz ${0:x4},x",           new Instruction { CPU = "65CE02",  Size = 3,  Opcode = 0xbb } },
                { "cpz #${0:x2}",            new Instruction { CPU = "65CE02",  Size = 2,  Opcode = 0xc2 } },
                { "dew ${0:x2}",             new Instruction { CPU = "65CE02",  Size = 2,  Opcode = 0xc3 } },
                { "asw ${0:x4}",             new Instruction { CPU = "65CE02",  Size = 3,  Opcode = 0xcb } },
                { "cmp (${0:x2}),z",         new Instruction { CPU = "65CE02",  Size = 2,  Opcode = 0xd2 } },
                { "bne ${0:x4}",             new Instruction { CPU = "65CE02",  Size = 3,  Opcode = 0xd3 } },
                { "cpz ${0:x2}",             new Instruction { CPU = "65CE02",  Size = 2,  Opcode = 0xd4 } },
                { "phz",                     new Instruction { CPU = "65CE02",  Size = 1,  Opcode = 0xdb } },
                { "cpz ${0:x4}",             new Instruction { CPU = "65CE02",  Size = 3,  Opcode = 0xdc } },
                { "lda (${0:x2},sp),y",      new Instruction { CPU = "65CE02",  Size = 2,  Opcode = 0xe2 } },
                { "inw ${0:x2}",             new Instruction { CPU = "65CE02",  Size = 2,  Opcode = 0xe3 } },
                { "row ${0:x4}",             new Instruction { CPU = "65CE02",  Size = 3,  Opcode = 0xeb } },
                { "sbc (${0:x2}),z",         new Instruction { CPU = "65CE02",  Size = 2,  Opcode = 0xf2 } },
                { "beq ${0:x4}",             new Instruction { CPU = "65CE02",  Size = 3,  Opcode = 0xf3 } },
                { "phw #${0:x4}",            new Instruction { CPU = "65CE02",  Size = 3,  Opcode = 0xf4 } },
                { "plz",                     new Instruction { CPU = "65CE02",  Size = 1,  Opcode = 0xfb } },
                { "phw ${0:x4}",             new Instruction { CPU = "65CE02",  Size = 3,  Opcode = 0xfc } }
            };

            _opcodes65816 = new OpcodeTable()
            {
                { "cop",                     new Instruction { CPU = "65816",   Size = 1,  Opcode = 0x02 } },
                { "cop #${0:x2}",            new Instruction { CPU = "65816",   Size = 2,  Opcode = 0x02 } },
                { "ora ${0:x2},s",           new Instruction { CPU = "65816",   Size = 2,  Opcode = 0x03 } },
                { "ora [${0:x2}]",           new Instruction { CPU = "65816",   Size = 2,  Opcode = 0x07 } },
                { "phd",                     new Instruction { CPU = "65816",   Size = 1,  Opcode = 0x0b } },
                { "ora ${0:x6}",             new Instruction { CPU = "65816",   Size = 4,  Opcode = 0x0f } },
                { "ora (${0:x2},s),y",       new Instruction { CPU = "65816",   Size = 2,  Opcode = 0x13 } },
                { "ora [${0:x2}],y",         new Instruction { CPU = "65816",   Size = 2,  Opcode = 0x17 } },
                { "tcs",                     new Instruction { CPU = "65816",   Size = 1,  Opcode = 0x1b } },
                { "ora ${0:x6},x",           new Instruction { CPU = "65816",   Size = 4,  Opcode = 0x1f } },
                { "jsl ${0:x6}",             new Instruction { CPU = "65816",   Size = 4,  Opcode = 0x22 } },
                { "jsr ${0:x6}",             new Instruction { CPU = "65816",   Size = 4,  Opcode = 0x22 } },
                { "and ${0:x2},s",           new Instruction { CPU = "65816",   Size = 2,  Opcode = 0x23 } },
                { "and [${0:x2}]",           new Instruction { CPU = "65816",   Size = 2,  Opcode = 0x27 } },
                { "pld",                     new Instruction { CPU = "65816",   Size = 1,  Opcode = 0x2b } },
                { "and ${0:x6}",             new Instruction { CPU = "65816",   Size = 4,  Opcode = 0x2f } },
                { "and (${0:x2},s),y",       new Instruction { CPU = "65816",   Size = 2,  Opcode = 0x33 } },
                { "and [${0:x2}],y",         new Instruction { CPU = "65816",   Size = 2,  Opcode = 0x37 } },
                { "tsc",                     new Instruction { CPU = "65816",   Size = 1,  Opcode = 0x3b } },
                { "and ${0:x6},x",           new Instruction { CPU = "65816",   Size = 4,  Opcode = 0x3f } },
                { "wdm",                     new Instruction { CPU = "65816",   Size = 1,  Opcode = 0x42 } },
                { "eor ${0:x2},s",           new Instruction { CPU = "65816",   Size = 2,  Opcode = 0x43 } },
                { "mvp ${0:x2},${1:x2}",     new Instruction { CPU = "65816",   Size = 3,  Opcode = 0x44 } },
                { "eor [${0:x2}]",           new Instruction { CPU = "65816",   Size = 2,  Opcode = 0x47 } },
                { "phk",                     new Instruction { CPU = "65816",   Size = 1,  Opcode = 0x4b } },
                { "eor ${0:x6}",             new Instruction { CPU = "65816",   Size = 4,  Opcode = 0x4f } },
                { "eor (${0:x2},s),y",       new Instruction { CPU = "65816",   Size = 2,  Opcode = 0x53 } },
                { "mvn ${0:x2},${1:x2}",     new Instruction { CPU = "65816",   Size = 3,  Opcode = 0x54 } },
                { "eor [${0:x2}],y",         new Instruction { CPU = "65816",   Size = 2,  Opcode = 0x57 } },
                { "tcd",                     new Instruction { CPU = "65816",   Size = 1,  Opcode = 0x5b } },
                { "jml ${0:x6}",             new Instruction { CPU = "65816",   Size = 4,  Opcode = 0x5c } },
                { "jmp ${0:x6}",             new Instruction { CPU = "65816",   Size = 4,  Opcode = 0x5c } },
                { "eor ${0:x6},x",           new Instruction { CPU = "65816",   Size = 4,  Opcode = 0x5f } },
                { "per ${0:x4}",             new Instruction { CPU = "65816",   Size = 3,  Opcode = 0x62 } },
                { "adc ${0:x2},s",           new Instruction { CPU = "65816",   Size = 2,  Opcode = 0x63 } },
                { "adc [${0:x2}]",           new Instruction { CPU = "65816",   Size = 2,  Opcode = 0x67 } },
                { "rtl",                     new Instruction { CPU = "65816",   Size = 1,  Opcode = 0x6b } },
                { "adc ${0:x6}",             new Instruction { CPU = "65816",   Size = 4,  Opcode = 0x6f } },
                { "adc (${0:x2},s),y",       new Instruction { CPU = "65816",   Size = 2,  Opcode = 0x73 } },
                { "adc [${0:x2}],y",         new Instruction { CPU = "65816",   Size = 2,  Opcode = 0x77 } },
                { "tdc",                     new Instruction { CPU = "65816",   Size = 1,  Opcode = 0x7b } },
                { "adc ${0:x6},x",           new Instruction { CPU = "65816",   Size = 4,  Opcode = 0x7f } },
                { "brl ${0:x4}",             new Instruction { CPU = "65816",   Size = 3,  Opcode = 0x82 } },
                { "sta ${0:x2},s",           new Instruction { CPU = "65816",   Size = 2,  Opcode = 0x83 } },
                { "sta [${0:x2}]",           new Instruction { CPU = "65816",   Size = 2,  Opcode = 0x87 } },
                { "phb",                     new Instruction { CPU = "65816",   Size = 1,  Opcode = 0x8b } },
                { "sta ${0:x6}",             new Instruction { CPU = "65816",   Size = 4,  Opcode = 0x8f } },
                { "sta (${0:x2},s),y",       new Instruction { CPU = "65816",   Size = 2,  Opcode = 0x93 } },
                { "sta [${0:x2}],y",         new Instruction { CPU = "65816",   Size = 2,  Opcode = 0x97 } },
                { "txy",                     new Instruction { CPU = "65816",   Size = 1,  Opcode = 0x9b } },
                { "sta ${0:x6},x",           new Instruction { CPU = "65816",   Size = 4,  Opcode = 0x9f } },
                { "lda ${0:x2},s",           new Instruction { CPU = "65816",   Size = 2,  Opcode = 0xa3 } },
                { "lda [${0:x2}]",           new Instruction { CPU = "65816",   Size = 2,  Opcode = 0xa7 } },
                { "plb",                     new Instruction { CPU = "65816",   Size = 1,  Opcode = 0xab } },
                { "lda ${0:x6}",             new Instruction { CPU = "65816",   Size = 4,  Opcode = 0xaf } },
                { "lda (${0:x2},s),y",       new Instruction { CPU = "65816",   Size = 2,  Opcode = 0xb3 } },
                { "lda [${0:x2}],y",         new Instruction { CPU = "65816",   Size = 2,  Opcode = 0xb7 } },
                { "tyx",                     new Instruction { CPU = "65816",   Size = 1,  Opcode = 0xbb } },
                { "lda ${0:x6},x",           new Instruction { CPU = "65816",   Size = 4,  Opcode = 0xbf } },
                { "rep #${0:x2}",            new Instruction { CPU = "65816",   Size = 2,  Opcode = 0xc2 } },
                { "cmp ${0:x2},s",           new Instruction { CPU = "65816",   Size = 2,  Opcode = 0xc3 } },
                { "cmp [${0:x2}]",           new Instruction { CPU = "65816",   Size = 2,  Opcode = 0xc7 } },
                { "wai",                     new Instruction { CPU = "65816",   Size = 1,  Opcode = 0xcb } },
                { "cmp ${0:x6}",             new Instruction { CPU = "65816",   Size = 4,  Opcode = 0xcf } },
                { "cmp (${0:x2},s),y",       new Instruction { CPU = "65816",   Size = 2,  Opcode = 0xd3 } },
                { "pei (${0:x2})",           new Instruction { CPU = "65816",   Size = 2,  Opcode = 0xd4 } },
                { "cmp [${0:x2}],y",         new Instruction { CPU = "65816",   Size = 2,  Opcode = 0xd7 } },
                { "stp",                     new Instruction { CPU = "65816",   Size = 1,  Opcode = 0xdb } },
                { "jmp [${0:x4}]",           new Instruction { CPU = "65816",   Size = 3,  Opcode = 0xdc } },
                { "cmp ${0:x6},x",           new Instruction { CPU = "65816",   Size = 4,  Opcode = 0xdf } },
                { "sep #${0:x2}",            new Instruction { CPU = "65816",   Size = 2,  Opcode = 0xe2 } },
                { "sbc ${0:x2},s",           new Instruction { CPU = "65816",   Size = 2,  Opcode = 0xe3 } },
                { "sbc [${0:x2}]",           new Instruction { CPU = "65816",   Size = 2,  Opcode = 0xe7 } },
                { "xba",                     new Instruction { CPU = "65816",   Size = 1,  Opcode = 0xeb } },
                { "sbc ${0:x6}",             new Instruction { CPU = "65816",   Size = 4,  Opcode = 0xef } },
                { "sbc (${0:x2},s),y",       new Instruction { CPU = "65816",   Size = 2,  Opcode = 0xf3 } },
                { "pea ${0:x4}",             new Instruction { CPU = "65816",   Size = 3,  Opcode = 0xf4 } },
                { "sbc [${0:x2}],y",         new Instruction { CPU = "65816",   Size = 2,  Opcode = 0xf7 } },
                { "xce",                     new Instruction { CPU = "65816",   Size = 1,  Opcode = 0xfb } },
                { "sbc ${0:x6},x",           new Instruction { CPU = "65816",   Size = 4,  Opcode = 0xff } },
            };

            _opcodes6502i = new OpcodeTable()
            {
                { "jam",                     new Instruction { CPU = "6502i",   Size = 1,  Opcode = 0x02 } },
                { "slo (${0:x2},x)",         new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x03 } },
                { "dop ${0:x2}",             new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x04 } },
                { "slo ${0:x2}",             new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x07 } },
                { "top",                     new Instruction { CPU = "6502i",   Size = 1,  Opcode = 0x0c } },
                { "top ${0:x4}",             new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0x0c } },
                { "slo ${0:x4}",             new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0x0f } },
                { "stp",                     new Instruction { CPU = "6502i",   Size = 1,  Opcode = 0x12 } },
                { "slo (${0:x2}),y",         new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x13 } },
                { "dop ${0:x2},x",           new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x14 } },
                { "slo ${0:x2},x",           new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x17 } },
                { "slo ${0:x4},y",           new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0x1b } },
                { "slo ${0:x4},x",           new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0x1f } },
                { "rla (${0:x2},x)",         new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x23 } },
                { "rla ${0:x2}",             new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x27 } },
                { "anc #${0:x2}",            new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x2b } },
                { "rla ${0:x4}",             new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0x2f } },
                { "rla (${0:x2}),y",         new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x33 } },
                { "rla ${0:x2},x",           new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x37 } },
                { "rla ${0:x4},y",           new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0x3b } },
                { "rla ${0:x4},x",           new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0x3f } },
                { "sre (${0:x2},x)",         new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x43 } },
                { "sre ${0:x2}",             new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x47 } },
                { "asr #${0:x2}",            new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x4b } },
                { "sre ${0:x4}",             new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0x4f } },
                { "sre (${0:x2}),y",         new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x53 } },
                { "sre ${0:x2},x",           new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x57 } },
                { "sre ${0:x4},y",           new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0x5b } },
                { "sre ${0:x4},x",           new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0x5f } },
                { "rra (${0:x2},x)",         new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x63 } },
                { "rra ${0:x2}",             new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x67 } },
                { "arr #${0:x2}",            new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x6b } },
                { "rra ${0:x4}",             new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0x6f } },
                { "rra (${0:x2}),y",         new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x73 } },
                { "rra ${0:x2},x",           new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x77 } },
                { "rra ${0:x4},y",           new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0x7b } },
                { "rra ${0:x4},x",           new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0x7f } },
                { "dop",                     new Instruction { CPU = "6502i",   Size = 1,  Opcode = 0x80 } },
                { "dop #${0:x2}",            new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x80 } },
                { "sax (${0:x2},x)",         new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x83 } },
                { "sax ${0:x2}",             new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x87 } },
                { "ane #${0:x2}",            new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x8b } },
                { "sax ${0:x4}",             new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0x8f } },
                { "sha (${0:x2}),y",         new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x93 } },
                { "sax ${0:x2},y",           new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0x97 } },
                { "tas ${0:x4},y",           new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0x9b } },
                { "shy ${0:x4},x",           new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0x9c } },
                { "shx ${0:x4},y",           new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0x9e } },
                { "sha ${0:x4},y",           new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0x9f } },
                { "lax (${0:x2},x)",         new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0xa3 } },
                { "lax ${0:x2}",             new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0xa7 } },
                { "lax ${0:x4}",             new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0xaf } },
                { "lax (${0:x2}),y",         new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0xb3 } },
                { "lax ${0:x2},y",           new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0xb7 } },
                { "las ${0:x4},y",           new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0xbb } },
                { "lax ${0:x4},y",           new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0xbf } },
                { "dcp (${0:x2},x)",         new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0xc3 } },
                { "dcp ${0:x2}",             new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0xc7 } },
                { "sax #${0:x2}",            new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0xcb } },
                { "dcp ${0:x4}",             new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0xcf } },
                { "dcp (${0:x2}),y",         new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0xd3 } },
                { "dcp ${0:x2},x",           new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0xd7 } },
                { "dcp ${0:x4},y",           new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0xdb } },
                { "dcp ${0:x4},x",           new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0xdf } },
                { "isb (${0:x2},x)",         new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0xe3 } },
                { "isb ${0:x2}",             new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0xe7 } },
                { "isb ${0:x4}",             new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0xef } },
                { "isb (${0:x2}),y",         new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0xf3 } },
                { "isb ${0:x2},x",           new Instruction { CPU = "6502i",   Size = 2,  Opcode = 0xf7 } },
                { "isb ${0:x4},y",           new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0xfb } },
                { "isb ${0:x4},x",           new Instruction { CPU = "6502i",   Size = 3,  Opcode = 0xff } },
            };
        }

        #endregion

        #region Properties

        /// <summary>
        /// Gets an array of the 65xx-based CPUs whose mnemonics this assembler recognizes.
        /// </summary>
        /// <value>The supported CPUs.</value>
        public static string[] SupportedCPUs { get; } =
        {
            "6502",
            "6502i",
            "65C02",
            "HuC6280",
            "R65C02",
            "65CE02",
            "65816"
        };

        #endregion

    }
}