//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asm6502.Net.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asm6502.Net.Resources.ErrorStrings", typeof(ErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown or invalid expression: &apos;{0}&apos;.
        /// </summary>
        internal static string BadExpression {
            get {
                return ResourceManager.GetString("BadExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve anonymous label.
        /// </summary>
        internal static string CannotResolveAnonymousLabel {
            get {
                return ResourceManager.GetString("CannotResolveAnonymousLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closure &apos;{0}&apos; does not close a block.
        /// </summary>
        internal static string ClosureDoesNotCloseBlock {
            get {
                return ResourceManager.GetString("ClosureDoesNotCloseBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closure {0} does not close a {1}.
        /// </summary>
        internal static string ClosureDoesNotCloseMacro {
            get {
                return ResourceManager.GetString("ClosureDoesNotCloseMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant expression in LValue &apos;{0}&apos;.
        /// </summary>
        internal static string ConstantExpressionInLVal {
            get {
                return ResourceManager.GetString("ConstantExpressionInLVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not process binary file &apos;{0}&apos;.
        /// </summary>
        internal static string CouldNotProcessBinary {
            get {
                return ResourceManager.GetString("CouldNotProcessBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directive &apos;{0}&apos; takes no arguments.
        /// </summary>
        internal static string DirectiveTakesNoArguments {
            get {
                return ResourceManager.GetString("DirectiveTakesNoArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename not specified.
        /// </summary>
        internal static string FilenameNotSpecified {
            get {
                return ResourceManager.GetString("FilenameNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal quantity &apos;{0}&apos;.
        /// </summary>
        internal static string IllegalQuantity {
            get {
                return ResourceManager.GetString("IllegalQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid constant assignment.
        /// </summary>
        internal static string InvalidConstantAssignment {
            get {
                return ResourceManager.GetString("InvalidConstantAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter reference &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidParamRef {
            get {
                return ResourceManager.GetString("InvalidParamRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Program Counter assignment &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidPCAssignment {
            get {
                return ResourceManager.GetString("InvalidPCAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol &apos;{0}&apos; not found.
        /// </summary>
        internal static string LabelNotDefined {
            get {
                return ResourceManager.GetString("LabelNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol &apos;{0}&apos; is not a valid label.
        /// </summary>
        internal static string LabelNotValid {
            get {
                return ResourceManager.GetString("LabelNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redefinition of label &apos;{0}&apos;.
        /// </summary>
        internal static string LabelRedefinition {
            get {
                return ResourceManager.GetString("LabelRedefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro parameter reference must be a letter or digit.
        /// </summary>
        internal static string MacroParamIncorrect {
            get {
                return ResourceManager.GetString("MacroParamIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro parameter not specified.
        /// </summary>
        internal static string MacroParamNotSpecified {
            get {
                return ResourceManager.GetString("MacroParamNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redefinition of macro &apos;{0}&apos;.
        /// </summary>
        internal static string MacroRedefinition {
            get {
                return ResourceManager.GetString("MacroRedefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing closure for block.
        /// </summary>
        internal static string MissingClosure {
            get {
                return ResourceManager.GetString("MissingClosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing closure for {0}.
        /// </summary>
        internal static string MissingClosureMacro {
            get {
                return ResourceManager.GetString("MissingClosureMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most significant bit should not be set &apos;{0}&apos;.
        /// </summary>
        internal static string MSBShouldNotBeSet {
            get {
                return ResourceManager.GetString("MSBShouldNotBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General syntax error.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Counter overflow &apos;{0}&apos;.
        /// </summary>
        internal static string PCOverflow {
            get {
                return ResourceManager.GetString("PCOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pstring size too large.
        /// </summary>
        internal static string PStringSizeTooLarge {
            get {
                return ResourceManager.GetString("PStringSizeTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote string not enclosed.
        /// </summary>
        internal static string QuoteStringNotEnclosed {
            get {
                return ResourceManager.GetString("QuoteStringNotEnclosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro or segment &apos;{0}&apos; is being called recursively.
        /// </summary>
        internal static string RecursiveMacro {
            get {
                return ResourceManager.GetString("RecursiveMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative branch out of range &apos;{0}&apos;.
        /// </summary>
        internal static string RelativeBranchOutOfRange {
            get {
                return ResourceManager.GetString("RelativeBranchOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too few arguments for directive &apos;{0}&apos;.
        /// </summary>
        internal static string TooFewArguments {
            get {
                return ResourceManager.GetString("TooFewArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many arguments for directive &apos;{0}&apos;.
        /// </summary>
        internal static string TooManyArguments {
            get {
                return ResourceManager.GetString("TooManyArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown instruction or incorrect parameters for instruction &apos;{0}&apos;.
        /// </summary>
        internal static string UnknownInstruction {
            get {
                return ResourceManager.GetString("UnknownInstruction", resourceCulture);
            }
        }
    }
}
